### ISSUE TITLE
Implement TypeDefinitionRequest

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1010]
Implement [TypeDefinitionRequest](http://hackage.haskell.org/package/haskell-lsp-types-0.8.0.1/docs/Language-Haskell-LSP-Types.html#t:TypeDefinitionRequest) so that we can go to the definition of the type of a variable etc.

**Comment by fendor** [comment]
I would be interested in implementing this feature, but I require a little guidance.

**Comment by bubba** [comment]
You'll probably want to start by adding in a handler for [`ReqTypeDefinition`](http://hackage.haskell.org/package/haskell-lsp-0.8.0.1/docs/Language-Haskell-LSP-Messages.html#t:FromClientMessage) inside `LspStdio.hs`, somewhere near here:

https://github.com/haskell/haskell-ide-engine/blob/e1aeb180ab8065bd6a8413e050c6277191d0d33f/src/Haskell/Ide/Engine/Transport/LspStdio.hs#L696-L705

And from then you can probably try seeing how `ReqDefinition` plugs into GhcMod to gather information. Hopefully this helps

**Comment by fendor** [comment]
Finally have the time to do this issue, but I have to ask, due to the lack of documentation, what is this Request supposed to do? 
My gut feeling is that it shows me the definition of a Type. 
When I press ctrl+left click on a type in VSCode it already sends me to the Definition of that type, so it seems this is not what I want?

**Comment by bubba** [comment]
> The go to type definition request is sent from the client to the server to resolve the type definition location of a symbol at a given text document position.

The specification is pretty vague I agree, from what I can grok from it I think its for jumping to the definition of a type for an expression/value. i.e. it looks up the type of what was just clicked, and then jumps to that type
