### ISSUE TITLE
Can not build HIE with GHC 8.6.3 on Windows 7

### ISSUE THREAD

**Issue by uzhas-sovka** [haskell/haskell-ide-engine#1026]
Last lines from build log:

Progress 177/218: cabal-plan-0.4.0.0, fclabels-2.0.3.3, mono-traversable-1.0.10.                                                                                mono-traversable-1.0.10.0: build
Progress 177/218: cabal-plan-0.4.0.0, fclabels-2.0.3.3, mono-traversable-1.0.10.                                                                                cabal-plan-0.4.0.0: copy/register
Progress 177/218: cabal-plan-0.4.0.0, fclabels-2.0.3.3, mono-traversable-1.0.10.                                                                                mono-traversable-1.0.10.0: copy/register
Progress 179/218: fclabels-2.0.3.3

And it freezes. Ghc.exe process is busy, one core is occupied.

Stack 1.9.3

**Comment by uzhas-sovka** [comment]
Second try, 8.6.3 already installed

haskell-lsp-types-0.8.0.1: configure
Progress 3/51: cabal-plan-0.4.0.0, fclabels-2.0.3.3, haddock-api-2.21.0, haskell                                                                                haskell-lsp-types-0.8.0.1: build
Progress 3/51: cabal-plan-0.4.0.0, fclabels-2.0.3.3, haddock-api-2.21.0, haskell                                                                                cabal-plan-0.4.0.0: copy/register
Progress 3/51: cabal-plan-0.4.0.0, fclabels-2.0.3.3, haddock-api-2.21.0, haskell                                                                                haddock-api-2.21.0: copy/register
Progress 6/51: fclabels-2.0.3.3

Freezes.

**Comment by fendor** [comment]
GHC 8.6.3 is broken on Windows for Template Haskell, see issue #1008

**Comment by Anrock** [comment]
Closing as dup of #1008
