### ISSUE TITLE
0.5.0.0: Could not fetch submodules

### ISSUE THREAD

**Issue by unclechu** [haskell/haskell-ide-engine#1030]
```
λ git branch
* (HEAD detached at 0.5.0.0)
  master
```
```
λ git submodule update
Submodule path 'submodules/HaRe': checked out '53979f062bebcaa132390d1fd0cec74a51662952'
error: Server does not allow request for unadvertised object 6c187da8f8166d595f36d6aaf419370283b3d1e9
Fetched in submodule path 'submodules/brittany', but it did not contain 6c187da8f8166d595f36d6aaf419370283b3d1e9. Direct fetching of that commit failed.
```

**Comment by unclechu** [comment]
It is some force-pusher's job? I just checkout `brittany` to `master` branch manually and `make build-all` is succeeded.

**Comment by bubba** [comment]
I'm not sure if anyone force-pushed, but `6c187da8f8166d595f36d6aaf419370283b3d1e9` is the correct hash for the current commit. The remote did change recently though which is probably what threw it off: 
https://github.com/haskell/haskell-ide-engine/commit/870e7c9ebe463c5f87f785188e4cf286e4d8c53f#diff-8903239df476d7401cf9e76af0252622

**Comment by unclechu** [comment]
I just did fresh `--recursive` clone of a repo and this went okay. I'm not sure what kind of this issue is. @bubba May be `git submodule sync --recursive` supposed to be added to `Makefile` or something? To avoid such issues in the future, since it `make build-all` is failing, and it does `git submodule update` which fails, I just pulled fresh `0.5.0.0` branch in existing repo.

**Comment by bubba** [comment]
@unclechu looks like the Makefile already had a step to sync the submodules but it didn't use `--recursive`. Thanks for spotting this, I've created a PR for it: #1032
