### ISSUE TITLE
Error hie-test-utils compiling for hie-8.6.3 on Mac OS X mojave.

### ISSUE THREAD

**Issue by wpoosanguansit** [haskell/haskell-ide-engine#1041]
I do get:

Installing internal library hie-test-utils in /Users/anonym/Downloads/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.0/8.6.3/lib/x86_64-osx-ghc-8.6.3/haskell-ide-engine-0.5.0.0-9vWVKrscep560EmwgxGLne-hie-test-utils
Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3: Error: Could not find module:
TestUtils with any suffix: ["hi"] in the search path:
[".stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/hie-test-utils"]

**Comment by bubba** [comment]
Does running `stack clean`/`stack clean --full` help? You might also want to make sure that you're on stack 1.9.3 for this, internal libraries were broken on stack 1.9.1, and you can upgrade to it with `stack upgrade`

**Comment by Anrock** [comment]
> rm -rf ~/.stack then stack upgrade did the trick. Thanks.

Fixed identical case in #1046, so closing this. If that wouldn't help - feel free to reopne.

**Comment by wpoosanguansit** [comment]
I am sorry for being late.  Just like to confirm that update stack to the latest version 1.9.3 resolves the issue.

  haskell-ide-engine git:(master) ✗ hie --version
Version 0.5.0.0, Git revision 81c26ad8e226688e4564ca907d59726dbe45ea02 (dirty) (2359 commits) x86_64 ghc-8.6.3
