### ISSUE TITLE
Hie build fails regularly

### ISSUE THREAD

**Issue by power-fungus** [haskell/haskell-ide-engine#1049]
Every now and then, someone opens an issue about a failing build. 2 questions arise

* is it known what causes the failing builds? Can it be prevented? 
* the solution is to clean the `.stack-work` dir. Can we hint inside the `install.hs` to this fix such that we reduce simple build issues?

**Comment by power-fungus** [comment]
I can add the notice about cleaning the `.stack-work` dir and to call `stack clean`. 

Is it known what causes regular build fails?

**Comment by alanz** [comment]
In my experience it is more likely to fail if one or more of the submodules have changed.  Typically the version numbers of the underlying packages (ghc-mod etc) do not change, so stack has no way of knowing it is stale.
