### ISSUE TITLE
Feature request: integrate with IntelliJ IDEA (or IntelliJ CLion)

### ISSUE THREAD

**Issue by mouse07410** [haskell/haskell-ide-engine#1050]
Subject says it all - it would be great if you could integrate your engine with the IntelliJ IDE.

Thank you!

**Comment by Anrock** [comment]
See #469

**Comment by mouse07410** [comment]
Request was to integrate with IntelliJ IDEA. #469 complains that building on Mac works fine, but integration with IntelliJ doesn't. 

What useful info, in your opinion, should I get from #469, besides that I'm not the only one who'd like to see your plugin working with IntelliJ?

**Comment by Anrock** [comment]
"Integration with IDEA not working" and "Request to integrate with IDEA" are pretty much the same thing.
In linked issue there are some useful links to LSP related instructions and some untested suggestions.
