### ISSUE TITLE
Pre-built binaries for latest version

### ISSUE THREAD

**Issue by pardom** [haskell/haskell-ide-engine#1052]
The readme describes a method of installation for macOS using pre-built binaries: https://github.com/haskell/haskell-ide-engine#installation-on-macos

The latest release with pre-built binaries is three versions old. Could we add this step to the release checklist and add binaries for the existing release?

**Comment by bubba** [comment]
Oops, that link in the readme should be taken out (for now). There's a pretty bad issue with the binaries involving paths that means that they can only run on the machine that they are built, so we've taken them down: https://github.com/haskell/haskell-ide-engine/issues/992
There is a new version of `cabal-helper` that should be integrated with HIE soon that avoids using the wrapper that requires relative paths, and hopefully then we should be able to get binaries up and running again

**Comment by pardom** [comment]
Okay, so should I build from source for now?

**Comment by pardom** [comment]
And in the meantime could we have a brew formula?

**Comment by pardom** [comment]
Actually, I'll make the formula and PR a README change if that's okay.

**Comment by bubba** [comment]
Certainly! There is a ticket for the homebrew formulae https://github.com/haskell/haskell-ide-engine/issues/529, and there was a PR for homebrew-core too but it was recently closed by the maintainers (they didn't like installing via stack nor cabal new-install it seemed): https://github.com/Homebrew/homebrew-core/pull/29800
It is definitely possible to host a formula though in this repository though, and any PRs are gladly welcomed
