### ISSUE TITLE
Purpose of target `dist` in install.hs

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-ide-engine#1059]
In the PR #1056 it is noted that target `dist` is usually not necessary for installation of HIE, thus, the dependency `zlib` could be removed from install.hs.

Things we could do with `dist`:
* Drop it without replacement
* Leave it unchanged in install.hs
* Extract a build script, potentially written in `shake`

**Comment by Anrock** [comment]
Does anyone even use it?

**Comment by fendor** [comment]
I dont think so. Most people write their custom build script to package all of the hie installations.
I am in favour of dropping it.

**Comment by Anrock** [comment]
If nobody uses - i'm for dropping it, too.

**Comment by lorenzo** [comment]
Yes, I think dropping it is the right choice
