### ISSUE TITLE
On the windows10 systems,HIE like a dead fish  

### ISSUE THREAD

**Issue by mecaocao** [haskell/haskell-ide-engine#1060]
On the windows10 systems,HIE like a dead fish ！

**Comment by lorenzo** [comment]
Could you please be more specific?

**Comment by fendor** [comment]
On my Windows 10, HIE just doesnt do anything, on hover the `loading...` tip is shown and in the output, after recognizing it as a stack project, nothing happens. Maybe that's the same issue?

While it is possible to build, Windows support seems generally broken, tests can not be run either, maybe we should open a issue where we collect information about the problem, currently problems are scattered over multiple issues.

**Comment by Anrock** [comment]
Are y'all taking about https://github.com/haskell/haskell-ide-engine/issues/983 ? I don't think we need yet another issue about it.

**Comment by bubba** [comment]
I think we can close this as a duplicate (feel free to reopen though)
