### ISSUE TITLE
Way to Disable Brittany?

### ISSUE THREAD

**Issue by Weizilla** [haskell/haskell-ide-engine#1064]
Is there a way to disable brittany? I would like to use a different formatter but I'm guessing that would be too difficult so I'm ok with disabling brittany in hie and just having my editor (VS Code) call a different formatter on save.

**Comment by bubba** [comment]
Does unselecting Format on Save in the VS Code settings disable the formatting for you? 
<img width="963" alt="image" src="https://user-images.githubusercontent.com/2488460/51780440-5a4c9700-2106-11e9-98dd-77d965e75475.png">

**Comment by Weizilla** [comment]
Ideally, I would like to use a different formatter but still have it execute on save and when using the Format Code editor command. 

I thought maybe VS Code delegated everything to hie including the formatting so if I turned off brittany in hie, I could tell VS Code to use something else like hindent. Would that not work?

**Comment by Weizilla** [comment]
There's an issue open with the VS Code HIE extension asking for the same thing: https://github.com/alanz/vscode-hie-server/issues/79

**Comment by bubba** [comment]
I think we could use the [dynamic capability stuff](url
https://microsoft.github.io/language-server-protocol/specification#client_registerCapability) to disable formatting with HIE, not sure if the internals support it yet. 
We could also just add the other formatter into HIE ;)
