### ISSUE TITLE
Importing local modules in Stack

### ISSUE THREAD

**Issue by rcarriga** [haskell/haskell-ide-engine#1065]
I can't seem to import modules from within my stack project. For the most basic example it won't work for a fresh project (ie: `stack new <name>`), where Main imports Lib. It shows "Could not find module 'Lib'". The projects has no issues when running `stack build`.

GHC: 8.6.3
Stack Version: 1.9.3 
Editor: Vim 8.0
OS: Ubuntu 18.10

**Comment by gregnwosu** [comment]
Is your hie compiled against 8.6.3 yaml?

**Comment by jneira** [comment]
@rumblesan @rcarriga hie changed the way it discovers the component and modules (now uses hie-bios), could you give a try and check if the issue is gone? feel free to reopen if it is not the case
