### ISSUE TITLE
Unable to parse cabal file

### ISSUE THREAD

**Issue by TheRealC05** [haskell/haskell-ide-engine#1071]
Since there are no instructions specifically for Mac, I tried to install it with:
```
$ git clone https://github.com/haskell/haskell-ide-engine
$ cd haskell-ide-engine && make build-all
```
but the `make build-all` command fails with
```
Unable to parse cabal file for base-noprelude-4.12.0.0@sha256:dcd5ece10257f79fa16e207d558b31ab3467b205adae5d1976abdee28b1c8b4a,6845: NoParse "reexported-modules" 42
Unable to load cabal files for snapshot
```
How do I fix this (or how to build it correcly)?

**Comment by bubba** [comment]
What version of `cabal`/`stack` do you have installed?
`stack --version` `cabal --version`

**Comment by TheRealC05** [comment]
```
$ stack --version
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0
```

**Comment by bubba** [comment]
Run `stack upgrade`, HIE currently requires stack 1.9.3 to build correctly

**Comment by bubba** [comment]
@TheRealC05 P.S let me know if that fixes it for you!

**Comment by TheRealC05** [comment]
It does
