### ISSUE TITLE
No package revision found for: PackageName "ghc"

### ISSUE THREAD

**Issue by mpilgrem** [haskell/haskell-ide-engine#1074]
I am on Windows 10, with HIE up to date to commit 239d07da8a3a7f80a4f0acef287256aae4cc2361 and trying to install HIE for GHC 8.6.2 with `stack --version` `Version 1.10.0, Git revision 48f4befb67860a24fc8c3310e6d55ace9fd35dfe (dirty) (6868 commits) x86_64 hpack-0.31.1`. Command
~~~~
stack --stack-yaml=stack-8.6.2.yaml install
~~~~
yields error:
~~~~
No package revision found for: PackageName "ghc"
CallStack (from HasCallStack):
  error, called at src/Stack\Build\ConstructPlan.hs:434:42 in stack-1.10.0-Gyq3czmxkWV9B1iWoXQn3F:Stack.Build.ConstructPlan
~~~~
I note that the only versions of the `ghc` package currently on Hackage are 8.2.1, 8.2.2, 8.4.1, 8.4.3, and 8.6.1 and this same error seems to occur only when trying to install HIE for versions of ghc not on Hackage (eg 8.4.2 or 8.4.4).

**Comment by bubba** [comment]
I'm not able to recreate this on stack 1.9.3, so we should probably take a look at this before stack 1.10 is released.
It is worth noting that the version of GHC on [stackage](https://www.stackage.org/lts-13.6/package/ghc-8.6.3) is more recent (8.6.3) than hackage, I'm not sure as to why this is though

**Comment by mpilgrem** [comment]
This was a `stack` problem that has now been fixed.
