### ISSUE TITLE
stack ./install.hs build-doc-8.6.3 is fail

### ISSUE THREAD

**Issue by waddlaw** [haskell/haskell-ide-engine#1075]
[Install specific GHC Version with Shake](https://github.com/haskell/haskell-ide-engine#install-specific-ghc-version-with-shake) is wrong instruction.

I get an error message:

```shell
$ stack ./install.hs build-doc-8.6.3
Error when running Shake build system:
* build-doc-8.6.3
Error, file does not exist and no rule available:
  build-doc-8.6.3
CallStack (from HasCallStack):
  error, called at src/Development/Shake/Internal/Rules/File.hs:180:58 in shake-0.16.4-LALOx6oztuyEhIGSKU1Pov:Development.Shake.Internal.Rules.File
```

`build-doc-8.6.3` is not exist.

**Comment by fendor** [comment]
The correct target is `build-doc-hie-8.6.3`.
Will fix this in the documentation since it is actually not even in the help message.

**Comment by waddlaw** [comment]
Thanks!
