### ISSUE TITLE
Add ids to commands

### ISSUE THREAD

**Issue by cocreature** [haskell/haskell-ide-engine#108]
We need a way to associate responses with requests since the communication is supposed to be async. We already have a counter internally but we don’t put that in the responses. Also I think the id should be provided by the IDE in the request instead of provided by us.

I propose that we wrap each response in something like

``` json
{"id": 1234,
  "content": {},
  "type": "typeresponse"}
```

The type can be used by the IDE to dispatch to the correct handler. It’s not essential since it could store the response it expects when it makes a request, but I imagine that for a lot of commands this would be the only thing it would need to store, so it’s nice to remove that burden by providing it on our side.

**Comment by alanz** [comment]
The dispatcher is put together to use an id.

It is up to the individual transport whether it manages the ids internally or exposes them to the IDE.

If the transport only ever operates in sync mode then there is no need to expose it.

But it could easily be added to `WireRequest` / `WireResponse` for the `JsonStdio` transport.
