### ISSUE TITLE
add to import list

### ISSUE THREAD

**Issue by shmish111** [haskell/haskell-ide-engine#1086]
The equivalent of
```
$> hsimport -m 'Control.Monad' -s 'when' SomeSource.hs
=> import Control.Monad (when)
```

**Comment by alanz** [comment]
Can you give some more context about what you are expecting here?

CodeAction suggestions need to happen based on some diagnostic coming from hie (which can be generated by a private plugin).

**Comment by alanz** [comment]
From the haskell-ide mailing list that is basically dead, @shmish111 writes

"I was having a look into the code to see how hard it would be to implement https://github.com/haskell/haskell-ide-engine/issues/1086 and I got stuck trying to understand CodeAction. With hsimport I want to have the option to add a symbol, that is the name of the function I want to import. Here is an example GHC error message:

    • Variable not in scope:
        readCreateProcessWithExitCode
          :: process-1.6.3.0:System.Process.Common.CreateProcess
             -> [Char] -> IO (ExitCode, String, String)
    • Perhaps you want to add ‘readCreateProcessWithExitCode’
      to the import list in the import of ‘System.Process’
      (src/Interpreter.hs:11:1-27).

In this case I want to construct 2 CodeActions, one that contains only System.Process and another that contains System.Process and readCreateProcessWithExitCode, how would I construct the second one?

Additionally, does ghc-mod return something extra than the ghc error message? I can't understand from https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/HsImport.hs#L135 where it is getting the "Perhaps you meant " part from since that isn't in the ghc error. In that case, how can I go about working out what this message looks like?"

**Comment by shmish111** [comment]
So currently if I write
```
lookupEnv "PATH"
```
and I don't have `System.Environment` in my imports list then HIE (in VSCode) gives me the option to add `import System.Environment`. Unfortunately unqualified imports suck so I want to do what GHC suggests and add `import System.Environment (lookupEnv)`. This is available in hsimport by filling in the `symbolName` see http://hackage.haskell.org/package/hsimport-0.8.8/docs/HsImport-Args.html#t:HsImportArgs

At the same time, some people might want to import unqualified so I think there should be 2 code actions, one with the symbol name and one without. Note that there can already be multiple actions, 1 for each module that (ghc-mod ?) suggests but for each one I guess we would then have 2.

It looks like hsimport can handle doing everything correctly, just need to expand the HIE functionality. Is HIE the only thing that needs to be modified? I think from my (complete noob) understanding that editor integrations won't need to change?

**Comment by alanz** [comment]
ghc-mod simply returns the GHC error messages, but bear in mind they may differ across GHC releases.

Also, take a look at the tests, this should be exercised there somewhere, else we must add a test to make it apparent.

And you can create as many code actions as you like from a given diagnostic.

**Comment by shmish111** [comment]
Yeah, I'm good with creating the many actions but how would I structure the possibility of having a symbol. i.e. if I add `symbolName :: Maybe T.Text` to https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/HsImport.hs#L47 will the generated json make sense to the IDE?

WRT the GHC error message, the error messages I see in my project don't seem to be parseable by https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/HsImport.hs#L135 so I don't get where they're coming from because HIE correctly provides the CodeActions.

**Comment by alanz** [comment]
All you have to work with in terms of identifying the symbol is the `Range` from

http://hackage.haskell.org/package/haskell-lsp-types-0.8.0.1/docs/Language-Haskell-LSP-Types.html#t:CodeActionParams

**Comment by shmish111** [comment]
So maybe I'm misunderstanding what happens here, as I understand it:

hie gets an error from ghc
this error is parsed and it produces `Just [CodeAction]` which in my case is some hisimport possibilities
these `CodeAction`s are sent to the editor
the user chooses on and this is sent back to HIE
HIE makes the change in this case by calling hsimport

Is that correct? In this case the editor does not need to do anything.

I don't get where `CodeActionParams` fits in?

**Comment by alanz** [comment]
It is close to that.

User changes the file, a diff is sent to hie.
Hie runs hlint, ghc-mod on the changed file, and sends the diagnostics from those to the client (vscode)
User moves through the file, and vscode sends a CodeActionRequest to hie, giving the current location (as a Range, typically the current line), and the existing diagnostics for that line.
Based on the request (Range, [Diagnostics]), each CodeActionProvider gets to calculate any code actions that may apply.
These get sent to the client, and presented to the user. The CodeActions typically have specific parameterisation in them to do the specific change, or could be a `WorkSpaceEdit` directly.
The user can choose to apply one, in which case the command is sent, or edit applied,

I give somewhat of an overview in my recent HaskellX talk, video at https://skillsmatter.com/skillscasts/12439-haskell-ide-support-via-lsp (login required)

**Comment by anonimitoraf** [comment]
In vscode, for typescript imports, if I go:
`import { <cursor here while opening intellisense> } from 'some-module`, intellisense opens up to suggest exposed members of 'some-module'. It would be nice to be able to go:
`import Control.Monad ( <cursor here while opening intellisense> )`

Is this related? Is this even possible to do?

**Comment by fendor** [comment]
This is not related to this issue, but an interesting feature anyway!
Dont know though, whether it is possible. (Probably?)

**Comment by anonimitoraf** [comment]
I'm quite a noob with haskell, but if you can point me into good starting points for implementing this feature (or good starting points in general for understanding hie), I'll try and do it.
