### ISSUE TITLE
GHC version support

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1087]
I am experimenting with the new cabal-helper / ghc-mod in https://github.com/alanz/haskell-ide-engine/tree/bleeding-edge-c-h

It uses `cabal-plan-0.5.0.0`.  Stack is unable to build this for GHC 8.2.1/8.2.2 because the Cabal bundled with the snapshot is 2.0.0.1 or something, and it does not understand the license field used in `cabal-plan-0.5.0.0`.

Not, it builds fine with `cabal new-build`, so long as it is version 2.4.1.0.

So, there are two options

1. When (eventually) this patch lands, drop support for GHC 8.2.x
2. Run a submodule of cabal-plan with the license changed.

I guess there is also

3. Request @hvr to move back to an older license format for `cabal-plan-0.5.0.0`.

Given the (not-so) imminent landing of GHC 8.8, I am leaning toward dropping support for GHC 8.2

Any opinions?

**Comment by hvr** [comment]
> it builds fine with cabal new-build, so long as it is version 2.4.1.0.

I don't think that's accurate. It's supposed to build as long as you have `cabal-2.2.x` or newer, which is far from being bleeding edge. 

> Request @hvr to move back to an older license format for cabal-plan-0.5.0.0.

While I understand that you're trying to workaround design flaws of Stack & Stackage with respect to its handling of the cabal spec, I don't think we should hold back everyone just to workaround limitations in Stack. This would set a very bad precedent.

**Comment by fendor** [comment]
Closed by #1430
