### ISSUE TITLE
Please write a script to uninstall hie completely and throuthly.

### ISSUE THREAD

**Issue by cwnevergg** [haskell/haskell-ide-engine#1089]
I don't know how to uninstall the engine completely, I want to reinstall hie totally,but I'm a noob. :(

**Comment by alanz** [comment]
Reinstalling will just overwrite the existing installation, so there is no need to uninstall first.

**Comment by cwnevergg** [comment]
> Reinstalling will just overwrite the existing installation, so there is no need to uninstall first.
Thanks
