### ISSUE TITLE
Make requires cabal executable to be in user path on macOS

### ISSUE THREAD

**Issue by faucct** [haskell/haskell-ide-engine#1095]
Hello. I am trying to build the HIE via `make build-all`, as the VS Code extension page says. My stack is installed from brew and `~/.local/bin` is not on my load path. The build fails on `cabal update`: it expects `cabal` to be on the load path. Is this something that should be fixed on my side?

**Comment by bubba** [comment]
@fendor Why does stack install Cabal-install, then Cabal-install install Cabal-install again? (bonus tongue twister)
https://github.com/haskell/haskell-ide-engine/blob/5b4f45c7a9f51378a1501e58455836f3c6d69f5b/install.hs#L140-L144

**Comment by fendor** [comment]
Cabal-2.4.1.0 is a library and is needed by `cabal-helper`, to read project information, I think, and speeds up the compilation process of HIE.
This is something I picked up from the Makefile and I can neither explain or prove it, though.

**Comment by fendor** [comment]
Regarding the question, while it is not the desired behaviour, you will need to add `$HOME/.local/bin` to the $PATH anyway, because we install the HIE executables to that path.
It might be sensible though to look whether `$HOME/.local/bin` is in the $PATH before attempting the installation.

**Comment by bubba** [comment]
@fendor ah I notice now that cabal is installing the libarary not the executable the second time round.

**Comment by Anrock** [comment]
Isn't `~/.local/bin` required to be in $PATH by Stack anyway?

**Comment by fendor** [comment]
Not required, but `stack install` won't do much without it
