### ISSUE TITLE
Executables not created when installing with Windows

### ISSUE THREAD

**Issue by mentoc3000** [haskell/haskell-ide-engine#1097]
I am trying to install hie on Windows 10.  I cloned the repository to C:\Git\haskell-ide-engine and ran the script .\build-all.ps1 with an admin instance of PowerShell.  The following error pops up for each version of ghc it installs:

```
cp : Cannot find path 'C:\hie.exe' because it does not exist.
At C:\git\haskell-ide-engine\build-all.ps1:37 char:5
+     cp "$stackbindir\hie.exe" "$stackbindir\hie-$version.exe"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\hie.exe:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

After the script is complete, no hie.exe or hie-wrapper.exe commands exist on the path, so cannot be used in VSCode.

I am using the following versions:
GHC: 8.4.3
stack: 1.7.1

**Comment by fendor** [comment]
First, upgrade stack with stack upgrade
afterwards, you can try to use install.hs via `stack install.hs build` to build hie for all ghc versions

**Comment by mentoc3000** [comment]
8.6.3 was the issue, it seems.  I set the resolver in stack.yaml to `ghc-8.6.2` and it compiles correctly.  Thanks!
