### ISSUE TITLE
Can't build specific hie version -- forces nightly resolver

### ISSUE THREAD

**Issue by pablox-cl** [haskell/haskell-ide-engine#1099]
I was trying to build a specific version as said in the documentation:

    $ make hie-8.4.3
    Preparing to install GHC (tinfo6) to an isolated location.
    This will not interfere with any system-level installation.
    Preparing to download ghc-tinfo6-8.6.3 ...

But it starts downloading, 8.6.3. This happens even when calling `make help`:

```
❯ make help
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-tinfo6-8.6.3 ...
```

I barely understand Makefiles, but trying to make any modification it still tried to download 8.6.3, so I don't understand why this is happening.

**Comment by pablox-cl** [comment]
Ok, I made an advance, sorry, problem is with lines 2 and 18 (`stack path --local-bin`). This happens because when those variables are being assigned, the `stack.yaml` is being used. Replacing the resolver there allows the Makefile to continue. 

I'm not sure, but I'm guessing this should be considered as a bug.

**Comment by fendor** [comment]
The fix would be to use `--stack-yaml shake.yaml` in addition to `stack path - -local-bin`
If I remember correctly, this will be fixed when #1092 has been merged.

**Comment by bubba** [comment]
I presume this will go away in #1033?

**Comment by fendor** [comment]
`stack install.hs hie-8.4.3` should no longer download a nightly resolver
however, there will still be two resolvers, one for install.hs and one to install the specific hie version
reopen if installation still forces a nightly resolver
