### ISSUE TITLE
Prelude.head: empty list

### ISSUE THREAD

**Issue by falsandtru** [haskell/haskell-ide-engine#1102]
Specifying incomplete language options such as `{-# LANGUAGE St #-}` makes an unrecoverable error.

```
2019-02-24 13:15:27.828573164 [ThreadId 13] - Using stack GHC version
Using hie version: Version 0.4.0.1, Git revision 337fd9bf6254b50820bfe73046353ae2c4f86b34 (dirty) (2315 commits) x86_64 ghc-8.6.3
Using hoogle db at: .../.hoogle/default-haskell-5.0.17.hoo
hie-8.6.3: Prelude.head: empty list
```

Ubuntu 18.04
VSCode
https://github.com/falsandtru/haskell-examples

**Comment by alanz** [comment]
Please update to current master, and try again. I am unable to reproduce this issue, and the completion infrastructure has been cleaned up in between, to prevent this sort of problem.

**Comment by falsandtru** [comment]
I updated but I saw another error which blocks reproducing.

```
Using hie version: Version 0.4.0.1, Git revision 337fd9bf6254b50820bfe73046353ae2c4f86b34 (dirty) (2315 commits) x86_64 ghc-8.6.3
Using hoogle db at: /home/abzu/.hoogle/default-haskell-5.0.17.hoo
hie-8.6.3: user error (Failed to find requested hint files:
  ~/.local/bin/data/hlint.yaml
)
```

**Comment by alanz** [comment]
When I run `hie --version` I get

```
$ hie --version
Version 0.6.0.0, Git revision ba4882488c12c77ce06230d71db46e10170e017a (2424 commits) x86_64 ghc-8.6.3
```

Your log file reports

```
Version 0.4.0.1, Git revision 337fd9bf6254b50820bfe73046353ae2c4f86b34 (dirty) (2315 commits) x86_64 ghc-8.6.3
```

So I suggest first checking out current master for `haskell-ide-engine`, running `./install.hs hie-8.6.3`, and then testing again, making sure the log file does show the appropriate version.

**Comment by falsandtru** [comment]
Thanks, I'll check it.

**Comment by falsandtru** [comment]
I understood. I'm certainly using the latest version but the VSCode extension for HIE uses another version.

```
$ hie --version
Version 0.6.0.0, Git revision ba4882488c12c77ce06230d71db46e10170e017a (dirty) (2424 commits) x86_64 ghc-8.6.3
```

I resolved by `make build-all`. `stack install` is wrong. It is suggested in the document (https://github.com/alanz/vscode-hie-server) and described as alternative but actually not alternative.

**Comment by falsandtru** [comment]
@alanz Your new command `./install.hs build-all` won't work.

https://github.com/alanz/vscode-hie-server#requirements

**Comment by alanz** [comment]
@falsandtru can show me what happens when you run that command?

**Comment by falsandtru** [comment]
```
$ ./install.hs build-all
/usr/bin/env: 'stack\r': No such file or directory
```

**Comment by falsandtru** [comment]
Your fixed command `stack install.hs` seems to work fine, thanks!

**Comment by bubba** [comment]
@fendor that `\r` looks like a carriage return, could that be messing up the hashbang?

**Comment by fendor** [comment]
Looks like it, but shouldnt git convert it automatically to `\n`?
Also, I dont think I ever commited code on windows. 
Moreover, I can not reproduce the problem on fedora, nixos, or windows... maybe git was configured on the user site to checkout code in windows line ending style?

**Comment by falsandtru** [comment]
I've enabled git autoctrf on Ubuntu. It might affect the installation.
