### ISSUE TITLE
HIE not found while installed on Manjaro by the Visual Studio Code HIE extension

### ISSUE THREAD

**Issue by ehouarn-perret** [haskell/haskell-ide-engine#1104]
When starting visual studio code with the hie extension, I got this error:
> hie executable missing, please make sure it is installed, see github.com/haskell/haskell-ide-engine.

However, I installed [hie via AUR](https://aur.archlinux.org/packages/haskell-ide-engine) (note: I am using Manjaro). 

When checking the path it seems that the hie is not present...
> `PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/perret/.dotnet/tools`

But when inspecting `/usr/bin` it seems that several versions are available:
- `hie-8.2.2`
- `hie-8.4.3`
- `hie-8.4.4`
- `hie-8.6.3`
- `hie-wrapper`

Which one should be exported to the `PATH` environment variable in my `.bashrc`?

**Comment by Anrock** [comment]
> Which one should be exported to the `PATH` environment variable in my `.bashrc`?
`hie-wrapper` and all `hie-x.y.z` you're gonna use. I.e. if you only have projects with ghc-8.6.3, then exporting only `hie-wrapper` and `hie-8.6.3` should be on path.

**Comment by ehouarn-perret** [comment]
@Anrock I just realized that `:/usr/bin` was already part of my `PATH`, am I supposed to alias one of the executables, to make it work?

**Comment by fendor** [comment]
According to the comment in the aur, some editors require `hie` to be on the path. Normally, this is a symlink to the most recent ghc version, e.g. Ghc 8.6.3.
if you install from source, e. g. `stack install.hs build` the executable is correctly generated.

**Comment by fendor** [comment]
Closing, since question answered
