### ISSUE TITLE
importModule always formats with brittany

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1115]
We now have formatProviders, but the `importModule` function always uses brittany if `formatOnImport` is enabled.

Rather use the configured formatter.

**Comment by fendor** [comment]
How are plugins supposed to access other plugins? Currently, it doesnt seem possible.

**Comment by lorenzo** [comment]
I think we are doing this incorrectly, we should maybe follow lead of what other languages' tooling are doing. I for instance like what Golang does: whenever you automatically insert an import, the whole of the import section gets automatically formatted.

We should probably do that: find the range of text were all the imports are and format that range with the chose formatter. We could expose a custom action from hie to format imports and use the custom action from any plugin inserting stuff into that section of code.

**Comment by fendor** [comment]
This is what I am currently trying to do. 
The problem I am currently facing is, that the type 
```haskell
type FormattingProvider = Uri -> FormattingType -> FormattingOptions -> IdeDeferM (IdeResult [TextEdit])
```
Can not be easily called within a `IdeGhcM`

**Comment by lorenzo** [comment]
I meant doing something like this: https://github.com/haskell/haskell-ide-engine/pull/889/files#diff-df7cc8b4c1792382d5165b401f9ba6d0R536

The `ghcmod` plugin instructs the client to request an action from the `hare` plugin. We could do the same here. Just build and action for formatting the range, and the right formatter will be used

**Comment by lorenzo** [comment]
@fendor maybe don't listen to me too much, I thought that lien was instructing the client to execute something, but it seems like the user still needs to select the action to be executed.
