### ISSUE TITLE
./install.hs build is not idempotent

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1116]
For current master (tag 0.7.0.0), on Debian Testing, if I run `./install.hs build` repeatedly, it copies the pre-build versions of all except for GHC 8.6.2, which it rebuilds every time, saying that `temporary` is not installed.

See https://gist.github.com/alanz/ffe5c4c0fa1b3fe79a3e2183dd033082

**Comment by alanz** [comment]
cc @fendor

**Comment by fendor** [comment]
Is fixed by setting the resolver in `shake.yaml` to something different to the other `stack-*.yaml` files.
What would be a sensible resolver? I think we would only download a different snapshot, thus, no ghc is downloaded twice.

**Comment by alanz** [comment]
What is the cause of it, if that is the fix? Seems odd to me.

**Comment by fendor** [comment]
`temporary` is an extra dep in `stack-8.6.2.yaml` and not in `shake.yaml`. In the latter, a different version of temporary is needed, thus, the respective temporary package is unregistered.
`shake.yaml` is currently being used to install `cabal-install`, to avoid that a nightly resolver is being used.

**Comment by alanz** [comment]
ok, so making sure that we use the same version of temporary for both should sort out the problem? Perhaps we should check if we already have one that does not override it, or set `shake.yaml` to have the override too.

**Comment by fendor** [comment]
That would increase the compilation time of the shake file even more.
But yes, we could use the same extra deps everywhere

**Comment by fendor** [comment]
I think, choosing a different resolver is faster and more efficient than trying to sync up the dependencies between any `stack-*.yaml` and `shake.yaml`.

**Comment by fendor** [comment]
@alanz Can you check if this really fixes the issue?

**Comment by fendor** [comment]
Fixed on windows and nixos, at least.

**Comment by alanz** [comment]
@fendor I can confirm it works for me. Thanks.
