### ISSUE TITLE
Installation copies cabal-install binary to my $PATH

### ISSUE THREAD

**Issue by hpdeifel** [haskell/haskell-ide-engine#1119]
I already have a cabal-install in PATH, ain't nobody needs two cabal-installs.

Now seriously: I have exactly the version of cabal-install installed that I want
to use in the command line. It's fine if stack/hie want to use another one, but
then it should probably install that to a private directory and set its own PATH
as needed.

**Comment by fendor** [comment]
#1168 will partly tackle that, e.g. If the installed version is new enough, it will be used.

**Comment by fendor** [comment]
Now the version on the path will be used if possible!
