### ISSUE TITLE
Replace logging package

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#112]
At the moment the logging has issues with not flushing if the exe is killed, and brings in `pcre` which complicated windows/mac installs.

Replace it with something else, or roll our own.

**Comment by cocreature** [comment]
I've used [monad-logger](https://hackage.haskell.org/package/monad-logger) in the past and was quite happy with it. It also has nice template haskell logging functions which insert the file and the line it was called from in the log message which is pretty nice for debugging.

**Comment by alanz** [comment]
Sounds good.

**Comment by rvion** [comment]
fwiw,
+1 on removing pcre deps
+1 on using monad-logger

**Comment by mgsloan** [comment]
+1 on monad-logger

**Comment by alanz** [comment]
I think we can use [fast-logger](https://hackage.haskell.org/package/fast-logger) directly, instead of the version wrapped in `monad-logger`.

**Comment by bergey** [comment]
The TH line numbers are only in `monad-logger` right?

**Comment by alanz** [comment]
I think so.  I was considering taking the simple approach and just
taking the source for `withStdoutLogging` and `withFileLogging` and
using it over fast-logger .

This has the advantage that logging is available in the plugins too,
without having to specifically expose the `IdeM` monad.

I guess we can just add `MonadLogger` to the context of the `CommandFunc`s.

**Comment by alanz** [comment]
@bergey I was just looking at this in more detail.

See https://github.com/haskell/haskell-ide-engine/blob/master/app/MainHie.hs#L96, which effectively ensures that a logging session is active for the life of the program.

The `Control.Logging` approach sets up an IORef with the logger details, once it is set up it can be accessed by any of the threads anywhere in the system

We know we are going to end up in a multi-threaded environment, off the bat we run a transport thread and a dispatcher thread, and the `AsyncCommandFunc` type exists to enable plugins to run multiple threads.

So an IORef based logging system rather than a monad transformer stack may be a good idea.

I suspect we will be able to use the log functions from `Control.Monad.Logger` by setting up the appropriate instances to call the IORef based functions.
