### ISSUE TITLE
Can't define multiple tests

### ISSUE THREAD

**Issue by falsandtru** [haskell/haskell-ide-engine#1121]
`stack test` makes no error but hie make errors with tests.

```
Could not load module ‘Test.Hspec’
It is a member of the hidden package ‘hspec-2.6.1’.
Perhaps you need to add ‘hspec’ to the build-depends in your .cabal file.
Use -v to see a list of the files searched for.
```

https://github.com/falsandtru/haskell-examples/blob/master/basic/test/LibSpec.hs

**Comment by falsandtru** [comment]
Accidentally fixed in debugging. Seems like Stack has unexpected side-effects.

**Comment by WillSewell** [comment]
> Seems like Stack has unexpected side-effects.

Could you explain what you mean by this in more detail please?

**Comment by falsandtru** [comment]
This problem was fixed by rebuilding. Probably this is a problem of build cache management.
