### ISSUE TITLE
Build fails on Mac

### ISSUE THREAD

**Issue by aztecrex** [haskell/haskell-ide-engine#1122]
Both `make build` and `./install.hs build` fail on MacOS 10.13.6 with:

```
Installing internal library hie-test-utils in /Users/gwiley/Working/haskell-ide-engine/.stack-work/install/x86_64-osx/lts-13.9/8.6.3/lib/x86_64-osx-ghc-8.6.3/haskell-ide-engine-0.7.0.0-3sOQ9JBLHrebYyOs7aKpj-hie-test-utils
Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3: Error: Could not find module:
TestUtils with any suffix: ["hi"] in the search path:
[".stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/hie-test-utils"]
```

Just cloned the source last night. Tried deleting `.stack-work` and `stack clean`-ing the project. Same result followed.

**Comment by bubba** [comment]
This looks like a bug with older versions of stack: does running `stack upgrade` fix it?

**Comment by antonlogvinenko** [comment]
@aztecrex I've recently encountered the same problem on MacOS. I did `stack upgrade` as @bubba suggested above; now following commands build HIE successfully:
`stack ./install.hs hie-8.6.3`
`stack ./install.hs build-doc-8.6.3`

**Comment by bubba** [comment]
I presume this is the same issue, so I’ll close it now, feel free to reopen!

**Comment by aztecrex** [comment]
confirmed works with updated stack

**Comment by maruks** [comment]
yes, it does
stack --version
Version 1.9.3
