### ISSUE TITLE
Windows Installation Fails with 'cabal: createProcess does not exist.'

### ISSUE THREAD

**Issue by andersyr** [haskell/haskell-ide-engine#1127]
On windows I followed the README.md installation instructions: Downloaded current versions of Git, Stack, and Shake. Applied the optional Win32 Long Paths. Cloned HIE, executed stack ./install.hs hie-8.6.3 and received the below error. Any help is appreciated as I'm quite unfamiliar with HIE and Shake.

```
...   --Prior install messages omitted for GitHub issue post.
cabal-install-2.4.1.0: copy/register
Completed 15 action(s).
Copying from C:\sr\snapshots\96a45ff6\bin\cabal.exe to C:\Users\Kaz\AppData\R-
oaming\local\bin\cabal.exe

Copied executables to C:\Users\Kaz\AppData\Roaming\local\bin:
- cabal.exe
# cabal (for cabal)
Warning: The update command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-update command
or the legacy v1-update alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal update --index-state='2019-03-06T21:33:39Z'
# cabal (for cabal)
Error when running Shake build system:
  at src/Development/Shake/Internal/Args.hs:81:69-79:
* Depends on: hie-8.6.3
  at install.hs:94:9-23:
* Depends on: cabal
* Raised the exception:
cabal: createProcess: does not exist (No such file or directory)
```
Cabal (version 2.4.1.0)
Stack (version 1.9.3)
Shake (version 0.17.6)
HIE (version 0.7.0.0-18-g26b0c16e)     --Found using `git describe --tags` in haskell-ide-engine folder.
Most recent HIE commit: 26b0c16e79f62c5eccdbff2b22f9a0915f46fead

**Comment by fendor** [comment]
You probably have to add `C:\Users\Kaz\AppData\Roaming\local\bin` to your `PATH`.
Stack installs executabels into this directory and it needs to find these executables again. I think, there is a notice about it in the README.

**Comment by andersyr** [comment]
Thanks for the quick reply. I was curious about that earlier as well. Windows shows it in my `PATH` environment under System Properties > Environment variables.

**Comment by Anrock** [comment]
Be aware of #1008. You won't be able to build it anyway.

**Comment by andersyr** [comment]
Ah, my apologies for missing that. I just finished setting up 8.6.2 and everything is working splendidly. Thanks a bunch for the assistance! =) Cheers
