### ISSUE TITLE
How do I install packages for HIE compilation?

### ISSUE THREAD

**Issue by steve3p0** [haskell/haskell-ide-engine#1138]
Hello, 
This might be more of a cabal/stack question, but how do I install additional Haskell packages that my code imports?  I have no idea how to do this?

Also, how do you keep the HIE packaging synched between HIE debugging and your IDE Haskell version?

Thanks, 
Steve

**Comment by Anrock** [comment]
> how do I install additional Haskell packages that my code imports?
`stack build` will install them automatically. Same for cabal. Read https://docs.haskellstack.org/en/stable/README/ and https://www.haskell.org/cabal/

I didn't understand your second question

**Comment by steve3p0** [comment]
2nd question: (sorry for my incompetence here)

It looks like my IDE, Visual Studio Code is using one version of Haskell, the binaries distributed with GHCi, to run Haskell code without debugging, and it is using HIE to debug.  

Is that the way it's supposed to be?

I have a 'play' button in Visual Studio Code which is shown in the upper right hand corner of each Haskell .hs file.  When I click this, my .hs is run (without debugging), and I get no errors.  

However, when I open up the debug panel, and click the play button there, I believe it's using HIE and it is there where I get compile errors for additional modules I am trying to use (import Test.Framework).

Below are the errors I get when trying run with debugging.  NOTE: I installed HTF (Haskell Test Framework using 'cabal install HTF').  I don't get any errors when I run without debugging.

`CWD: C:\workspace_courses\gf_steve3po\gf-rgl\tests 
CMD: stack ghci --test --no-load --no-build --main-is foobar --ghci-options -fprint-evld-with-show 


Note: No local targets specified, so a plain ghci will be started with no package hiding or package
      options.
      
      If you want to use package hiding and options, then you can try one of the following:
      
      * If you want to start a different project configuration
        than C:\sr\global-project\stack.yaml, then you can use stack init to create a new stack.yaml
        for the packages in the current directory. 
        
      * If you want to use the project configuration
        at C:\sr\global-project\stack.yaml, then you can add to its 'packages' field.
      
Configuring GHCi with the following packages: 
GHCi, version 8.6.4: http://www.haskell.org/ghc/  :? for help
Prelude>:set prompt "H>>= "
 H>>= :set prompt-cont "H>>= "
H>>= :load C:/workspace_courses/gf_steve3po/gf-rgl/tests/run.hs
[1 of 1] Compiling Main             ( C:\workspace_courses\gf_steve3po\gf-rgl\tests\run.hs, interpreted )

C:\workspace_courses\gf_steve3po\gf-rgl\tests\run.hs:7:1: error:
    Could not find module `Test.Framework'
    Use -v to see a list of the files searched for.
  |
7 | import Test.Framework hiding ( runTest )
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

C:\workspace_courses\gf_steve3po\gf-rgl\tests\run.hs:8:1: error:
    Could not find module `Test.Framework.TestManager'
    Use -v to see a list of the files searched for.
  |
8 | import Test.Framework.TestManager ( makeBlackBoxTest )
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

C:\workspace_courses\gf_steve3po\gf-rgl\tests\run.hs:9:1: error:
    Could not find module `Test.Framework.TestTypes'
    Use -v to see a list of the files searched for.
  |
9 | import Test.Framework.TestTypes ( Test )
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

C:\workspace_courses\gf_steve3po\gf-rgl\tests\run.hs:10:1: error:
    Could not find module `Test.Framework.BlackBoxTest'
    Use -v to see a list of the files searched for.
   |
10 | import Test.Framework.BlackBoxTest ( defaultDiff )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed, no modules loaded.
H>>= :module + *Main

<no location info>: error:
    Could not find module `Main'
    It is not a module in the current program, or in any known package.
H>>= :break Main 62

<no location info>: error:
    Could not find module `Main'
    It is not a module in the current program, or in any known package.
H>>= :set -fno-break-on-exception
H>>= :set -fno-break-on-error
H>>= 

  Now, ghci launched and configuration done.
  Press F5 to start debugging.
  Or modify source code. it will be loaded to ghci automatically.
 
H>>= :trace main

<interactive>:8:1: error:
    * Variable not in scope: main
    * Perhaps you meant `min' (imported from Prelude)
H>>= :quit
Leaving GHCi.
ExitSuccess


`

**Comment by steve3p0** [comment]
OK, I created my Haskell project using 'stack new projectname', but when I open up my workspace in Visual Studio Code, I get this warning message:

```
Mismatching GHC versions: Project is Active code page: 65001
8.6.4, HIE is 8.6.4
You may want to use hie-wrapper. Check the README for more information
```

**Comment by steve3p0** [comment]
Thank you very much for your help and pointing me in the right direction.  I am reading up on stack now and making some progress.

I do have a question:

- I am supposed to put import module dependencies in the dependencies section of the project's stack.yaml file.  I have done that for some of the libraries and that's cleared up some of the "Could not find module XXX" errors.  It's not exactly intuitive on what the name of the dependency should be. I don't know what name the stack.yaml file expects for "Test.Framework" in the dependency section.  The Haskell Test Framework doesn't provide any guidance either.

Here are my remaining imports that are still getting errors:

```
import Test.Framework hiding ( runTest )
import Test.Framework.TestManager ( makeBlackBoxTest )
import Test.Framework.TestTypes ( Test )
import Test.Framework.BlackBoxTest ( defaultDiff )
import Test.HUnit ( assertFailure )
```

Any help resolving this is greatly appreciated.

Steve

**Comment by Anrock** [comment]
> I am supposed to put import module dependencies in the dependencies section of the project's stack.yaml file

You should put dependencies in corresponding section of your `projectname.cabal` file. Stack then will read it, determine what exact versions are suitable according to `resolver` set and download them. In case specified dependency isn't in stackage, stack will print an instruction on how to add the package to `extra-deps`.
So generally in `stack.yaml` you only need three fields: 
* `resolver` - specifies the set of packages `stack` will use to resolve dependencies of your project
* `packages` - specifies path to the package you're developing, most of the it's just `.`
* `extra-deps` - list of dependencies that aren't in `resolver` set, but you still want to use in your project, most of the time it's empty `[]`.

>  It's not exactly intuitive on what the name of the dependency should be

There is special search engine for haskell, called Hoogle. You can use it to find info on modules, packages, functions, types, etc.
If you're using stack for development, then open https://www.stackage.org/, click on resolver you're using (lower left) and it will take you to Hoogle search that searches over packages that are in this resolver.
For example, you mentioned that test **package** is called HTF. Then [query](https://www.stackage.org/lts-13.13/hoogle?q=is%3Apackage+htf) is `is:package HTF`.
If you don't know what package name is but you know a **module** name in it you can try searching for it like [this](https://www.stackage.org/lts-13.13/hoogle?q=is%3Amodule+Test.Framework.TestManager): `is:module Test.Framework.TestManager`.

Both queries yield only one result which is `HTF` package.

I recommend you visit [some haskell channel in IRC](https://www.haskell.org/irc/) or discord. Probably you will get help better and faster there then in HIE-specific bugtracker.

**Comment by steve3p0** [comment]
Thanks Anrock!  I eventfully figured most of this out, painfully.  I was thinking of using IRC.  I should have!  I've spent way too much time doing config.

It's funny you mention Hoogle.  Haskell Docs is the last piece I need to finishing integrating with Visual Studio Code.

Cheers!
