### ISSUE TITLE
Mismatched GHC versions

### ISSUE THREAD

**Issue by steve3p0** [haskell/haskell-ide-engine#1139]
Can someone briefly explain to where Visual Studio Code is getting the path for the Haskell compiler to run code (without debugging)?

I'm not talking about HIE.  Sorry, if this is a stupid question, but I have this mismatch, and I can't even find where and how Visual Source Code is launching the Haskell compiler.

I do know where HIE is set for debugging.

![image](https://user-images.githubusercontent.com/33675736/54487159-7f7c9c80-484f-11e9-9192-556f72ad201d.png)

`Mismatching GHC versions: Project is Active code page: 
65001 8.6.3, HIE is 8.6.4 You may want to use hie-wrapper. 
Check the README for more information
`
Thanks, 
Steve

**Comment by Anrock** [comment]
Probably it just reads `resolver` from `stack.yaml` and then tries to use GHC that correspond to that resolver. You should either change resolver so corresponding GHC is matching HIE or build a HIE that matches GHC in selected resolver and setup hie-wrapper using instructions in README.
