### ISSUE TITLE
HTTP endpoints given in doc and comments are not working

### ISSUE THREAD

**Issue by rvion** [haskell/haskell-ide-engine#114]
both https://github.com/haskell/haskell-ide-engine/blob/f99b6f520856c9f4230234d06bb8185bdabc484a/src/Haskell/Ide/Engine/Transport/JsonHttp.hs#L38 and https://github.com/haskell/haskell-ide-engine/blob/f99b6f520856c9f4230234d06bb8185bdabc484a/docs/Hacking.md seems to refer to an old implementation of the http rest interface.

``` shell
curl -v http://localhost:8081/req/base -X POST -H Content-Type:application/json --data-binary '{"ideParams":{},"ideCommand":"version","ideContext":{"ctxEndPos":null,"ctxCabal":null,"ctxStartPos":null,"ctxFile":null}}'
```

gives 

``` shell
invalid request body: key "command" not present%
```

**Comment by rvion** [comment]
also, after several iterations trying to fix the query, the error message seems "wrong" and not really helpfull

```javascript
 {"fail":{"msg":"need `file` parameter","code":"MissingParameter","info":"file"
```

but I tried to put file param everywhere:
```js
{
  "params":{

  },
  "command":"lint",
  "file":"/Users/rvion/dev/ride/src/Main.hs",
  "context":{
    "ctxEndPos":null,
    "ctxCabal":null,
    "ctxStartPos":null,
    "file":"/Users/rvion/dev/ride/src/Main.hs"
  },
  "ideContext":{
    "ctxEndPos":null,
    "ctxCabal":null,
    "ctxStartPos":null,
    "file":"/Users/rvion/dev/ride/src/Main.hs"
  },
  "msg":{
    "ctxEndPos":null,
    "ctxCabal":null,
    "ctxStartPos":null,
    "file":"/Users/rvion/dev/ride/src/Main.hs"
  }
}
```

**Comment by rvion** [comment]
and code is not helping me much here: https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Transport/JsonHttp.hs since I haven't play with servant yet

**Comment by rvion** [comment]
when I
```shell
curl -v http://localhost:4005/req/ghcmod \
  -X POST -H Content-Type:application/json --data-binary \ '{"params":{"file":"/Users/rvion/dev/ride/src/Main"},"command":"lint"}'
```

the error message becomes
```shell
invalid request body: empty%
```

**Comment by cocreature** [comment]
This is not really a problem with servant, but more a problem with our json being strange and the most important problem: undocumented. The json needs to look like this: `{"command": "lint", "params": {"file": {"file": "/home/moritz/code/haskell/playground/src/Main.hs"}}}`. The extra "file" comes from the type, see `ParamValP`. I don’t particularly care how the format looks like, so I’ll leave the discussion if we want/need this to other people.

For the documentation part, I was planning to add autogenerated documentation containing example requests and example responses for each command. Autogenerated being important here, since this is the only way to avoid it getting out of date. I’m not sure when I’ll find time, so if anybody else wants to give it a shot, go for it.

**Comment by cocreature** [comment]
Also for the servant case we should go for `req/plugin/command` instead of putting the command in as a parameter. Then we can drop the params field and just make a map containing the params.

**Comment by rvion** [comment]
Thanks for the explanation !

as a side observation, if the file specified doesn't exists, the server dies silently and all subsequent request are lost.

This command never finish and I have to stop it (^C)
```shell
haskell-ide-engine git:(foo) ✗ curl -v -H "Content-Type: application/json" -X POST -d '{"command": "lint", "params":{"file":{"file":"/Users/rvion/dev/ride/src/MainPLOP.hs"}}}' http://localhost:4005/req/ghcmod

*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4005 (#0)
> POST /req/ghcmod HTTP/1.1
> Host: localhost:4005
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 87
>
* upload completely sent off: 87 out of 87 bytes

^C
```

hie complains that
```
2015 Nov-29 20:22:17.599864 [INFO] doDispatch:req=IdeRequest {ideCommand = "lint", ideParams = fromList [("file",ParamValP {unParamValP = ParamFile "/Users/rvion/dev/ride/src/MainPLOP.hs"})]}
hie: Couldn't find file: /Users/rvion/dev/ride/src/MainPLOP.hs
```

Here is an other command with a correct filename (and a timeoutlimit:
```shell
➜  haskell-ide-engine git:(bar) ✗ haskell-ide-engine git:(foo) ✗ curl -v -m 10 -H "Content-Type: application/json" -X POST -d '{"command": "lint", "params":{"file":{"file":"/Users/rvion/dev/ride/src/Main.hs"}}}' http://localhost:4005/req/ghcmod

*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4005 (#0)
> POST /req/ghcmod HTTP/1.1
> Host: localhost:4005
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 87
>
* upload completely sent off: 87 out of 87 bytes
* Operation timed out after 10000 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
```

but I get no response back, and hie do not output anything

**Comment by cocreature** [comment]
Yeah our error handling is pretty much non existent :)
10s seems fairly long, does it also take that long if you send it via stdio?

**Comment by rvion** [comment]
the 10 second timeout is because of the `-m 10` curl option. If not specified, curl just don't return (or maybe it does, but not before `too long for me to wait`) :)

I don't really know how the stdio transport layer work, didn't try it yet. I'll reply to this thread when I'll spend some time playing with it.

**Comment by cocreature** [comment]
Is there anything left to do here?

**Comment by alanz** [comment]
Supersed by move to LSP
