### ISSUE TITLE
error with `readCreateProcess`

### ISSUE THREAD

**Issue by andrewufrank** [haskell/haskell-ide-engine#1144]
I have seen the error msg others have seen before but none of the explanations seem to apply. I found that I had two cabal executables on my search path, one on `.local/bin` and the other on `.cabal/bin`. This seems to have confused `ghc-mod`. Deleting one of the two helped. 

I use  `Version 0.7.0.0 (2487 commits) x86_64 ghc-8.6.4` with ghc 8.6.44 and cabal-2.4.1.0 (on linux debian butcher).

**Comment by power-fungus** [comment]
@andrewufrank do you know which command failed? I would like to try to repeat your issue.

**Comment by andrewufrank** [comment]
I run vs code and hie runs there to run something like `stack build --configure-only .` (from memory). 
The complete error msg was 
```
{
	"resource": "/home/frank/Workspace8/ssg/Lib/ReadSettingFile.hs",
	"owner": "Haskell HIE (ssg)",
	"severity": 8,
	"message": "readCreateProcess: /home/frank/Workspace8/fromOthers/haskell-ide-engine/.stack-work/install/x86_64-linux-tinfo6/lts-13.12/8.6.4/bin/cabal-helper-wrapper \"--with-ghc=/home/frank/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.4/bin/ghc\" \"--with-ghc-pkg=/home/frank/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.4/bin/ghc-pkg\" \"--with-cabal=cabal\" \"v1-style\" \"/home/frank/Workspace8/ssg\" \"/home/frank/Workspace8/ssg/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1\" \"package-db-stack\" \"flags\" \"compiler-version\" \"ghc-merged-pkg-options\" \"config-flags\" \"non-default-config-flags\" \"ghc-src-options\" \"ghc-pkg-options\" \"ghc-lang-options\" \"ghc-options\" \"source-dirs\" \"entrypoints\" \"needs-build-output\" (exit 1): failed\n",
	"source": "ghcmod",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}

but I had not the impression, this is helpful.
```

**Comment by power-fungus** [comment]
`cabal-helper-wrapper` is werid. Could you execute the command `hie` tried to execute?
```
/home/frank/Workspace8/fromOthers/haskell-ide-engine/.stack-work/install/x86_64-linux-tinfo6/lts-13.12/8.6.4/bin/cabal-helper-wrapper "--with-ghc=/home/frank/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.4/bin/ghc" "--with-ghc-pkg=/home/frank/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.4/bin/ghc-pkg" "--with-cabal=cabal" "v1-style" "/home/frank/Workspace8/ssg" "/home/frank/Workspace8/ssg/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output"
```
The output of this command might uncover the real issue

**Comment by andrewufrank** [comment]
the command was `stack build --only-configure .` and I had the same error msg (on a different installation) and tried it running in a terminal. This time, the cause was a problem with having two cabal files somewhere in the dependencies and extra dependencies. The output from the stack command was informative - perhaps HIE should just forward the error message from stack?  
i did reconstruct my previous situation with two cabal executables (perhaps not perfectly, as one was just a copy of the other, whereas before they were produce likely one by cabal and one by stack) and got the error in HIE but the stack command run fine - seems to be a different bug, with the same outcome.

**Comment by andrewufrank** [comment]
I have a similar error again: 

`got error while processing diagnostics: readCreateProcess: /home/frank/localinstall/haskell-ide-engine/.stack-work/install/x86_64-linux/lts-13.12/8.6.4/bin/cabal-helper-wrapper "--with-ghc=/usr/bin/ghc" "--with-ghc-pkg=/usr/bin/ghc-pkg" "--with-cabal=cabal" "v1-style" "/home/frank/Workspace8/4lit/jsonld4hs" "/home/frank/Workspace8/4lit/jsonld4hs/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output" (exit 1): failed`

when I run the same command in a terminal, I get the error

`cabal-helper-wrapper: /home/frank/Workspace8/4lit/jsonld4hs/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup-config: openFile: does not exist (No such file or directory)`

and the file is indeed not present. A similar file was created in the directory `Cabal-2.2.0.1`. I cannot understand why it searches for 1.24.2.0?

Perhaps this helps?

**Comment by fendor** [comment]
We are no longer using the wrapper, so this issue is no longer applicable! 
Note the new section of the readme about project configuration: https://github.com/haskell/haskell-ide-engine#project-configuration

**Comment by andrewufrank** [comment]
thank you for the improvement and the detailed explanations!
