### ISSUE TITLE
New install.sh builds hie-8.6.3 on Windows... and fails

### ISSUE THREAD

**Issue by bscottm** [haskell/haskell-ide-engine#1155]
Might want to either comment it out or make it a platform-dependent addition to the list of versions compiled.

BTW: Would also be handy to have a script that can execute the build, at least on Windows.

**Comment by fendor** [comment]
GHC 8.6.3 does not work on windows, see #1008 

What do you mean with script? It is possible to execute the install.hs with `stack install.hs hie-8.6.4`, for example.

**Comment by fendor** [comment]
You mean, since GHC 8.6.3 does not work on windows, there should be a check/warning for it?

What kind of script? You can execute `install.hs` with `stack install.hs`.

**Comment by jneira** [comment]
Maybe the script (`install.cmd`) could be simply:
```
stack install --stack-yaml=stack-8.6.2.yaml
```
... cause afaik it is the last stack config that works in windows.

In general, it could be a place to put the hacks to install it in windows with the least possible friction for users.

**Comment by Anrock** [comment]
@jneira Pls no additional platform-dependant scripts. We just recently merged a PR that deleted 3 of them, because synchronizing them is a pain and most of active devs don't have windows to test.

Put everything build-related into `install.hs`. Proper fix for this would be an exception for Windows for 8.6.3 target that just bails early with error message, just nobody implemented it.

> ... cause afaik it is the last stack config that works in windows.
Nope, latest is 8.6.4.

**Comment by jneira** [comment]
> @jneira Pls no additional platform-dependant scripts. We just recently merged a PR that deleted 3 of them, because synchronizing them is a pain and most of active devs don't have windows to test.

sorry for being late to the party but the project is being built with appveyor in windows, right? the script could be tested with it automatically, including a smoke test executing hie-wrapper with no error output.

sorry if it is obvious but what were the caveats to sync it?

it would be great to get a balance between user and dev experience 

> Nope, latest is 8.6.4.

In windows 10 it works but it doesnt for me in windows 7 ( see https://github.com/haskell/haskell-ide-engine/issues/1008#issuecomment-479774564)

**Comment by jneira** [comment]
@Anrock never mind, `install.hs` could be the right place to do the windows handling as you can get with it almost the same behaviour of a cmd script

**Comment by power-fungus** [comment]
I am currently in the process of reviewing the install-script. What feature exactly is requested here?

**Comment by alanz** [comment]
@power-fungus if the build platform is windows, building the `hie-8.6.3` target should print out a warning, not build the target, but not error out, so the rest of the targets still get built.

**Comment by fendor** [comment]
Should be very similar to implement as using cabal new-install on windows.

**Comment by power-fungus** [comment]
I will tackle this issue in #1168.

**Comment by fendor** [comment]
Now version 8.6.3 will no longer be installed on windows.
