### ISSUE TITLE
stack install.hs hie-8.4.4 installs ghc-8.6.2 and ghc-8.6.4 compilers as well

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#1159]
And 3 respective snapshots: lts-12.26,  lts-13.12, nightly-2018-12-15.

I think that at least one of the 2 "extra" snapshots/ghcs can be eliminated.

**Comment by jneira** [comment]
As a side note, `stack script` does not use `.stack/config.yaml` so it reinstalls `ghc-8.6.2` in the default `local-programs-path` if you have change it to other location in the config. 
Hopefully it seems it is going to honour it: https://github.com/commercialhaskell/stack/issues/3887#issuecomment-478650724

**Comment by nponeccop** [comment]
@jneira apparently the stack bug is already closed. Can you recheck with stack-git?

**Comment by jneira** [comment]
Of course, i've just downloaded the artifacts of build here: https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=1170
and it honours my user config file. 👍

**Comment by fendor** [comment]
Yes, normally only one additional snapshot should be required. 
The PR #1168 may address this problem.

**Comment by nponeccop** [comment]
It isn't merged as of April 20

**Comment by fendor** [comment]
Should be fixed now, please check!

**Comment by bubba** [comment]
On a related note, is it possible to use 
`system-ghc: true` in shake.yaml to avoid stack having to download another snapshot/compiler? Assuming that install.hs is backwards compatible with other versions of ghc?

**Comment by fendor** [comment]
Possibly yes. @power-fungus?

**Comment by power-fungus** [comment]
I will test that. What happens if there is nö system-ghc

**Comment by fendor** [comment]
Afaik, it errros out.

**Comment by nponeccop** [comment]
> Should be fixed now, please check!

works for me

**Comment by Avi-D-coder** [comment]
Can the shake `resolver` be bumped to `nightly-2019-04-30` so that it's in sync with `stack.yaml`?

Have the issues with 8.6.3 on windows been fixed for 8.6.5?

**Comment by fendor** [comment]
The issue of 8.6.3 ist fixed on 8.6.4 already. At least, I can build hie 8.6.4 on windows.

Regarding bumping shake-resolver, in general, there is no problem with that, in general. We can open a new issue for that.

**Comment by fendor** [comment]
I opened an issue for bumping the shake resolver #1266.
