### ISSUE TITLE
stack install.hs cabal fails

### ISSUE THREAD

**Issue by arrowd** [haskell/haskell-ide-engine#1160]
I'm running `stack install.hs cabal` on FreeBSD and get the following output:

```
┌─[arr]─[/home/arr/projects/haskell-ide-engine]──╼
└──╼ % stack ./install.hs cabal 
# stack (for cabal)
# stack (for cabal)
Copying from /usr/home/arr/.stack/snapshots/x86_64-freebsd-ino64/nightly-2018-12-15/8.6.2/bin/cabal to /usr/home/arr/.local/bin/cabal

Copied executables to /usr/home/arr/.local/bin:
- cabal

Warning: The cabal executable found on the PATH environment variable is /usr/home/arr/.stack/snapshots/x86_64-freebsd-ino64/nightly-2018-12-15/8.6.2/bin/cabal and not the version that was just
         installed. This means that cabal calls on the command line will not use this version.
# cabal (for cabal)
Warning: The update command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-update command
or the legacy v1-update alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
# cabal (for cabal)
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
cabal: There is no package named 'Cabal'.
You may need to run 'cabal update' to get the latest list of available
packages.

Error when running Shake build system:
  at src/Development/Shake/Internal/Args.hs:81:69-79:
* Depends on: cabal
* Raised the exception:
user error (Development.Shake.command_, system command failed
Command: cabal install Cabal-2.4.1.0 --with-compiler=/usr/home/arr/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.3/bin/ghc
Exit code: 1
Stderr:
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
cabal: There is no package named 'Cabal'.
You may need to run 'cabal update' to get the latest list of available
packages.

)

```

The warning message about PATH seems unrelated and harmless, but

> No remote package servers have been specified

seems suspicious.

Any ideas how fix/debug this?

**Comment by mpickering** [comment]
I think the problem is actually `cabal: There is no package named 'Cabal'.`

I have no idea what the install script does but the fact it called `cabal install` seems dubious to me. What is that supposed to do?

**Comment by fendor** [comment]
Line is copied from the original Makefile, I dont know what it actually does or why it is needed.
Maybe @alanz knows more?

**Comment by alanz** [comment]
There is a package called `Cabal` on hackage, which is the base library used by `cabal-install`, and also by GHC (I think).

I recall at some stage we had to pull it in specifically, because the older GHC versions shipped with a version that is too early for ghc-mod.  I am not sure if it is still needed, perhaps do an experiment to see what happens, but make sure to test the actual installed version of hie for that GHC version, with Cabal uninstalled.

**Comment by power-fungus** [comment]
I am currently investigating the need of this step and it currently seems that this step is not required.

**Comment by arrowd** [comment]
I removed "cabal" rule from install.hs and `stack install.hs hie-8.6.3` finished fine for me.

**Comment by fendor** [comment]
@arrowd, was it a complete clean install? E.g. only stack and git were freshly installed?

**Comment by arrowd** [comment]
Hmm, not sure. I also have `ghc` installed system-wide, but not `cabal`.

**Comment by power-fungus** [comment]
does running `cabal update` fix the issue?

**Comment by arrowd** [comment]
Which `cabal`? Installed by "cabal" rule? I didn't try.

**Comment by power-fungus** [comment]
`stack install.hs cabal` currently calls `stack instal cabal-install`. Then, you should have `cabal` in the path, normaly `~/.local/bin`.

**Comment by power-fungus** [comment]
Is this still an issue? I am not able to reproduce this error

**Comment by arrowd** [comment]
Ah, I found the source of the error. I had empty `~/.cabal/config` file and this was causing `cabal update` to fail.

I'm still don't like that it installs `cabal-install` into my PATH, though.

**Comment by power-fungus** [comment]
@arrowd have a look out for #1168. This fixes the problem
