### ISSUE TITLE
Add 'Add EmptyDataDecls' code action

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-ide-engine#1183]
Given the below code, GHC suggests turning on `EmptyDataDecls`:

```haskell
data Foo
```

The error message from GHC looks like `‘Foo’ has no constructors (EmptyDataDecls permits this)`

It would be great to have this as a code action.

See also #890

**Comment by fendor** [comment]
Looks like this is a single line change in `Pragmas.hs`, adding `"EmptyDataDecls"` to line 96.

**Comment by fendor** [comment]
Actually, that just compiles for me on ghc-8.2.2, what ghc version is that for?

**Comment by expipiplus1** [comment]
@fendor I'm using ghc 8.6.4

**Comment by fendor** [comment]
Still just compiles for me. Very weird.

**Comment by fendor** [comment]
@expipiplus1 Can you check whether #1187 solves your issue? Because, I can not reproduce that problem at all.

**Comment by expipiplus1** [comment]
#1187 works perfectly, ++@fendor!
