### ISSUE TITLE
Possibly wrong bounds for `lsp-test`

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-ide-engine#1195]
This pops up when using `cabal new-build`, see https://github.com/bubba/lsp-test/commit/91086dedbd6ee34ce5c9f3cc47081d839882e29c#commitcomment-33279281.

**Comment by bubba** [comment]
Has been fixed with a revision on hackage

**Comment by michaelpj** [comment]
I'm still observing this, as is @power-fungus, even after updating my hackage index. Possibly best to just push a restriction to the bounds in this repo for now.

**Comment by power-fungus** [comment]
There was some issue that *has* been solved by a hackage revision. However the issue about incorrect bounds is still present (see #1210, sorry for the duplicate issue) a quick PR #1211 fixes this issue temporarily.

**Comment by alanz** [comment]
Sometimes you have to tell stack to use a specific revision, for some reason. e.g. see `monad-dijkstra` in the current deps.

**Comment by fendor** [comment]
The problem is with `cabal new-build`, not stack, stack seems to work just fine.

**Comment by power-fungus** [comment]
For `stack` we actually fix the version to the correct one.
