### ISSUE TITLE
Functional tests rely on stack and don't seem to work with new-build

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-ide-engine#1197]
After adding stack to the `shell.nix` dependencies and `hie` to the `build-tool-depends` I get:
```
Test suite func-test: RUNNING...
Warming up HIE cache...
func-test: fd:45: hGetLine: end of file
func-test: Language server unexpectedly terminated
Test suite func-test: FAIL
```

**Comment by bubba** [comment]
I did a bit of debugging on this last night: the hie instance invoked by `cabal new-test :func-test` isn’t able to find cabal-helper-wrapper. Oddly enough `cabal new-run :func-test` is. 
The solution was to add `cabal-helper:cabal-helper-wrapper` to build-tool-depends for func-test, but then I ran into this issue with cabal https://github.com/haskell/cabal/issues/6011

**Comment by jneira** [comment]
hie does not longer use cabal-helper-wrapper and we are gonna to run the test suite with cabal soon: #1571
