### ISSUE TITLE
v1 style warnings during stack ./install.hs

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#1201]
`Warning: The update command is a part of the legacy v1 style of cabal usage.` and I think a few different ones later.

**Comment by power-fungus** [comment]
I *think* this is because `cabal-helper` does not yet work with `cabal new-build`. Running `cabal (v1-)update` is necessary for it to work. Hopefully, after #1168, only one such error appears.

When the `hie-bios` replaces `cabal-helper`, it will bring a lot more sanity to this project :tada:

**Comment by power-fungus** [comment]
#1126

**Comment by nponeccop** [comment]
I didn't mean to move to `new-build`. I only meant to replace `update` with `v1-update` to suppress the warning.

**Comment by power-fungus** [comment]
I can do that
