### ISSUE TITLE
cabal-help-wrapper fails with wrong ghc path

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#1203]
When I open a file in neovim and try to edit it, it shows the following error:

```
[LC] [Error] Got error while processing diagnostics: readCreateProcess: /home/andy/github/haskell-ide-engine/.stack-work/install/i386-linux/lts
-12.26/8.4.4/bin/cabal-helper-wrapper "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" "/home/hooy/github/n2o.hs" "/ho
me/hooy/github/n2o.hs/dist" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "g
hc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output" (exit 1): failed
```
`--with-ghc=ghc` option seems wrong to me. `ghc` isn't in PATH when I run neovim.

Running the command manually obviously says that ghc isn't found there.

I used `stack ./install.hs ghc-8.4.4` to install hie, and the project I try to open is 8.4.4 too.

**Comment by power-fungus** [comment]
This is a bit weird indeed. What does the process say when executed manually? Does `/home/.../.stack-work/.../lts-*/.../bin/cabal-helper-wrapper` even exist?

**Comment by nponeccop** [comment]
> Running the command manually obviously says that ghc isn't found there.

**Comment by fendor** [comment]
the wrapper doesnt exist anymore, therefore we are closing this for now. Feel free to reopen.
