### ISSUE TITLE
Use install.hs to avoid boilerplate in stack*.yaml

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#1204]
Can/should we generate various `stack*.yaml` from some form of declarative specification in `install.hs` sources? Currently they consist of largely the same info.

**Comment by power-fungus** [comment]
This is an idea worth investigating. I am puzzled by the different lists of extra-deps in the `stack-*.yaml` files. If these are really required, I would prefer having the files explicit as hiding them behind a template would introduce more complexity than necessary. 

However, I will do some experiments towards this.

**Comment by fendor** [comment]
I don't think we should generate them.
The `stack*.yaml` files are used for development and building, while `install.hs` is used to install the binaries and provide a sane environment. I don't see why we would like to generate them in the install script.

**Comment by power-fungus** [comment]
A bit of research shows that the extra-deps make this thing. *Maybe* it would be ok to define the same extra-deps for all ghc verisons, however this is another decision to be made.

**Comment by nponeccop** [comment]
> the extra-deps make this thing complicated

Yes, the dependency lists are different for different versions, so our description mini-language should include such overrides. We may still want to store the generated files in source control. The idea is to make dependency updates easier than not forgetting to update in 5+ places. We can even make update.hs script (or even .sh) which patches the `.stack` files.

Something like

`./update conduit-parse 9.5.3`

and then you review a diff.

Or some sanity check that parses git diff and warns that not everything was updated, I don't know.

**Comment by power-fungus** [comment]
I doubt that the features are worth the extra complexity.
