### ISSUE TITLE
HIE chrashes even if I use HieWrapper

### ISSUE THREAD

**Issue by RoelofWobben** [haskell/haskell-ide-engine#1208]
Hello, 

I installed sghci-4.8.6. 
So I did stack install.hs hie-4.8.6 

but still I see this error 

![afbeelding](https://user-images.githubusercontent.com/47429430/56759002-2e3dc200-6798-11e9-9998-72bf97e2d13b.png)

**Comment by fendor** [comment]
You need a `*.cabal` file in the project. 
Use `cabal init`, or `stack init` in your project to generate one, and tweak it accordingly.

**Comment by RoelofWobben** [comment]
yep, on some way the project has lost the .cabal file.
Case closed
