### ISSUE TITLE
hie-8.6.4/8.4.4 stalls after 3-4 requests

### ISSUE THREAD

**Issue by bscottm** [haskell/haskell-ide-engine#1216]
I hesitated to open this in a new issue, looking for closely related issues to ensure that the issue list doesn't get overly cluttered... HIE stalls after a 3-4 requests. At first I thought the problem was with SublimeText, the LSP package and the Windows implementation of pipes. I tried hie-8.6.4 under Linux on VirtualBox, same problem. It seems to take about three or four JSON RPCs before hie-8.6.4 stalls.

LSP's basic loop calls Python's `str.readline()` to grab the next line of input looking for the "Content-length" header. That just stalls waiting for input. At first I thought that it might be a closed file descriptor, but I would expect the `str.readline()` loop to return EOF (an empty string.)

This particular problem showed up about two to three weeks ago, and I've been trying to diagnose it when I can free cycles. I'm on the latest github version with submodules synced. `hie-wrapper` log is attached, although I anonymized some of my paths. Apologies for the big source file that gets downloaded to the server...

[hie-wrapper.log](https://github.com/haskell/haskell-ide-engine/files/3125228/hie-wrapper.log)

**Comment by mpickering** [comment]
This looks quite clear cut, the last message of the log is:

```
{"code":-32603,"message":"haskell-lsp:parse error. Object (fromList [(\"jsonrpc\",String \"2.0\"),(\"method\",String \"shutdown\"),(\"id\",Number 10.0)]) \"When parsing the record RequestMessage of type Language.Haskell.LSP.Types.Message.RequestMessage the key params was not present.\" `stack update` and install new haskell-lsp. Or check information on https://marketplace.visualstudio.com/items?itemName=xxxxxxxxxxxxxxx"},"jsonrpc":"2.0","id":10}
```

Any ideas whose fault this is @bubba ?

**Comment by bscottm** [comment]
@mpickering: Wait a sec. The last message lacks `key` attribute, which, coincidentally, happens to be the last message ever sent to `hie` when the editor exits. 

I'm not so sure that this is quite so clear cut, if none of the `hover` requests return a response. `hie` stops responding after request id 4.

**Comment by Anrock** [comment]
@bscottm can you check if this [edit](https://github.com/haskell/haskell-ide-engine/issues/983#issuecomment-457882300) helps?

**Comment by bubba** [comment]
@mpickering that parsing issue looks like it’s our fault, specifically `Haskell-lsp-types`. The specification does allow for null to be set for the params field of a request, so [https://hackage.haskell.org/package/haskell-lsp-types-0.11.0.0/docs/Language-Haskell-LSP-Types.html#t:RequestMessage](params) should really be `Maybe params`. This is going to need a lot of changes though throughout haskell-ide-engine. It might be better just to have a custom FromJSON instance for ShutdownRequest

**Comment by bscottm** [comment]
> @bscottm can you check if this [edit](https://github.com/haskell/haskell-ide-engine/issues/983#issuecomment-457882300) helps?

Yes, tremendously. Slow as molasses, but at least `hie` responds.

**Comment by Anrock** [comment]
Welp, so this could be just another case of #983 (if it's even a single issue). Personally i'm running HIE with this edit since then.

**Comment by bscottm** [comment]
@Anrock: So long as `cabal-helper` doesn't change in the near future, there's no danger of the `cabal-helper.cabal` being changed or merged, so I shouldn't get unexpected surprises.
