### ISSUE TITLE
Should we update submodules with --recursive?

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1218]
As far as I know none of our dependencies *need* a recursive clone, and some of them bring in copies of submodules we already provide ourselves, which are used when building the package in standalone fashion.

So things will go faster and probably still work if we do not do the recursive update.

**Comment by power-fungus** [comment]
Will test!

**Comment by nponeccop** [comment]
See #1256

**Comment by power-fungus** [comment]
closed by #1221
