### ISSUE TITLE
On import action, add package to project description.

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-ide-engine#1223]
On import module action, check whether the associated package is already installed and add it to the project description if necessary. 

Is that the wanted behaviour? Or is it better to let the user decide it for themselves?

**Comment by alanz** [comment]
By project description do you mean the cabal file?

**Comment by fendor** [comment]
Yes, or package.yaml.

**Comment by fendor** [comment]
In my opinion, it is fine to demand the user to explictly add the package to cabal file or hpack file.

**Comment by fendor** [comment]
Since nobody expressed any strong opinions, for now I declare that packages need to be manually added to package.yaml or cabal files.
