### ISSUE TITLE
Travis fails with "Could not find module: TestUtils" on MacOS

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#1229]

**Comment by fendor** [comment]
For which test-suite? Or is that the whole error message?

**Comment by nponeccop** [comment]
See Travis logs: https://travis-ci.org/haskell/haskell-ide-engine/jobs/526823736

To find this log by hand do the following:

- go to https://github.com/haskell/haskell-ide-engine/commits/master
- see all those X which mean failed CI
- click on any X to see a popup
- click `details` link in a failed Travis build (the first line)

**Comment by bubba** [comment]
Stack 1.7.1 is outdated: there's a [bug with internal libraries](https://github.com/commercialhaskell/stack/issues/4265) that was fixed in 1.9.1.
I think there is a flag you can use to tell travis to run `brew update`

**Comment by bubba** [comment]
We can close this now since there's been enough time for Stack 1.9.1
