### ISSUE TITLE
Windows CI options

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1233]
At the moment we are doing our windows CI on appveyor.  It works well enough, but we are using a single account for the main repo, and it builds everything in a queue with a single worker on it.

This is severely limiting our ability to merge PRs, as it takes over 90mins to validate any change.

How can we speed this up?
- Reduce the number of builds per commit, perhaps to only the latest of each GHC release (so 8.2.2, 8.4.4,8.6.5)
- Find a way to run builds in parallel on Appveyor
- Find a way to run appveyor builds against personal repos (as with circleci)
- Identify an alternative CI provider which can give a better experience

**Comment by alanz** [comment]
Possibly related #993

**Comment by power-fungus** [comment]
I am Wirkung on Integration azure

**Comment by nponeccop** [comment]
JFYI https://www.appveyor.com/docs/build-configuration/#build-queue

> First, the maximum number of build jobs running simultaneously is defined by account plan. For example, **for Free, Basic and Pro it’s 1 concurrent job**, for Premium it’s 2. Also, there are a lot of additional plans with greater number of concurrent build jobs available on billing page.

**Comment by power-fungus** [comment]
I will work on this in #1238, however tests need to be fixed first

**Comment by jneira** [comment]
Tests in appveyor are not enabled and running them without cache makes the build exceded the 1 hour limit so i think we have to get them working in azure as only option.
Otoh circle ci has added windows envs recently but i think you have to pay for them.
(So maybe we could close this one)

**Comment by jneira** [comment]
I think it is clear that appveyor doenst fullfill our requeriments (parallelism, cache, artifacts) and azure is already set up so i think we can close this one
