### ISSUE TITLE
LTS-13.11 is mutated back to ghc-8.6.3

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#1236]
https://github.com/commercialhaskell/lts-haskell/commit/ebafeb5402c9bb52bdf236b699490c28fb907972

So we can bump the snapshot for hie-8.6.3

**Comment by alanz** [comment]
We originally had 13.11, but it was wrong, so stepped back to 13.10. I think the stackage docs are incorrect.

**Comment by nponeccop** [comment]
Did you look at the linked commit? Snoyman changed GHC in 13.11 snapshot to be 8.6.3 from incorrect 8.6.4 some 10 days ago.

**Comment by alanz** [comment]
Sorry, was traveling, did not look in detail.  So I guess we can bump this next release?  I don't thing there is anything urgent in the one vs the other. Or is there?

**Comment by nponeccop** [comment]
> So I guess we can bump this next release?

Yes

**Comment by nponeccop** [comment]
There isn't anything urgent
