### ISSUE TITLE
Can't install in Docker

### ISSUE THREAD

**Issue by stereobooster** [haskell/haskell-ide-engine#1244]
Trying to install hie in Docker for theia, but it fails https://github.com/theia-ide/theia-apps/compare/master...stereobooster:haskell?expand=1

```
...
foundation-0.0.23: download
foundation-0.0.23: configure
foundation-0.0.23: build
The command '/bin/sh -c git clone https://github.com/haskell/haskell-ide-engine --recursive --depth 1 &&     cd haskell-ide-engine &&     stack install' returned a non-zero code: 137
```

Any advice?

**Comment by Anrock** [comment]
Can you get full log?

**Comment by stereobooster** [comment]
Here is log for `docker build . -t theiaide/theia-haskell:latest`, if this is what you asked for

<details>
<pre><code>Sending build context to Docker daemon   7.68kB

Step 1/13 : ARG NODE_VERSION=10
Step 2/13 : FROM node:${NODE_VERSION}-stretch
 ---> 64c810caf95a
Step 3/13 : RUN curl -sSL https://get.haskellstack.org/ | sh
 ---> Using cache
 ---> 98a5341333dd
Step 4/13 : RUN git clone https://github.com/haskell/haskell-ide-engine --recursive --depth 1 &&     cd haskell-ide-engine &&     stack install
 ---> Running in 33bce71fc0b0
Cloning into 'haskell-ide-engine'...
Submodule 'submodules/HaRe' (https://github.com/alanz/HaRe.git) registered for path 'submodules/HaRe'
Submodule 'submodules/brittany' (https://github.com/lspitzner/brittany.git) registered for path 'submodules/brittany'
Submodule 'submodules/cabal-helper' (https://github.com/alanz/cabal-helper.git) registered for path 'submodules/cabal-helper'
Submodule 'submodules/floskell' (https://github.com/ennocramer/floskell) registered for path 'submodules/floskell'
Submodule 'submodules/ghc-mod' (https://github.com/alanz/ghc-mod.git) registered for path 'submodules/ghc-mod'
Cloning into '/haskell-ide-engine/submodules/HaRe'...
Cloning into '/haskell-ide-engine/submodules/brittany'...
Cloning into '/haskell-ide-engine/submodules/cabal-helper'...
Cloning into '/haskell-ide-engine/submodules/floskell'...
Cloning into '/haskell-ide-engine/submodules/ghc-mod'...
Submodule path 'submodules/HaRe': checked out '53979f062bebcaa132390d1fd0cec74a51662952'
Submodule 'submodules/cabal-helper' (https://github.com/alanz/cabal-helper.git) registered for path 'submodules/HaRe/submodules/cabal-helper'
Submodule 'submodules/ghc-mod' (https://github.com/alanz/ghc-mod.git) registered for path 'submodules/HaRe/submodules/ghc-mod'
Cloning into '/haskell-ide-engine/submodules/HaRe/submodules/cabal-helper'...
Cloning into '/haskell-ide-engine/submodules/HaRe/submodules/ghc-mod'...
Submodule path 'submodules/HaRe/submodules/cabal-helper': checked out '7df8b47d3b68651f907b64ecccb5b4b76c07df76'
Submodule path 'submodules/HaRe/submodules/ghc-mod': checked out 'e5b7daf1a2c949b2d2900ae11b13a267ed25eedb'
Submodule path 'submodules/brittany': checked out '6c187da8f8166d595f36d6aaf419370283b3d1e9'
Submodule path 'submodules/cabal-helper': checked out '754e60fbce458ee4311a3ed59e5de6ee80f5a512'
Submodule path 'submodules/floskell': checked out '13af3d9b1967a244c2661e31f0b8f8cb1e3a0f79'
Submodule path 'submodules/ghc-mod': checked out 'b20536757f34769c6fe4478f13b71a55c9ae582e'
Downloading nightly-2019-04-30 build plan ...
Downloaded nightly-2019-04-30 build plan.
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-8.6.5 ...
ghc-8.6.5: download has begun
ghc-8.6.5:    1.96 MiB / 175.83 MiB (  1.11%) downloaded...
ghc-8.6.5:    5.54 MiB / 175.83 MiB (  3.15%) downloaded...
ghc-8.6.5:    8.83 MiB / 175.83 MiB (  5.02%) downloaded...
ghc-8.6.5:   12.44 MiB / 175.83 MiB (  7.08%) downloaded...
ghc-8.6.5:   16.35 MiB / 175.83 MiB (  9.30%) downloaded...
ghc-8.6.5:   19.38 MiB / 175.83 MiB ( 11.02%) downloaded...
ghc-8.6.5:   22.77 MiB / 175.83 MiB ( 12.95%) downloaded...
ghc-8.6.5:   27.10 MiB / 175.83 MiB ( 15.41%) downloaded...
ghc-8.6.5:   31.47 MiB / 175.83 MiB ( 17.90%) downloaded...
ghc-8.6.5:   36.18 MiB / 175.83 MiB ( 20.57%) downloaded...
ghc-8.6.5:   41.02 MiB / 175.83 MiB ( 23.33%) downloaded...
ghc-8.6.5:   45.43 MiB / 175.83 MiB ( 25.83%) downloaded...
ghc-8.6.5:   49.85 MiB / 175.83 MiB ( 28.35%) downloaded...
ghc-8.6.5:   54.44 MiB / 175.83 MiB ( 30.96%) downloaded...
ghc-8.6.5:   59.49 MiB / 175.83 MiB ( 33.83%) downloaded...
ghc-8.6.5:   66.29 MiB / 175.83 MiB ( 37.70%) downloaded...
ghc-8.6.5:   72.24 MiB / 175.83 MiB ( 41.08%) downloaded...
ghc-8.6.5:   78.32 MiB / 175.83 MiB ( 44.54%) downloaded...
ghc-8.6.5:   83.79 MiB / 175.83 MiB ( 47.65%) downloaded...
ghc-8.6.5:   89.18 MiB / 175.83 MiB ( 50.72%) downloaded...
ghc-8.6.5:   95.13 MiB / 175.83 MiB ( 54.10%) downloaded...
ghc-8.6.5:  101.16 MiB / 175.83 MiB ( 57.53%) downloaded...
ghc-8.6.5:  107.64 MiB / 175.83 MiB ( 61.22%) downloaded...
ghc-8.6.5:  113.35 MiB / 175.83 MiB ( 64.46%) downloaded...
ghc-8.6.5:  119.38 MiB / 175.83 MiB ( 67.89%) downloaded...
ghc-8.6.5:  125.57 MiB / 175.83 MiB ( 71.41%) downloaded...
ghc-8.6.5:  131.71 MiB / 175.83 MiB ( 74.91%) downloaded...
ghc-8.6.5:  137.27 MiB / 175.83 MiB ( 78.07%) downloaded...
ghc-8.6.5:  142.74 MiB / 175.83 MiB ( 81.18%) downloaded...
ghc-8.6.5:  147.58 MiB / 175.83 MiB ( 83.93%) downloaded...
ghc-8.6.5:  153.55 MiB / 175.83 MiB ( 87.33%) downloaded...
ghc-8.6.5:  159.41 MiB / 175.83 MiB ( 90.66%) downloaded...
ghc-8.6.5:  165.39 MiB / 175.83 MiB ( 94.06%) downloaded...
ghc-8.6.5:  170.49 MiB / 175.83 MiB ( 96.96%) downloaded...
ghc-8.6.5:  174.75 MiB / 175.83 MiB ( 99.39%) downloaded...
ghc-8.6.5:  175.83 MiB / 175.83 MiB (100.00%) downloaded...
Downloaded ghc-8.6.5.
Unpacking GHC into /root/.stack/programs/x86_64-linux/ghc-8.6.5.temp/ ...
Configuring GHC ...
Installing GHC ...
Installed GHC.
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading root
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
Updated package index downloaded
Update complete
Populating index cache ...
Populated index cache.
No packages found in snapshot which provide a "cabal" executable, which is a build-tool dependency of "cabal-helper"
[1 of 2] Compiling Main             ( /root/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /root/.stack/setup-exe-src/setup-mPHDZzAJ.o )
[2 of 2] Compiling StackSetupShim   ( /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /root/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
Linking /root/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 ...
Diff-0.3.4: download
Diff-0.3.4: configure
Cabal-2.4.1.0: download
Diff-0.3.4: build
Cabal-2.4.1.0: configure
Cabal-2.4.1.0: build
Diff-0.3.4: copy/register
StateVar-1.1.1.1: download
StateVar-1.1.1.1: configure
StateVar-1.1.1.1: build
StateVar-1.1.1.1: copy/register
appar-0.1.7: download
appar-0.1.7: configure
appar-0.1.7: build
appar-0.1.7: copy/register
auto-update-0.1.4.1: download
auto-update-0.1.4.1: configure
auto-update-0.1.4.1: build
auto-update-0.1.4.1: copy/register
base-compat-0.10.5: download
base-compat-0.10.5: configure
base-compat-0.10.5: build
base-compat-0.10.5: copy/register
base-orphans-0.8.1: download
base-orphans-0.8.1: configure
base-orphans-0.8.1: build
base-orphans-0.8.1: copy/register
base-prelude-1.3: download
base-prelude-1.3: configure
base-prelude-1.3: build
base-prelude-1.3: copy/register
base16-bytestring-0.1.1.6: download
base16-bytestring-0.1.1.6: configure
base16-bytestring-0.1.1.6: build
base16-bytestring-0.1.1.6: copy/register
base64-bytestring-1.0.0.2: download
base64-bytestring-1.0.0.2: configure
base64-bytestring-1.0.0.2: build
base64-bytestring-1.0.0.2: copy/register
basement-0.0.10: download
basement-0.0.10: configure
basement-0.0.10: build
basement-0.0.10: copy/register
blaze-builder-0.4.1.0: download
blaze-builder-0.4.1.0: configure
blaze-builder-0.4.1.0: build
blaze-builder-0.4.1.0: copy/register
blaze-markup-0.8.2.2: download
blaze-markup-0.8.2.2: configure
blaze-markup-0.8.2.2: build
blaze-markup-0.8.2.2: copy/register
bsb-http-chunked-0.0.0.4: download
bsb-http-chunked-0.0.0.4: configure
bsb-http-chunked-0.0.0.4: build
bsb-http-chunked-0.0.0.4: copy/register
byteable-0.1.1: download
byteable-0.1.1: configure
byteable-0.1.1: build
byteable-0.1.1: copy/register
byteorder-1.0.4: download
byteorder-1.0.4: configure
byteorder-1.0.4: build
byteorder-1.0.4: copy/register
call-stack-0.1.0: download
call-stack-0.1.0: configure
call-stack-0.1.0: build
call-stack-0.1.0: copy/register
HUnit-1.6.0.0: download
HUnit-1.6.0.0: configure
HUnit-1.6.0.0: build
HUnit-1.6.0.0: copy/register
cereal-0.5.8.0: download
cereal-0.5.8.0: configure
cereal-0.5.8.0: build
cereal-0.5.8.0: copy/register
clock-0.7.2: download
clock-0.7.2: configure
clock-0.7.2: build
clock-0.7.2: copy/register
cmdargs-0.10.20: download
cmdargs-0.10.20: configure
cmdargs-0.10.20: build
cmdargs-0.10.20: copy/register
colour-2.3.4: download
colour-2.3.4: configure
colour-2.3.4: build
colour-2.3.4: copy/register
ansi-terminal-0.8.2: download
ansi-terminal-0.8.2: configure
ansi-terminal-0.8.2: build
ansi-terminal-0.8.2: copy/register
ansi-wl-pprint-0.6.8.2: download
ansi-wl-pprint-0.6.8.2: configure
ansi-wl-pprint-0.6.8.2: build
ansi-wl-pprint-0.6.8.2: copy/register
constrained-dynamic-0.1.0.0: download
constrained-dynamic-0.1.0.0: configure
constrained-dynamic-0.1.0.0: build
constrained-dynamic-0.1.0.0: copy/register
contravariant-1.5: download
contravariant-1.5: configure
contravariant-1.5: build
contravariant-1.5: copy/register
cryptohash-sha256-0.11.101.0: download
cryptohash-sha256-0.11.101.0: configure
cryptohash-sha256-0.11.101.0: build
cryptohash-sha256-0.11.101.0: copy/register
czipwith-1.0.1.1: download
czipwith-1.0.1.1: configure
czipwith-1.0.1.1: build
czipwith-1.0.1.1: copy/register
data-default-class-0.1.2.0: download
data-default-class-0.1.2.0: configure
data-default-class-0.1.2.0: build
data-default-class-0.1.2.0: copy/register
cookie-0.4.4: download
cookie-0.4.4: configure
cookie-0.4.4: build
cookie-0.4.4: copy/register
data-default-instances-containers-0.0.1: download
data-default-instances-containers-0.0.1: configure
data-default-instances-containers-0.0.1: build
data-default-instances-containers-0.0.1: copy/register
deque-0.2.7: download
deque-0.2.7: configure
deque-0.2.7: build
deque-0.2.7: copy/register
digest-0.0.1.2: download
digest-0.0.1.2: configure
digest-0.0.1.2: build
digest-0.0.1.2: copy/register
dlist-0.8.0.6: download
dlist-0.8.0.6: configure
dlist-0.8.0.6: build
dlist-0.8.0.6: copy/register
data-default-instances-dlist-0.0.1: download
data-default-instances-dlist-0.0.1: configure
data-default-instances-dlist-0.0.1: build
data-default-instances-dlist-0.0.1: copy/register
easy-file-0.2.2: download
easy-file-0.2.2: configure
easy-file-0.2.2: build
easy-file-0.2.2: copy/register
echo-0.1.3: download
echo-0.1.3: configure
echo-0.1.3: build
echo-0.1.3: copy/register
ed25519-0.0.5.0: download
ed25519-0.0.5.0: configure
ed25519-0.0.5.0: build
ed25519-0.0.5.0: copy/register
erf-2.0.0.0: download
erf-2.0.0.0: configure
erf-2.0.0.0: build
erf-2.0.0.0: copy/register
executable-path-0.0.3.1: download
executable-path-0.0.3.1: configure
executable-path-0.0.3.1: build
executable-path-0.0.3.1: copy/register
fclabels-2.0.3.3: download
fclabels-2.0.3.3: configure
fclabels-2.0.3.3: build
fclabels-2.0.3.3: copy/register
fingertree-0.1.4.2: download
fingertree-0.1.4.2: configure
fingertree-0.1.4.2: build
fingertree-0.1.4.2: copy/register
fmlist-0.9.2: download
fmlist-0.9.2: configure
fmlist-0.9.2: build
fmlist-0.9.2: copy/register
foundation-0.0.23: download
foundation-0.0.23: configure
foundation-0.0.23: build
</code></pre>
</details>

**Comment by nponeccop** [comment]
The build script uses `stack install` which isn't enough. Should use `stack ./install.hs ghc-8.6.5`

**Comment by stereobooster** [comment]
@nponeccop thanks for the help, but it doesn't work

```
    [158 of 220] Compiling Distribution.Simple.Command ( Distribution/Simple/Command.hs, .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/Distribution/Simple/Command.o )
    [159 of 220] Compiling Distribution.Simple.Setup ( Distribution/Simple/Setup.hs, .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/Distribution/Simple/Setup.o )
The command '/bin/sh -c git clone https://github.com/haskell/haskell-ide-engine --recursive --depth 1 && \
     cd haskell-ide-engine && \
     stack ./install.hs hie-8.6.5 && \
     stack ./install.hs build-doc' returned a non-zero code: 1
```

**Comment by nponeccop** [comment]
> THIS MAY INDICATE OUT OF MEMORY

I think it needs some 2GB of RAM to build. Check your system journal for out of memory killing.

**Comment by stereobooster** [comment]
Yeah that is what I'm trying at the moment. I increased memory to 4GB and trying again.

**Comment by stereobooster** [comment]
Yes it worked after I increased Docker memory to 4GB. Thanks for the help
