### ISSUE TITLE
Heavy

### ISSUE THREAD

**Issue by roberbnd** [haskell/haskell-ide-engine#1254]
Why is so heavy haskel ide?
I mean to install whatever lsp (python, js, ruby) it was so easy but I have 1 hour in this and my computer is almost frozen
![hask](https://user-images.githubusercontent.com/4907027/57564225-1eb0a280-736e-11e9-806e-3e17e4fd0cee.jpg)

Is this normal?

**Comment by roberbnd** [comment]
I use archlinux and I did yay -S haskell-ide-engine-git,  I better stopped it because I feel this isn't normal

**Comment by Avi-D-coder** [comment]
It takes a while to compile. This is pretty normal. Work is being done towards distributing binaries, last I checked.

**Comment by fendor** [comment]
The compilation process is slow and takes up a lot of resources at the moment.
I don't believe that can easily be fixed or mitigated. I would like to close this issue, since the fix is discussed in #1068. Feel free to reopen.
