### ISSUE TITLE
Completions should be aware of infix backticks

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1259]
Doing completion on

```haskell
"a" `should
```
gives the option `shouldBe`, but the completion/snippet does not have the closing backtick, and is presented as requiring two more params.

**Comment by fendor** [comment]
I would like to take a look at this in the next week, any pointers which files are responsible for this behaviour?

**Comment by lorenzo** [comment]
@fendor This is the function you need to change https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Support/HieExtras.hs#L323
