### ISSUE TITLE
Package elisp on MELPA

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#126]
We seem to be getting to some level of stability / functionality on the emacs side.

I think the sooner we get the infrastructure in place to publish via MELPA the better, even if the initial functionality is very limited.

**Comment by cocreature** [comment]
Personally I would prefer to wait a bit more, but I am not sure if there is any policy for the state a package needs to be in to be ready for MELPA, so if anybody wants to add it, feel free to do so.

**Comment by alanz** [comment]
It just allows us to start experimenting more easily in spacemacs, and also
means that so long as the `hie` exe is in the path we can easily load the
elisp code, without having to mess around with load paths.

And the sooner we do it the better, even if we state that it is pre-alpha,
experimental, etc.

**Comment by cocreature** [comment]
Alright, let’s make this a newcomer task. The documentation on how to get a package on melpa is in the [readme](https://github.com/milkypostman/melpa).

**Comment by mgsloan** [comment]
I think we should wait till some folks are using HIE as their daily driver.  Then again, maybe this is already the case?

**Comment by alanz** [comment]
I was reading the process of getting it onto MELPA, and I think I agree
that it is premature

**Comment by alanz** [comment]
This has been superseded by https://github.com/emacs-lsp/lsp-haskell
