### ISSUE TITLE
error readCreateProcess: cabal-helper-wrapper "print-build-platform" (exit 1): failed

### ISSUE THREAD

**Issue by luochen1990** [haskell/haskell-ide-engine#1262]
## I'm using:

- Ubuntu 18.04.2 LTS (under Windows WSL)
- NVIM v0.4.0-811-gca1ce5902
- LanguageClient-neovim 41c948e (2019-05-08 21:17:55)
- haskell-ide-engine 33d4581f (2019-05-18 21:37:50)

## My workaround:

```
export PATH="$PATH:$(stack path --compiler-bin)"
```

## The problem of my workaround:

When I'm working on single files outside of any project, hie cannot find modules correctly.

## Another workaround I have tried:

Add following file into PATH dir, name it `ghc` and `chmod +x ghc`

```
#!/bin/sh
stack exec -- ghc "$@"
```

But this workaround failed, seems that `cabal-helper-wrapper` is not finding `ghc` in PATH.

Here is a related issue: https://github.com/alanz/vscode-hie-server/issues/128

**Comment by power-fungus** [comment]
Hie does not work if the cabal file is missing, iirc.

**Comment by nponeccop** [comment]
The error message could be better. User errors should never look like crashes.

**Comment by fendor** [comment]
That feature request should be a separate issue.

**Comment by nponeccop** [comment]
Can we close the issue as invalid?

**Comment by fendor** [comment]
Not supported out of the box. 
Can be worked around now with a custom cradle, e.g. `direct` cradle where you specify all the ghc options.
