### ISSUE TITLE
Got setTraceNotification ignoring

### ISSUE THREAD

**Issue by teto** [haskell/haskell-ide-engine#1271]
I use coc.nvim, I think this is due to an unimplemented LSP feature and you are almost certainly already aware about it but the issue could help track a resolution:
I get this message from times to times, I believe when I change the coc-settings.json, which may trigger send in turn some notificiation to the LSP server:
`Error output from languageserver.haskell: haskell-lsp:Got setTraceNotification ignoring`

**Comment by jneira** [comment]
@teto this one should be fixed by https://github.com/alanz/haskell-lsp/pull/171,the change is is already included in hie master.
Feel free to reopen if you continue experiencing the issue.
