### ISSUE TITLE
Refresh hackage index failed

### ISSUE THREAD

**Issue by c4dr01d** [haskell/haskell-ide-engine#1275]
Hi, I'm a Haskell developer from China, I clone the repository and following the README.md instruction to build HIE, at refreshing the hackage package index, I got: Connection timeout. Can I change the hackage mirror address to China hackage mirror server? I don't know how to change the HIE project mirror.

**Comment by bubba** [comment]
You might get some help from the people at https://github.com/commercialhaskell/stack or https://github.com/haskell/cabal
