### ISSUE TITLE
Got error while processing diagnostics

### ISSUE THREAD

**Issue by maxco2** [haskell/haskell-ide-engine#1282]
![image](https://user-images.githubusercontent.com/11772699/58748515-9a54c980-84ac-11e9-8a59-869ca95c4166.png)
![image](https://user-images.githubusercontent.com/11772699/58748630-67133a00-84ae-11e9-8e90-20533177cd4e.png)

I got above error when I open a project file (VIM also got the same error).
I'm using Ubuntu 18.10 & ghc-8.6.4 . 

Any help is appreciated.

**Comment by fendor** [comment]
You can try to execute the command in your project root:
`cabal configure --with-ghc=ghc --flags` and show the output. Likely, your project does not build with cabal old-style builds.

**Comment by maxco2** [comment]
Thanks for the quick reply. I think it is my project problem. I tested it on another project. Everything works fine.
