### ISSUE TITLE
Migrate CI to use stack 2.1

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1298]
At some point we need to migrate CI to use stack 2.1

But I think we should keep at least one build using 1.9.3, to make sure we don't break backward compatibility.

**Comment by jneira** [comment]
it seems azure and circleci (with the `stack upgrade` in the docker file? https://hub.docker.com/r/alanz/haskell-hie-ci/dockerfile) and travis (cause it uses homebrew) uses stack 2.1.
@alanz maybe we could close this one

**Comment by nponeccop** [comment]
> we should keep at least one build using 1.9.3

We should at least document which builds use stack 1.9.x

**Comment by fendor** [comment]
I think, currently all CI's are using stack 2.1.3.1 or something like that?

**Comment by fendor** [comment]
Closed by accident

**Comment by jneira** [comment]
We are validating in the install script that stack version is greater than `2.1.1` and it is listed in README as one of the requirements to build so in fact we've deprecated stack-1.9.3 to build hie
