### ISSUE TITLE
Decide how haskell-ide project is run

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-ide-engine#13]
Process needs to be sorted out, for example:

- [ ] ways to communicate within the project
- [ ] what are github issues for and how to use them
- [ ] how github issues are pushed forward in process and when are they closed
- [x] describe github issue labels and operational meaning of the labels (if used)
- [ ] who, how, where and how often publishes progress report
- [ ] who, how, where and how often publishes release notes
- [ ] what is current project focus
- [ ] standards for code contributions (checklist)
- [ ] pull request review and merging process
- [ ] documentation standards

**Comment by tkvogt** [comment]
- Mailing list: Good for announcements.
- Github issues: Ideas, bugs, problems. 
  But it is likely that there will be more than a hundred issues in a few years. So it would be nice to close an issue and write the conclusion in the github wiki and link back to the issue.
- documentation standards: I would enjoy some general overview of a library. In my latest library I did a "Walkthrough" with links into the code (https://github.com/diagrams/diagrams-input). Sometimes an article would be helpful. This helped me to start with ghc-api: http://aosabook.org/en/ghc.html

**Comment by gracjan** [comment]
@tkvogt: thanks for input. You seem to be talking about deliverables, where I wanted to talk about the process itself. To give a hint what I mean I'd like to take rust-lang as example:

1. They decided on fixed schedule releases every 6 weeks. What is the release schedule here?
2. They decided to use github issues for discussions. On the contrary ruby on rails has discussions going on on mailing lists and issues are only for issues.
3. Rust project has versatile labeling implemented, just see here: https://github.com/rust-lang/rust/issues
4. etc

**Comment by gracjan** [comment]
For a better exposition: http://words.steveklabnik.com/how-to-be-an-open-source-gardener

**Comment by cocreature** [comment]
Is there anything left to do here? We seem to get along pretty well, so I’m not sure if we need to hammer down the process more than we already have.

**Comment by cocreature** [comment]
Closing, feel free to reopen if needed. Preferably more specific issues.
