### ISSUE TITLE
_flymake.hs file automatically generated

### ISSUE THREAD

**Issue by roro47** [haskell/haskell-ide-engine#1307]
Hi
I just install hie using  cabal-build-all. I follow the README to add configuration on spacemacs. There are flymake files generated when I was editing my stack project. The flymake file make stack build fails. Is this an intended behaviour?

**Comment by alanz** [comment]
That is something to do with the emacs config.

Customize the `lsp-prefer-flymake` variable to be `nil`.

**Comment by codygman** [comment]
@alanz Does haskell-ide-engine not use flymake at all?

**Comment by freckletonj** [comment]
https://github.com/emacs-lsp/lsp-haskell/issues/41

> If you prefer flycheck and lsp-ui-flycheck is available, (setq lsp-prefer-flymake nil). If set to :none neither of two will be enabled.
