### ISSUE TITLE
latest HIE and its submodule HaRE mutally includes each other, causing recursive download and building to fail

### ISSUE THREAD

**Issue by ZZYSonny** [haskell/haskell-ide-engine#1308]
When running "git clone https://github.com/haskell/haskell-ide-engine --recurse-submodules" from the installation instructions, my git keeps downloading things all over again. 
![image](https://user-images.githubusercontent.com/28442838/60235849-bf85fd80-98db-11e9-814a-4b9d77569095.png)

If I stop at the middle or remove HIE inside HaRE, it fails to build. Any solution on this?

**Comment by ZZYSonny** [comment]
There was a post discussing this. #1256

**Comment by power-fungus** [comment]
A non recursive clone follkwed by `git submodule update --init` seems to work fine.

**Comment by fendor** [comment]
general issue is discussed in #1218

**Comment by ZZYSonny** [comment]
@power-fungus using `git submodule update --init` could download. (It doesn't download submodules in the submodules, so this is fine.).
But when I try to build hie, stack seems to do the recursive git and cause error.
![批注 2019-06-27 182409](https://user-images.githubusercontent.com/28442838/60259409-c75c9680-9909-11e9-8552-b3edfffeeb69.jpg)
I think probably the only way to fix the building issue is to remove the dependency of HIE for HaRE in code. 

I've not tried using a older version of HaRE (which don't requires HIE) with HIE 0.10.0.0. Not sure if that works.

**Comment by fendor** [comment]
Are you sure that submodules cause you problems? Because in the logs you posted, the complaint is that the filename is too long.

**Comment by ZZYSonny** [comment]
@fendor Thank you! I removed the 256 character limit and git downloading works fine. I might try building it later.

Now the file structure is somehow like
HIE has a submodule HaRE
   HaRE has a submodule HIE (an older version)
      HIE has a submodule HaRE(an older version, which don't have a dependency of HIE)
