### ISSUE TITLE
s2i stack build failed 

### ISSUE THREAD

**Issue by sputniiik** [haskell/haskell-ide-engine#1313]
Im trying to build my cardano full node application

I am having some issue with the stack.yaml, I am using current stack-2.1.1 and I installed all the dependencies for cardano-sl:
[https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md](url)

I wonder 

```
---> Building application from source...
Going to build:  cardano-sl-networking cardano-sl-binary cardano-sl-util cardano-sl-crypto cardano-sl-core cardano-sl-db cardano-sl-chain cardano-sl-infra cardano-sl cardano-sl-node cardano-sl-client cardano-sl-generator cardano-sl-auxx cardano-sl-tools cardano-sl-explorer cardano-sl-wallet
Building cardano-sl-networking

stack build --ghc-options=" -Wwarn" --test --no-haddock-deps --bench --jobs=1 --no-run-tests --no-run-benchmarks --dependencies-only  cardano-sl-networking

Could not parse '/opt/app-root/src/stack.yaml':
Aeson exception:
Error in $.packages[32]: failed to parse field 'packages': expected Text, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/
Build failed
ERROR: An error occurred: non-zero (13) exit code from mycardano-s2i

```

stack.yaml:

`resolver: lts-12.17

flags:
  ether:
    disable-tup-instances: true

extra-package-dbs: []

packages:
- util
- util/test
- networking
- binary
- binary/test
- crypto
- crypto/test
- core
- core/test
- db
- db/test
- infra
- infra/test
- chain
- chain/test
- lib
- generator
- client
- auxx
- script-runner
- explorer
- node
- tools
- tools/post-mortem
- utxo
- wallet
- node-ipc
- faucet
- acid-state-exts
- x509
- cluster
- mnemonic

`

**Comment by power-fungus** [comment]
How is this related to the haskell-ide-engine? When does the error occur?
