### ISSUE TITLE
emacs : process HieDiff result

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#132]
A `HieDiff` captures a change to a file based on an action of the plugin.

There are two possible ways of dealing with it

1. Just apply it to the file in question, in an undoable way
2. Present it as a preview, using ediff or similar, and then accept if appropriate.

These two cases should probably be captured by a semantic type wrapper around the `HieDiff`.

**Comment by mgsloan** [comment]
(1) seems way more convenient, seems like a better default.

**Comment by mgsloan** [comment]
(1) seems way more convenient, seems like a better default.  If folks are curious about the diff, they can use undo-tree-visualize or similar.

**Comment by alanz** [comment]
Historically HaRe has presented a preview, which is probably more useful to a HaRe dev than to a user. But it is useful when it operates over multiple files, and you can check that it is in fact doing what you want.

Problem is, by sending an actual diff the ediff stuff is more complicated to do.

**Comment by alanz** [comment]
It seems the simplest way of implementing this is to use the elisp function `elisp-patch-buffer`.
This seems to point to using a standard patch format for the returned `HieDiff` value.

**Comment by alanz** [comment]
@cocreature this is done?

**Comment by cocreature** [comment]
Oh yes, I forgot about this issue.
