### ISSUE TITLE
Tests with stack-2.1.1 result in modified test cabal file

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1320]
Using stack-2.1.1, and a clean hie checkout, after running `stack test` the following file always shows up as modified

```
test/testdata/addPackageTest/hybrid-exe/asdf.cabal
```

To get git clean it needs to be checkout out over the modification.

Does the file need to be in git?

**Comment by fendor** [comment]
This test case explicitly checks if both a `package.yaml` and a `*.cabal` file is present that changes are added to the `package.yaml`. As far as I remember, this shouldn't result in any changes to the `*.cabal` file.

**Comment by alanz** [comment]
That's as I understand it, but I think there is a different `hpack` with stack 2.1.1, so even though the info is the same, the generated file is different.

**Comment by fendor** [comment]
Oh, I see, so, open the project in hie results in a modified cabal file? would it be sensible to change the cabal file in the test case, to fit the generated one? E.g., add the cabal file to the repo instead of the old one?

**Comment by alanz** [comment]
This file is changed as a result of running the tests. It is not needed for any project.

I have a feeling it can be left out of git completely, because it is mechanically generated as a side-effect of running the test.

So either we remove it from git, or come up with a way of setting it up in the test environment according to the stack version the test is being run with. Or more explicitly, the hpack version.

**Comment by fendor** [comment]
removing it is probably fine, the test case still checks the use-case since hpacks generates a cabal file. In this sense, we can probably delete all tests regarding `hybrid-*` where both package.yaml and *.cabal are present.

**Comment by alanz** [comment]
I think a first step would be to remove the file from git (and the filesystem) and confirm the tests still pass. Hopefully that is all that is needed.

**Comment by fendor** [comment]
The tests still do pass after `asdf.cabal` has been removed. 
However, if we delete `asdf.cabal`, then there is no need to have that test-case after all, since it would be the same as `hpack` only test-cases.

**Comment by alanz** [comment]
Ok, that makes sense, just wanted to make sure we are on the same page.

So that sounds like the thing to do.
