### ISSUE TITLE
Create/find a script to do an initial ChangeLog

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1321]
Even if it just slurps and formats all the PR's in the given date range, to be edited afterward for groupinp.

**Comment by alanz** [comment]
Perhaps use a tweak on https://coderwall.com/p/5cv5lg/generate-your-changelogs-with-git-log

cc @bubba

**Comment by Anrock** [comment]
There are plenty of ready-made scripts like [this](https://github.com/github-changelog-generator/github-changelog-generator) or [that](https://github.com/semantic-release/release-notes-generator) to name a few. Most of them are written in JS or Ruby for some reason, but I don't think it's a problem if you're only going to run it locally.
