### ISSUE TITLE
Show entire compiler error or information message

### ISSUE THREAD

**Issue by mb720** [haskell/haskell-ide-engine#1332]
I'm having a great time using HIE with Vim, thanks for your work! 👍

I was wondering whether it's possible to show compiler errors and informational messages like hints in their own buffer.

For example, HIE kindly points out that the following can be eta-reduced:

    stringLength :: String -> Int
    stringLength s = foldr (\_ length -> length + 1) 0 s

But the message is cut off:

![cut-off message screenshot](https://i.imgur.com/4Men7wz.png)

I browsed the functions in `help :LanguageClient` but couldn't find anything that puts the message in its own buffer.

**Comment by Anrock** [comment]
I think this is a question for LanguageClient, not for HIE. HIE sends full messages, how to display is client implementation. I'm using CoC and that's how it looks in my neovim:

<img width="822" alt="изображение" src="https://user-images.githubusercontent.com/1689392/61289825-f496b900-a7d2-11e9-8607-655b363936e5.png">

**Comment by mb720** [comment]
I see, thanks for your comment.

If I read the issue correctly, [this](https://github.com/autozimu/LanguageClient-neovim/issues/792) is a feature request

**Comment by Anrock** [comment]
@mb720, no, but what you see should be default config of CoC. Just follow their installation instructions.
