### ISSUE TITLE
emacs: how to run hie with arguments / logging

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#134]
Starting `hie` as

```
hie -d -l /tmp/hie.log
```

results in it writing debug info to the log file at /tmp/hie.log

It appears that customizing [hie-command-args](https://github.com/haskell/haskell-ide-engine/blob/master/elisp/hie.el#L20) should do this, but if a value is set the inferior `hie` process does not start.

**Comment by alanz** [comment]
I am currently using a file `hie.sh` to work around this, with the following contents

```bash
#!/bin/sh

hie -d -l /tmp/hie.log
```

**Comment by cocreature** [comment]
I can’t reproduce this. If I `(setq hie-command-args '("-d" "-l" "/tmp/hie.log"))` it does exactly what I would expect it to do which is write logs in /tmp/hie.log.

**Comment by alanz** [comment]
This is what ends up in my `(custom-set-variables...)`

     '(hie-command-args (quote ("-d" "-l /tmp/hie.log")))
 
The only difference seems to be that you have the parameters in 3 parts

Changing it to be in three parts gets it to work

**Comment by alanz** [comment]
Details captured in https://github.com/haskell/haskell-ide-engine/blob/master/docs/emacs.md
