### ISSUE TITLE
Does HIE necessarily depend on the global .stack directory?

### ISSUE THREAD

**Issue by DavSanchez** [haskell/haskell-ide-engine#1348]
Hello there! I was wondering if it is necessary that HIE in VSCode depends on calling the contents of my `$HOME/.stack` directory (image related) as well as the `haskell-ide-engine` repo?

Having HIE for all versions of GHC can make said directory to grow to like 20 GB, and I have seen people recommending to delete it from time to time... It would be a pain to build HIE over and over whenever the `.stack` directory grows out of control.

Thanks for all this work guys, I am determined to learn some Haskell, and your tool is of invaluable help for that!

<img width="460" alt="image" src="https://user-images.githubusercontent.com/11422515/62092391-e2a22500-b26c-11e9-95dd-0c72ee3559e0.png">

**Comment by DanielG** [comment]
That is a good question! In fact HIE doesn't depend on the entire `~/.stack` directory but the ghc `settings` file from the error message really in particular really is absolutely required ;)

In fact the entirety of GHC intsallations in `~/.stack/programs` are required if you compiled HIE with stack.

You should be able to get back into a working state with an appropriate invocations of `stack setup GHC_VER` to get the relevant ghc installations back.

If you want to cleanup `~/.stack` next time you really ought to delete stuff in `~/.stack/snapshots` and not the entire stack directory, then you wouldn't have this problem. The GHC installations are "just" 1.5GBish per, not quite as bad as all the library build products in the snapshots directory.

**Comment by power-fungus** [comment]
I advise to only install the versions of hie that you really need. No single person is using 4 ghc versions concurrently. If you do, its not hie that clutters the stack folder.

Hie does in fact depend in its compiler it was compiled with as well as its original install location. If you delete its compiler or delete the hie source folder from which it Was built, it wont work

**Comment by DavSanchez** [comment]
I see, I had the curiosity to ask, since I run into the problems when I last deleted the `.stack` directory.

In order to save space and use the last LTS resolver (13.26) for both HIE compilation and use, I guess I must change the resolver in `install/shake.yaml` right? I remember trying it amad running into some problem, but I cannot recall what it was. If I run into it and can’t solve it I’ll get back to you.

Thank you!

**Comment by power-fungus** [comment]
Yes, you can. We decided against it because of issue #1116. However, this should not be a major issue in your case.

If you know what you are doing, `stack install --stack-yaml <correct yaml>` should work fine as well.

**Comment by DavSanchez** [comment]
Using `stack install --stack-yaml=stack-8.6.5.yaml` begins downloading GHC 8.6.4. I thought it would download only 8.6.5?

Modifying the resolver in `shake.yaml` downloads 8.6.5 but warns about the version of `shake` being newer (0.17.9), which I can force to 0.17.8 by adding the specific version to `extra-deps:`. I don't know if this is the recommended course of action. The thing is I'm trying to have as few different GHC versions downloaded as possible, while working with the latest LTS.

**Comment by power-fungus** [comment]
> Using `stack install --stack-yaml=stack-8.6.5.yaml` begins downloading GHC 8.6.4. I thought it would download only 8.6.5?

This is a problem and we should fix this.

**Comment by DavSanchez** [comment]
Hmm, I'm trying this again then, maybe I'm doing something wrong.

For example, to install HIE for GHC 8.6.5, one would do:

```bash
stack install --stack-yaml=stack-8.6.5.yaml ./install.hs hie-8.6.5
stack install --stack-yaml=stack-8.6.5.yaml ./install.hs build-data
```

Am I right?

**Comment by power-fungus** [comment]
Running `stack install --stack-yaml=stack-8.6.5.yaml` (this is the whole command) in the root-directory should copy `hie` and `hie-wrapper` binaries to `~/.local/bin` (or whatever that is in macos).

The command `stack install --stack-yaml=stack-8.6.5.yaml ./install.hs hie-8.6.5` does not make much sense.

**Comment by DavSanchez** [comment]
I see, I was mixing the two different commands then (`stack ./install.hs ...` vs `stack install ...`).

I guess using `stack install ...` also includes the hoogle docs generation for that GHC version?

**Comment by power-fungus** [comment]
> I guess using stack install ... also includes the hoogle docs generation for that GHC version?

It does not. However:
* hoogle-docs are not ghc-version-dependent
* calling `hoogle generate` once a while is fine and does not need to happen on every rebuild of `hie`

**Comment by DavSanchez** [comment]
Ok! Already done. Thanks for all the assistance! Please feel free to close the issue.
