### ISSUE TITLE
Configure specific hints

### ISSUE THREAD

**Issue by mb720** [haskell/haskell-ide-engine#1350]
I'd like to configure specific code hints that HIE provides. Let's say I'm hinted to

    [Use tuple-section]

in my code but I decide that `tuple-section` is just not for me.

How would I tell HIE that I don't want to see that hint again?

**Comment by fendor** [comment]
Afaik, hie uses hlint to offer linting. Adding `.hlint.yaml` to your project root is honoured. Have a look at https://github.com/ndmitchell/hlint/blob/master/data/default.yaml to see how that may look like.

**Comment by mb720** [comment]
You're right!

Creating a `.hlint.yaml` in the project root with

    - ignore: {name: Use tuple-section}

achieved what I wanted to do. Sweet!
