### ISSUE TITLE
GHC 8.8.1-rc1 is out

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#1353]
https://www.haskell.org/ghc/blog/20190722-ghc-8.8.1-rc1-released.html

I wonder if we can use it to try building HIE with `cabal` and file some dependency bugs and/or fix some easily fixed breakage, e.g. due to `MonadFail`.

**Comment by Avi-D-coder** [comment]
I read on Reddit the plan was for 8.8 to hit stack nightly after lts-14 is released. 
Does anyone know where the status of lts-14 is being tracked?
It will be much easier to fix hie once we have a stack nightly to work with.

**Comment by CaptJakk** [comment]
Stack LTS 14 is out now

**Comment by chkno** [comment]
I got stuck at `hslogger`.

`haskell-ide-engine` depends on `hslogger`.

Choosing an older `hslogger` doesn't work: Versions of `hslogger` less than 1.3.0.0 require and old `network` <2.9, and all stackage 8.8.1 snapshots have a newer `network` 3.1.1.0.

Choosing a newer `hslogger` doesn't work: Versions of `hslogger` 1.3.0.0 and greater introduce a dependency on `network-bsd`, and `network-bsd` requires an old `network` <3.1.1.  There is an open issue in `network-bsd` about this: https://github.com/haskell/network-bsd/issues/6

**Comment by alanz** [comment]
I started on it, but with https://github.com/haskell/haskell-ide-engine/pull/1126 hopefully landing soon I will defer until afterwards.

**Comment by bubba** [comment]
Also to keep track, hare is depending on https://github.com/haskell-infra/hackage-trustees/issues/244#issuecomment-544140731

**Comment by jneira** [comment]
There is a pr to make hie gh-8.8.1 compatible: #1482 that will close this one

**Comment by fendor** [comment]
Closed by #1482
