### ISSUE TITLE
HIE error - "Got error while processing diagnostics: readCreateProcess:" in Atom / VSCode

### ISSUE THREAD

**Issue by razvan-panda** [haskell/haskell-ide-engine#1364]
I am getting the following error:

> Got error while processing diagnostics: readCreateProcess: /nix/store/a1fgqywyav0dkmk3kkq3hm8219aas6cw-cabal-helper-0.9.0.0/bin/cabal-helper-wrapper "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" "/home/neo/Projects/haskell-stack-fix" "/home/neo/Projects/haskell-stack-fix/dist-newstyle/build/x86_64-linux/ghc-8.6.4/stack-fix-0.1.0.0" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output" (exit 1): failed

HIE version 0.12.0.0 x86_64 ghc-8.6.4
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library

**Comment by razvan-panda** [comment]
I had done a `cabal new-build` before running in this issue.

The fix was to `rm -rf dist-newstyle/`

**Comment by drewboardman** [comment]
I have the same issue and `rm -rf dist-newstyle/` doesn't fix it.

**Comment by jneira** [comment]
@drewboardman is the error related with `cabal-helper-wrapper` as well? if it is so you could try to execute the call to `cabal-helper-wrapper` directly in a shell to see if it prints some more info about the error.

**Comment by juliendehos** [comment]
I had the same problem. Deleting `~/.cache/cabal-helper` fixed this.
https://github.com/haskell/haskell-ide-engine#nix-cabal-helper-no-such-file-or-directory
