### ISSUE TITLE
A bad SYB traversal eats up a lot of memory

### ISSUE THREAD

**Issue by mpickering** [haskell/haskell-ide-engine#1371]
Observe this heap profile which was taken whilst loading the `Cabal` library into `h-i-e`.

You can see that when opening the `LicenseId.hs` module, something very bad happens. I'm not sure which `IntervalMap` gets so large but it's probably because a `SYB` traversal traverses into some generated definitions which it should avoid. 

http://mpickering.github.io/cabal.hp.html

**Comment by mpickering** [comment]
I fixed it here. Any volunteers to backport to master?

https://github.com/mpickering/haskell-ide-engine/commit/13daf07124770a2643b63f8d581f88cacdea7ce1

When the `.hie` stuff gets merged then this will be unnecessary but for now it makes a huge difference on some modules.

**Comment by fendor** [comment]
I volunteer

**Comment by mpickering** [comment]
This patch doesn't completely solve the issue but it does get part of the way. I am still seeing big memory spikes (300mb of list cons) which must come from generating some of the other maps.

**Comment by mpickering** [comment]
Merged.
