### ISSUE TITLE
Support Cabal 3.0.0.0

### ISSUE THREAD

**Issue by Infinisil** [haskell/haskell-ide-engine#1376]
Recently [Cabal 3.0.0.0](https://hackage.haskell.org/package/Cabal-3.0.0.0/changelog) and [cabal-install 3.0.0.0](https://hackage.haskell.org/package/cabal-install-3.0.0.0/changelog) was released, bringing along the following relevant changes I could find:
- Deprecation of old symbols in https://github.com/haskell/cabal/pull/6022
  This change is relevant because [the version of `cabal-helper` HIE is using](https://github.com/alanz/cabal-helper/tree/eafed5e8c1d82b8daa35775b52361132f2e70261) still references these old symbols. [upstream `cabal-helper`](https://github.com/DanielG/cabal-helper) doesn't reference them anymore.
- New-style builds are now the default, meaning `cabal configure` is not using old-style builds anymore. This is a problem because both `cabal-helper` and `ghc-mod` have the assumption that old-style builds are the default in that they use `cabal configure` and such, and not `cabal v1-configure`. 
  Relevant code in `ghc-mod`: https://github.com/alanz/ghc-mod/blob/910887b2c33237b703417ec07f35ca8bbf35d729/core/GhcMod/CabalHelper.hs#L192-L197.
  Relevant code in `cabal-helper`: https://github.com/alanz/cabal-helper/blob/eafed5e8c1d82b8daa35775b52361132f2e70261/src/CabalHelper/Compiletime/Compile.hs#L452

As far as I can see, this results in HIE being broken for everybody using Cabal 3.0.0.0

### Possible solutions

- Patch `ghc-mod` and `cabal-helper` to use `v1-` commands explicitly
- One of
  - Patch `cabal-helper` to not use the deprecated symbols anymore, by looking at what upstream `cabal-helper` did to remove them. This might be simple or it might not be simple at all
  - Update `cabal-helper` to the upstream version, this is what https://github.com/haskell/haskell-ide-engine/pull/1245 tries to do, but there seems to be some problems
  - I also think [hie-bios](https://github.com/haskell/haskell-ide-engine/pull/1126) by @mpickering would solve this, though this doesn't look like it's going to be merged quickly

Ping @fendor @bubba @alanz @mpickering @DanielG 

Related issues:
- https://github.com/Infinisil/all-hies/issues/22
- https://github.com/haskell/haskell-ide-engine/issues/1373
- https://github.com/NixOS/nixpkgs/issues/67761

**Comment by mouse07410** [comment]
I'm afraid it still does not work with the current master:
```
$ cabal v2-run ./install.hs --project-file install/shake.project hie-8.6.5
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (exe:script) (configuration changed)
Configuring executable 'script' for fake-package-0..
Preprocessing executable 'script' for fake-package-0..
Building executable 'script' for fake-package-0..
[1 of 1] Compiling Main             ( Main.hs, /Users/ur20980/src/haskell-ide-engine/dist-newstyle/build/x86_64-osx/ghc-8.6.5/fake-package-0/x/script/build/script/script-tmp/Main.dyn_o )
Linking /Users/ur20980/src/haskell-ide-engine/dist-newstyle/build/x86_64-osx/ghc-8.6.5/fake-package-0/x/script/build/script/script ...
. . . . .
Installing   cabal-install-3.0.0.0 (all, legacy fallback)
Completed    cabal-install-3.0.0.0 (all, legacy fallback)
Symlinking 'hie'
Warning: Failed to build documentation for haddock-api-2.22.0 (which is
required by exe:hie-wrapper from haskell-ide-engine-0.12.0.0 and exe:hie from
haskell-ide-engine-0.12.0.0).
Symlinking 'hie-wrapper'
Error when running Shake build system:
  at want, called at src/Development/Shake/Internal/Args.hs:81:69 in shk-0.17.8-b3e20d9c:Development.Shake.Internal.Args
* Depends on: hie-8.6.5
  at need, called at src/HieInstall.hs:90:37 in hie-install-0.8.0.0-inplace:HieInstall
* Depends on: cabal-hie-8.6.5
* Raised the exception:
/Users/ur20980/.local/bin/hie: copyFile:atomicCopyFileContents:withReplacementFile:copyFileToHandle:openBinaryFile: does not exist (No such file or directory)

```

Here's the full output:  [cabal-v2-fail.txt](https://github.com/haskell/haskell-ide-engine/files/3614329/cabal-v2-fail.txt)

Before you ask - `stack` fails to build `hie` too:
```
$ stack -v ./install.hs hie-8.6.5 2>&1 | tee ~/stack-fail.txt

--  While building package hie-install-0.8.0.0 using:
      /Users/ur20980/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 build lib:hie-install --ghc-options ""
    Process exited with code: ExitFailure 1
$
$ /Users/ur20980/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --version
Cabal library version 2.4.0.1
$
```

Versions:
- MacOS 10.14.6
- GHC-8.6.5 installed via current `ghcup`
- Cabal-3.0.0.0
-Stack-2.1.3

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
$ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
$ uname -a
Darwin xxxxxx 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
$
```

**Comment by fendor** [comment]
Current master does not supprot Cabal 3.0.0.0. 
However, the [hie-bios](https://github.com/mpickering/haskell-ide-engine/) branch does support Cabal 3.0.0.0.
The current efforts to merge hie-bios into master are located in [merge-hie-bios](https://github.com/fendor/haskell-ide-engine/tree/merge-hie-bios) and will be merged as soon as regressions and tests work.

**Comment by mouse07410** [comment]
What would you recommend me to do? Pull a different branch?

**Comment by fendor** [comment]
Yes, please different issue. It may be stack and MacOS specific.

**Comment by bubba** [comment]
@mouse07410 see https://gitlab.haskell.org/ghc/ghc/issues/15769

**Comment by fendor** [comment]
We are supporting Cabal 3.0.0.0 from #1126 on!
