### ISSUE TITLE
Change HieDiff to represent a standard patch format

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#138]
At the moment, `HieDiff` is defined as

```haskell
data HieDiff = HieDiff
  { dFirst  :: !FilePath
  , dSecond :: !FilePath
  , dDiff   :: ![Diff (Int,T.Text)]
  } deriving (Show,Eq,Generic)
```

Change this to use a standard patch format, so that existing tools to apply patches in an IDE can be used. So it becomes

```haskell
data HieDiff = HieDiff
  { dFirst  :: !FilePath
  , dSecond :: !FilePath
  , dDiff   :: !T.Text
  } deriving (Show,Eq,Generic)
```

Where `dDiff` is formatted according to [unified format](http://www.gnu.org/software/diffutils/manual/html_node/Unified-Format.html), or similar.

The diff could possibly be represented as `[T.Text]`, one string per line instead.

See also #132

**Comment by mgsloan** [comment]
:+1:

**Comment by alanz** [comment]
Perhaps we should create a plugin that manages applying patches, which takes a possibly mult-file diff and returns a list of changed files, so they can be reloaded in the IDE if there are buffers for them.

**Comment by alanz** [comment]
But my original point is that applying patches is not a haskell-specific thing, so should perhaps be delegated to the idiomatic mechanism within a given IDE.

**Comment by JPMoresmau** [comment]
Yes, if we return only a string in a given format, we also need to provide an operation that parses that string and returns a structure, to avoid several different clients to duplicate the same work. A patch plugin that can parse, apply, etc patches would be good.

**Comment by alanz** [comment]
Well, we already have that structure in the current HieDiff structure.
Perhaps we need this new one too, and we move into the content negotiation
space, where the calling command can specify which format should be returned

**Comment by alanz** [comment]
The [ppDiff](http://hackage.haskell.org/package/Diff-0.3.2/docs/Data-Algorithm-DiffOutput.html#v:ppDiff) function puts out

    5,9c5,9
    < foo x = if odd x
    <         then
    <           x + 3
    <         else
    <           x
    ---
    > foo x = case odd x of
    >   True  ->
    >             x + 3
    >   False ->
    >             x

I note with interest that @JPMoresmau is listed as one of the authors.

Is this ok?

**Comment by cocreature** [comment]
Looks reasonable.
