### ISSUE TITLE
Installing fails with network related error

### ISSUE THREAD

**Issue by dadepo** [haskell/haskell-ide-engine#1387]
OS: MacOs Mojave, 10.14.5
Stack --version: Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2 

I am installing by running the following commands:

```
$ git clone https://github.com/haskell/haskell-ide-engine --recursive
$ cd haskell-ide-engine && ./install.hs build-all
```

But doing this ends the installation processes with the following message:

```
HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/hackage.fpcomplete.com/package/connection-0.2.8.tar.gz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 6, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "s3.amazonaws.com", service name: Just "443"): does not exist (nodename nor servname provided, or not known))
Progress 85/101
)

```

*Edit*
I tried this twice already with the same error

**Comment by fendor** [comment]
This is an error thrown by `stack`. Probably temporary, or your `stack` is not properly configured.
So, can yan try to build the project only with `stack build` and see if the same error happens.

NOTE: `build-all` is with a high likelihood not what you want see, #1383 for why.
I would suggest, you install it only for ghc versions you are currently using, e.g. 
```bah
# install hie for ghc version 8.6.4
> stack install.hs hie-8.6.4

# generate hoogle db, etc...
# you only have to do this once in a while
> stack install.hs build-data 
```

**Comment by dadepo** [comment]
Followed your suggestion...

First time it failed...with same error...
Second time, it succeeded! 

Thanks!
