### ISSUE TITLE
"Mismatching GHC versions" warning occurred but both HIE and project are using same version, 8.6.5

### ISSUE THREAD

**Issue by MaguroChicken** [haskell/haskell-ide-engine#1390]
![image](https://user-images.githubusercontent.com/37610753/65349109-9b596480-dc1d-11e9-99e5-e2484d900f8b.png)
![image](https://user-images.githubusercontent.com/37610753/65349134-a9a78080-dc1d-11e9-888b-c69ed8844398.png)

My environment:
Windows 10 1903
stack 2.1.3
hie build command: "~$ stack ./install.hs hie-8.6.5"

**Comment by fendor** [comment]
That is a very creative error message!
Seemingly, the output of some tool has changed. since hie believes the GHC version is: `Project is Active code page: 65001 8.6.5`, which should not be the output of any of the tools.
What is the output of the commands: `stack ghc -- --numeric-version` and `ghc --numeric-version`?
Is the project a stack or cabal project?

**Comment by MaguroChicken** [comment]
Ok, I executed.
PS> stack ghc -- --numeric-version
8.6.5

PS> ghc --numeric-version
ghc command not found

This is stack project generated in my Linux environment, Arch Linux.
I had installed hie to the linux environment in same way, same version; it was working successfully.

stack PATH has been already been added to System “PATH” environment variable by stack installer.
Is it necessary to add ghc-path to System PATH environment variable?

**Comment by fendor** [comment]
No, it is fine that ghc is not on the path.
However, the error is rather mysterious for me.

**Comment by MaguroChicken** [comment]
Sorry, some important imformations are lacking.
so, let me walk you through the process.

When I built hie first time,
Permission denied error occurred due to cp932 default encoding.
so I executed `chcp 65001` to set default encoding to UTF-8.
then, I executed `stack ./install.hs stack-hie-8.6.5` again.
Building was finished and hie, hie-wrapper binaries were copied to my local/bin directory, on the path.

However the error shown below has occurred.
I overlooked that yesterday.

-----------------
Copied executables to C:\Users\\AppData\Roaming\local\bin:
- hie.exe
- hie-wrapper.exe
# stack (for stack-hie-8.6.5)
stack: src\System\Console\Terminal\Windows.hs:54:39-80: Irrefutable pattern failed for pattern [r, c]

Error when running Shake build system:
  at want, called at src\Development\Shake\Internal\Args.hs:81:69 in shake-0.17.8-61Y8ymjNYLmLEwiUr1tvUu:Development.Shake.Internal.Args
* Depends on: stack-hie-8.6.5
* Raised the exception:
user error (Development.Shake.command, system command failed
Command line: stack --stack-yaml=install/shake.yaml path --local-bin
Exit code: 1
Stderr:
stack: src\System\Console\Terminal\Windows.hs:54:39-80: Irrefutable pattern failed for pattern [r, c]

)
-------------

I don't now why this error occurred, because my another Arch Linux environment did this job well.
Even in this state, both hie and hie-wrapper can be executed and works on VSCode successfully, but
the "Mismatching GHC versions" warning occurred.

**Comment by Anrock** [comment]
`Active code page: 65001` looks like output of `chcp`.

**Comment by MaguroChicken** [comment]
You are probably right.

I'll execute build command again with cp932 encoding tomorrow.
there is some time difference. sorry.

**Comment by MaguroChicken** [comment]
I realized that "Mismatching GHC versions" error is causing by my `chcp 65001`.
I'm sorry that it was my fault.

However,
The problem is that the build fails on the Japanese version of Windows, because of cp932 default encoding.

To check it is Japanese version specific issue, I installed Windows 1809, US version to my Hyper-V virtual machine, and built hie.
It works fine.

Turn to my Host machine and next, I rebuilt hie from first step with cp932 default encoding.
`git clone https://haskell/haskell-ide-engine --recurse-submodule`
`stack install.hs stack-hie-8.6.5`
but permission error occurred. and there were some garbled in warning log. 
```
ghc-mod-core      > GhcMod\Types.hs:364:1: warning: [-Wunused-top-binds]
ghc-mod-core      >     Defined but not used: 窶詫GhcPkgProgram窶・[0m
ghc-mod-core      >     |
ghc-mod-core      > 364 | mkLabel ''Programs
ghc-mod-core      >     | ^^^^^^^^^^^^^^^^^^
ghc-mod-core      >
ghc-mod-core      > GhcMod\Types.hs:364:1: warning: [-Wunused-top-binds]
ghc-mod-core      >     Defined but not used: 窶詫GhcProgram窶・[0m
ghc-mod-core      >     |
ghc-mod-core      > 364 | mkLabel ''Programs
ghc-mod-core      >     | ^^^^^^^^^^^^^^^^^^
ghc-mod-core      >
ghc-mod-core      > GhcMod\Types.hs:364:1: warning: [-Wunused-top-binds]
ghc-mod-core      >     Defined but not used: 窶詫StackProgram窶・[0m
ghc-mod-core      >     |
ghc-mod-core      > 364 | mkLabel ''Programs
ghc-mod-core      >     | ^^^^^^^^^^^^^^^^^^
ghc-mod-core      > [11 of 44] Compiling GhcMod.Options.Options
ghc-mod-core      > [12 of 44] Compiling GhcMod.Monad.Newtypes
ghc-mod-core      > [13 of 44] Compiling GhcMod.Monad.State
ghc-mod-core      >
ghc-mod-core      > GhcMod\Monad\State.hs:67:19: warning: [-Wsimplifiable-class-constraints]
terminateProcess: permission denied (Permission denied)
Progress 3/7
)
```

**Comment by Anrock** [comment]
@MaguroChicken does this error persist if you rerun install.hs? I had similar error multiple times on Windows and after multiple reruns build was successful.

**Comment by MaguroChicken** [comment]
@Anrock
Just like you said, It was built successfully after 3 reruns.
Not only me, but also some people using Windows says that building multiple time is needed.
But I still don't know why "Permission error" and "garbled" occur.

**Comment by Anrock** [comment]
@MaguroChicken AFAIK it's a Windows-specific bug of stack or cabal. And same for garbles probably.

**Comment by Anrock** [comment]
Closing this as upstream issue not specific for HIE.
