### ISSUE TITLE
Serverized stack

### ISSUE THREAD

**Issue by mgsloan** [haskell/haskell-ide-engine#140]
This would be a lot of work, and I'm not sure if the benefits are worth it.  I think it's worth noting down the idea as a P3, though:

It'd be quite cool if HIE serverized stack, by using it as a library. Similarly to how HIE is serverizing GHC, this would mean that the sorts of commands described in #136 could be run without running a new stack process. This way, build environment info could be cached.  This could save us from so noticeable pauses, particularly when using stack with a docker container.  The serverized stack could also potentially provide the info for initializing ghc-mod.

This is likely quite tricky to get correct, as well, particularly if it supports other processes concurrently modifying the package DBs (which would require knowing when to reload the info).

**Comment by arrowd** [comment]
The problem with this is static linking. That is, if user upgrades stack executable, HIE wouldn't immediately pick this upgrade up. It might be OK for stack, but for Cabal it poses a compatibility problem. And we are already linking to Cabal too via ghc-mod (and also directly by my would-be-build-plugin).

There is a smart wrapper called cabal-helper that is used there, actually. It checks if the Cabal varsion it was linked into matches the version that the package was configured with. In case of mismatch, cabal-helper compiles a copy of self and links to the right Cabal version.

So, ideally, we either should create sort of stack-helper, or stick to calling executables. While serverizing stack and Cabal is certainly attractive, I'm currently leaning towards second way.

**Comment by alanz** [comment]
And realistically stack upgrades are rare, and restarting the server when it happens is not that much of a deal

**Comment by jneira** [comment]
I think the use of hie-bios makes this somewhat out of hie scope
