### ISSUE TITLE
Implement a simple cli debugging command

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-ide-engine#1412]
It would be super useful to have an argument in `hie` which when passed causes hie to start, load the project, typecheck files, report any errors and exit. This would allow one to diagnose problems with hie's operation without setting up a lsp client.

Observe a run on `ghcide` with no arguments:

```
 $ ghcide
Starting ghcide (GHC v8.6)
/home/j/projects/upfind
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "/home/j/projects/upfind", cradleOptsProg = CradleAction: default}

[2/6] Converting Cradle to GHC session

[3/6] Initialising IDE session

[4/6] Finding interesting files
Found 2 files

[5/6] Setting interesting files
[DEBUG] Set files of interest to: [NormalizedFilePath "./Setup.hs",NormalizedFilePath "./src/Main.hs"]
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)

[6/6] Loading interesting files
[DEBUG] Finishing shakeRun (took 0.00s, exception: thread killed)
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)
[DEBUG] Finishing shakeRun (took 0.15s, completed)
Files that worked: 2
Files that failed: 0
Done
```

The most important parts of this output to me are: 
- The root directory
- The files of interest 
- The number of working and failed files

It might be the case that this already exists, if so then it would be great to:

- Document this in the readme alongside searchable words like "debug" and "cli"
- Document this in `hie --help`

**Comment by alanz** [comment]
It just struck me that now that we have removed the jsonstdio transport, we were considering removing the `--lsp` flag. This broke clients, so we put it back as a no-op.

Perhaps if `--lsp` is not set, we should run in the CLI diagnostic mode. This will be the logical behaviour for people just having installed it.

**Comment by alanz** [comment]
And I notice the `--lsp` flag is what ghcide does too.

**Comment by fendor** [comment]
Enhanced by #1569 
Now the functionality mirrors more the behaviour of `ghcide`, although since our internals are very different, the output is also different. In particular, we are way more verbose, and I hope that this will prove useful in debugging.

**Comment by expipiplus1** [comment]
Thanks!
