### ISSUE TITLE
Using go-to-definition function twice makes weird jump to temporary file and breaks HIE

### ISSUE THREAD

**Issue by sim590** [haskell/haskell-ide-engine#1415]
I am using HIE with Vim 8 and the LanguageClient plugin.

1. I issue `:call LanguageClient#textDocument_definition()` on the keyword under the cursor.
2. The cursor ends up to the expected location but in a different file named `MyFileName$N-0.hs` where `$N` is some number.
3. I press `ctrl-o` to make the cursor jump back to its previous location (therefore the initial word).
4. I issue the same command again and the cursor ends up in another buffer called `MyFileName$N-0.hs`. This buffer is empty.
5. I jump back to previous location (the actual file) with `ctrl-o` and HIE is broken with message (here my file was named "Toto.hs"):

        [LC] [Error] Got error while processing diagnostics: <no location info>: error:^@    module ?main:M    ain? is defined in multiple files: ghc-mod23608/Toto21840-023605-3.hs^@                                                         ghc-mod23609/Toto23188-023605-4.hs^@                                                         ghc-mod23607/Toto23605-023605-11.hs
6. Steps 4 to 5 can be repeated indefinitely.

I then have to restart either Vim or LanguageClient to make everything work again. For exemple, I can reproduce with this [file](https://github.com/haskell/haskell-ide-engine/files/3739587/Toto.hs.txt). I can't reproduce this with [this file](https://github.com/haskell/haskell-ide-engine/files/3739603/Deque.hs.txt) though.

Curiously, after step 2, I can stick in that foreign buffer and I won't be having trouble using the go-to-definition function in there.

**Comment by sim590** [comment]
I have just found out that this happens only when using a file `/tmp/`... I consider this a bug, but it is restricted to a specific case.

**Comment by jneira** [comment]
@sim590 this one could be fixed with the recent changes merging the hie-bios branch, could you try again with hie master?

**Comment by sim590** [comment]
I have to recompile the program. I will try to do that in the coming days.

**Comment by sim590** [comment]
Rebuilding with `stack ./install.hs hie-8.6.5` on current master (revision 9e9432a2) does seem to lead me to the conclusion that the bug is gone. So we could close this.

**Comment by jneira** [comment]
@sim590 thanks for test it, closing
