### ISSUE TITLE
Can't load clang++

### ISSUE THREAD

**Issue by ilyakooo0** [haskell/haskell-ide-engine#1417]
I installed hie from nix and it fails when loading a project with the following message:

```
DEBUG: loadTargets: filterModSums: True
info: loadTargets:
      Target needs interpeter, switching to LinkInMemory/HscInterpreted. Perfectly normal if anything is using TemplateHaskell, QuasiQuotes or PatternSynonyms.
hie-8.6.5: loadArchive: Neither an archive, nor a fat archive: `/nix/store/z96dbzxpz1mcdxajc3k12b65mspqbb21-clang-wrapper-7.1.0/bin/clang++'
hie-8.6.5: loadArchive "/nix/store/z96dbzxpz1mcdxajc3k12b65mspqbb21-clang-wrapper-7.1.0/bin/clang++": failed
```

**Comment by mpickering** [comment]
Steps to reproduce?

**Comment by ilyakooo0** [comment]
I didn't really do anything special. I just opened my project. 

Can't share the project itself unfortunately. 

Tried nuking whole `/nix` and reinstalling. Didn't help.

**Comment by mpickering** [comment]
Unless you provide a way to reproduce the problem then there's not much we can do.

**Comment by ilyakooo0** [comment]
This is definitely a nix-related issue. Just installed from source and it works fine with the exact same project.
