### ISSUE TITLE
Install.hs: cabal-ghcs shows unsupported GHC versions

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-ide-engine#1445]
Based on https://github.com/haskell/haskell-ide-engine/issues/1436#issuecomment-552214342.

Example:
```bash
$ stack install.hs cabal-ghcs
run from: stack

******************************
Found the following GHC paths:
ghc-8.8.1: /opt/ghc/bin/ghc
ghc-8.0.1: /usr/bin/ghc

******************************

Build completed in 0.00s
```

However, since we do not support these versions, they should not be detected, since these are transitively used to show the help-message. 
Bug-fix could be to intersect the found ghc versions with the supported ghc versions, which are obtained by parsing all `stack-*.yaml` files in the directory.

**Comment by jneira** [comment]
Ideally we should not rely on stack if user are executing the script with cabal so  maybe we should keep a explicit list of ghc supported versions, although it would be somewhat duplicated as stack.yaml resolvers

**Comment by fendor** [comment]
We are not reyling on stack but only on the existence of `stack-$GHC.yaml` files to support version `$GHC`.
This is fine, since we support the same GHC versions for cabal and stack.

**Comment by jneira** [comment]
Oh you are right, stack itself would not be needed only access to `stack*.yaml` files. 
But it still could be done the other way around: to have the explicit versions in the code and even check that the `stack-*.yaml` files match those versions (it had catch the recent reintroduction of stack-8.2.2.yaml file f.e.) so only supported versions would be available in the stack script independently of the actual stack.yaml files.

But maybe it goes so far in see the code as the unique source of truth :wink:
