### ISSUE TITLE
Loosen restriction on shake version

### ISSUE THREAD

**Issue by flip111** [haskell/haskell-ide-engine#1460]
I changed this to LTS-14.14 https://github.com/haskell/haskell-ide-engine/blob/master/install/shake.yaml#L2

Then i got

```
$ stack ./install.hs help

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hie-install-0.8.0.0(+run-from-stack):
    shake-0.18.3 from stack configuration does not match ==0.17.8  (latest matching version is 0.17.8)
needed since hie-install is a build target.

Some different approaches to resolving this:

  * Set 'allow-newer: true' in C:\sr\config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the following to your extra-deps in C:\Users\philippe\haskell\haskell-ide-engine\install\shake.yaml:

- shake-0.17.8@sha256:d049e261ca6365b6378af6470cb2fca908ced8c5cc862fafc89f00d6baa2f35f,14842

Plan construction failed.
```

Which seems to be declared here https://github.com/haskell/haskell-ide-engine/blob/master/install/hie-install.cabal#L22

Is it absolutely required to have that exact version of the build system? Perhaps it could be changed to require some minimum version instead ??

**Comment by fendor** [comment]
Using a lower bound should be fine.

**Comment by jneira** [comment]
As bonus it would be great that shake resolver ghc was the same as the latest used by hie itself to only download/use one ghc for both.

**Comment by fendor** [comment]
I think that is not possible in general, but people can do it themselves if they want to by changing the snapshot in `shake.yaml`.
