### ISSUE TITLE
What is pre-requirements on hie-runtime?

### ISSUE THREAD

**Issue by junjihashimoto** [haskell/haskell-ide-engine#1467]
What is pre-requirements on hie-runtime?
When we run hie, what should we needs programs and data?
(I read architecture-document of hie.)

Hie needs some programs and data files, when it runs on IDE like vscode.
I want to copy and move the file because it takes a long time to compile when running in a new environment.
So I copied following files and hoogle-db.

```
cabal-helper-wrapper
hie
hie-8.6
hie-8.6.5
hie-wrapper
```

But the system output next errors. It may try to read dist-dir of cabal-helper.
I would like to know what files should I copy.
```
hie-8.6.5: Could not find $libexecdir/cabal-helper-wrapper
```

**Comment by fendor** [comment]
Yeah, until #1126 lands, it is almost impossible to reliably move an hie installation.
See https://github.com/haskell/haskell-ide-engine/issues/1068 for details.

**Comment by junjihashimoto** [comment]
Thank you for sharing current status.
