### ISSUE TITLE
Mac+vs code: The Haskell HIE server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by YouWillBe** [haskell/haskell-ide-engine#1470]
Can not work with vscode in macOS
![image](https://user-images.githubusercontent.com/16474244/69592948-8d1b3080-1032-11ea-9d44-7ea061d192cd.png)
Environment:
- macOS 10.15.1
- ```
  which hie
  /Users/kangyu/.local/bin/hie
  ```
- ```
  $ hie --version
  Version 0.13.0.0, Git revision c1e57f5c11c504badb7a0aaf5897e6433d6243e3 (3114 commits) x86_64 ghc-8.6.5
  ```
- ```
  $ ls ~/.stack/programs/x86_64-osx
  ghc-8.6.5           ghc-8.6.5.installed ghc-8.6.5.tar.bz2
  ```

**Comment by mpickering** [comment]
Sounds like you don't have `hie-8.6.5` installed.

**Comment by YouWillBe** [comment]
> Sounds like you don't have `hie-8.6.5` installed.

Seriously? Look at the third environment.

**Comment by fendor** [comment]
They are referring to `hieWrapper: callProcess: /Users/kangyu/.local/bin/hie-8.6.5 (exit -11): failed `.
So, what happens if you manually invoke this process?

**Comment by YouWillBe** [comment]
> They are referring to `hieWrapper: callProcess: /Users/kangyu/.local/bin/hie-8.6.5 (exit -11): failed `.
> So, what happens if you manually invoke this command?

![image](https://user-images.githubusercontent.com/16474244/69729037-94d8f300-1160-11ea-9213-2694440a2f49.png)
![image](https://user-images.githubusercontent.com/16474244/69729076-aa4e1d00-1160-11ea-9bc3-bff0c4fed079.png)

**Comment by fendor** [comment]
In your log above, hie-wrapper tries to invoke `hie-8.6.5` with the path `/Users/kangyu/.local/bin/hie-8.6.5` but fails.
What happens if you invoke `/Users/kangyu/.local/bin/hie-8.6.5`?

**Comment by YouWillBe** [comment]
> In your log above, hie-wrapper tries to invoke `hie-8.6.5` with the path `/Users/kangyu/.local/bin/hie-8.6.5` but fails.
> What happens if you invoke `/Users/kangyu/.local/bin/hie-8.6.5`?

![image](https://user-images.githubusercontent.com/16474244/69729450-4e37c880-1161-11ea-946e-d37136078b11.png)

**Comment by fendor** [comment]
Maybe a haskell-lsp bug?

**Comment by bubba** [comment]
Can you turn the verbose logging option in the vscode options and attach the logs?

**Comment by codygman** [comment]
Is this issue not because of the mismatching project ghc version of 8.8.1 and hie version of 8.6.5 in the attached images?

**Comment by YouWillBe** [comment]
stack ghc is 8.6.5, I init project use this:
```bash
stack new my-project yesodweb/sqlite && cd my-project
stack install yesod-bin --install-ghc
stack build
```

**Comment by codygman** [comment]
@YouWillBe In [this comment](https://github.com/haskell/haskell-ide-engine/issues/1470#issuecomment-559099199) I see:

![image](https://user-images.githubusercontent.com/225847/70148483-e525e880-166b-11ea-9869-a7b6a1e6783e.png)

**Comment by YouWillBe** [comment]
> @YouWillBe In [this comment](https://github.com/haskell/haskell-ide-engine/issues/1470#issuecomment-559099199) I see:
> 
> ![image](https://user-images.githubusercontent.com/225847/70148483-e525e880-166b-11ea-9869-a7b6a1e6783e.png)

... It's in my home`~`, not my project
![image](https://user-images.githubusercontent.com/16474244/70197116-c7c54d00-1745-11ea-820c-1309cfc44ba1.png)

**Comment by YouWillBe** [comment]
> Can you turn the verbose logging option in the vscode options and attach the logs?
> […](#)
> On 27 Nov 2019, at 15:30, 亢禹 ***@***.***> wrote: Maybe a haskell-lsp bug? Oddly enough, it works fine in nvim. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Same as stderr

**Comment by aomerk** [comment]
Did you install haskellstack from [their site](https://docs.haskellstack.org/en/stable/README/)
