### ISSUE TITLE
Improve installation documentation (For Fedora, zlib-devel is also needed)

### ISSUE THREAD

**Issue by Shenmin-Z** [haskell/haskell-ide-engine#1471]
In `Installation` part(https://github.com/haskell/haskell-ide-engine/blame/master/README.md#L170), it says
```
Fedora:

sudo dnf install libicu-devel ncurses-devel
```

In my experience, `zlib-devel` is not installed by default and is needed in the building process, otherwise there would be error like `While building package digest-0.0.1.2 `.

**Comment by jneira** [comment]
Thanks for reporting, could you make a pr to improve the README?

**Comment by Shenmin-Z** [comment]
https://github.com/haskell/haskell-ide-engine/pull/1472/commits

Not sure if I put it in the right place...

**Comment by jneira** [comment]
closed by #1472, thanks for the update!

**Comment by JohnTasto** [comment]
`zlib1g-dev` is needed in Ubuntu 20.04.

**Comment by jneira** [comment]
@JohnTasto thanks for pointing it out, are you interested in make a pr wadding it?

**Comment by JohnTasto** [comment]
#1787

I just followed @Shenmin-Z's lead since I'm not sure that it affects all variants.
