### ISSUE TITLE
Got error while processing diagnostics: readCreateProcess

### ISSUE THREAD

**Issue by fuszenecker** [haskell/haskell-ide-engine#1477]
Cabal 3.0.0.0, GHC 8.6.5 (pinned).

```
VS Code 
Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

When I create a pure cabal project, I receive the same error message:

```
Got error while processing diagnostics: readCreateProcess: 
C:\Users\rofu01\dev\haskell-ide-engine\.stack-work\install\f2ceea48\bin\cabal-helper-wrapper.exe 
"--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" 
"C:\\Users\\rofu01\\dev\\_x" 
"C:\\Users\\rofu01\\dev\\_x\\dist-newstyle/build\\x86_64-windows\\ghc-8.6.5\\x-0.1.0.0" 
"package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" 
"non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" 
"ghc-options" "source-dirs" "entrypoints" "needs-build-output" (exit 1): failed
```

**Comment by jneira** [comment]
Hi! could you share the output calling directly the `cabal-helper-wrapper` executable in debug mode with something like:
```
set CABAL_HELPER_DEBUG=1 && C:\Users\rofu01\dev\haskell-ide-engine\.stack-work\install\f2ceea48\bin\cabal-helper-wrapper.exe "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "v1-style" "C:\\Users\\rofu01\\dev\\_x" "C:\\Users\\rofu01\\dev\\_x\\dist-newstyle/build\\x86_64-windows\\ghc-8.6.5\\x-0.1.0.0" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output"
```
...replacing the paths with the actual ones if necessary

**Comment by vvviiimmm** [comment]
Happens for me after upgrading to VSCode 1.40.2. 
MacOS Catalina 10.15

Logs:
```
cabal-helper-wrapper: /Users/vi/dev/projects/test-project/dist-newstyle/build/x86_64-osx/ghc-8.6.5/x2019-0.1.0.0/setup-config: openFile: does not exist (No such file or directory)
```

The `setup-config` file is actually located at 
`/Users/vi/dev/projects/test-project/dist-newstyle/build/x86_64-osx/ghc-8.6.5/x2019-0.1.0.0/x/x2019/setup-config`

**Comment by fendor** [comment]
Current hie master does not support cabal 3.0.0.0, is your cabal version 3.0.0.0?

**Comment by vvviiimmm** [comment]
@fendor 
```
~ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
```

**Comment by fendor** [comment]
Try deleting `~/.cache/cabal-helper-wrapper`. Other than that, hopefully this issue is resolved when we mege #1126

**Comment by fendor** [comment]
Initial issue is about Cabal 3.0.0.0, afaict. Should be fixed by #1126. 
@vvviiimmm would you mind trying, too, with the new changes and report back?

**Comment by AraragiHokuto** [comment]
> Happens for me after upgrading to VSCode 1.40.2.
> MacOS Catalina 10.15
> 
> Logs:
> 
> ```
> cabal-helper-wrapper: /Users/vi/dev/projects/test-project/dist-newstyle/build/x86_64-osx/ghc-8.6.5/x2019-0.1.0.0/setup-config: openFile: does not exist (No such file or directory)
> ```
> 
> The `setup-config` file is actually located at
> `/Users/vi/dev/projects/test-project/dist-newstyle/build/x86_64-osx/ghc-8.6.5/x2019-0.1.0.0/x/x2019/setup-config`
> 
> For new `cabal init` projects HIE starts and works normally until `cabal new-build` is executed, then we get the error above.

Got similar issue here under Archlinux & Emacs, with HIE build from source (AUR one hangs at 'Typechecking <file> in VSCode and gave no response in emacs here)

Just pulled new source from master branch and building now, will report back as soon as building is finished

**Comment by vvviiimmm** [comment]
Confirm, it is fixed, thanks a lot!
