### ISSUE TITLE
Applying refactor using apply-refact removes unrelated code

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-ide-engine#1478]
* From https://github.com/mpickering/haskell-ide-engine/issues/77
* When trying to apply a refactor unrelated code (usually above the refactor) is removed
* Although it is reproduced some times in other os's in windows fails consistently
* It could be caused by the fact temp vfs files has other line endings than the original (in other os's would be triggered by being the vfs temp file not in sync with the original one)

![hie-bad-refactor](https://user-images.githubusercontent.com/54035/70461632-6c82ba00-1ab9-11ea-9256-dc764e11d9ff.gif)

It has removed imports and the function above the one with the redundant brackets (but it removed the brackets as well 😆 )

Maybe related #1448

**Comment by alanz** [comment]
I suspect it could be the line ending issue.

Can you perhaps add a copy of the `applyEdit` command sent for this example?  together with the actual file used.

**Comment by jneira** [comment]
Yeah, that was my guess too. I collected some data for the original issue:
* [json message with the code edits formatted](https://gist.github.com/jneira/382b172f118d99ea1ced8e504197146c#file-edit-json)
* temp files [before](https://gist.github.com/jneira/382b172f118d99ea1ced8e504197146c#file-870452232-6-lib-hs-hs) and [after ](https://gist.github.com/jneira/382b172f118d99ea1ced8e504197146c#file-870452232-7-lib-hs-hs)the refactor

**Comment by alanz** [comment]
maybe you should invoke hlint CLI on that file on the given machine, to see what it does.  That gives a baseline at least.

**Comment by jneira** [comment]
i tested hlint + apply-refact in the console and they apply the refactor fine, so i am inclined to think that the main suspect would be the temp file.

**Comment by jneira** [comment]
I've just checked it again:

```console
PS D:\dev\ws\haskell\cabal-test> type .\src\Lib.hs
module Lib where
import qualified Data.ByteString.Char8 as BS

test :: BS.ByteString
test = BS.pack "Hello Haskell"

test2 :: [a]
test2 = ([])
PS D:\dev\ws\haskell\cabal-test> hlint .\src\Lib.hs --refactor
module Lib where
import qualified Data.ByteString.Char8 as BS

test :: BS.ByteString
test = BS.pack "Hello Haskell"

test2 :: [a]
test2 = []
PS D:\dev\ws\haskell\cabal-test> 
```

**Comment by jneira** [comment]
Ok, i am testing master version of hie + master of haskell lsp (to get hlint hints in windows) in win 7 and cant reproduce and temp files are exactly equal to original ones.
 I've switched again to hie-bios and the issue is reproduced and the temp files have incorrect line endings (so it confirms our suspects)

So maybe i moved the issue here hastily, i'll test again in windows 10 master version just in case.

**Comment by jneira** [comment]
Ok, i've traced the write of the temp file in the mpickering/write-persist-file branch:
```
2019-12-12 12:28:38.6743356 [ThreadId 51] - haskell-lsp:persistFileVFS: Writing virtual file contents: uri = NormalizedUri "file:///D:/ws/haskell/cabal-test/lib/CabalTestLib.hs", virtual file ="C:\\TEMP\\haskell-lsp10420\\CabalTestLib.hs-00000-74206730.hs", contents = {-# LANGUAGE OverloadedStrings #-}

module CabalTestLib where



import Network.HTTP.Types.URI

import qualified Data.ByteString.Char8 as BS

import Data.Char



urlEncoded :: BS.ByteString

urlEncoded = BS.pack "Hi"



test :: IO ()

test = (putStrLn "hi")
```
Otoh i've checked that if i edit the temp file to make it equal to the original one the refactor works

**Comment by jneira** [comment]
Ok, i think i've found what triggers the issue: to having set CRLF (you can see it in the bottom right of the vscode window) in visual studio line endings. It doesnt depend on hie version.
I dont know why a project had one or another cause i did not change it manually

So the immediate workaround is to use LF in vscode (clicking the CRLF label in the bootom right and choosing LF)

However imo hie should handle CRLF gracefully so maybe we should replace `\r\n` by `\n` them at top level, when handling the files content

**Comment by jneira** [comment]
Another solution could be honour `\r\n` and fix the write of the temp file to avoid additional line breaks

**Comment by jneira** [comment]
The fix has been applied to the next `haskell-lsp` version. This version can't be used by actual hie master version as is so the fix will be available only for the hie-bios branch until it is merged (hopefully sooner than later)
