### ISSUE TITLE
Issue with hover and linting errors stopped working

### ISSUE THREAD

**Issue by cdimitroulas** [haskell/haskell-ide-engine#1501]
Hi there I'm having some issues getting haskell-ide-engine to work correctly in `neovim` (I'm using `Coc`).

I had everything working at one point but I believe that since I started using multiple versions of `hie` I have had problems.

The main issues are that the hover action hangs (`Coc` throws a timeout error) and that the linting errors are not appearing in my editor any longer.

Versions:
- stack 2.1.3
- Attempting to use `hie-8.6.4` (installed via stack with `stack ./install.hs stack-hie-8.6.4` && `stack ./install.hs stack-build-data`)
- neovim 0.4.2

Looking at `CocInfo` when I open a Haskell file shows the following info from `hie-wrapper`:
```
2019-12-26 18:19:09.420849473 [ThreadId 4] - Run entered for HIE(hie-8.6.4) Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea4be977fa405dc41f (3496 commits) x86_64 ghc-8.6.4
2019-12-26 18:19:09.421134102 [ThreadId 4] - Current directory:/home/cdimitroulas/code/cdimitroulas/haskell-learning
2019-12-26 18:19:09.421314011 [ThreadId 4] - args:[]
hie-8.6.4: ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Using hie version: Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea4be977fa405dc41f (3496 commits) x86_64 ghc-8.6.4
2019-12-26 18:19:09.451671501 [ThreadId 8] - Cabal-Helper dirs: ["/home/cdimitroulas/code/cdimitroulas/haskell-learning","/home/cdimitroulas/code/cdimitroulas/haskell-learning/File.hs"]
```

I'm not sure why the `Cabal-Helper` dirs includes a file called `File.hs` which doesn't exist?

The relevant part of my Coc config:
```
  "languageserver": {
    "haskell": {
      "command": "hie-wrapper",
      "rootPatterns": ["stack.yaml", "cabal.config", "package.yaml"],
      "filetypes": ["hs", "lhs", "haskell"],
      "initializationOptions": {
        "languageServerHaskell": {
          "hlintOn": true
        }
      }
    }
  },
```

I've tried running `hie-wrapper` with the `--debug` and `--vomit` arguments but I wasn't able to glean any information from that. If you would like those verbose logs then let me know and I can post them here.

**Comment by fendor** [comment]
You are encountering #1495 
Work-around, put a `ghc` on the path or wait for #1496 to land.

**Comment by cdimitroulas** [comment]
Ah that's great, thanks for the links and for your hard work to fix this particular issue @fendor.

Feel free to close this issue as a duplicate since it's already being tracked in 1495
