### ISSUE TITLE
Create --one-shot flag to run one cmd and exit

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#154]
And/or add a new "Exit" command to the base plugin

**Comment by glittershark** [comment]
:+1:

**Comment by glittershark** [comment]
:grinning:

**Comment by alanz** [comment]
What is an appropriate single char short form, or should we go with the long form only.

"-o" tends to mean output file in most cases. "-s" does not really mean much.

**Comment by glittershark** [comment]
My instinct is -n (which in my experience usually means --dry-run, but could be adapted to --oNe-shot). I don't feel a short option is entirely necessary, however, since the idea is this'll mostly be run by IDE/editor frontends instead of by the users themselves

**Comment by cocreature** [comment]
I would just go for a long form, if a short form is not immediately obvious and you don’t need to type it hundreds of times a short form isn’t very useful.

**Comment by alanz** [comment]
agree, and that is how I did it already. Just need to coordinate reply, and it is done
