### ISSUE TITLE
Enable nix for cabal

### ISSUE THREAD

**Issue by voidcontext** [haskell/haskell-ide-engine#1543]
Now that cabal 3.0.0.0 is supported, is it possible to enable nix for hie's internal cabal build when building the project?

**Comment by mpickering** [comment]
What does this question mean? I don't know what "enabling nix" means. If you can use `cabal v2-repl` to load the project then you can load it into HIE.

**Comment by voidcontext** [comment]
It means that when I run `cabal build` only the project files are compiled, all other dependencies are downloaded from the nix cache (using `--enable-nix` or `nix: True` in `~/.cabal/config`). But when `hie` builds the project it downloads and compile the dependencies just like without `--enable-nix`.

I hope it is clear now.

**Comment by fendor** [comment]
I thought enable-nix doesn't do anything with cabal 3.0?

**Comment by voidcontext** [comment]
@fendor I am going to be honest here: I am just starting with nix and part of the whole setup is still a bit mystery to me, but somehow it works. What I did is I ran cabal configure in the nix-shell (following the answer here: https://stackoverflow.com/questions/27968909/how-to-get-cabal-and-nix-work-together).

**Comment by mpickering** [comment]
`hie` (probably) just invokes `cabal v2-repl` and I was under that impression that "worked with nix". It might be that you need to set hie up to run in your nix shell?

**Comment by voidcontext** [comment]
@mpickering You're right that was it! I am using `hie` with `emacs` and the `lsp-haskell` plugin can be configured to run the `hie` in a `nix-shell`. (For reference: https://github.com/emacs-lsp/lsp-haskell/blob/master/lsp-haskell.el#L61)

Thanks everyone for all the help!
