### ISSUE TITLE
HIE errors on startup for single standalone file

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1550]
Creating a directory with a single `main.hs` file no longer works.  See https://github.com/alanz/vscode-hie-server/issues/190

```
$ hie-8.6.5
Running HIE(hie-8.6.5)
  Version 1.0.0.0, Git revision 7f0824033c3870eb0814e72681dc2bb74fd435e6 (3560 commits) x86_64 ghc-8.6.5
To run as a LSP server on stdio, provide the '--lsp' argument
Current directory:/tmp/blah

args:[]

Looking for project config cradle...

2020-01-05 18:11:04.183746134 [ThreadId 4] - Could not find a Project for file: /tmp/blah/File.hs
2020-01-05 18:11:04.183923802 [ThreadId 4] - Module "/tmp/blah/File.hs" is loaded by Cradle: Cradle {cradleRootDir = "/tmp/blah", cradleOptsProg = CradleAction: Cabal-Helper-None}
Cradle:Cabal project
```

**Comment by fendor** [comment]
Correct, that's why we updated the README: https://github.com/haskell/haskell-ide-engine#project-configuration
Possible work-around: add an explicit `hie.yaml` with a `direct` cradle where you specify the build flags required to build the file.

**Comment by alanz** [comment]
Surely this is a simple case, which we should just support?
