### ISSUE TITLE
BlockArguments support

### ISSUE THREAD

**Issue by paolino** [haskell/haskell-ide-engine#1553]
Is there a way to let hie parse code using BlockArguments syntax extension ? Is it supported ?

**Comment by mpickering** [comment]
Yes, it is supported, could you provide an example which shows your problem?

**Comment by paolino** [comment]
```haskell
{-# LANGUAGE BlockArguments, NoMonomorphismRestriction #-}

f = fmap
        do \x -> 2 * x
```

![image](https://user-images.githubusercontent.com/56350/71818853-623ce700-308a-11ea-96e8-3d7a3187aba3.png)

**Comment by paolino** [comment]
oh I noticed now it's hlint error, then I will have to disable it. Is it possible ?

**Comment by paolino** [comment]
Ok, I've found a flag in vscode settings to exclude hlint. I'm closing the issue. Thanks for such fast response.

**Comment by fendor** [comment]
@paolino You can disable hlint diagnostics.

This bug has the same cause as #1374, hlint is not aware of the language extensions.
