### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by cocreature** [haskell/haskell-ide-engine#159]
We seem to have accumulated some warnings, most of which are probably completely unnecessary (like unnecessary imports), so it would be great if someone could go through them and fix them.

This sounds like a nice issue to get started with hie development.

One thing that’s annoying about this is that we can’t just use `--pedantic` since stack also enables the flags for extra-deps, but that is supposed to be fixed.

**Comment by glittershark** [comment]
Any interest in setting -Werr on CI so this doesn't happen again?

**Comment by cocreature** [comment]
Theoretically: absolutely, I think we even had that some point.

Particallly: Not an potion atm because stack will also set `-Werr` for all extra-deps which causes the build to fail since some of them don’t compile with `-Werr`. We should be able to get rid of the extra-deps rather soon and the stack guys also said they’re going to change this so when either of those happens, we should definitely do that again.
