### ISSUE TITLE
Drop support for GHC 8.6.3

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-ide-engine#1592]
Afaict, it is broken for windows #1008, nobody should be using it.
Removing support for GHC 8.6.3 reduces pressure on CI

**Comment by alanz** [comment]
Given there have been two releases since then, this probably makes sense.

**Comment by fendor** [comment]
The implied question is now how many versions of GHC `8.6` should be supported? For stack users, we should support as many GHC versions as possible, but there is no LTS for GHC versions `8.6.1` and `8.6.2`. That means, for me, that we could drop support for these versions, too, since within an LTS, an update should be trivially possible.
