### ISSUE TITLE
Support GHC 8.8.2

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#1599]
Especially since we now have

Stackage Nightly 2020-01-24 (ghc-8.8.2)
Stackage Nightly 2020-01-21 (ghc-8.8.1)

and `stack setup 8.8.2` does the right thing

**Comment by alanz** [comment]
Currently blocked by https://github.com/haskell/haddock/issues/1123

**Comment by bubba** [comment]
Kinda done in #1607

**Comment by jneira** [comment]
Support added by #1607 (including the exclusion (he) for windows, in install.hs and azure)
