### ISSUE TITLE
Error when running Shake build system

### ISSUE THREAD

**Issue by conradwt** [haskell/haskell-ide-engine#1626]
Given

- macOS 10.15.3
- Stack Version 2.1.3 x86_64 hpack-0.31.2
- GHC 8.6.5
- VSCode Insiders Version: 1.42.0-insider

When I type 

```zsh
git clone https://github.com/haskell/haskell-ide-engine --recursive
cd haskell-ide-engine && ./install.hs build
```

Then I get the following error message:

```text
Error when running Shake build system:
  at want, called at src/Development/Shake/Internal/Args.hs:83:69 in shake-0.18.3-K6N2eLzVtai6jtZeWAmEIo:Development.Shake.Internal.Args
* Depends on: build
  at error, called at src/Development/Shake/Internal/Rules/File.hs:179:58 in shake-0.18.3-K6N2eLzVtai6jtZeWAmEIo:Development.Shake.Internal.Rules.File
* Raised the exception:
Error, file does not exist and no rule available:
  build
```

**Comment by alanz** [comment]
`build` is not a valid command.  See https://github.com/haskell/haskell-ide-engine/blob/master/README.md#building

**Comment by conradwt** [comment]
Hi, I'm new to Haskell and I'm following these instructions:

https://marketplace.visualstudio.com/items?itemName=alanz.vscode-hie-server

**Comment by conradwt** [comment]
@alanz I'm starting to make much better progress now.  After performing the following steps:

```zsh
stack ./install.hs hie-8.6.5
stack ./install.hs data
```

Should I then install the VS Code extension?

**Comment by fendor** [comment]
Yes, the vscode extensions is required, but apparently its documentation is not up-to-date!

**Comment by conradwt** [comment]
Thanks @alanz and @fendor for your assistance and this issue can be closed.
