### ISSUE TITLE
Documentation plugin

### ISSUE THREAD

**Issue by cocreature** [haskell/haskell-ide-engine#164]
We should have some plugin for documentation. Here’s what I would like it to do:
- Find the haddock for a an identifier (probably a fully qualified identifier). It sould then be up to the ide to decide what to do with the filepath to that haddock.
- Some sort of search functionality, possibly building on hoogle.

**Comment by glittershark** [comment]
:+1:

**Comment by alanz** [comment]
I was chatting to @hvr on irc about this. He is keen on doing something about https://ghc.haskell.org/trac/ghc/ticket/2168

It might be interesting to make a plugin that just parses a project in haddock mode, stores the haddock comments and makes them available when queried.

As a precursor to them being in the .hi file and available via GHC API

**Comment by cocreature** [comment]
@alanz If I understand you correctly that would mean that you can’t lookup haddocks for libraries, which would make it significantly less useful (at least for my purposes). If it’s just in your project, usually grep is not too bad to find the function and so also the haddock, or you can just :i in ghci and then go to the line it shows you.

So I would say that the effort should be put into working with the generated haddocks instead of parsing the project in haddock mode.

**Comment by alanz** [comment]
I was thinking more along the lines that this will be something that exists
in the future, maybe we build towards that rather than something else.

We can always build a cache of the haddock comments, perhaps via a future
hackage server.

But it is all just thinking out loud at present.

**Comment by Hrothen** [comment]
Some of this functionality is available via the [ghc-imported-from](https://github.com/carlohamalainen/ghc-imported-from) package.

**Comment by alanz** [comment]
This has been done.
