### ISSUE TITLE
utf-8 related error in windows

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-ide-engine#1641]
* From #1560, reported by @andregpss 
* The error is triggered by using non ascii chars in a haskell source code:

![error utf](https://user-images.githubusercontent.com/24927386/73229778-ad15c000-4159-11ea-84c1-149a0c63f939.png)

I can't reproduce in windows+vscode and the error seemed to stop trying another branch: https://github.com/haskell/haskell-ide-engine/issues/1560#issuecomment-580531900

**Comment by jneira** [comment]
@andregpss afaiu this one has also been fixed, right?
I am a little bit worried cause i never had this one (only the hlint specific one) but anyway i think we can close it and reopen if it reproduces in isolation

**Comment by andregpss** [comment]
@jneira yes, this issue has been fixed.
