### ISSUE TITLE
Missing Uninstalling Documentation

### ISSUE THREAD

**Issue by conradwt** [haskell/haskell-ide-engine#1644]
The project is currently missing uninstalling documentation.

**Comment by fendor** [comment]
yeah, that is true. The project inherits the uninstallation protocol of stack and cabal:
Delete the executables, and then you may or may not purge the store directories of both tools.

**Comment by conradwt** [comment]
@fendor I was able to remove things and thanks for the information.  Thus, this issue can be closed.
