### ISSUE TITLE
Navigation between multiple components

### ISSUE THREAD

**Issue by backuitist** [haskell/haskell-ide-engine#1656]
It would be nice to be able to navigate between symbols of different components in a multi cradle setup. Currently it says "no definition found".

**Comment by fendor** [comment]
That is a nice feature request, but will not be addressed in hie! Such features will be implemented in the new umbrella project of the haskell language Server (hls), see #1525

**Comment by backuitist** [comment]
Ok, should I create a ticket there and close this one?

**Comment by backuitist** [comment]
If you guys want a test project for this I created one there: https://github.com/backuitist/nix-haskell-multi-package

**Comment by jneira** [comment]
@backuitist move it to the new repo would be really nice, thanks!
