### ISSUE TITLE
Build does not respect job configuration (-j1)

### ISSUE THREAD

**Issue by oconnore** [haskell/haskell-ide-engine#1657]
I’ve passed the job limit both to the stack executable and to the `install.hs` script. Both are being ignored, because the build attempts to build Cabal and ghc-lib-parser in parallel. I do not have enough RAM in my VPS to do that simultaneously. 

```
ubuntu@ip-10-0-0-24 ~/hs-ide> stack -j1 ./install.hs -j1 hie-8.6.5
# stack (for check)
# git (for submodules)
# git (for submodules)
# stack (for hie-8.6.5)
Cabal                > configure
Cabal                > Configuring Cabal-2.4.1.0...
Cabal                > build
ghc-lib-parser       > configure
Cabal                > Preprocessing library for Cabal-2.4.1.0..
Cabal                > Building library for Cabal-2.4.1.0..
ghc-lib-parser       > Configuring ghc-lib-parser-8.8.2...
ghc-lib-parser       > build
Cabal                > [  1 of 220] Compiling Distribution.Compat.Binary
Cabal                > [  2 of 220] Compiling Distribution.Compat.Directory
Cabal                > [  3 of 220] Compiling Distribution.Compat.Exception
ghc-lib-parser       > Preprocessing library for ghc-lib-parser-8.8.2..
^CCabal                > `gcc' failed in phase `Assembler'. (Exit code: -2)
Progress 0/149

********************************************************************************
Building failed, Try running `stack clean` and restart the build
If this does not work, open an issue at
        https://github.com/haskell/haskell-ide-engine
********************************************************************************

user interrupt
```

**Comment by jneira** [comment]
* related: #1302
* Till now we have managed to not add args to the build script for the shake of simplicity so the build is determined by the build config files (`stack-${ghcVersion}.yaml` for `stack` and `cabal.project` for `cabal`)
* As a workaound you could change `stack-8.6.5.yaml` adding `jobs: 1`, see https://docs.haskellstack.org/en/stable/yaml_configuration/#jobs
  * You could add it to the stack global config in `$STACK_ROOT/config.yaml`

**Comment by oconnore** [comment]
> Till now we have managed to not add argument handling to the build script for the shake of simplicity so the build is determined by the build config files (stack-${ghcVersion}.yaml for stack and cabal.project for cabal)

That’s weird, because the `./install.hs —help` documents a `—jobs` option.

**Comment by fendor** [comment]
That manages the number of threads of the script itself and is a feature of `shake` that comes for free.

**Comment by jneira** [comment]
Mmm, i am afraid that the help shown by `--help` is from the `stack` (check it running `stack --help`) executable and no from the `install.hs` script.
It looks a little bit confusing but `stack` is the tool we are using to compile and run a script written in haskell (the `install.hs` part). The command is a shorthand for (`stack run ./install.hs`) and when running something with `stack run <program>` you have to pass specific arguments to program after a `--` (check `stack run --help`) to not mix them with `stack` arguments.

So if we would have arguments for our build script the call would look:
`stack ./install.hs -- --jobs X`

**Comment by oconnore** [comment]
@fendor ah, that makes sense. Sorry, I guess I was just confused then. Thanks for explaining. 
@jneira thanks for the workaround, I’ll close this since it’s already discussed in #1302 

FWIW — re: #1302 — I would be fine with binaries so long as they’re distributed from a reasonable source (i.e. Github Releases vs. random S3 bucket).
