### ISSUE TITLE
How to set the HIE to use stack/cabal for the current project

### ISSUE THREAD

**Issue by 524119574** [haskell/haskell-ide-engine#1674]
In my current project I have both `stack` and `cabal` configuration file, however, how do I set up HIE so that it only uses say `stack`?

The problem here is that if it uses the other one it won't be able to work properly. My current workaround is temporarily deleting the `cabal.project` file so that it always uses `stack`.

Thanks for the help!

**Comment by fendor** [comment]
Hi! To tell HIE to always use `stack`, use a `hie.yaml` file! https://github.com/haskell/haskell-ide-engine#project-configuration

**Comment by 524119574** [comment]
Thanks for the response! 
But it seems like setting up the `hie`.yaml` can be quite tedious if we have multiple components, e.g. more than 15 components.  So I am wondering is there any more efficient way to do this?

**Comment by fendor** [comment]
No, currently not. 
A fix would be to implement https://github.com/haskell/haskell-ide-engine/issues/1516, which should be quite trivial. There you can tell cabal-helper which build-tool to use.

**Comment by jneira** [comment]
Another one could be add a cli flag to tell hie prefer one over another: https://github.com/haskell/haskell-ide-engine/issues/1432
