### ISSUE TITLE
ghc.exe: unable to load package "unix-time-0.4.5" unknown symbol  "_create_locale". ExitFailure 1

### ISSUE THREAD

**Issue by kirillFedorov1** [haskell/haskell-ide-engine#1714]
Actually ide engine worked fine for me, but then I screwed up some files. Now I'm trying `stack ./install.hs hie` and there's an error. So I wonder, is there a way to completely delete stack and ide engine from windows, and any mentions. Because when I had installed it for the first time, there were not any problems.

**Comment by fendor** [comment]
IIRC stack files are all in `C:\sr` and `C:\Users\<user>\AppData\Roaming\stack`. That removes all global caches.
Then, you can do `stack purge` in `haskell-ide-engine`, that removes all local caches
If you really want to remove the executables `hie`, they are located in I think either somewhere in `C:\Users\<user>\AppData\Roaming\local\bin` or `C:\Users\<user>\AppData\Local\local\bin`

**Comment by jneira** [comment]
@kirillFedorov1 are you building the latest hie version (master or release)?. hie has a lower bound over `unix-time` to avoid that bug since quite time ago:
https://github.com/haskell/haskell-ide-engine/blob/35f62cffb6bae6c3f86113cb0c55f52b7192689d/haskell-ide-engine.cabal#L97

**Comment by kirillFedorov1** [comment]
Then I'm not sure I tried to install the latest version when I get the error (I've tried different commands)
Okay, now ide engine is deleted entirely, trying `stack ./install.hs hie` and have this:
```
hoogle                           > ghc.exe: unable to load package `unix-time-0.
4.5'
hoogle                           > ghc.exe:  | C:\sr\snapshots\24e195a2\lib\x86_
64-windows-ghc-8.6.4\unix-time-0.4.5-HDRVGETo2bcDYyIhgFBVQm\HSunix-time-0.4.5-HD
RVGETo2bcDYyIhgFBVQm.o: unknown symbol `_create_locale'
Completed 101 action(s).

--  While building package hoogle-5.0.17.3 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6
.4.exe --builddir=.stack-work\dist\e626a42b build --ghc-options ""
    Process exited with code: ExitFailure 1
install.hs: <stdout>: hPutBuf: resource exhausted (Not enough space)
```

**Comment by kirillFedorov1** [comment]
@jneira what is a log of the build, should I show everything that terminal says after `stack ./install.hs hie`? There is too much I'm afraid

**Comment by jneira** [comment]
@kirillFedorov1 you could paste it in a gist or other service and share the link.

But maybe it is not needed: try edit `./install/shake.yaml`, adding `- unix-time-0.4.7` in the `extra-deps` list. It will look somethig like:

```
extra-deps:
- shake-0.18.5
# for resolvers with ghc < 8.6
# - shake-0.17
- unix-time-0.4.7
```

The error is triggered installing `hoogle` and the script uses `./install/shake.yaml` config file to do it.

**Comment by kirillFedorov1** [comment]
@jneira Sorry, could you help me please with a similar problem: I need "scotty" package for my project, and when trying `stack install scotty` or to build a project, I get this:
```
unix-time        > Registering library for unix-time-0.4.7..

--  While building package regex-posix-0.96.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_3.0.1.0_ghc-8.8.3.exe --builddir=.stack-work\dist\29cc6475 build --ghc-options ""
    Process exited with code: ExitFailure 1
```
So there is unix-time-0.4.7 but still a similar error

**Comment by fendor** [comment]
This has nothing to do with Haskell IDE Engine? 
I recommend a tutorial for stack: https://docs.haskellstack.org/en/stable/README/#quick-start-guide
`stack install <library` is virtually never what you want. Set up a proper project and add it to your build-depends.

>     install.hs: <stdout>: hPutBuf: resource exhausted (Not enough space)

Do you have enough space on your device?

**Comment by jneira** [comment]
@kirillFedorov1 Build errors not always are useful, but in the last log you can note that the message:
```
C:\sr\snapshots\24e195a2\lib\x86_
64-windows-ghc-8.6.4\unix-time-0.4.5-HDRVGETo2bcDYyIhgFBVQm\HSunix-time-0.4.5-HD
RVGETo2bcDYyIhgFBVQm.o: unknown symbol `_create_locale'
```
is gone, cause unix-time-0.4.7 fixed it.

This is a new one: could you post the complete log (pasting it in a gist or something alike)?

**Comment by kirillFedorov1** [comment]
@jneira my last message is irrelevant to ide engine, sorry for confusing
Now I fixed unix-time and got this:
```

**Comment by kirillFedorov1** [comment]
@jneira my last message is irrelevant to ide engine, sorry for confusing
Now I fixed unix-time and got this:
```
...
ng.Char8
attoparsec                       > [20 of 21] Compiling Data.Attoparsec.Char8
attoparsec                       > [21 of 21] Compiling Data.Attoparsec
attoparsec                       > copy/register
attoparsec                       > Installing library in C:\sr\snapshots\3add1aa
5\lib\x86_64-windows-ghc-8.6.5\attoparsec-0.13.2.3-GA4ycFABWuC8tgunM2kJRL
attoparsec                       > Registering library for attoparsec-0.13.2.3..

Cabal                            > `gcc.exe' failed in phase `Assembler'. (Exit
code: 1)

--  While building package Cabal-2.4.1.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6
.5.exe --builddir=.stack-work\dist\e626a42b build --ghc-options ""
    Process exited with code: ExitFailure 1

terminateProcess: permission denied (Permission denied)
Progress 100/229

********************************************************************************

Building failed, Try running `stack clean` and restart the build
If this does not work, open an issue at
        https://github.com/haskell/haskell-ide-engine
********************************************************************************


install.hs: <stdout>: hPutBuf: resource exhausted (Not enough space)
```
There are 60 gb on the local disc, perhaps it is related to ram?
And here is everything from the terminal: https://pastebin.com/yXxp6NHa

**Comment by jneira** [comment]
Mmm, maybe a shot in the dark but, what is the program path, where stack is downloading ghc's?
You can get it with `stack path --programs`. I would change it to a short path like you did for '%STACK_ROOT%`. IT can be changed in `%STACK_ROOT%\config.yaml`. Mine is:
```
local-bin-path: D:/bin # where stack installs executables
local-programs-path: D:/bin/stack # where stack downloads ghc's
```
