### ISSUE TITLE
'id' has the wrong type in HIE

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-ide-engine#1744]
When reified in a TH splice it has the type `forall a. b -> c`

Using this TH splice to print the info for `id` I get different results in HIE compared to ghci or `cabal build`

```haskell
idInfo :: Q [Dec]
idInfo = do
  idInfo <- reify 'id
  runIO $ writeFile "idInfo" (show idInfo)
  pure []
```

hie's version (where did `a_283715364993` and `a_283589853497` come from, and why are they different?!:

```haskell
VarI
  GHC.Base.id
  (ForallT
     [ KindedTV a_283531855113 StarT ]
     []
     (AppT (AppT ArrowT (VarT a_283715364993)) (VarT a_283589853497)))
  Nothing
```

The expected output
```haskell
VarI
  GHC.Base.id
  (ForallT
     [ KindedTV a_6989586621679079338 StarT ]
     []
     (AppT
        (AppT ArrowT (VarT a_6989586621679079338))
        (VarT a_6989586621679079338)))
  Nothing
```

**Comment by expipiplus1** [comment]
Repro here: https://github.com/expipiplus1/hie-reload-example/tree/reify

It happens for me on 865 and 882

**Comment by expipiplus1** [comment]
Repro improved https://github.com/expipiplus1/hie-reload-example/tree/reify

It now demonstrates the difference between hie-bios compiled with the haskell.nix infra and the nixpkgs infra.

**Comment by wz1000** [comment]
hie-bios/ghc/nix bug trackers would be a better place for this report.

**Comment by expipiplus1** [comment]
yeah, I've opened an issue against haskell.nix which *seems* at the moment to be the point of diverging behaviour: https://github.com/input-output-hk/haskell.nix/issues/553
