### ISSUE TITLE
Bug : addDLL - libpq or dependencies not loaded

### ISSUE THREAD

**Issue by Kurren123** [haskell/haskell-ide-engine#1745]
Hi

I'm trying to use the `postgresql-simple` package on windows 10. I have postgresql installed, and the following file _does_ exist on my pc:  `C:\Program Files\PostgreSQL\11\lib\libqp.dll`. 

However I am getting the following HIE error: 

```
2020-04-19 07:46:59.9398293 [ThreadId 3] - Ghc error on cradle initialisation: "addDLL: C:\\PROGRA~1\\POSTGR~1\\11\\lib\\libpq or dependencies not loaded. (Win32 er"
```

Full output of `hie --debug --vomit` can be found [here](https://gist.github.com/Kurren123/788bbfae1e0a841a2b72294ad33044c8). Source repository [here](https://github.com/Kurren123/hie-error).

Any help would be much appreciated!

**Comment by jneira** [comment]
Hi! i am afraid that i've tried to reproduce it with no luck:

![imagen](https://user-images.githubusercontent.com/54035/79689495-901ef380-8255-11ea-8cca-0c173ea4b471.png)

Are you able to build the project in the command line with `stack build`? did you that before opening the project dir with the editor?

The output of the extension in vscode could be useful, too. Mine is [here](https://gist.github.com/jneira/694f47d1139af9dc342ad076a9938de6).

**Comment by Kurren123** [comment]
Hi @jneira , thanks for your reply. Seeing as it was working on yours, I re-installed postgresql 11 using the windows installer (previously I used chocolatey) and it works. I think its because some libraries that `libqp.dll` depended on were missing. Closing issue
