### ISSUE TITLE
unable to ./cabal-hie-install hie-8.8.3

### ISSUE THREAD

**Issue by tofutim** [haskell/haskell-ide-engine#1767]
I have used both cabal and stack to install hie-bios-0.5.0. In fact, I have one copy in .cabal and one copy in .local. Yet, when I try to install the ide engine, it complains that
```
cabal: Could not resolve dependencies:
[__0] trying: haskell-ide-engine-1.4 (user goal)
[__1] next goal: hie-bios (dependency of haskell-ide-engine)
[__1] rejecting: hie-bios-0.4.0 (conflict: haskell-ide-engine => hie-bios>=0.5
&& <0.6.0)
```
Any ideas how I can overcome this? 8.8.3 is installed in my machine by both cabal and stack. Not sure if this is a related issue, but using stack tries to download 8.6.5:
```
tim@Tims-MBP haskell-ide-engine % stack ./install.hs hie-8.8.3
ghc-8.6.5:    7.32 MiB / 215.78 MiB (  3.39%) downloaded...
```

**Comment by fendor** [comment]
You probably have to execute `cabal update` to get the latest package list?
