### ISSUE TITLE
Could not obtain flags for: "Setup.hs".

### ISSUE THREAD

**Issue by GordonGgx** [haskell/haskell-ide-engine#1772]
I try to run `hie - r .` in the root directory of the stack project.I got a mistake：
```
/home/ggx/Documents/hsProject/Test/app/Main.hs: FAILED
        "cannot satisfy -package-id Test-0.1.0.0-HK9i1m1pnE35zUxSYHWtx0\n    (use -v for more information)"
/home/ggx/Documents/hsProject/Test/Setup.hs: FAILED
        Fail on initialisation for "/home/ggx/Documents/hsProject/Test/Setup.hs". Could not obtain flags for: "Setup.hs".
/home/ggx/Documents/hsProject/Test/test/Spec.hs: FAILED
        Fail on initialisation for "/home/ggx/Documents/hsProject/Test/test/Spec.hs". Could not obtain flags for: "test/Spec.hs".
```
I use stack tool version 2.3.1 and GHC version 8.8.3.

**Comment by Avi-D-coder** [comment]
Install and use [gen-hie](https://github.com/Avi-D-coder/implicit-hie) to generate a `hie.yaml` file.  In your project run `stack build` then `gen-hie > hie.yaml`(or the windows equivalent of `>`).

An explicit `hie.yaml` file should fix everything, except `Setup.hs`(there is no way to load `Setup.hs`).

**Comment by GordonGgx** [comment]
> In your project run `stack build` then

Yes. I am try it.Now there's only one mistake left：
```
/home/ggx/Documents/stack/Hello/Setup.hs: FAILED
	Fail on initialisation for "/home/ggx/Documents/stack/Hello/Setup.hs". Multi Cradle: No prefixes matched
```

**Comment by Avi-D-coder** [comment]
This is expected nothing can load `Setup.hs` files.
