### ISSUE TITLE
thread blocked indefinitely in an STM transaction -- Running tests

### ISSUE THREAD

**Issue by ankhers** [haskell/haskell-ide-engine#178]
I'm getting a test failure on current master (6078c36ed5a1e9965fccdd16d49dfa20abbc3ff1). Below is a gist with the entire output of the test suite. It appears STM is blocking indefinitely.

https://gist.github.com/ankhers/11ed470df40662f0570a

I'm on OS X Yosemite (10.10.5).

Let me know if there is any other information I can give.

**Comment by cocreature** [comment]
You didn’t install ide-backend-server.
Run `stack install ide-backend-server`. I think `stack build ide-backend-server` should be enough but I’m not sure.

**Comment by ankhers** [comment]
That fixed it. Thanks for the quick response.
