### ISSUE TITLE
unable to install on windows10 build 2004

### ISSUE THREAD

**Issue by ratanakkim** [haskell/haskell-ide-engine#1784]
[error.log](https://github.com/haskell/haskell-ide-engine/files/4739493/error.log)

**Comment by jneira** [comment]
I am afraid that hie cant be built with ghc-8
8.3 and stack due to a ghc bug.
The workaround until version 8.8.4 is released is to use ghc-8.6.5 or build it with cabal

**Comment by jneira** [comment]
Duplicate of #1779
