### ISSUE TITLE
emacs: prompt to save files before doing action

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#189]
If an action is invoked on a file, e.g. `hie-hare-rename`, prompt the user to save the buffer if it has been modified but not saved.

It may be worth indicating on a per-command basis whether it acts on the single file or on the whole project, and prompt to save modified buffers accordingly.

**Comment by mgsloan** [comment]
Hmm, is undo not sufficient?  In other words, it seems just as difficult (if not moreso) to visit all of the affected buffers and revert them, versus invoking undo on them.

One of my schemes for FPHC's refactoring support was to do something similar to [git-monitor](https://github.com/jwiegley/gitlib/blob/master/git-monitor/Main.hs), and create git commits upon each refactoring step.  These commits are not included in development history, but they do allow keeping track of the automatic changes and selectively reverting them.

**Comment by alanz** [comment]
I am talking about a scenario of

1. Do some edits
2. Decide to rename something
3. Without saving the modified buffer, invoke a hie command.

Step 3 is where there should be a prompt to save the buffer, especially if the command operates on the file on the disk.

Once the change is made you end up with a modified buffer that you can save or not, or hit undo to reverse the change.

**Comment by mgsloan** [comment]
Ah, I see!  Yes, if the edits happen on disk, then that makes sense.

**Comment by ankhers** [comment]
Is this still an issue that wants to be fixed? I just did a test with `hie-hare-rename` and `hie-hare-dupdef`. They both appeared to work on modified buffers. It looks like a temporary file is being created, `Api.refactored.hs` in my case. Though, I'm unsure if this is how HaRe works, or if it is how emacs is handling it.

**Comment by cocreature** [comment]
I haven’t tested it but it should still be an issue. The problem is that hare reads the file from disk does the refactoring then sends it back to us and we replace the buffer content. If you have made unsafed changes your buffer they get lost.
