### ISSUE TITLE
ghcmod:info fails to find (some) symbols under qualified names

### ISSUE THREAD

**Issue by afcady** [haskell/haskell-ide-engine#190]
These are the relevant imports from the file:

```
import qualified Data.ByteString.Lazy       as Lazy
import qualified OVH.Enum                   as OVH
```

This works, although I would expect it *wouldn't*:

```
HIE> ghcmod:info file:src/OVH.hs expr:OperationStatus
{"ok":"data OperationStatus\u0000  = [...]  -- Defined at src/OVH/Enum.hs:5:10\n"}
```

But when I use the name as it appears in the source file, this happens:

```
HIE> ghcmod:info file:src/OVH.hs expr:OVH.OperationStatus
EXCEPTION: info:     Not in scope: ‘OVH.OperationStatus’
{"ok":"Cannot show info\n"}
```

Meanwhile, this qualified import works as expected:

```
HIE> ghcmod:info file:src/OVH.hs expr:Lazy.ByteString
{"ok":"data Lazy.ByteString\u0000  = Data.ByteString.Lazy.Internal.Empty [...]
```

My first suspicion is that the difference has to do with the first qualified import being local to the same project as the queried source file while the second is an external dependency.  But I haven't done other testing to try to falsify that.

**Comment by alanz** [comment]
See https://github.com/DanielG/ghc-mod/issues/432, is this the same issue?

**Comment by afcady** [comment]
Looks the same to me.

**Comment by alanz** [comment]
This is a ghc-mod issue, closing.
