### ISSUE TITLE
<stdin>: hGetBufSome: resource exhausted (Not enough space), thread blocked indefinitely in an STM transaction

### ISSUE THREAD

**Issue by TamaraBrandstaetter** [haskell/haskell-ide-engine#194]
When I tried to launch hie http listener, I got the following output:
(launching the REPL worked as you can see on the picture below)
![cmd](https://cloud.githubusercontent.com/assets/15701223/13738712/138f419c-e9c7-11e5-9f2c-9ee743907a0a.PNG)
I deleted the package "hie-docs-generator" from stack.yaml and I work on a PC with Windows 7.
I also installed ide-backend-server as it was mentioned in issue  https://github.com/haskell/haskell-ide-engine/issues/178 , but it did not cause a change.
Does anyone have an idea?

**Comment by cocreature** [comment]
Here are a few ideas:
- Have you tried building with --trace?
- Does it work if you just use the json stdio transport (don’t specify any argument)? Since it seems to read stdin I would expect it to not be related to the http transport. (both are enabled if you specify --http).

Searching around there are a of [very](https://github.com/haskell/bytestring/issues/35) [similar](https://github.com/jgm/pandoc-citeproc/issues/207) [issues](https://www.reddit.com/r/haskellquestions/comments/45sb9h/conduit_tcp_client_and_server_stdin_hgetbufsome/) all on windows and even a [ghc bug](https://ghc.haskell.org/trac/ghc/ticket/11009#ticket) but I don’t see a clear solution. Most of them seem related to lazy IO but I don’t think we are using that anywhere. We use pipes-bytestring for the stdio stuff and that uses strict bytestrings.

**Comment by cocreature** [comment]
Also we no longer depend on `ide-backend-server`.

**Comment by TamaraBrandstaetter** [comment]
When building with --trace I get the following output:

    C:\Temp\haskell-ide-engine>stack build --trace
    hie-base-0.1.0.0: configure
    hie-base-0.1.0.0: build
    djinn-ghc-0.0.2.3: configure
    djinn-ghc-0.0.2.3: build
    ghc-dump-tree-0.2.0.0: configure
    ghc-dump-tree-0.2.0.0: build
    ghc-syb-utils-0.2.3: configure
    djinn-ghc-0.0.2.3: copy/register
    ghc-syb-utils-0.2.3: build
    ghc-exactprint-0.5.0.1: configure
    ghc-exactprint-0.5.0.1: build
    ghc-syb-utils-0.2.3: copy/register
    ghc-mod-5.5.0.0: configure
    ghc-mod-5.5.0.0: build
    hie-base-0.1.0.0: copy/register
    ghc-dump-tree-0.2.0.0: copy/register
    ghc-exactprint-0.5.0.1: copy/register
    apply-refact-0.2.0.0: configure
    apply-refact-0.2.0.0: build
    apply-refact-0.2.0.0: copy/register
    ghc-mod-5.5.0.0: copy/register
    hie-plugin-api-0.1.0.0: configure
    HaRe-0.8.2.3: configure
    hie-plugin-api-0.1.0.0: build
    HaRe-0.8.2.3: build
    hie-plugin-api-0.1.0.0: copy/register
    hie-example-plugin2-0.1.0.0: configure
    hie-apply-refact-0.1.0.0: configure
    hie-example-plugin2-0.1.0.0: build
    hie-eg-plugin-async-0.1.0.0: configure
    hie-apply-refact-0.1.0.0: build
    hie-example-plugin2-0.1.0.0: copy/register
    hie-eg-plugin-async-0.1.0.0: build
    hie-ghc-mod-0.1.0.0: configure
    hie-ghc-mod-0.1.0.0: build
    hie-apply-refact-0.1.0.0: copy/register
    hie-eg-plugin-async-0.1.0.0: copy/register
    hie-ghc-mod-0.1.0.0: copy/register
    hie-ghc-tree-0.1.0.0: configure
    hie-ghc-tree-0.1.0.0: build
    hie-ghc-tree-0.1.0.0: copy/register
    HaRe-0.8.2.3: copy/register
    hie-hare-0.1.0.0: configure
    hie-hare-0.1.0.0: build
    hie-hare-0.1.0.0: copy/register
    haskell-ide-engine-0.1.0.0: configure
    haskell-ide-engine-0.1.0.0: build
    Completed 16 action(s).

    --  While building package haskell-ide-engine-0.1.0.0 using:
    C:\Users\91972.FHWN.000\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1
    f3 build lib:haskell-ide-engine exe:hie --ghc-options " -ddump-hi -ddump-to-file
    "
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Temp\haskell-ide-engine\.stack-work\logs\haskell-ide-engine-0.1.0.0.log
    Configuring haskell-ide-engine-0.1.0.0...
    Preprocessing library haskell-ide-engine-0.1.0.0...
    [ 1 of 12] Compiling Haskell.Ide.Engine.Utils ( src\Haskell\Ide\Engine\Utils.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Utils.o )
    [ 2 of 12] Compiling Haskell.Ide.Engine.Transport.JsonHttp.Undecidable ( src\Haskell\Ide\Engine\Transport\JsonHttp\Undecidable.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\JsonHttp\Undecidable.o )
    [ 3 of 12] Compiling Haskell.Ide.Engine.Options ( src\Haskell\Ide\Engine\Options.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Options.o )
    [ 4 of 12] Compiling Haskell.Ide.Engine.Types ( src\Haskell\Ide\Engine\Types.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Types.o )
    [ 5 of 12] Compiling Haskell.Ide.Engine.Dispatcher ( src\Haskell\Ide\Engine\Dispatcher.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Dispatcher.o )

    [ 6 of 12] Compiling Haskell.Ide.Engine.Transport.JsonHttp ( src\Haskell\Ide\Engine\Transport\JsonHttp.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\JsonHttp.o )
    [ 7 of 12] Compiling Haskell.Ide.Engine.Transport.Pipes ( src\Haskell\Ide\Engine\Transport\Pipes.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\Pipes.o )
    [ 8 of 12] Compiling Haskell.Ide.Engine.Transport.JsonStdio ( src\Haskell\Ide\Engine\Transport\JsonStdio.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\JsonStdio.o )
    [ 9 of 12] Compiling Haskell.Ide.Engine.Transport.JsonTcp ( src\Haskell\Ide\Engine\Transport\JsonTcp.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\JsonTcp.o )
    [10 of 12] Compiling Paths_haskell_ide_engine ( .stack-work\dist\2672c1f3\build\autogen\Paths_haskell_ide_engine.hs, .stack-work\dist\2672c1f3\build\Paths_haskell_ide_engine.o )
    [11 of 12] Compiling Haskell.Ide.Engine.BasePlugin ( src\Haskell\Ide\Engine\BasePlugin.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\BasePlugin.o )

    [12 of 12] Compiling Haskell.Ide.Engine.Console ( src\Haskell\Ide\Engine\Console.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Console.o )
    [ 1 of 12] Compiling Haskell.Ide.Engine.Utils ( src\Haskell\Ide\Engine\Utils.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Utils.p_o )
    [ 2 of 12] Compiling Haskell.Ide.Engine.Transport.JsonHttp.Undecidable ( src\Haskell\Ide\Engine\Transport\JsonHttp\Undecidable.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\JsonHttp\Undecidable.p_o )
    [ 3 of 12] Compiling Haskell.Ide.Engine.Options ( src\Haskell\Ide\Engine\Options.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Options.p_o )
    [ 4 of 12] Compiling Haskell.Ide.Engine.Types ( src\Haskell\Ide\Engine\Types.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Types.p_o )
    [ 5 of 12] Compiling Haskell.Ide.Engine.Dispatcher ( src\Haskell\Ide\Engine\Dispatcher.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Dispatcher.p_o )
    [ 6 of 12] Compiling Haskell.Ide.Engine.Transport.JsonHttp ( src\Haskell\Ide\Engine\Transport\JsonHttp.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\JsonHttp.p_o )
    [ 7 of 12] Compiling Haskell.Ide.Engine.Transport.Pipes ( src\Haskell\Ide\Engine\Transport\Pipes.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\Pipes.p_o )
    [ 8 of 12] Compiling Haskell.Ide.Engine.Transport.JsonStdio ( src\Haskell\Ide\Engine\Transport\JsonStdio.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\JsonStdio.p_o )
    [ 9 of 12] Compiling Haskell.Ide.Engine.Transport.JsonTcp ( src\Haskell\Ide\Engine\Transport\JsonTcp.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Transport\JsonTcp.p_o )
    [10 of 12] Compiling Paths_haskell_ide_engine ( .stack-work\dist\2672c1f3\build\autogen\Paths_haskell_ide_engine.hs, .stack-work\dist\2672c1f3\build\Paths_haskell_ide_engine.p_o )
    [11 of 12] Compiling Haskell.Ide.Engine.BasePlugin ( src\Haskell\Ide\Engine\BasePlugin.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\BasePlugin.p_o )
    [12 of 12] Compiling Haskell.Ide.Engine.Console ( src\Haskell\Ide\Engine\Console.hs, .stack-work\dist\2672c1f3\build\Haskell\Ide\Engine\Console.p_o )
    In-place registering haskell-ide-engine-0.1.0.0...
    Preprocessing executable 'hie' for haskell-ide-engine-0.1.0.0...
    [1 of 2] Compiling Paths_haskell_ide_engine ( .stack-work\dist\2672c1f3\build\autogen\Paths_haskell_ide_engine.hs, .stack-work\dist\2672c1f3\build\hie\hie-tmp\Paths_haskell_ide_engine.p_o )
    [2 of 2] Compiling Main             ( app\MainHie.hs, .stack-work\dist\2672c1f3\build\hie\hie-tmp\Main.p_o )
    C:\Temp\haskell-ide-engine\app\MainHie.hs:89:18:
        cannot find normal object file `.stack-work\dist\2672c1f3\build\hie\hie-tmp\Paths_haskell_ide_engine.o'
        while linking an interpreted expression

**Comment by cocreature** [comment]
Meh, I’ve seen similar things when using `--trace`, but never managed to figure out what caused it. In some cases running a `stack clean` seemed to help. I can’t reproduce it right now. Pinging @mgsloan who might have an idea what’s going on here.

**Comment by TamaraBrandstaetter** [comment]
Building it again after a `stack clean` gives me the following additional outputs: 
   ```
hie-apply-refact-0.1.0.0: unregistering (missing dependencies: hie-base, hie-plugin-api)
hie-base-0.1.0.0: unregistering (local file changes: Haskell\Ide\Engine\PluginTypes.hs Haskell\Ide\Engine\PluginTypes\Singletons.hs Haskell\Ide\Engine...)
hie-eg-plugin-async-0.1.0.0: unregistering (missing dependencies: hie-plugin-api)
hie-example-plugin2-0.1.0.0: unregistering (missing dependencies: hie-plugin-api)
hie-ghc-mod-0.1.0.0: unregistering (missing dependencies: hie-base, hie-plugin-api)
hie-ghc-tree-0.1.0.0: unregistering (missing dependencies: hie-base, hie-ghc-mod, hie-plugin-api)
hie-hare-0.1.0.0: unregistering (missing dependencies: hie-base, hie-plugin-api)

hie-plugin-api-0.1.0.0: unregistering (missing dependencies: hie-base)
```
and then comes the same output as before.

**Comment by mgsloan** [comment]
I'm not sure what's going on there.  Perhaps listing `Paths_haskell_ide_engine` in `other-modules` or `exposed-modules` will resolve it?

**Comment by TamaraBrandstaetter** [comment]
The problem has to do with Windows7. I wasn't able to fix the problem on Windows7 (I tried it with x86 and x64), so I had to switch the OS - it works fine on Windows10.

**Comment by nponeccop** [comment]
The STM issue doesn't happen anymore on Windows 7 x64. 

![image](https://user-images.githubusercontent.com/528415/33584073-0932e5a6-d934-11e7-8c24-828235ef8e89.png)

**Comment by alanz** [comment]
Superseded by move to LSP

**Comment by jneira** [comment]
@alanz hi! i am hitting this bug in win 7 but i've not found the issue in `lsp-haskell`, where could i find it?
I think it worked for me not much time ago... :thinking: 
Now `stack run hie` in master, and the executables generated by `stack install.hs hie-8.6.4` and `stack install.hs hie-8.6.5`, throw it.
