### ISSUE TITLE
Fork ghc-mod from back when it was BSD3

### ISSUE THREAD

**Issue by drbo** [haskell/haskell-ide-engine#197]
`ghc-mod` is currently an AGPL project.  This means that HIE is not usable in proprietary software unless another backend is used.  Furthermore, if HIE makes any changes that are based on AGPL `ghc-mod` code, then the license of `ghc-mod` may "infect" HIE.

The only solution is to fork `ghc-mod` from when it was under the BSD license, or at least have a fixed interface between HIE and the AGPL `ghc-mod` code that does not change.

**Comment by joehillen** [comment]
> This means that HIE is not usable in proprietary software

I fail to see the problem.

**Comment by cocreature** [comment]
We are a small project and don’t have the resources to maintain part of ghc-mod ourselves. When someone steps up that can do this, we can debate this again, until then it won’t happen.
