### ISSUE TITLE
Consider intero as the ghci backend

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#206]

**Comment by bitemyapp** [comment]
What would be entailed? Wrapping it into the larger API?

**Comment by alanz** [comment]
My understanding, based on a brief discussion with @mgsloan, is that we
must find the right way to start it, and then expose it into the larger API.

Coupled to that, it may be needed to write a stdio transport that basically
mirrors what ghci does, else manage the hie elisp to work with it.

Personally I think intero is moving too fast for that to be feasible
initially

**Comment by bitemyapp** [comment]
I'd expect some churn for at least the next 3-6 months as people adopt it and find sticking points, yes.

**Comment by cocreature** [comment]
I don’t understand what exactly is the goal here. Do you want to make an intero plugin that provides the functionality that exposes the functionality of intero, do you want to replace the use of ghc-mod for figuring out the project by intero or do you want to add an additional mode/transport where hie pretends to be GHCi and use intero for that?

**Comment by alanz** [comment]
To be honest, I am not sure, basically because I have not looked at Intero
yet. However, hie does not have a repl yet, and needs one. Intero provides
a repl, together with some additional functionality.

So I would see two different things happening

1. Integrate Intero as a plugin into hie, using our existing transports
2. Consider creating a new transport that mimics the one that intero
currently uses, to be able to tap into the current Intero emacs support

Doing 2 would allow us to easily expose additional commands into emacs.

At the end of the day, there is nothing holy about a particular transport,
and the only reason to have fewer of them is to reduce maintenance effort.
But getting traction is the most important right now.

Alan

**Comment by alanz** [comment]
I'm hoping that the external ghci support now in GHC 8.0.1 can help with the running code and querying case, and the separation you discuss being built into ghci makes sense for this.

And I think there is a general design force within ghci / Intero / hie to use properly typed function calls into the part that does the work, with a separate layer doing interfacing for the end user.  This should be a natural consequence of the libraryification process mentioned above.

**Comment by alanz** [comment]
I am starting to tackle this now.

My thoughts so far:

Given that intero is basically ghci-ng on steroids, at the base it is simply a variant of ghci, with some significant tweaks.

My initial thinking about integrating ghci was to see it as a specialised command interface onto a GHC session, mediated via the haskeline REPL.

I have come to the conclusion that the external interpreter does not make a huge difference for the ghci integration.

So my intention is firstly to continue seeing if I can tease apart the haskeline REPL, to a) allow redirection of stdin/stdout/stderr for everything, so these can be separately managed. I suspect this will be hard/impossible. 

When this fails, the next approach will be to attack the command parser in ghci/intero, and get it to support the HIE plugins as well, so the standard ghci interface is then the transport.

Potentially other layers of transport can be built on top of that. It comes down to where the dispatcher sits.

All in all, experimentation time.

**Comment by jneira** [comment]
Not sure it this still makes sense cause intero has been discontinued
I think we could close it if nobody complains
