### ISSUE TITLE
Re-introduce GHC BIOS concept

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#208]
When HIE was originally conceived there was the concept of a GHC BIOS, which is basically a set of functions to be provided in a given dev environment to enable a tool to run against a project.

This was captured via a type class constraint on the monad, and the initial BIOS provider was ghc-mod.

Given the state of stack, the upcoming improvements in cabal via backpack and nix-like builds, it may be time to re-introduce this concept.

This should allow us to piggy-back onto existing infrastructure around these environments quite quickly.

Thoughts?

**Comment by DemiMarie** [comment]
I like the idea!

**Comment by phadej** [comment]
Is this a prerequisite for using `cabal.project` / `cabal new-build`, or is there another way to add support for that?

**Comment by alanz** [comment]
In terms of the current layering, the new cabal features should be managed in ghc-mod (ghc-mod-core, as it splits out).

I think there has already been some discussion/thought about this, on the ghc-mod side.

cc/ @DanielG

**Comment by phadej** [comment]
@alanz 

Do I understand right that `ghc-mod` (later `ghc-mod-core`) will act (acts?) as HIE's BIOS (which means Basic Input/Output System here too?).

Should this ticket be retagged, "decision needed" fills misguiding here. (I'm :+1: for having some abstraction over sandboxes/new-build/stack)

**Comment by alanz** [comment]
I think the original "decision-needed" related to whether or not ghc-mod should serve this role. 

And I agree, the decision has been taken, and ghc-mod(-core) *is* the BIOS.

So I am going to close it.
