### ISSUE TITLE
REPL can not deal with paths that include blanks

### ISSUE THREAD

**Issue by TamaraBrandstaetter** [haskell/haskell-ide-engine#209]
If I want to check a file with the REPL (Windows10) that is located in a path that includes blanks, I get the following message:

![foldernamewithwhitespace](https://cloud.githubusercontent.com/assets/15701223/16184099/a31ab82a-36b9-11e6-9e57-5cf68e087bd4.PNG)

**Comment by KarlFish** [comment]
This project hasn't had a REPL/Console in a while, looks like this issue is out of date.

**Comment by alanz** [comment]
yes indeed, no longer supported.
