### ISSUE TITLE
So, is it dead?

### ISSUE THREAD

**Issue by Profpatsch** [haskell/haskell-ide-engine#218]
The last commit is 4 months old. What happened?

**Comment by alanz** [comment]
See https://github.com/alanz/haskell-ide-engine/tree/lsp.

**Comment by Profpatsch** [comment]
This means you were/are the only person working on it (irregularly) for the better part of last year?

**Comment by alanz** [comment]
Pretty much. The front-end integration originally got bogged down, then intero came out.

But I always had something like LSP in mind from the beginning, it now exists (in very early form), so HIE will be focussed on that from now on.   Or my efforts on it anyway.  Time available for OSS is always a problem.

**Comment by merlinnot** [comment]
You might want to give me some thumbs up: https://github.com/haskell/ecosystem-proposals/pull/3

**Comment by IvanMalison** [comment]
@alanz What's the state of this project? Is there anything people can do if they want to help?

**Comment by alanz** [comment]
My current goal is to implement the language server protocol, which is coming along quite well, and will immediately bring functionality to all supported IDEs.

And I am considering slimming it down, then building it up with features driven from the front end.

So if anyone want to help it comes down to basically scratching their own itch, I do not have a specific set of features I am aiming for.

And I guess I should move my current work into master so people can see it more easily.

**Comment by alanz** [comment]
And this includes learning elisp properly for https://github.com/alanz/emacs-lsp/tree/hie

**Comment by alanz** [comment]
See https://github.com/haskell/haskell-ide-engine/pull/219
