### ISSUE TITLE
Vim support?

### ISSUE THREAD

**Issue by wizzup** [haskell/haskell-ide-engine#225]
I can't find any information related to vim.

**Comment by alanz** [comment]
See https://github.com/autozimu/LanguageClient-neovim and https://github.com/tjdevries/nvim-langserver-shim

**Comment by wizzup** [comment]
So, this repo implement [LSP](https://github.com/Microsoft/language-server-protocol) for Haskell.

If I want to use this in vim I need to install [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) or [nvim-langserver-shim](https://github.com/tjdevries/nvim-langserver-shim)

Am I understand it right?
--- 
Additional question:

What is the relation of this repo with this [haskell-lsp](https://github.com/alanz/haskell-lsp)?

**Comment by alanz** [comment]
haskell-lsp is a library providing types and some interaction for LSP.  HIE makes use of it to provide a haskell language server.

Other people use it to build language servers for other languages.

**Comment by hasufell** [comment]
> If I want to use this in vim I need to install LanguageClient-neovim or nvim-langserver-shim

The latter seems to be a neovim plugin that will be incorporated into neovim itself. I don't see how that is vim support.

**Comment by alanz** [comment]
The client implementations are listed at https://microsoft.github.io/language-server-protocol/implementors/tools/ and/or https://langserver.org

**Comment by hasufell** [comment]
> The client implementations are listed at https://microsoft.github.io/language-server-protocol/implementors/tools/

That should probably be part of the documentation. And the documentation should be fixed to say "vim/neovim".
