### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#267]
Which can show up as the extension icon in vscode, among other places.

**Comment by wz1000** [comment]
Can the haskell icon do for now?

**Comment by alanz** [comment]
Yes, as a start.  But I am hoping there is someone creative out there who can do something to give HIE a visual identity.

**Comment by damienflament** [comment]
![hie-logo](https://user-images.githubusercontent.com/2023682/33788723-13946ae0-dc74-11e7-8c43-efc2944d6aad.png)
I just tweaked the original Haskell logo.

What do you feel about that one ? Not really innovative. But maybe a starting point ?

**Comment by waddlaw** [comment]
I'm very interested in this! What is the concept of the logo?
Must include `λ`? :)

**Comment by nponeccop** [comment]
I like the `>λie` logo above

**Comment by alanz** [comment]
@waddlaw No specific concept, but should be "relevant" in some way.

And @damienflament 's one is definitely a candidate.

So perhaps let us know if you want to make an attempt, and we will wait for it and then do a small poll on it.

**Comment by damienflament** [comment]
@waddlaw The concept is simply to take the two lines present in the Haskell logo, add a third one to make a _E_. Then add another one vertically to make the _I_.

![haskell_logo](https://user-images.githubusercontent.com/2023682/33794292-1e989790-dcc9-11e7-9ce5-5c47d72200fe.png)

![hie_logo_without_point_on_i](https://user-images.githubusercontent.com/2023682/33794298-464cc734-dcc9-11e7-9300-75f9c2ac96ea.png)

Then, as the _I_ without point looks like being part of the _E_ (and people may read "HE"), add a point to the _I_.

![hie_logo](https://user-images.githubusercontent.com/2023682/33794311-7e4b9f8e-dcc9-11e7-8b34-5088d7e36e70.png)

**Comment by damienflament** [comment]
@alanz I'm not really happy with the current logo. But currently I have not any new idea to improve it. A poll may reveal some talented people and new idea.

It lacks colors ! I will think about it. Then I will give you a SVG file.

**Comment by damienflament** [comment]
Here some colour variations:
### 1. [Thompson Wheeler](https://wiki.haskell.org/ThompsonWheelerLogo)
![hie_logo](https://user-images.githubusercontent.com/2023682/33794855-5136d666-dcd4-11e7-96aa-9b60d91a34a9.png)

### 2. [Haskell website](https://www.haskell.org/static/img/haskell-logo.svg)
![hie_logo_haskellweb](https://user-images.githubusercontent.com/2023682/33794943-ed65d356-dcd5-11e7-8ddd-7d18d45ec03c.png)

### 3. Blue
![hie_logo_blue](https://user-images.githubusercontent.com/2023682/33794856-515bbc4c-dcd4-11e7-8ff5-0ac19d5dc57b.png)

### 4. [Engine](http://www.colourlovers.com/palette/2954146/Engine)
![hie_logo_engine](https://user-images.githubusercontent.com/2023682/33794857-5186da94-dcd4-11e7-86c0-9f70ea00dd01.png)

### 5. [Moteur](http://www.colourlovers.com/palette/1787049/Moteur)
![hie_logo_moteur](https://user-images.githubusercontent.com/2023682/33794858-51b6774a-dcd4-11e7-91f8-025e30f36e8f.png)

### 6. [Sigma Lambda Beta](http://www.colourlovers.com/palette/394980/Sigma_Lambda_Beta)
![hie_logo_sigmalambdabeta](https://user-images.githubusercontent.com/2023682/33794859-51dbc39c-dcd4-11e7-88e8-f17e4c9f29ee.png)

**Comment by saurabhnanda** [comment]
Any examples of other LSP implementations with a logo
​

**Comment by mgsloan** [comment]
I like it!  I'm no longer very involved with this project unfortunately, but that looks pretty good to me.  Might be interesting to play around with making the E backwards like mathematical existentials

**Comment by Tehnix** [comment]
@saurabhnanda I checked out all LSP servers on https://langserver.org, and couldn't find a single one that had it, at least not on their frontpage.

I think this is because the servers are usually subprojects of something else, and therefore hasn't required an identity. HIE on the other hand is a bit more grand unifying, and I think it makes sense here :)

Personally I like the yellow `iE` in 5., since it makes it stand out, but am not entirely sure about the green. How would it look mixing 2.'s `>λ` with 5.'s `iE`?

**Comment by damienflament** [comment]
@Tehnix 

![hie_logo_haskellweb_yellow](https://user-images.githubusercontent.com/2023682/33795262-64fe6538-dcde-11e7-9274-25223ea428f2.png)

**Comment by Tehnix** [comment]
@damienflament I like it! It kinda feels like the `iE` is sneaking up behing the lambda :)

**Comment by damienflament** [comment]
@mgsloan 

![hie_logo_there_exists](https://user-images.githubusercontent.com/2023682/33795375-7257c81c-dce0-11e7-8454-287014d02540.png)

**Comment by damienflament** [comment]
@saurabhnanda Maybe we need to find a symbol which express the concepts behind the LSP. Then haskellify it.

I don't find anything relevant has LSP is just implementing standard code editor features to an external process and allow communicating using JSON-RPC.

**Comment by damienflament** [comment]
Here the SVG file: [HIE_logo.svg](https://gist.github.com/damienflament/6f8a1b43386157f36881b3f70a9bc232#file-hie_logo-svg)

**Comment by alanz** [comment]
This stuff is looking really great.

What is the next step?  How do we make a decision?

**Comment by Tehnix** [comment]
Twitter poll, with it being linked on /r/haskell (can reddit do polls?)? Or just make up a decision here, since I don't think anyone will have much against it :)

**Comment by alanz** [comment]
There is also the danger of bikeshedding, which can send it off into endless delay/stupidity.

Maybe we should just list this thread, and ask people to give reactions on the individual ones as listed. With that emoji thing GH now has.

**Comment by alanz** [comment]
Except we would have to break https://github.com/haskell/haskell-ide-engine/issues/267#issuecomment-350448770 out into its component parts.

**Comment by damienflament** [comment]
I created an **[open images poll](http://www.anonvote.com/poll/dr587990y)**.

Not any subscription required. You can share it on Twitter and Reddit.

What do you think about it ?

N.B: The poll allow to vote for multiple images. But this feature can be disabled.

**Comment by alanz** [comment]
Looks great, time to publicise it

**Comment by alanz** [comment]
I will send a mail to haskell-cafe, and link it on reddit

**Comment by alanz** [comment]
Done, at https://www.reddit.com/r/haskell/comments/7in9ab/haskellcafe_haskell_ide_engine_logo_poll/

**Comment by theindigamer** [comment]
@damienflament , maybe have i∈ instead of iE or i∃ (which looks like i3)? I think the three lines (plus diagonal instead of verticals) look much cooler than the joined thing, so something like (the lengths of the arms can be tweaked...)

```
    ---------
   /        /
   ---------
  -------
  |     |
  -------
   ---------
   \        \
    ---------
```

**Comment by waddlaw** [comment]
![hie-logo](https://user-images.githubusercontent.com/24648398/33803859-e76268fe-dddc-11e7-83c2-fee0c24f7d6d.jpg)

@alanz @damienflament
How is this?

**Comment by nponeccop** [comment]
IMO too many details. It won't look good as an icon.

**Comment by MitchStevens** [comment]
That circular overlay is good though, keep working on simplifying the design and it'll be a ripper!

**Comment by damienflament** [comment]
@waddlaw 

It's **Haskell IDE Engine**. It's a Language Server, not an IDE !

Your logo stands for an Integrated Development Environment.

**Comment by waddlaw** [comment]
Oh, I see. Thanks.
`HIE` is Haskell Ide Engine. OK, I'll try fix.

**Comment by owiecc** [comment]
![hie](https://user-images.githubusercontent.com/6896639/33809665-d5107bfa-ddfa-11e7-85e7-6c3d118302e1.png)

**Comment by alanz** [comment]
@damienflament , can you add @owiecc 's one to the poll?

**Comment by damienflament** [comment]
@alanz the poll can't be modified until created. We need to create a new one.

Maybe should we wait for the end of the current poll.

Then we make a new one with the winner and the those new proposals: @owiecc one, @waddlaw one if  he modified its actual logo to better match HIE, and any other proposal done until Friday.

**Comment by alanz** [comment]
Ok, makes sense.

**Comment by damienflament** [comment]
A variation of my logo proposal (idea from fredefox on Reddit):

![hie_logo_little_i](https://user-images.githubusercontent.com/2023682/33833355-ae43be58-de7f-11e7-9ccc-6cee49223fb0.png)

**Comment by owiecc** [comment]
![hie cross](https://user-images.githubusercontent.com/6896639/33847513-0dc77ccc-deab-11e7-9b69-b52b3e9c3a63.png)

**Comment by lettier** [comment]
![haskell-ide-engine-logo-david-lettier](https://user-images.githubusercontent.com/1661343/33931843-49c1cf60-dfbf-11e7-8ec1-486bc0268d49.png)

:+1:

**Comment by waddlaw** [comment]
![hie](https://user-images.githubusercontent.com/24648398/33994178-d8d8fc42-e11c-11e7-89f0-585a12b06b30.png)

**Comment by saurabhnanda** [comment]
Absolute random thought -- how about renaming to Haskell IDEntity and
building the brand around that?

**Comment by saurabhnanda** [comment]
It's a word play. **IDE**ntity. And the fact that it's going to be the
underlying base for multiple IDE plugins.

Another option could be insIDE

**Comment by alanz** [comment]
Ok, by my clock the poll has closed, with the consistent winner being the first one.

@damienflament can you set up another one with that and the new entries, some time?

**Comment by damienflament** [comment]
As the poll may not be persistent, the results are below:

Total votes: **578**

Rank | Preview | Votes | Rate (%)
------|------|--------|------
**1** | ![hie_logo_haskellweb](https://user-images.githubusercontent.com/2023682/34060284-4a352c14-e1e3-11e7-92e7-d693835ce4ca.png) | **223** | **39**
2 | ![hie_logo](https://user-images.githubusercontent.com/2023682/34060279-49266040-e1e3-11e7-9183-4728ba0af8ed.png) | 97 | 17
3 | ![hie_logo_haskellweb_yellow](https://user-images.githubusercontent.com/2023682/34060285-4a943d30-e1e3-11e7-8975-61af04bcbe84.png) | 90 | 16
4 | ![hie_logo_sigmalambdabeta](https://user-images.githubusercontent.com/2023682/34060288-4b80f792-e1e3-11e7-974a-cfcbebb2728f.png) | 58 | 10
5 | ![hie_logo_engine](https://user-images.githubusercontent.com/2023682/34060283-4a076888-e1e3-11e7-86bf-a84507401efc.png) | 55 | 10
6 | ![hie_logo_blue](https://user-images.githubusercontent.com/2023682/34060281-495a0b02-e1e3-11e7-961f-41ac7e579233.png) | 39 | 7
7 | ![hie_logo_moteur](https://user-images.githubusercontent.com/2023682/34060287-4b519664-e1e3-11e7-8f3e-994ee81c3121.png) | 16 | 3

**Comment by damienflament** [comment]
@waddlaw , @lettier and @owiecc please share a PNG file with a height of 128 px for each logo you want to be added to the poll.

You can submit many logos. The poll will allow multiple votes for each participant.

Thanks !

**Comment by owiecc** [comment]
![hie cross 128](https://user-images.githubusercontent.com/6896639/34061477-d80adc0a-e1e8-11e7-82cb-d18c2d1d4699.png)
![hie ribbons 128](https://user-images.githubusercontent.com/6896639/34061478-d8244e56-e1e8-11e7-93c7-7867189c1bb9.png)
I modified them quickly for 128px. I kept the canvas square as a logo will probably be used in that context most of the times.

**Comment by damienflament** [comment]
@owiecc It's up to you. But by doing that you added space on top and bottom of the logos. This make them look smaller.

**Comment by lettier** [comment]
Hello @damienflament 

# 1 

![haskell-ide-engine-engine-no-border-lettier](https://user-images.githubusercontent.com/1661343/34065213-c6ef6b4a-e1cd-11e7-84e0-c8824cd0565d.png)

# 2

![haskell-ide-engine-engine-border-lettier](https://user-images.githubusercontent.com/1661343/34065220-d4a9215e-e1cd-11e7-96d9-e4927c3d6b63.png)

# 3

![haskell-ide-engine-gears-lettier](https://user-images.githubusercontent.com/1661343/34065226-df6bc894-e1cd-11e7-9d97-6a74a3c7eadb.png)

:+1:

**Comment by waddlaw** [comment]
@damienflament

![logo](https://user-images.githubusercontent.com/24648398/34067664-a6b84296-e26f-11e7-8cce-5eba89382e20.png)

**Comment by gareth-rowlands-akqa** [comment]
My 2c:

I like @lettier option 2. Visually, it's an engine. With lambdas.

I prefer it to logos that include "HIE" or "IE". When the project uses words and letters, I think "Haskell IDE Engine" is best - that name was quite carefully chosen. To me, "IE" is Internet Explorer. And "HIE" is the Highlands and Islands Enterprise, the birth defect Hypoxic Ischemic Encephalopathy, or an archaic verb meaning to go quickly.

**Comment by nponeccop** [comment]
I'm a non-native speaker and to me `hie` looks just another short name in `/bin` not used elsewhere :)

**Comment by garethrowlands** [comment]
@nponeccop I think `hie` is perfectly reasonable as the name for the binary. I was just trying to justify my preference for a graphic in the logo rather than the acronym. Sorry if I sounded rude.  (I posted under gareth-rowlands-akqa).

**Comment by damienflament** [comment]
The new poll is available here: http://freeonlinesurveys.com/p/Cw1FRJ2G?qid=1017541

**Comment by nponeccop** [comment]
I wonder if we should make a second tour among 1-5-7 :) or we should declare 7 the winner. The poll doesn't make it clear which is which either.

**Comment by damienflament** [comment]
@nponeccop Yes. This poll is not specifically made for images. But it does not resize images (contrary to the previous one).

![image](https://user-images.githubusercontent.com/2023682/34396471-988da846-eb6b-11e7-8f4c-3fcc48883b16.png)

**Comment by ismailmustafa** [comment]
Perhaps we should run the same poll again, but this time advertise it on reddit and IRC. I don’t think ~50 votes is very representative of the community. Also, @damienflament’s upgraded logo didn’t make it into this poll.

**Comment by alanz** [comment]
I think we should wait for the festive season to be over too, and then run it. So in about a week.

**Comment by damienflament** [comment]
@ismailmustafa If your talking about the logo variation I introduced [in this comment](https://github.com/haskell/haskell-ide-engine/issues/267#issuecomment-350724300), I made it to show it to the community. But it's not my favourite. As it didn't get any upvote neither here and on Reddit, I didn't add it to the poll.

About advertisement, I added [a comment](https://www.reddit.com/r/haskell/comments/7in9ab/haskellcafe_haskell_ide_engine_logo_poll/dr2yes5/) to the original Reddit post and sent [an email](https://mail.haskell.org/pipermail/haskell-cafe/2017-December/128314.html) to the Haskell-cafe mailing list.

**Comment by damienflament** [comment]
What do we do about this poll ?
Currently, it got only 98 voters.

**Comment by alanz** [comment]
I see #7 got 47% of the vote, which iirc is the one that won the first round too?

In which case it is the winner, and we start updating the README etc to use it.

**Comment by damienflament** [comment]
I closed the poll as nobody voted since January, 3rd.

Here the results:

Total votes: **168**
Total voters: **97**

Rank | Index | Preview | Votes | Rate (%)
:------:|:-------:|-----------|--------:|------------:
**1** | **7** | ![image](https://user-images.githubusercontent.com/2023682/35182581-31639070-fdd8-11e7-9377-54f88ccf5b16.png) | **47** | **27.98**
2 | 5 | ![image](https://user-images.githubusercontent.com/2023682/35182593-66ae413a-fdd8-11e7-9445-1e0a059be64a.png) | 29 | 17.36
3 | 1 | ![image](https://user-images.githubusercontent.com/2023682/35182599-89dcef58-fdd8-11e7-904e-3ec9640af18f.png) | 26 | 15.48
4 | 2 | ![image](https://user-images.githubusercontent.com/2023682/35182602-99192b08-fdd8-11e7-9e0e-71e201492d50.png) | 22 | 13.10
5 | 6 | ![image](https://user-images.githubusercontent.com/2023682/35182609-a72ad688-fdd8-11e7-8ada-d9faefac9c4f.png) | 19 | 11.31
6 | 4 | ![image](https://user-images.githubusercontent.com/2023682/35182613-b32b15ce-fdd8-11e7-833f-f063dd053bd6.png) | 13 | 7.74
7 | 3 | ![image](https://user-images.githubusercontent.com/2023682/35182621-d839950c-fdd8-11e7-8f70-40aaecea9c66.png) | 12 | 7.14
||| **Total** | 168 | 100

**Comment by alanz** [comment]
So we go with the top one, it won the prior round too.

There were some nice options there, I must say. Thanks to all who submitted candidates.

**Comment by damienflament** [comment]
I uploaded the SVG file and some PNG exports to [this gist](https://gist.github.com/damienflament/848dbe79064186d83496b26605ea93b6).

**Comment by alanz** [comment]
Could you make a PR, that adds a directory called logos with those in it?
