### ISSUE TITLE
hie: <command line>: cannot satisfy -package-id yi-core

### ISSUE THREAD

**Issue by noughtmare** [haskell/haskell-ide-engine#271]
When I open the yi folder with vscode I get this error:

```
hie: <command line>: cannot satisfy -package-id yi-core-0.14.1-9CsxBCkuqnUG0u6MtAWARr
    (use -v for more information)
```

This might have something to do with multi-package stack projects.

**Comment by alanz** [comment]
Have you built the dir recently? is it a stack project, or using cabal new-build?

**Comment by noughtmare** [comment]
Ah, the problem was that I didn't build it yet.
