### ISSUE TITLE
Document the was LSP is supposed to work with plugins

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell/haskell-ide-engine#274]
Please document how functionality that is provided by plugins can be accessible via LSP.

For example, I am trying to call `applyrefact:applyAll` and I am doing it this way:

```
interface AllFixesParams {
	file: String;
}

interface AllFixesResult {
	res: String;
}


namespace AllFixesRequest {
	export const type = new RequestType<AllFixesParams, AllFixesResult, void, void>('applyrefact:applyAll');
}

let cmd = commands.registerTextEditorCommand("hie.type.insert", (editor, edit) => {
	let parms = { file: editor.document.uri.toString() }
	langClient.sendRequest(AllFixesRequest.type, parms, null).then(x => {
		console.log(x);
	});
});
```

It doesn't work:

```
[Error - 8:01:47 PM] haskell-lsp:unknown message received:method='applyrefact:applyAll', Content-Length: 158

 {"jsonrpc":"2.0","id":10,"method":"applyrefact:applyAll","params":[{"file":"file:///Users/araga/src/test/src/App/Foo.hs"},null]}
```

I have similar problems when implementing other perks.

How should the command look like in these cases?
Or, if not through LSP, what is the design for "custom" functionality, like "insert type", "apply refactoring", etc?

**Comment by alanz** [comment]
This is an open question at the moment, see https://github.com/Microsoft/language-server-protocol/issues/61

For the emacs client we are exposing client-side functions, and you can get an idea of the parameters by looking at e.g. https://github.com/alanz/lsp-haskell/blob/master/lsp-haskell.el#L57

You can also look at the format of the commands returned from the [/document/CodeAction](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#code-action-request) request, which is used to implement the `applyRefact:applyOne` command. The `applyAll` will have the same format.

**Comment by alanz** [comment]
@AlexeyRaga what client are you working on?

**Comment by AlexeyRaga** [comment]
Oh, thanks, I didn't know that `applyOne` was implemented, I'll have a look, thanks!

I am trying to hack around VSCode plugin because I was _really_ impressed with the speed (compare to Haskero and Haskell ghc-mod plugins)! So thank you guys for that!

But there are a a couple of features I'd love to have, like applying suggestions and inserting type.

**Comment by AlexeyRaga** [comment]
Which client implements `applyOne`, where I can see it? Is it also emacs?

**Comment by wz1000** [comment]
You need to use the executeCommand request to use arbitary HIE plugin commands - https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_executeCommand

Currently, you can send an executeCommand Request that looks like:

     {"jsonrpc":"2.0","id":10,"method":"executeCommand","params":{"command":" applyrefact:applyAll", "arguments":[{"file":"file:///Users/araga/src/test/src/App/Foo.hs"}]}}

However, the argument format is going to change soon, so I recommend you work against https://github.com/wz1000/haskell-ide-engine/tree/cleanup

The request you would send to that branch should look like this:

    {"jsonrpc":"2.0","id":10,"method":"executeCommand","params":{"command":" applyrefact:applyAll", "arguments":[{"file:///Users/araga/src/test/src/App/Foo.hs"}]}}

**Comment by alanz** [comment]
In vscode, you can apply the individual hint suggestions by hovering over the line it is on (the first line of the hint) until the lightbulb shows up, then click on that

**Comment by AlexeyRaga** [comment]
@wz1000 really valuable hints, thanks!

**Comment by wz1000** [comment]
@AlexeyRaga the method needs to be "workspace/executeCommand", not "executeCommand", sorry. 

Do try it out and get back to me if it works. We haven't integrated any of the extra commands into the vscode plugin, mainly because both of us ( @alanz and I ) have limited experience with Typescript and vscode plugins. It would be really great if you figured out a way to integrate all the various HaRe refactorings in `hie-hare`. We hang out on `#haskell-ide-engine` on freenode, so you can drop in there any time.

**Comment by AlexeyRaga** [comment]
@wz1000 a quick question: when I use `workspace/executeCommand` with `sendRequest` I get an error:

```
Object (
	fromList [
		("jsonrpc",String "2.0"),
		(
			"params",
			Array [Object (fromList [("command",String "applyrefact:applyAll"),
			(
				"arguments",
				Array [
					Object (fromList [("file",String "file:///Users/araga/src/arbor/attackstream-unifier/src/App/Submissions.hs")])
				]
			)]),Null]),
				("method",String "workspace/executeCommand"),
				("id",Number 2.0)])


"When parsing the constructor ExecuteCommandParams of type Language.Haskell.LSP.TH.DataTypesJSON.ExecuteCommandParams expected Object but got Array."
```

It looks like `params` is expected to be `Object`, but `sendRequest` sends it as an array.

I tried using it in these two ways:
```
langClient.sendRequest('workspace/executeCommand', { file: editor.document.uri.toString() }, null)
```
and
```
langClient.sendRequest(
  ExecuteCommandRequest.type, 
  {
	command: "applyrefact:applyAll",
	arguments: [{file: file}]
  },
  null
);
```

but it always comes as an array.

Is it something that is in the middle of change or I am doing something wrong?

**Comment by wz1000** [comment]
@AlexeyRaga I have no idea about the vscode api. The LSP spec clearly specifies that ExecuteCommandParams is an object. Maybe open an issue on the vscode-lsp library tracker?

Can't you somehow send raw JSON that you construct yourself?

**Comment by wz1000** [comment]
@AlexeyRaga did you try removing the `null` argument? Because it seems like it is passed as the second element of the array.

**Comment by AlexeyRaga** [comment]
Sorry, that was silly me, not used to optional parameters.
I interpreted this 
```
sendRequest<R, E, RO>(type: RequestType0<R, E, RO>, token?: CancellationToken): Thenable<R>;
```
as a "maybe" (nullable) parameter, but in TS it means that I can omit it (why would one do that?!).

Of course removing `null` helped.
