### ISSUE TITLE
No hoogle db found

### ISSUE THREAD

**Issue by ismailmustafa** [haskell/haskell-ide-engine#285]
Upon pulling and installing a more recent version of hie, I've started getting the following warning when opening a Haskell project in vscode:

![image](https://user-images.githubusercontent.com/6578679/29253526-544f5b86-804d-11e7-92e5-ec18b5add4bd.png)

I'm running the following versions of hie and hoogle:

```
Version 0.1.0.0, Git revision 2dfb5d8635a233c9765ed11c5fc299f68adea91f (963 commits) x86_64
Hoogle 5.0.12, http://hoogle.haskell.org/
```

Hoogle is installed globally using stack and I've run `hoogle generate` globally as well.

**Comment by wz1000** [comment]
You need to update to hoogle 5.0.13.

**Comment by AlexeyRaga** [comment]
I'd add to it: if there IS hoogle db found, then there is no need to display an info popup since it doesn't require any attention and doesn't bring any value to the user.

**Comment by wz1000** [comment]
But hie can recognise different hoogle dbs for different projects. So if
you run `stack hoogle`, it will generate a hoogle db under `.stack/` that
HIE can pick up on.

**Comment by ismailmustafa** [comment]
Upgrading to 5.0.13 worked. Thanks! Also @AlexeyRaga +1 on not displaying an info popup if a hoogle db is found. It's quite annoying. What about using `fmServerLogMessageNotification` here https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Transport/LspStdio.hs#L341? That way we can still find out which hoogle db is being used by looking through the logs.
