### ISSUE TITLE
Release the extension to VS Code marketplace

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-ide-engine#296]
As a Haskell developer, I have all the knowhow to do all the git pieces and build pieces required to get this project going. What I don't know all about is writing VS Code extensions and setting up npm, so having the VS Code extension released would be great. I recommend releasing it in whatever embryonic state it is and just rereleasing it every month or so.

(Well, actually I do know, since I wrote a VS Code extension, https://marketplace.visualstudio.com/items?itemName=ndmitchell.haskell-ghcid, and releasing it was trivial.)

**Comment by alanz** [comment]
Ok.  I have been holding off because things were not mature enough on the backend, and I was worried about floods of bug reports for things that are not really ready for use yet.

**Comment by ndmitchell** [comment]
Is the vs code piece itself immature? If not, making it more easily available might help people fix the backend bugs.

**Comment by alanz** [comment]
No, it is pretty solid, as it does not have to do much. The immaturity was in the backend, I am only just starting to feel confident about using it for daily tasks.

**Comment by ndmitchell** [comment]
In that case I'd strongly consider a release. Last night I saw the screenshots and thought "wow". Then I saw the "run npm ..." and added looking at it to my todo list. With that one step removed, I'd have tried it there and then.

**Comment by alanz** [comment]
Here goes nothing: https://marketplace.visualstudio.com/items?itemName=alanz.vscode-hie-server
