### ISSUE TITLE
Travis build should be deterministic

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-ide-engine#30]
It seems that TravisCI somehow does not produce deterministic builds. master branch at https://travis-ci.org/haskell/haskell-ide-engine/builds/89591048 compiles, after a useless change in README a pull request does not compile https://travis-ci.org/haskell/haskell-ide-engine/builds/89742925. It ends up with a warning in HaRe:

```
    src/Language/Haskell/Refact/Utils/Monad.hs:211:10: Warning:
      No explicit implementation for
          ‘GM.gmoAsk’
        In the instance declaration for ‘GM.GmOut (StateT RefactState IO)’
```

Build system must be reliable and deterministic.

**Comment by alanz** [comment]
It seems the problem was an OOM error when compiling HaRe. A new version has been released which compiles with -O0, reducing memory usage. This is now no longer a problem,
