### ISSUE TITLE
Instructions for build on the main page doesn't work on Windows

### ISSUE THREAD

**Issue by varosi** [haskell/haskell-ide-engine#300]
During ```stack install``` on the master branch it asks for some C libraries:

Configuring text-icu-0.7.0.1...
    Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe: Missing dependencies on foreign
    libraries:
    * Missing C libraries: icuuc, icuin, icudt

**Comment by tonyfloatersu** [comment]
You may try this: [Issue 12](https://github.com/bos/text-icu/issues/12), the solution is from RyanGlScott.

This method seems to solve the same problem (stated by you) on me.

(BTW, my platform information if needed: GHC 8.0.2 with stack 1.5.0)

**Comment by Friede80** [comment]
I was able to build using Neil Mitchell's answer here: https://stackoverflow.com/questions/16127710/how-do-i-get-text-icu-working-on-windows

Although, I had to use ICU version 55, for some reason that was the only one that worked for me.

**Comment by varosi** [comment]
hm, all those ways are not trivial for installing a IDE Haskell environment. May be text-icu replacement could be considered? or maybe pre-built binaries.

**Comment by Anrock** [comment]
Successfully built e3f921df897e7a5f4fe33da000b0eb70664c8c47 today on win10 x64.

**Comment by Anrock** [comment]
Latest buildable: 9a00bc84a3

**Comment by varosi** [comment]
```Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for unix-2.7.2.1:
    unbuildable must match <0, but the stack configuration has no specified version
needed due to hie-build-plugin-0.1.0.0 -> unix-2.7.2.1```

**Comment by Anrock** [comment]
Instructions are ok, dependencies aren't. See https://github.com/DanielG/cabal-helper/pull/36

**Comment by Anrock** [comment]
@alanz https://github.com/DanielG/cabal-helper should build again on Windows since https://github.com/DanielG/cabal-helper/commit/eb178a5ba4c9432e951b6c206f8baf21257ecb28

**Comment by Anrock** [comment]
@varosi current master should be buildable on Windows.

**Comment by varosi** [comment]
Great! Thanks! It's working for master 04af8885a89402168cf464b119697d2539df1e61
