### ISSUE TITLE
Error in VScode on Mac

### ISSUE THREAD

**Issue by arichardson20** [haskell/haskell-ide-engine#301]
Hey, I'm fairly new to programming, but I was just trying to setup the engine with VScode on mac. I followed all the instructions, but when I open up the new window with f5, Vscode tells me "connection to server got closed. Server will restart."

I followed all the steps shown on the instructions, including the special icu4c setup. Any idea what's going wrong for me?

If you need more info, or I need to follow certain guidelines, just let me know. Thanks.

**Comment by wz1000** [comment]
Can you give me the contents of `/tmp/hie.log`

**Comment by arichardson20** [comment]
I've decided to go with Haskero for VSCode, but thanks for your help. Sorry for the false alarm.
