### ISSUE TITLE
HIE should start web server only on demand

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-ide-engine#31]
If there are multiple hie engines started they all try to listen on the same port.

If the only interface used is stdin/stdout it is not wise to make startup fail just due to inet port being busy.

**Comment by alanz** [comment]
Agree

**Comment by alanz** [comment]
At the moment in MainHie.hs we have

    -- TODO: pass port in as a param from GlobalOpts
    _ <- forkIO (jsonHttpListener cin)

Modify Options.hs to have a flag to enable the listener, and only launch it if the flag is set.

This should be a copy-paste of the option for "--console", just renamed.

As a bonus, consider adding a port parameter too.
