### ISSUE TITLE
Error using with vscode. "Reason: unknown dependency `justusadam.language-haskell`".

### ISSUE THREAD

**Issue by SzymonPajzert** [haskell/haskell-ide-engine#317]
I got error while following instructions for usage with vscode:

> Extension `alanz.vscode-hie-server` failed to activate. Reason: unknown dependency `justusadam.language-haskell`.

**Comment by ismailmustafa** [comment]
Did you download `vscode-hie-server` through vscode, or did you follow the instructions in the readme and build it yourself from source? I have a feeling extension dependencies only work when using the former approach.

**Comment by SzymonPajzert** [comment]
I have followed instructions from READ.me. I'll check tommorow the first
way of doing it and update readme accordingly if it happens to work.

**Comment by alanz** [comment]
I just uninstalled and reinstalled via the marketplace, and it went in fine.

So if you want to play with it using the local version first install the required dependency, I guess.

**Comment by SzymonPajzert** [comment]
Closed since installing via vscode works. But still we should update docs.

**Comment by alanz** [comment]
I agree. And I thought I had, to be honest. But I think it is on an unmerged branch somewhere
