### ISSUE TITLE
Prioritise compile errors over hlint errors

### ISSUE THREAD

**Issue by saurabhnanda** [haskell/haskell-ide-engine#319]
If `hlint` throws a parse error (especially due to a syntax-related extension, like QuasiQuotes or Arrows), HIE doesn't show any compile errors. I feel compile errors should be prioritised over style/hlint errors.

**Comment by alanz** [comment]
Note also that in vscode you can filter the problems using the window on the bottom right, part of the bar with "Problems" on it

**Comment by xldenis** [comment]
From what I can tell this issue has been resolved?

**Comment by alanz** [comment]
Yes
