### ISSUE TITLE
Make all ToJSON instances clearly visible

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#32]
Because JSON is used for external interfaces for many of the transports, the JSON generated must be stable. Hence it should not be generated by automated means that may change with compiler or library version.

Replace all `ToJSON` instances with hand-written ones, which make the encoding explicit.

**Comment by bitemyapp** [comment]
Concur with this. Manual JSON instances are best.

**Comment by alanz** [comment]
PR's welcome :)
