### ISSUE TITLE
After build of a new version doesn't work hie

### ISSUE THREAD

**Issue by xgrommx** [haskell/haskell-ide-engine#323]
Hello! I have some problem with a new build of hie. This is what I got
![recursionschemesexample hs app10 2017-09-26 17-44-10](https://user-images.githubusercontent.com/1499594/30866785-dd65153e-a2e2-11e7-813f-d38024bedb80.png)

**Comment by alanz** [comment]
Which commit of hie?

The current master may require you to clear out `~/.cache/ghc-mod` and/or `~/.ghc-mod`. On linux, or whatever the equivalents are on other o/s's

**Comment by xgrommx** [comment]
@alanz still error. I use master as branch

**Comment by alanz** [comment]
Is the project you are working against publicly available? I would like to try and reproduce it.

Also, possibly try it with https://github.com/alanz/haskell-ide-engine/tree/ghc-8.2.1-wz1000-additions-2, which uses the current master branches of `cabal-helper` and `ghc-mod`.

**Comment by xgrommx** [comment]
@alanz I got this error when I tried install your version
```
    /Users/dstoyano/tmp/hie/.stack-work/downloaded/-0GDjqosnE3W/Setup.hs:1:2: error:
        parse error on input ‘#!/’
```

**Comment by alanz** [comment]
Ok, this is still experimental, only tested on linux so far.

The only thing I can suggest that might help is to do

```bash
find . -iname ".stack-work" | xargs rm -fr
```

because sometimes the sub-projects build with the wrong versions of stuff when using git dependencies.

Otherwise roll back to the prior version.

**Comment by xgrommx** [comment]
@alanz I still get error which I provided on image.

**Comment by xgrommx** [comment]
@alanz I also doesn't work with pretty easy application via `stack new app`

**Comment by alanz** [comment]
ok, I will take a look

**Comment by alanz** [comment]
@xgrommx can you tell me what operating system you are on?

And you say it used to work, but now does not? Do you know which version used to work?

And this is the behaviour when it starts up?  Are you installing the plugin from the repo, or from the market?

**Comment by alanz** [comment]
I think the problem is that the vscode plugin is unable to find the `hie` executable. I was unable to get a decent error message in this case. See https://github.com/alanz/vscode-hie-server/issues/17

**Comment by xgrommx** [comment]
@alanz Solved! Not relevant anymore
