### ISSUE TITLE
Go to Definition within module opens redundant file

### ISSUE THREAD

**Issue by FongHou** [haskell/haskell-ide-engine#324]
Hi,

When "Go to Definition" on type or term within the module, VSCode always open another file, rather than just jump to the local definition. For example, I have Main.hs opened. "Go to Definition" opens another file at /var/folders/xm/vkg11d9n74ngq3zsbjlms04w0000gn/T/ghc-mod57475/Main168072824752498235644401115438165.hs (this is on MacOS). Is this a bug? anybody else see this behavior? 

I'm using 0.2.0 vscode plugin, and latest git for server.

Thanks,
Feng

**Comment by homam** [comment]
Related to #322 and #279

**Comment by FongHou** [comment]
Works if checkout Aug-31 commit [63a26084](https://github.com/haskell/haskell-ide-engine/commit/63a26084a67fdd5e0cb8dddeb43eba647f525623). It seems @wz1000's fix for #279 was lost.

**Comment by nponeccop** [comment]
It works for me now. 

@FongHou Can you recheck with last hie? If it still happens, which version of GHC do you use?

**Comment by FongHou** [comment]
latest HIE works for me now. with GHC 8.2.2.
