### ISSUE TITLE
No completion in Neovim

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#331]
I have neovim + deoplete + LanguageClient set up, and completion works with TypeScript LSP server.

However, it doesn't work with haskell. E.g. 

```
$ stack new foo
$ cd foo
$ stack build # verify the project is buildabl
$ nvim src/Lib.hs
```
Then try adding an import and nothing happens. The HIE diagnostic log says that completion RPC is received (actually 2 of them - one with "autosave on click" and one with completion position) but nothing happens.

I already checked that hie is started, and it even produces hlint warnings (but unreliably - e.g. it doesn't seem to rerun after I change a file)

How can I  track the problem down?

**Comment by Anrock** [comment]
> How can I track the problem down?
`:call LanguageClient_setLoggingLevel('DEBUG')` and restart LanguageClient, then check LanguageClient.log, maybe something there.

**Comment by nponeccop** [comment]
It didn't help however it seems `hie` writes more than one log. I found `/tmp/LanguageServer.log` (in addition to the main `-d -l` log which says

```
hie: Could not find $libexecdir/cabal-helper-wrapper
```
followed by instructions on how to setup the environment so `cabal-helper-wrapper` can be found.

Am I supposed to have `cabal-helper-wrapper` executable on PATH when I run hie? I was under impression that all I need is `hie`

**Comment by Anrock** [comment]
Maybe on current master, i don't know. At least few commits back hie only was enough.

**Comment by nponeccop** [comment]
I'm actually using e3f921df897e7a5f4fe33da000b0eb70664c8c47

**Comment by Anrock** [comment]
Yeah, that one works for me without cabal-helper-wrapper. Could you post LanguageClient/Server logs?

**Comment by nponeccop** [comment]
Are versions of Cabal supposed to match? hie was built with 2.x but `stack new` uses the last lts snapshot.

The logs are:
- `-d -l` log: https://pastebin.com/VcpQ7yfx
- /tmp/LanguageClient.log:
```
03:03:01 WARNING [MainThread] Unknown parameter key: rootPath
03:03:01 WARNING [MainThread] register completion manager source failed. Error: NvimError(b'Error calling function.',)
```
- /tmp/LanguageServer.log:
```
hie: user error (Failed to read YAML configuration file /home/andy/.local/bin/data/hlint.yaml
  YAML exception:
Yaml file not found: /home/andy/.local/bin/data/hlint.yaml)
```

**Comment by nponeccop** [comment]
Current version 04af8885a89402168cf464b119697d2539df1e61 works for me
