### ISSUE TITLE
Update README with sublime text instructions

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#334]
Via @nh2 on IRC/Matrix

As for instructions, I just installed the "LSP" Sublime plugin (which is maintained here: https://github.com/tomv564/LSP), opened its settings, and wrote this config:

```
{
  "clients": {
    "haskell-ide-engine": {
      "command": ["/home/niklas/.local/bin/hie", "--lsp"],
      "scopes": ["source.haskell"],
      "syntaxes": ["Packages/Haskell/Haskell.sublime-syntax"],
      "languageId": "haskell",
    },
  },
}
```

**Comment by nh2** [comment]
Example screenshot that shows an error highlighted: ![Example screenshot](https://user-images.githubusercontent.com/399535/31627058-36ab251a-b2ac-11e7-937c-3318794cdf7b.png)
