### ISSUE TITLE
Type holes

### ISSUE THREAD

**Issue by xgrommx** [haskell/haskell-ide-engine#336]
Hello @alanz How about add support for type holes? This is really helpful thing

**Comment by xgrommx** [comment]
@alanz looks like it supported now?
![brainfuck hs app10 2017-10-19 00-02-38](https://user-images.githubusercontent.com/1499594/31742679-025de430-b461-11e7-9cf8-22062da62caf.png)
I built a new version of hie and got it! But maybe will be better use some more better user interface for it

**Comment by BjornMelgaard** [comment]
What about showing possible functions, that can fill type hole, based on current import list?

purescript has this feature

**Comment by kRITZCREEK** [comment]
@BjornMelgaard GHC will get a version of this feature in 8.4, but it can't be implemented inside editor tooling since it needs access to the typing judgements of the type checker.

**Comment by BjornMelgaard** [comment]
@kRITZCREEK wooooow O_O, thanks)

**Comment by lorenzo** [comment]
This was implemented in https://github.com/haskell/haskell-ide-engine/pull/771
