### ISSUE TITLE
hie times out, when moving over package names

### ISSUE THREAD

**Issue by 9b17fe** [haskell/haskell-ide-engine#342]
When I move over the package names in an import statement (~10 times), hie times out
and doesn't respond anymore.
Steps to reproduce:
- Use this minimal emacs config: https://gist.github.com/9b17fe/ef870e9c948cfb7d7e2a3bf70fe6415f
- https://github/alanz/lsp-mode async branch
- `stack new hie-bork protolude`
- `emacs hie-bork/app/Main.hs`
- Move the cursor to the first letter of the package name in the import statement, moving up and down
between Protolude and Lib

**Comment by alanz** [comment]
@9b17fe See https://github.com/alanz/haskell-ide-engine/tree/fast-hover, and for emacs https://github.com/alanz/lsp-mode/tree/async

**Comment by 9b17fe** [comment]
Sorry for the late reply, like I said in IRC, this fixes the lag/time out. :+1:
