### ISSUE TITLE
Ready for langserver.org?

### ISSUE THREAD

**Issue by Tehnix** [haskell/haskell-ide-engine#343]
I was wondering if it would make sense to document HIE on http://langserver.org for Haskell. That would also make it a bit easier to track the progress of which features are implemented etc.

I would be more than happy to do it, though I'm a bit unsure as to how far the progress is atm. It's a simple PR to https://github.com/langserver/langserver.github.io.

Listed are (I've checked off what I could gather from the README):

- [x] Code completion
- [x] Hover
- [ ] Stream reference results
- [x] Jump to def 
- [x] Workspace symbols 
- [x] Find references
- [x] Diagnostics

Can you correct me if I'm wrong?

**Comment by alanz** [comment]
Looks good, and yes, please do so.

FYI, it is also listed on https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations

**Comment by Tehnix** [comment]
@alanz awesome!

PR tracked in https://github.com/langserver/langserver.github.io/pull/53. Once it's closed I'll close this one as well :)

**Comment by Tehnix** [comment]
PR was merged, so I’m gonna close this :)

**Comment by alanz** [comment]
Nice, thanks.
