### ISSUE TITLE
Integration with Nuclide (Atom editor)

### ISSUE THREAD

**Issue by Tehnix** [haskell/haskell-ide-engine#344]
As shortly discussed with @JonCoens in #311 and over Twitter, this ticket is to track the progress of integrating HIE into Nuclide and to let others join if they want :)

The goal is to create a [nuclide-language-service](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-language-service). From what I can gather the part that'll require some work is the RPC part that allows the integration from a remote server, which the local setup reuses. I think [nuclide-clang](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-clang) and [nuclide-clang-rpc](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-clang-rpc) are good starting points for an integration.

**Comment by JonCoens** [comment]
The combination of [nuclide-ocaml-rpc](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-ocaml-rpc) and [nuclide-ocaml](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-ocaml) could also be a good starting point.

From my initial perusing, I find `codeAction`s out of Nuclide to never get a response from `hie`, and initializing a directory does not build anything.

**Comment by Anrock** [comment]
@Tehnix @JonCoens is this still actual?

**Comment by Tehnix** [comment]
@Anrock It never really got started, and since Nuclide is being retired[0], I think we can consider this issue dead.

I'll close this issue to help triaging :)

[0] https://nuclide.io
