### ISSUE TITLE
hie doesn't start with vscode.

### ISSUE THREAD

**Issue by waddlaw** [haskell/haskell-ide-engine#350]
Hello. 
I usually using `vscode + hie` but It stopped working recently.

`output` pane was displayed like below;

```bash
2017-11-15 13:58:08.315963559 [ThreadId 5] - Setting home directory:/home/bm12
2017-11-15 13:58:08.319181354 [ThreadId 5] - run entered for HIE Version 0.1.0.0, Git revision e1d400e2a6443147bfee533bc945a3cca2d8883f (1061 commits) x86_64
2017-11-15 13:58:08.381193558 [ThreadId 5] - Current directory:/home/bm12
Using hoogle db at: /home/bm12/.hoogle/default-haskell-5.0.13.hoo
hie: GMEString "Pattern match failure in do expression at src/GhcMod/Stack.hs:43:3-10"
```

How can I solve it?

## Environments

- vscode:  `1.18.0`
- Haskell Language Server extension: `0.0.5`

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

$ stack --version
Version 1.6.0, Git revision 10559c85d45e53dc4957aae1dda2a911cf7a961b (5337 commits) x86_64 hpack-0.18.1

$ hie --version
Version 0.1.0.0, Git revision e1d400e2a6443147bfee533bc945a3cca2d8883f (1061 commits) x86_64

$ ghc-mod --version
ghc-mod version 5.8.0.0 compiled by GHC 8.0.2
```

Thank you.

**Comment by wz1000** [comment]
Does your project build with stack? (i.e does `stack build` work)

It seems like ghc-mod is not able to find the ghc binary stack is using.

**Comment by waddlaw** [comment]
I solved it maybe.

My project was enable `docker integration build` of `stack` (`stack build --docker`), because of to use database.Once disable it, above error fixed.

**Comment by waddlaw** [comment]
How to use `hie` in docker build?
Not supported yet?

**Comment by alanz** [comment]
Nope, not yet.

Perhaps create a new issue that it should be supported.

It is actually one of the original goals of hie, given that the ide can talk via a protocol.

**Comment by waddlaw** [comment]
@alanz Thank you for your reply.
I made new issue [#376](https://github.com/haskell/haskell-ide-engine/issues/376).

**Comment by hanjoosten** [comment]
I have the same issue. I have built hie, and it definetly is in my path. However, when I start code, I get the error message:

![image](https://user-images.githubusercontent.com/1159672/33798646-cad5181e-dd1c-11e7-9a9e-afcb2915c614.png)

If I start hie from the console, I get the following output:

~~~~
PS C:\Users\hjo20125\Git\Ampersand> hie
2017-12-09 20:10:43.9029813 [ThreadId 3] - Setting home directory:C:\Users\hjo20125
2017-12-09 20:10:43.9059808 [ThreadId 3] - run entered for HIE Version 0.1.0.0, Git revision 34900cc444bb0a7f512ac92e9aaf9cb52ff37899 (1090 commits) x86_64
2017-12-09 20:10:43.9109803 [ThreadId 3] - Current directory:C:\Users\hjo20125
~~~~

I'm on Windows 10. There is no ghc-mod, but stack build works fine

Any ideas?

**Comment by nponeccop** [comment]
Stack doesn't use `ghc-mod` executable, `hie.exe` is enough.

The problem is not in hie-engine, but in Typescript code of hie-server:

https://github.com/alanz/vscode-hie-server/blob/a8cc80783ea8133e42747b1f5c623a38a1acd8f0/src/extension.ts#L121-L126

`which` is not present on Windows, and even on Linux/MacOS something less fragile should be used.

Interestingly there are already such modules on `npm`, e.g. `command-exists`, and it uses `command` (which is shell builtin so it's present in more cases than `which`) and `where` on Windows.

**Comment by hanjoosten** [comment]
Thanks for these suggestions! On my windows machine, I copied where.exe to which.exe . This did the trick for me. 
Of course this is only a workaround. Other people could benefit from this, while there is no fix on Windows.
