### ISSUE TITLE
Use 'hie' as a library or installed executable: Type Checking

### ISSUE THREAD

**Issue by chshersh** [haskell/haskell-ide-engine#353]
I have a file with Haskell source code. I want to type check this file. In my case it means that I want to annotate each value with corresponding type. So later I can ask for type of any value.

Unfortunately, I cannot find documentation for how to do this :(

So any help is appreciated! Even if you just point to related functions that can help me a lot! :blush:

**Comment by alanz** [comment]
If you follow the install instructions for hie, you should get type information on hover.

Please let me know if this is still a problem.

**Comment by jneira** [comment]
I think we could close this one
