### ISSUE TITLE
Vscode : Apply Hint having trouble with guards

### ISSUE THREAD

**Issue by IronGremlin** [haskell/haskell-ide-engine#354]
On windows 10, using VSCode, and having built HIE using most recent pull request -

Using apply hint seems to have some trouble when functions with guards are defined after the target of the hint.

See this [gist](https://gist.github.com/IronGremlin/4f5fdb4c1bec458cf3efd74ecb05f4ac) for an example of the behavior.

I haven't been able to isolate any specific behaviors, but, off the cuff, it really seems like something must be mangling the AST, and not just confusing line numbers.

I would be happy to dig further in if someone can point me in a direction.

**Comment by nponeccop** [comment]
Can you execute `stack install apply-refact` to install refact.exe and use it to apply the refactorings manually?

**Comment by nponeccop** [comment]
We have recently found out that hints don't work with CRLF files (with Windows line ends).

Can you retest with latest HIE (it changed a lot in the last 14 days) and see if the problem still appears with unix-style line separators?

If the problem disappears then it's a duplicate of #396

**Comment by IronGremlin** [comment]
I've been unable to actually get HIE up and running again due to unrelated issues that have nothing to do with this project, and it is unlikely that I'll have time to resolve this before it becomes a completely moot point.
