### ISSUE TITLE
Nix / Nixos support

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#357]
See https://github.com/NixOS/nixpkgs/issues/31697

**Comment by mrkgnao** [comment]
Here are two logs with `hie --lsp --vomit`. I generated a `hie` executable from the Nix derivation in the linked thread, using `nix-build`, and put it on my `$PATH` as `real-hie`. I then made a wrapper script called `hie`:

```sh
#!/bin/sh
real-hie -d -l /tmp/hie.log --vomit $@ | tee /tmp/hie-wire.log
```

The first one is from a `nix-shell`+Cabal project, where VSCode was started from inside a Nix shell.

```
info: Found Cabal project at: /home/mrkgnao/code/sans/sound-and-complete
info: Using Cabal project at: /home/mrkgnao/code/sans/sound-and-complete
Using hoogle db at: /home/mrkgnao/code/sans/sound-and-complete/hiehoogledb.hoo
info: Found Cabal project at: /home/mrkgnao/code/sans/sound-and-complete
info: Using Cabal project at: /home/mrkgnao/code/sans/sound-and-complete
DEBUG: reading cache: /home/mrkgnao/code/sans/sound-and-complete/dist/setup-config.ghc-mod.cabal-components
DEBUG: resolveEntrypoint:
       ["-i","-idist/build/sound-and-complete/sound-and-complete-tmp","-isrc","-idist/build/sound-and-complete/autogen","-idist/build/global-autogen","-Idist/build/sound-and-complete/autogen","-Idist/build/global-autogen","-Idist/build/sound-and-complete/sound-and-complete-tmp","-optP-include","-optPdist/build/sound-and-complete/autogen/cabal_macros.h"]
Warning: resolveModule "/home/mrkgnao/code/sans/sound-and-complete/src/Main.md":
         cannot compile this file to desired target:
/home/mrkgnao/code/sans/sound-and-complete/src/Main.md
DEBUG: resolveEntrypoint: []
DEBUG: making sure autogen files exist
DEBUG: autogen files out of sync
DEBUG: writing Cabal autogen files
DEBUG: reading cache: dist/setup-config.ghc-mod.resolved-components
DEBUG: Could not find a component assignment, falling back to
       picking library component in cabal file.
VOMIT: Using the following mapped files:
VOMIT: Initializing GHC session with following options: "-fbuilding-cabal-package" "-O" "-outputdir" "dist/build/sound-and-complete/sound-and-complete-tmp" "-odir" "dist/build/sound-and-complete/sound-and-complete-tmp" "-hidir" "dist/build/sound-and-complete/sound-and-complete-tmp" "-stubdir" "dist/build/sound-and-complete/sound-and-complete-tmp" "-i" "-idist/build/sound-and-complete/sound-and-complete-tmp" "-isrc" "-idist/build/sound-and-complete/autogen" "-idist/build/global-autogen" "-Idist/build/sound-and-complete/autogen" "-Idist/build/global-autogen" "-Idist/build/sound-and-complete/sound-and-complete-tmp" "-optP-include" "-optPdist/build/sound-and-complete/autogen/cabal_macros.h" "-hide-all-packages" "-Wmissing-home-modules" "-package-id" "base-4.10.0.0" "-package-id" "mtl-2.2.1-19EL8AGBsN3DnnOhrC9xY3" "-package-id" "transformers-0.5.2.0" "-package-id" "safe-0.3.15-5SmTamu8dz8KnTA9MfNcRD" "-package-id" "lens-4.15.4-4q970k0XvkV7aqAQ5eBtP3" "-package-id" "prettyprinter-1.1.1-2QNu42iMc4MGCD9K0ZJaq" "-package-id" "hspec-2.4.4-FJuRtB7WMYqKF0brZ7icE5" "-package-id" "containers-0.5.10.2" "-package-id" "adjunctions-4.3-18NVfKnieoxAHaA9U5pxMh" "-package-id" "profunctors-5.2.1-1lOUsE8aiaZLtdvF0ROsOX" "-package-id" "text-1.2.2.2-5RuPYjcevF59B6YENNKuiP" "-package-id" "bytestring-0.10.8.2" "-package-id" "hashable-1.2.6.1-BqrB4iRJk0C8e42ef63nR4" "-package-id" "unordered-containers-0.2.8.0-KsuUwaupoRi1cUuuci0Zxb" "-XHaskell2010" "-pgmL" "markdown-unlit" "-O0" "-Wall"
DEBUG: initSession: Session not initialized, creating new one
real-hie: <command line>: cannot satisfy -package-id base-4.10.0.0
    (use -v for more information)
```

The second one is a Stack project with `nix: {enable: true}` in `stack.yaml` (I think all this does is use Nix for GHC and `zlib`).

```
info: Found Cabal project at: /home/mrkgnao/code/sans/sound-and-complete
info: Using Cabal project at: /home/mrkgnao/code/sans/sound-and-complete
Using hoogle db at: /home/mrkgnao/code/sans/sound-and-complete/hiehoogledb.hoo
info: Found Cabal project at: /home/mrkgnao/code/sans/sound-and-complete
info: Using Cabal project at: /home/mrkgnao/code/sans/sound-and-complete
DEBUG: reading cache: /home/mrkgnao/code/sans/sound-and-complete/dist/setup-config.ghc-mod.cabal-components
DEBUG: resolveEntrypoint:
       ["-i","-idist/build/sound-and-complete/sound-and-complete-tmp","-isrc","-idist/build/sound-and-complete/autogen","-idist/build/global-autogen","-Idist/build/sound-and-complete/autogen","-Idist/build/global-autogen","-Idist/build/sound-and-complete/sound-and-complete-tmp","-optP-include","-optPdist/build/sound-and-complete/autogen/cabal_macros.h"]
Warning: resolveModule "/home/mrkgnao/code/sans/sound-and-complete/src/Main.md":
         cannot compile this file to desired target:
/home/mrkgnao/code/sans/sound-and-complete/src/Main.md
DEBUG: resolveEntrypoint: []
DEBUG: making sure autogen files exist
DEBUG: autogen files out of sync
DEBUG: writing Cabal autogen files
DEBUG: reading cache: dist/setup-config.ghc-mod.resolved-components
DEBUG: Could not find a component assignment, falling back to
       picking library component in cabal file.
VOMIT: Using the following mapped files:
VOMIT: Initializing GHC session with following options: "-fbuilding-cabal-package" "-O" "-outputdir" "dist/build/sound-and-complete/sound-and-complete-tmp" "-odir" "dist/build/sound-and-complete/sound-and-complete-tmp" "-hidir" "dist/build/sound-and-complete/sound-and-complete-tmp" "-stubdir" "dist/build/sound-and-complete/sound-and-complete-tmp" "-i" "-idist/build/sound-and-complete/sound-and-complete-tmp" "-isrc" "-idist/build/sound-and-complete/autogen" "-idist/build/global-autogen" "-Idist/build/sound-and-complete/autogen" "-Idist/build/global-autogen" "-Idist/build/sound-and-complete/sound-and-complete-tmp" "-optP-include" "-optPdist/build/sound-and-complete/autogen/cabal_macros.h" "-hide-all-packages" "-Wmissing-home-modules" "-package-id" "base-4.10.0.0" "-package-id" "mtl-2.2.1-19EL8AGBsN3DnnOhrC9xY3" "-package-id" "transformers-0.5.2.0" "-package-id" "safe-0.3.15-5SmTamu8dz8KnTA9MfNcRD" "-package-id" "lens-4.15.4-4q970k0XvkV7aqAQ5eBtP3" "-package-id" "prettyprinter-1.1.1-2QNu42iMc4MGCD9K0ZJaq" "-package-id" "hspec-2.4.4-FJuRtB7WMYqKF0brZ7icE5" "-package-id" "containers-0.5.10.2" "-package-id" "adjunctions-4.3-18NVfKnieoxAHaA9U5pxMh" "-package-id" "profunctors-5.2.1-1lOUsE8aiaZLtdvF0ROsOX" "-package-id" "text-1.2.2.2-5RuPYjcevF59B6YENNKuiP" "-package-id" "bytestring-0.10.8.2" "-package-id" "hashable-1.2.6.1-BqrB4iRJk0C8e42ef63nR4" "-package-id" "unordered-containers-0.2.8.0-KsuUwaupoRi1cUuuci0Zxb" "-XHaskell2010" "-pgmL" "markdown-unlit" "-O0" "-Wall"
DEBUG: initSession: Session not initialized, creating new one
real-hie: <command line>: cannot satisfy -package-id base-4.10.0.0
    (use -v for more information)
```

**Comment by alanz** [comment]
Please show the contents of `/tmp/hie.log`

**Comment by mrkgnao** [comment]
So the problem in the Stack project turned out to be the old `ghc-mod` `dist/setup-config` thing, and deleting the `dist/` folder fixed it. 

The Nix project, on the other hand, seemed to be an incompatibility in GHC versions. I compiled `hie` from source using `stack-8.2.1.yaml`. Here's the output from VSCode:

```
2017-11-18 22:12:00.607307544 [ThreadId 11] - Setting home directory:/home/mrkgnao
2017-11-18 22:12:00.611015588 [ThreadId 11] - run entered for HIE Version 0.1.0.0, Git revision 9e39517408fd2948c60ac49e56267c93051f8878 (1066 commits) x86_64
2017-11-18 22:12:00.619058282 [ThreadId 11] - Current directory:/home/mrkgnao
hie: <command line>: cannot satisfy -package-id mtl-2.2.1-19EL8AGBsN3DnnOhrC9xY3
    (use -v for more information)
```

**Comment by Fresheyeball** [comment]
I have but a bounty on this issue. https://www.bountysource.com/issues/51713360-nix-nixos-support would love to see this resolved ASAP.

**Comment by domenkozar** [comment]
@fresheyeball @imalsogreg do you want to have IDE support for projects using nix-shell/nix-build or is stack+nix enough?

**Comment by imalsogreg** [comment]
@domenkozar Preferably nix-shell aware; most of my work is on projects with dependencies managed by nix.

**Comment by Fresheyeball** [comment]
@domenkozar I don't use `stack`. I'm in the same boat as @imalsogreg.

**Comment by shlevy** [comment]
https://github.com/NixOS/nixpkgs/pull/32947 fixes this I think.

**Comment by alanz** [comment]
Does anything need to change in https://github.com/haskell/haskell-ide-engine#installation-with-nix because of this?

**Comment by shlevy** [comment]
@alanz Those instructions are still reasonable for building and installing a local checkout with stack + nix, but end-users will probably want to install from nixpkgs which they can do with my PR. If it would be welcome, I'd be happy to also add nix expressions to make it possible to do a self-contained (not via stack) nix build from a nix checkout.

**Comment by shlevy** [comment]
Note that there may be some confusion on my part if this addresses the issue here. The idea with that PR is that your nix environment (nix-shell, nix-buffer, whatever) would build haskell-ide-engine with the same haskell package set as your package is using, and that would fix the version mismatch here. But @Fresheyeball is testing to see if that's enough.

**Comment by Fresheyeball** [comment]
@shlevy would you mind reaching out on slack?

**Comment by shlevy** [comment]
@Fresheyeball Which slack?

**Comment by Fresheyeball** [comment]
Idk, I am on fpchat.

**Comment by shlevy** [comment]
@imalsogreg @Fresheyeball The nixpkgs PR is now merged, testing appreciated 😄

**Comment by shlevy** [comment]
@domenkozar This seems very hard to integrate in with nixpkgs haskell package sets

**Comment by michalrus** [comment]
@domenkozar, so if I add this `ghc-8.2.nix` to my project’s `default.nix`/`shell.nix`… will it see correct dependencies declared in that same `default.nix` (e.g. by `callCabal2Nix ./.`)?

@shlevy is this what you mean, that it won’t?

**Comment by domenkozar** [comment]
@shlevy why would you need that?

**Comment by shlevy** [comment]
@domenkozar Because we're defining package environments for our projects based on nixpkgs (plus our own overlays), and we want (well, need) to have the same dependencies (not just the same GHC version!) to use hie with our projects.

**Comment by shlevy** [comment]
So I want to make an env that contains "the hie appropriate for this project" and launch that hie per-project.

**Comment by michalrus** [comment]
^ Exactly. What’s the point otherwise?

**Comment by domenkozar** [comment]
Afaik HIE does this at runtime using ghc-mod, so you'd have to run it with nix-shell of your environment.

**Comment by michalrus** [comment]
It does, working v. well. =) Thank you, @domenkozar!

**Comment by domenkozar** [comment]
@Fresheyeball @imalsogreg could you provide a Nix project you'd like to see HIE working with? I think with hie-nix it should be trivial, but I want to make sure we agree that's the acceptance criteria for this to pass :)

**Comment by srid** [comment]
Here's a skeleton Nix project:
https://github.com/ElvishJerricco/reflex-project-skeleton

The frontend package can be compiled using ghcjs, although for editor integration purposes one could compile it using ghc. It even targets android and iOS.

Should be a good candidate to test HIE support?

**Comment by alanz** [comment]
Once this thing settles down to best practice, can someone make a PR on the README, for future NIX users?

**Comment by domenkozar** [comment]
@alanz https://github.com/haskell/haskell-ide-engine#installation-with-nix

@srid @ElvishJerricco made it work, but not sure he posted the steps (although they are as in README with usual caveats).

Is this considered then done? :)

**Comment by alanz** [comment]
Well, the link is good, but the instructions at https://github.com/domenkozar/hie-nix/blob/master/README.md don't  work.

We now seem to have
  - default.nix
  - ghc-8.0.nix
  - ghc-8.2.nix

Rather than hie-nix.nix

**Comment by domenkozar** [comment]
It did work (I've tested locally), but I see your point, it was confusing.

What about this: https://github.com/domenkozar/hie-nix#install

**Comment by alanz** [comment]
Yep, that works.

And a pretty neat way of doing it.

Thanks.

**Comment by alanz** [comment]
@domenkozar I presume at some stage this will end up on a binary cache somewhere?

My install (admittedly for a fresh nixpkgs install) is building the world.

**Comment by domenkozar** [comment]
Yes, that's the plan :)

**Comment by Camsbury** [comment]
Writing here to thank @michalrus again. Coming back to this months later, and your strategy has worked for me.
