### ISSUE TITLE
How to check what is wrong with the set up?

### ISSUE THREAD

**Issue by wpoosanguansit** [haskell/haskell-ide-engine#362]
Hi,

I have installed Neovim and HIE with stack --nix.  hie command is in the path and seems to be working fine as I do not see any error.  However, in Neovim things do not seem to be working as there is no highlight or anything showing hints or error when I open .hs file.  I checked the vim.rc and see that the configuration for HIE is loaded correctly.  Is there any documentation on how to set things up for Neovim in more detail?  Thanks for your help.

**Comment by nponeccop** [comment]
You can
1. Enable the HIE log (see the extra command line options to `hie` below)
2. Use a working lsp server such as the typescript's to see that everything works on neovim side

```vim
let g:LanguageClient_serverCommands = {
    \ 'haskell': ['hie', '--lsp', '-d', '-l', '/home/foo/hie.log'],
    \ 'typescript' : [ 'typescript-language-server', '--stdio' ]
    \ }
```

**Comment by wpoosanguansit** [comment]
Thank you.  Let me try that.
    On Friday, November 24, 2017, 11:41:51 PM EST, nponeccop <notifications@github.com> wrote:  
 
 
You can
   
   - Enable the HIE log (see the extra command line options to hie below)
   - Use a working lsp server such as the typescript's to see that everything works on neovim side
let g:LanguageClient_serverCommands = {
    \ 'haskell': ['hie', '--lsp', '-d', '-l', '/home/foo/hie.log'],
    \ 'typescript' : [ 'typescript-language-server', '--stdio' ]
    \ }

**Comment by nponeccop** [comment]
Closing as there is no feedback and/or actual issue
