### ISSUE TITLE
Respect ghc-options

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#365]
If I have something like this in `.cabal` HIE outputs the suppressed warnings:

```cabal
  ghc-options: -Wall -Wno-name-shadowing
    -Wno-unused-matches -Wno-incomplete-patterns -Wno-missing-signatures -Wno-orphans
```
I.e. `stack build` shows 1 warning but HIE shows a dozen

**Comment by wz1000** [comment]
I believe https://github.com/DanielG/ghc-mod would be a better place to report this issue.

**Comment by nponeccop** [comment]
Done: https://github.com/DanielG/ghc-mod/issues/918

**Comment by DanielG** [comment]
@wz1000 this is not cool. Don't just redirect users upstream without doing any triage. Please come back with a test case or reproduction instructions relevant to ghc-mod.

**Comment by nponeccop** [comment]
I couldn't reproduce the problem with `ghc-mod check`: it properly reports 1 warning.
