### ISSUE TITLE
no handler for textDocument/references

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#370]
When I try to use references in neovim (through `:Denite references`) it crashes with this message:

```
[Error] haskell-lsp:no handler for. Object (fromList [("params",Object (fromList [("textDocument",Object (fromList [("uri",String "file:///home/foo/Main.hs")])),("position",Object (fromList [("character",Number 0.0),("line",Number 50.0)])),("context"
,Object (fromList [("includeDeclaration",Bool True)]))])),("method",String "textDocument/references"),("id",Number 1.0),("jsonrpc",Str
ing "2.0")])
```

Is it an issue of HIE or of the neovim LSP client which sends a message for a capability not advertised?

**Comment by wz1000** [comment]
Project wide references haven't been implemented yet. use
textDocument/documentSymbol for references in the file.

**Comment by nponeccop** [comment]
I've read the spec more carefully and it seems that `textDocument/references`  is a capability of LSP 2.0 and we can only opt out of 3.0 capabilities.

So is it a good idea to provide a stub implementation returning no references so the clients expecting it to be implemented as per the spec (e.g. neovim) don't crash?

**Comment by alanz** [comment]
@nponeccop can you try that branch I just committed. It returns an empty list for now, but will stop any crash at least.

**Comment by nponeccop** [comment]
`:Denite references` doesn't crash anymore. It just displays an empty pane.
