### ISSUE TITLE
Use severity:3 (info) for hlint errors and warnings

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#375]
Now it uses warnings (severity:2) so hints and warnings are blended together in neovim.

**Comment by nponeccop** [comment]
severity:4 is used correctly for hlint "hints". However, hlnt warnings use the same severity as ghc warnings. I think we could use severity: 3 (info) for hlint errors and warnings.

**Comment by alanz** [comment]
Makes sense.

Would you be interested in making a PR? It is quite straightforward.
