### ISSUE TITLE
Doesn't work with Atom 1.22.0

### ISSUE THREAD

**Issue by domenkozar** [haskell/haskell-ide-engine#381]
Using https://github.com/Tehnix/ide-haskell-hie/ I can observe running hie in process list, but no support in browser (nothing happens on hover).

@alanz says it's line 22 in https://paste.pound-python.org/show/a3JzTsxiZ0bUL7r9swa4/

**Comment by alanz** [comment]
The `workspace/didChangeWatchedFiles` message is not currently handled by `hie`

**Comment by domenkozar** [comment]
@alanz with your branch I'm able to see HIE working in Atom.
