### ISSUE TITLE
neovim LanguageClient warns on rootPath and settingsPath

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#382]
The former is deprecated, and the later is non-standard. They get logged in LanguageServer.log created at temp folder (`/tmp` on Linux and `%temp%` on Windows):

```
08:22:06 WARNING [MainThread] Unknown parameter key: rootPath
08:22:06 WARNING [MainThread] Unknown parameter key: settingsPath
```
from the source it seems it is harmless:

[LanguageClient.py#L103](https://github.com/autozimu/LanguageClient-neovim/blob/0d9a8160bd1eec817c2ca455037951db2605b8e7/rplugin/python3/LanguageClient/LanguageClient.py#L103) called from [LanguageClient.py#L60](https://github.com/autozimu/LanguageClient-neovim/blob/0d9a8160bd1eec817c2ca455037951db2605b8e7/rplugin/python3/LanguageClient/LanguageClient.py#L60) (it's the only place with non-constant arg)

What we should do with these? We could just ask @autozimu ignore these keys, or we could drop them or?

**Comment by autozimu** [comment]
They’re harmless warnings.

I should have use info instead of warning.

**Comment by nponeccop** [comment]
The problem doesn't happen with the last LanguageClient
