### ISSUE TITLE
Parallel circleci build

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#389]
I have a beta ready on https://github.com/nponeccop/haskell-ide-engine/blob/master/.circleci/config.yml

It fails though but fails in parallel 🥇 

https://circleci.com/gh/nponeccop/haskell-ide-engine

![image](https://user-images.githubusercontent.com/528415/33592984-b9bb844e-d963-11e7-88bd-d3805e9c8afe.png)

I will work on it tomorrow

**Comment by Tehnix** [comment]
Perhaps not the scope of this, but would it be possible to build the binaries for HIE on CircleCI?

**Comment by nponeccop** [comment]
The script does it (saves the binaries)

**Comment by Tehnix** [comment]
Awesome! I could imagine that being used to make the setup process super simple then :)

**Comment by nponeccop** [comment]
There's no such thing as cross-distribution linux binary, but with some tricks it could probably work. After all, `stack` managed to get cross-platform `ghc` by building several flavors of it, so we could do the same.

**Comment by nponeccop** [comment]
![image](https://user-images.githubusercontent.com/528415/33792245-ef6eb84e-dc70-11e7-953e-67f107cdd60a.png)
Finally all 3 builds are green. Few issues related to caching remain.

- [ ] Hoogle generate is not cached
- [ ] Stack upgrade --git is not cached (should we attempt to install the latest stack at all?)
- [ ] There is no clear mechanism to update caches. Ideally we should use whatever cache we have and save its updated version after the build. But with circleci it's not possible. So I resorted to manual invalidation.

**Comment by alanz** [comment]
Nice. 

See also https://github.com/haskell/haskell-ide-engine/pull/408

**Comment by nponeccop** [comment]
Yep. I'll rebase tomorrow

**Comment by nponeccop** [comment]
Some more remaining issues:

- [ ] Avoid re-download of GHC 8.0.2 by tests
- [ ] Use lts-10 Docker image for 8.2.2
- [ ] Excessive verbosity of 8.0.2 tests
- [ ] Decide on whether to use git stack (with --only-snapshot useful feature) and how to pin its git revision
- [ ] Excessive verbosity of 8.2.2 stack install
- [ ] Hackage index is not cached

**Comment by jneira** [comment]
It seems most of remaining issues are adressed or we are not longer working on them so closing
