### ISSUE TITLE
Decide on package name for the plugin API / plugin packages

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#39]
At the moment the plugin API package is called `haskell-ide-plugin-api`.

Before this goes on to hackage, we must agree on an appropriate package name for it, and a naming scheme for packages in general.

Some ideas to kick off the discussion

* haskell-ide-plugin-api (i.e. stays as is)
* haskell-ide-engine-api
* hie-plugin-api
* others?

In a related fashion, a given plugin can be called

* haskell-ide-plugin-hare
* hie-hare
* hiep-hare
* hie-plugin-hare

Note: I fully expect future tools to provide the `PluginDescriptor` as part of the normal package, so `HaRe` would simply export

```haskell
hareDescriptor :: PluginDescriptor
```

**Comment by alanz** [comment]
Any comments on this? I would like to make the change.

I am leaning towards `hie-xxx`

**Comment by mgsloan** [comment]
I like `hie-*`.  Also the definition is nice - "to go quickly" - http://www.merriam-webster.com/dictionary/hie

**Comment by alanz** [comment]
ok, makes sense to me. I will put in a PR to do this.

I am keen to get something on hackage, even if just the `hie-plugin-api` so I can experiment with exposing plugins in other packages, such as HaRe.
