### ISSUE TITLE
Help packages maintainer

### ISSUE THREAD

**Issue by damienflament** [haskell/haskell-ide-engine#394]
Hi!

I added an [haskell-ide-engine package](https://aur.archlinux.org/packages/haskell-ide-engine/) to the ArchLinux User Repository. But your git repository has not any tags to fix the version source code state, even if [the Cabal package is tagged as 0.1.0.0](https://github.com/haskell/haskell-ide-engine/blob/701723324eef5101a0c1bbcfac0d58d6ffaaaef0/haskell-ide-engine.cabal#L2).

I will be helpful to add a tag even if the version hasn't changed since the beginning of the development. It will help us fix the source code state used for building.

**Comment by nponeccop** [comment]
There is a concept of `-git` packages in AUR. At this point (haskell-ide-engine doesn't have stable releases yet) you should add `haskell-haskell-ide-engine-git` instead. See (https://aur.archlinux.org/packages/haskell-haskell-src-exts) for why 2 times haskell.

Also I wonder what happened to `cblrepo` tool? Is it used in any way these days?https://github.com/magthe/cblrepo

**Comment by damienflament** [comment]
In the official ArchLinux repositories, only Haskell libraries are prefixed with _haskell_. Executable tools are not. This prefix is always used in the ArchHaskell repository.

Concerning _cblrepo_, I don't see any reason to use it as you use Stack to manage building. So the building process is quite simple. Maybe I'm wrong ?

Concerning the _git_ package, you're right.

Thanks !
