### ISSUE TITLE
Cabal-helper uses older snapshots for its runtime part

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#395]
It appears that circleci builds use inconsistent snapshots. Below is an excerpt from build 100, `stack test -j 2 haskell-ide-engine` step. You can see that "runtime" cabal-helper and/or `testdata` package is built using `nightly-2017-06-16` while its `library` part uses `lts-9.14` (which is correct). 

```
functional spec
  consecutive plugin commands
Downloading nightly-2017-06-16 build plan ...
Downloaded nightly-2017-06-16 build plan.
mtl-2.2.1: using precompiled package
text-1.2.2.2: using precompiled package
parsec-3.1.11: using precompiled package
testdata-0.1.0.0: configure (exe)
Configuring testdata-0.1.0.0...
Completed 4 action(s).
[1 of 5] Compiling CabalHelper.Shared.Sandbox ( /tmp/cabal-helper-source30336/CabalHelper/Shared/Sandbox.hs, cabal-helper0.8.0.0-Cabal1.24.2.0.build/CabalHelper/Shared/Sandbox.o )
[2 of 5] Compiling CabalHelper.Shared.InterfaceTypes ( /tmp/cabal-helper-source30336/CabalHelper/Shared/InterfaceTypes.hs, cabal-helper0.8.0.0-Cabal1.24.2.0.build/CabalHelper/Shared/InterfaceTypes.o )
[3 of 5] Compiling CabalHelper.Shared.Common ( /tmp/cabal-helper-source30336/CabalHelper/Shared/Common.hs, cabal-helper0.8.0.0-Cabal1.24.2.0.build/CabalHelper/Shared/Common.o )
[4 of 5] Compiling CabalHelper.Runtime.Licenses ( /tmp/cabal-helper-source30336/CabalHelper/Runtime/Licenses.hs, cabal-helper0.8.0.0-Cabal1.24.2.0.build/CabalHelper/Runtime/Licenses.o )
```

**Comment by alanz** [comment]
When you change some deps (like cabal-helper), you have to manually "run without cache", to restart the build clean.

**Comment by nponeccop** [comment]
ok I've initiated build 101 to see

**Comment by nponeccop** [comment]
**Update:** The inconsistency is still there in https://circleci.com/gh/haskell/haskell-ide-engine/101. It's a clean build and you can check that "no cache is used" during `Restoring cache` step.

```
functional spec
  consecutive plugin commands
Downloading nightly-2017-06-16 build plan ...
Downloaded nightly-2017-06-16 build plan.
```

Probably we should ask @DanielG to see if it's normal and safe behaviour or it's problematic.

**Comment by nponeccop** [comment]
Here they are:

https://github.com/haskell/haskell-ide-engine/blob/72516f9e5a38f4964be62bfb89565ea83869ca43/test/TestUtils.hs#L71-L75

```hs
-- |Choose a resolver based on the current compiler, otherwise HaRe/ghc-mod will
-- not be able to load the files
resolver :: String
resolver =
#if (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,2,2,0)))
  "resolver: nightly-2017-11-25"
#elif __GLASGOW_HASKELL__ >= 802
  "resolver: nightly-2017-11-24"
#else
  "resolver: nightly-2017-06-16"
#endif
```
Should I change them to the respective resolvers we use for 8.2.2, 8.2.1 and 8.0.2? Is there a non-fragile way to avoid such hardcoding?

**Comment by nponeccop** [comment]
Although the build is not yet complete, the fix worked:

```
functional spec
  consecutive plugin commands
Building all executables for `testdata' once. After a successful build of all of them, only specified executables will be rebuilt.
testdata-0.1.0.0: configure (exe)
Configuring testdata-0.1.0.0...
[1 of 5] Compiling CabalHelper.Shared.Sandbox ( /tmp/cabal-helper-source35945/CabalHelper/Shared/Sandbox.hs, cabal-helper0.8.0.0-Cabal1.24.2.0.build/CabalHelper/Shared/Sandbox.o )
[2 of 5] Compiling CabalHelper.Shared.InterfaceTypes ( /tmp/cabal-helper-source35945/CabalHelper/Shared/InterfaceTypes.hs, cabal-helper0.8.0.0-Cabal1.24.2.0.build/CabalHelper/Shared/InterfaceTypes.o )
```
Note that there are no "downloading snapshot" messages unlike in the beginning of this thread.

**Comment by alanz** [comment]
Because the resolvers affect the GHC used, they have to be hardcoded like that for the tests, unfortunately.

We should perhaps add a comment in the stack-XXX.yaml files to remember to update the test file when changing the resolver.

**Comment by nponeccop** [comment]
I was thinking of parsing the three `stack.yaml` or something like this. Are you not merging?

**Comment by alanz** [comment]
How? We need to support GHC 8.0.2, 8.2.1, 8.2.2

Each needs its own snapshot, its the way stack works.

**Comment by nponeccop** [comment]
I mean like this:

```hs
resolver :: IO String
resolver = readResolverFrom $
#if (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,2,2,0)))
  "stack-8.2.2.yaml"
#elif __GLASGOW_HASKELL__ >= 802
  "stack-8.2.1.yaml"
#else
  "stack.yaml"
#endif
```
Note `readResolverFrom $` and `IO String`.

**Comment by alanz** [comment]
Because then you end up cloning a whole bunch of git repos into the test
subdirs.

**Comment by nponeccop** [comment]
I still don't understand :(

The new code is equivalent in external behaviour to the old one. Except that "resolver: nightly-2017-06-16" string is defined in one place instead of two places.

readResolverFrom parses the argument file (stack.yaml or stack-8.2.2.yaml) and returns the resolver string, just like it does now.

**Comment by alanz** [comment]
I missed the `readResolver` bit.

And after I replied I thought that something like it would be the way to go.

Does such a thing exist?

**Comment by nponeccop** [comment]
It doesn't exist yet but I can use https://hackage.haskell.org/package/yaml library (the same one Stack uses) to correctly parse the `resolver` root-level key. Then I only need some plumbing to pass IO effect from `setupStackFiles :: IO ()`. If you agree it should be an easy endeavor.

**Comment by alanz** [comment]
Please do, it will definitely simplify things
