### ISSUE TITLE
What would the smallest useful haskell-ide look like

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#4]
haskell-ide has a potentially very large scope.

A useful approach to managing this is to identify some useful, uncontroversial, small functionality that can test our architectural choices.

I think there are three broad categories of things that can be provided via `haskell-ide`

* A place where a tool writer can host a tool as a plugin, and make use of standardised services to access the raw project and communication with the IDE, thus minimising this effort for all to get the tool integrated into multiple environments.

* A way to query information about a project, and present it to the user. This in turn is a large topic, and can cover anything from contents of available libraries, to type information of loaded modules, to information to support syntax highlighting.

  This may include on the fly error checking

* Providing access to a REPL

So I suggest we come up with something from one of these categories, and aim to let it communicate with at least 2 different IDEs via the process identified in #2 / #3 

What should these be?

**Comment by gracjan** [comment]
Isn't that 'REPL', 'type info', 'library info' are plugins for the architecture you are talking about in item number one?

**Comment by alanz** [comment]
They are probably all plugins. To me the split is more REPL, the stuff you normally expect in an IDE haskell mode, then anything else (working from the bottom up)

So in terms of the question, do we start trying to get a REPL going, some basic editor features, or some new feature (HaRe?)

**Comment by gracjan** [comment]
I vote for new feature. REPL is easy to get by, HaRe is a killer feature.

**Comment by alanz** [comment]
That ties in nicely with my motivation for this project. (Cue evil cackle)

**Comment by alanz** [comment]
I am beginning to think the best approach is to first put the standard syntax check command in place, as a plugin, to ensure that the communication channel(s) to the IDE can be designed.

Once we have a clearer view of the communication we can see how to plug additional commands in for a plugin such as HaRe.

This would allow an initial straight drop in of the Idris IDE protocol

**Comment by alanz** [comment]
We are making progress, this question is no longer all that relevant.
