### ISSUE TITLE
Bullet-proof installation instructions

### ISSUE THREAD

**Issue by saurabhnanda** [haskell/haskell-ide-engine#409]
Over the past week I've directed 4 newbies in my team to the HIE installation instructions and all 4 of them messed it up. I'm just opening this as a reminder for myself. I plan to figure out what went wrong a raise a PR to fix this.

**Comment by saurabhnanda** [comment]
Okay, this is what I have, till now. Is this acceptable for a PR: http://www.vacationlabs.com/haskell/environment-setup.html#installing-vscode-hie

**Comment by ianchanning** [comment]
@saurabhnanda the link that you gave is no longer available. Have you got these instructions anywhere else?

**Comment by saurabhnanda** [comment]
@ianchanning we were moving sites and missed out this folder. The earlier link should be up now. Sorry about the trouble.

**Comment by ianchanning** [comment]
Brilliant - thanks!

**Comment by ianchanning** [comment]
I did some work on the installation process (https://github.com/haskell/haskell-ide-engine/pull/998) that's now been merged.

Your article is great and I love the simplicity of:

```
$ git clone https://github.com/haskell/haskell-ide-engine
$ cd haskell-ide-engine
$ stack install
```

The only difference is that I was advised that it's better to use the `make hie-x.x.x` command which is a wrapper on `stack install`, plus even the default `make` command doesn't install the hoogle documentation. So I think for your instructions you could switch to:

```
$ git clone https://github.com/haskell/haskell-ide-engine
$ cd haskell-ide-engine
$ make hie-8.6.2
```

This would be the same version that `stack install` would do.

**Comment by kRITZCREEK** [comment]
`make` is a non-trivial dependency on Windows. So unless it can't be done without that I'd suggest to avoid it in bulletproof installation instructions.

**Comment by ianchanning** [comment]
I agree that that means there is a different path for Windows (there is a powershell script). But the make file does extra required checks to make it more bullet proof than `stack install` and is [recommendation from the core developers][1]:

> The preferred installation mechanism is actually via the makefile, as it makes sure the repo is synced, installs the required cabal libraries if missing, and makes copies of the executables with suffixes to be able to tell them apart.

[1]: https://github.com/haskell/haskell-ide-engine/pull/998#issuecomment-447648096

**Comment by Anrock** [comment]
> `make` is a non-trivial dependency on Windows
That was discussed multiple times and i still think that `stack exec -- pacman install make` is trivial enough, although still an additional step it takes care of all the extra quirks so user wouldn't have to run them manually.. Make dependency will go away with #991, btw.

**Comment by Anrock** [comment]
Makefile support is dropped and README was heavily modified recently. If you found it's still lacking - please open a new issue.
