### ISSUE TITLE
Problem with installing a new version of HIE

### ISSUE THREAD

**Issue by xgrommx** [haskell/haskell-ide-engine#411]
Hello @alanz I have some problem with installing a new version of HIE. Here my terminal
```
hie:master λ stack install
Unable to parse cabal file for base-4.10.1.0: NoParse "build-depends" 96
hie:master λ
```

**Comment by alanz** [comment]
master has switched the default `stack.yaml` to be one using GHC 8.2.2

The old behaviour can be had by

```bash
$ stack --stack-yaml=stack-8.0.2.yaml install
```

**Comment by xgrommx** [comment]
@alanz What is difference between 8.0.2 and 8.2.2 for HIE? Maybe some interesting features?

**Comment by alanz** [comment]
Basically the same. 

The main thing is that the GHC hie was installed with must match the GHC used in the project you are using hie on.

Otherwise it will not be able to load the project and provide information about it.

**Comment by nponeccop** [comment]
@xgrommx You need a new version of Stack, too.

**Comment by xgrommx** [comment]
Thanks @nponeccop and @alanz
