### ISSUE TITLE
Build fails: "Invalid flag name" with stack 1.5

### ISSUE THREAD

**Issue by chris-martin** [haskell/haskell-ide-engine#417]
This is what I get when I run `stack install --nix`:

```
Downloaded nightly-2017-12-15 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

I'm using the latest stack available from nixpkgs-unstable, version 1.5.1

**Comment by nponeccop** [comment]
We test with the stack you get with `stack upgrade` (currently it's 1.6.1)

**Comment by chris-martin** [comment]
thanks, I'll fix the docs

**Comment by nponeccop** [comment]
Is the issue gone with 1.6?

**Comment by chris-martin** [comment]
It seems to be building with 1.6.1. I'm not sure how to get 1.6.

**Comment by nponeccop** [comment]
I meant 1.6.1, sorry
