### ISSUE TITLE
ghcModPlugin "type" command removed

### ISSUE THREAD

**Issue by halhenke** [haskell/haskell-ide-engine#420]
Hey,

I'm not completely familiar with how this whole repo fits together but I notice that the `showType` command from https://github.com/alanz/vscode-hie-server no longer works - seems to be due to these changes from #403 

https://github.com/haskell/haskell-ide-engine/pull/403/files#diff-7b73da39d2cdccd6267a96bbb00d7fd6L56

I'm just wondering - is there another way that we should try to request the same functionality from now on or is it an oversight that `newTypeCmd` or something similar are not exposed to the client or are there plans for something else?

**Comment by wz1000** [comment]
Sorry, I removed it while hacking around a bit, didn't realise anything
used it. I will add it back.

**Comment by halhenke** [comment]
Thanks! 👍
