### ISSUE TITLE
Haskell / Google Summer of Code 2018

### ISSUE THREAD

**Issue by saurabhnanda** [haskell/haskell-ide-engine#434]
The ideas page at https://summer.haskell.org/ideas.html seems to have no project ideas related to HIE. A PR needs to be raised at https://github.com/haskell-org/summer-of-haskell/

**Comment by saurabhnanda** [comment]
@alanz @wz1000 friendly reminder to raise a PR to get HIE included in the HSoC/GSoC idea list.

**Comment by alanz** [comment]
See https://github.com/haskell-org/summer-of-haskell/pull/36
