### ISSUE TITLE
Encourage stateless programming style

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-ide-engine#45]
Each command should be as self-contained as possible, It should preferably not depend on hidden state at all. Visible state, like contents of visible files, is less of a problem.

Encourage stateless programming in what is supposed to be async system.

Encourage using full absolute paths to files because current working directory is state.

**Comment by bitemyapp** [comment]
Tend to agree, although for performance (later?) may want to mediate access to project state (probably namespaced by project path root or some-such).

**Comment by alanz** [comment]
I also tend to agree, in particular with the approach of always running hie wrt a given, known directory, and using absolute file paths.
