### ISSUE TITLE
Hoogle version mismatch

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell/haskell-ide-engine#452]
Currently `hie` is linked with a particular version of `hoogle`, and if a currently installed `hoogle` has a different version then `hie` doesn't show documentation and complains about version mismatch.
The way to fix it is not quite obvious: one would need to figure out which version of `hoogle` is required by `hie`, install that specific version and rebuild documentation (make sure that `stack hoogle` inside the project runs the same version of `hoogle`).

I realised that `hoogle` itself implements a version check perhaps too aggressively and I raised an issue here: https://github.com/ndmitchell/hoogle/issues/238

But making a check to be less aggressive would not fix 100% of the issue because sometimes the format will change anyway, even if not so often.

I was thinking if `hie` itself can help its users to deal with this issue, for example:
- Allow `hie` to trigger hoogle database generation (do what `hoogle generate` does). This will allow users to generate the database HIE would definitely understand
- Expose this trigger in a `hie` hoogle plugin
- Add a `Generate Documentation` command in `vscode-hie-server` so users can painlessly use the UI in order to build compatible documentation.

Do you think it is something that can/should be done?

**Comment by wz1000** [comment]
Sounds good. However, how will this make sure that `stack hoogle` uses the correct version?

**Comment by AlexeyRaga** [comment]
BTW, Neil just relaxed the version check to first 3 version components. This should help for patch releases in `hoogle`.

**Comment by ndmitchell** [comment]
I'm not sure how much `stack hoogle` really does for you - see https://github.com/commercialhaskell/stack/blob/a9042ad6fa1d7c813a1c79713a518ee521da9add/src/Stack/Hoogle.hs. It basically just calls `hoogle generate --local`, which isn't a massive saving. It also generates all the Haddock first, but I think you can do that with a separate command.

**Comment by ndmitchell** [comment]
BTW, it would be `stack exec -- hoogle generate --local` if you did want to do it yourself.

**Comment by AlexeyRaga** [comment]
I haven't seen it for a while so I'll close it.
