### ISSUE TITLE
Describe hie in the digest of Gabriel Gonzales (author of pipes etc)

### ISSUE THREAD

**Issue by nponeccop** [haskell/haskell-ide-engine#453]
https://github.com/Gabriel439/post-rfc/pull/126

@alanz @wz1000 

I don't know the names/urls of hie servers for atom/sublime/etc

**Comment by alanz** [comment]
The available clients are listed at

https://microsoft.github.io/language-server-protocol/implementors/tools/
and
http://langserver.org/

**Comment by nponeccop** [comment]
This is not always enough. For example, for vim7/neovim it's enough to install `LanguageClient-neovim`, but for `vscode` you need a separate Haskell-specific extension.

**Comment by alanz** [comment]
Whenever someone asks on the IRC channel about how to set things up I ask
them to make a PR on the readme for HIE.

Because we are going to need to build up documentation about how to set it
up per client. But only people actually doing it can make those docs.

**Comment by nponeccop** [comment]
> But only people actually doing it can make those docs.

Sure

**Comment by nponeccop** [comment]
ok it's largely done (by me)
