### ISSUE TITLE
Make autocomplete more fuzzy.

### ISSUE THREAD

**Issue by AnthonyJacob** [haskell/haskell-ide-engine#467]
Currently when I write `file`, i get only suggestions which start with `f`. It would be great to remove this requirement, so that if I write `file` I will see suggestions like 
```
readFileBinary
writeFileBinary
readFileUtf
...
```

**Comment by dpren** [comment]
I'm working toward this – Currently refactoring completions so they're cached and indexed in advanced upon module updates.

I'm open to suggestion on algorithms/libraries.
http://hackage.haskell.org/packages/search?terms=fuzzy

`yi-fuzzy-open` seems a good place to start.

**Comment by dpren** [comment]
Closed by https://github.com/haskell/haskell-ide-engine/pull/484
