### ISSUE TITLE
stderr output should go to the/a log file

### ISSUE THREAD

**Issue by michalrus** [haskell/haskell-ide-engine#475]
While trying to come up with an idea of how to debug https://github.com/haskell/haskell-ide-engine/issues/468#issuecomment-366712277 I added `2>$HOME/hie.stderr` to my wrapper script and…

```
[…]
DEBUG: initSession: Session not initialized, creating new one
hie: <command line>: cannot satisfy -package-id base-noprelude-4.10.1.0-8G41o1ZlnHKCHbdn9h82aS
    (use -v for more information)
```

This would’ve been awesome to have in the log file specified with `-d`. I’d lose much less time to pinpoint the issue!

Maybe some sort of `dup2()` syscall could be used to achieve that without many changes to the logging code, cf. https://github.com/michalrus/intero-nix-shim/blob/59776d8b39eba7473bc3424eff5e391728911879/src/cbits/silence_stderr.c — but then we have many threads writing to a single fd, and the log could/would end up garbled… So maybe a separate file.

-------

I guess that maybe some editors display hie’s stderr nicely (vscode?), but Emacs doesn’t. =( Maybe it should? Now it’s just swallowed. /cc @alanz @vibhavp @sebastiencs @MaskRay

**Comment by MaskRay** [comment]
The stderr of the language server goes to the `*lsp-* stderr*` buffer in Emacs.

I'd also like to know how to make logging more intuitive as we are also trying to make diagnostics simpler in the cquery language server https://github.com/cquery-project/cquery/issues/357

**Comment by michalrus** [comment]
Oh! Right. But I wouldn’t think of that, among hundreds of other buffers. :crying_cat_face:

**Comment by michalrus** [comment]
Maybe stderr could also go to `*Messages*`?

**Comment by MaskRay** [comment]
lsp-mode/lsp-io.el#L327

You can `(setq lsp-print-io t)` to log all traffic of the language server.

**Comment by jneira** [comment]
Not sure if there is something left to do here, feel free to reopen if it is the case
