### ISSUE TITLE
HLint is not respecting `arguments:` (`-XQuasiQuotes` etc.) defined in project’s .hlint.yaml

### ISSUE THREAD

**Issue by michalrus** [haskell/haskell-ide-engine#476]
If I define a non-standard `my-project/.hlint.yaml`, it will be picked and used by regular hlint:

```
$ cd my-project/

$ cat .hlint.yaml 
- arguments: [-XQuasiQuotes, -XTypeApplications]

$ hlint src/
No hints
```

… while on fragments with quasi quotes, e.g. `[sql|select 5|]` from https://hackage.haskell.org/package/postgresql-simple, HIE will report HLint errors: parse errors — ones which would also happen with `hlint` in terminal above, if I didn’t specify `-XQuasiQuotes` in `.hlint.yaml`.

**Comment by alanz** [comment]
Ok, we *are* using the hint file, but not processing the arguments field, as well call it as a library, and leave hlint to decide what config file to use.

So it is a bit of a chicken and egg situation.

**Comment by michalrus** [comment]
Updated the description accordingly!

**Comment by alanz** [comment]
I am pretty sure this is sorted now, please confirm.

**Comment by fendor** [comment]
I confirm that hie respects projects `.hlint.yaml`.
