### ISSUE TITLE
Add QuickCheck tests for FromJSON / ToJSON instances

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#48]
We are hand coding the JSON instances.

Provide quickcheck tests that confirm that we can successfully roundtrip all JSON instances.

i.e. decode . encode == id

**Comment by bitemyapp** [comment]
Could we have people make a comment when they're taking a shot at a ticket and let others know when they're setting it aside if they didn't reach a PR-able state?

**Comment by alanz** [comment]
Or just assign the issue to themselves. The "Asignee" button on the right.

**Comment by bitemyapp** [comment]
@alanz ah right, at'll do 'er.

**Comment by cocreature** [comment]
Note that you can only assign issues to you if you are part of the project, so especially for newcomers this is not an option.

**Comment by alanz** [comment]
ok. does anyone need to be added at the moment?

**Comment by bitemyapp** [comment]
@alanz perhaps make it known that a comment is an acceptable fallback if somebody that isn't on the project yet wants to claim a ticket and doesn't want to wait to get added?
