### ISSUE TITLE
Don't mark HLint parse errors as errors

### ISSUE THREAD

**Issue by LeanderK** [haskell/haskell-ide-engine#490]
I have some `hlint` parse errors that happen because `haskell-source-exts` can't handle my code, but it compiles fine. I think only ghc-mod parse errors should handled as errors.

EDIT: I use an Extension that is not robustly handled by `haskell-source-exts` and nearly every file is marked red, which is a bit annoying.

**Comment by alanz** [comment]
It is possible to turn off the hlint check, in vscode, by setting `languageServerHaskell.hlintOn` to `false`.

I am not sure if this configuration setting is enabled for other clients at the moment, make an issue on the relevant client if not.

I will also look at turning off hlint parse errors.

Can you give a short  example of a file that has this problem?

**Comment by LeanderK** [comment]
Here https://github.com/ndmitchell/hlint/issues/450 is one and I opened another on haskell-src-exts https://github.com/haskell-suite/haskell-src-exts/issues/403.
