### ISSUE TITLE
mishandling "type instance"

### ISSUE THREAD

**Issue by eklavya** [haskell/haskell-ide-engine#500]
At every save "type instance" is replaced with "type".

Hie version: Version 0.1.0.0, Git revision 392cadd70b0baff039a56e065e011186be3f358b (1237 commits) x86_64 ghc-8.2.2

MacOS, using VSCode HIE plugin 0.0.9

Code to try: http://haskell-servant.readthedocs.io/en/stable/cookbook/jwt-and-basic-auth/JWTAndBasicAuth.html

Could be a bug in HIE or brittany, not sure. I am sorry for the poor bug report.

**Comment by lspitzner** [comment]
This is lspitzner/brittany/issues/89 which is alanz/ghc-exactprint/issues/52.

**Comment by lspitzner** [comment]
This should be fixed, as https://github.com/lspitzner/brittany/issues/89 is long closed with a workaround.

**Comment by lorenzo** [comment]
Closing, then
