### ISSUE TITLE
HIE not working on Atom 1.24.1

### ISSUE THREAD

**Issue by razvan-panda** [haskell/haskell-ide-engine#512]
Using HIE for ghc-8.2.2 https://github.com/domenkozar/hie-nix
When using it with Visual Studio Code the types can be seen on hover but in Atom nothing is shown on hover, just a lot of CPU activity happening.

**Comment by razvan-panda** [comment]
There aren't any errors in the console, only a warning:

    IntersectionObserver.observe(target): target element is not a descendant of root.
    TreeView @ <embedded>:121025

**Comment by Tehnix** [comment]
If you enable the LSP debug in Settings -> Core -> Debug LSP, do you get any more information ( I can't remember if you also have to open the Atom developer tools to get the info on stderr)?

**Comment by razvan-panda** [comment]
I can't find it under `Edit -> Preferences -> Core`.
How do I find `Settings -> Core -> Debug LSP` in Atom?

**Comment by razvan-panda** [comment]
Do I need to add it manually under `Debug -> Config... -> config.cson -> core section` ?

**Comment by Tehnix** [comment]
Hmm, in your preferences -> core, do you have a DEBUG LSP like this (in the bottom)?

<img width="793" alt="screenshot 2018-03-31 22 55 27" src="https://user-images.githubusercontent.com/1189998/38167529-b114eda6-3536-11e8-9f72-c9956037eb13.png">

Then you can open 

the developer console for more errors. Other thing, the ide-haskell-hie extension should automatically install https://atom.io/packages/atom-ide-ui, but just for the heck of it, can you make sure that is installed?

**Comment by razvan-panda** [comment]
@Tehnix I can't find that setting:

![](https://user-images.githubusercontent.com/1758708/38168250-06c74912-353f-11e8-9e36-beb2d63edac7.png)

![](https://i.imgur.com/kzrQSVM.png)

**Comment by razvan-panda** [comment]
@Tehnix atom-ide-ui wasn't installed. I installed it but the setting is still not there.

**Comment by razvan-panda** [comment]
Ah. And I tried this with camelCase https://github.com/thomasjo/atom-ide-cpp/issues/2#issuecomment-339881784

**Comment by Tehnix** [comment]
Hmm, this is very puzzling. I'm on Atom 1.25, and currently have it working fine,

![screenshot 2018-04-01 02 05 19](https://user-images.githubusercontent.com/1189998/38168594-28fcb78a-3551-11e8-949c-fd2f229d0dd6.png)

You say it works for VSCode on the exact same project?

**Comment by razvan-panda** [comment]
@Tehnix I think that installing atom-ide-ui fixed it as it is now running fine. Thank you

**Comment by razvan-panda** [comment]
@Tehnix Yes, it works for VS Code on same project. I was currently on Atom 1.24.1
I guess someone else will run into the issue if atom-ide-ui does not get installed at same time with the main plugin. I am on NixOS btw, if that helps.
