### ISSUE TITLE
Check PluginDescriptor on loading

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#52]
When HIE starts up, it is presented with a list of `Plugin`s.

Each of these defines commands in a `CommandDescriptor`

For each `CommandDescriptor`, check that the parameter names introduced via `cmdContexts` and `cmdAdditionalParameters` are unique.

If this is not the case, exit with an error.

**Comment by cocreature** [comment]
I wonder if it wouldn't be nicer to just namespace all parameter names implicitely with the cmdName. We're going to end up with something like that anyway since there are probably similar names in a lot of plugins so enforcing that seems like a good idea.

**Comment by alanz** [comment]
I think I have phrased this badly.  What I mean is that the parameters for a given command must be unique. Because the `AcceptedContext` values bring fixed parameter names into scope for a command this is not always obvious, and always better to check this kind of thing.

**Comment by cocreature** [comment]
Ah yeah, then we are on the same page.

**Comment by tobiasgwaaler** [comment]
So these: https://github.com/haskell/haskell-ide-engine/blob/master/hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs#L104
... should not collide with these:
https://github.com/haskell/haskell-ide-engine/blob/master/hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs#L354
... right?

**Comment by alanz** [comment]
Yes, in the sense that the `pName`s must all be unique within a given command for the union of 
https://github.com/haskell/haskell-ide-engine/blob/master/hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs#L133 for the contexts defined for the command and
https://github.com/haskell/haskell-ide-engine/blob/master/hie-plugin-api/Haskell/Ide/Engine/PluginDescriptor.hs#L77

**Comment by tobiasgwaaler** [comment]
Any thoughts on how the error message should be worded? My suggestion is quite verbose:
```
Error: Parameter name collision in plugin description
Parameter names must be unique for each command. The following collisions were found:
In plugin "ghc-mod", command "check", the parameter name "file" is defined in:
		cmdAdditionalParams
			pName = "file"
			pHelp = "the file to read for blablabla"
	and 
	    cmdContexts
			pName = "file"
			pHelp = "a file name"
In plugin "ghc-mod", command "info", the parameter name "name" is defined in:
		cmdAdditionalParams
			pName = "name"
			pHelp = "name of the blabla"
	and 
	    cmdAdditionalParams
			pName = "name"
			pHelp = "nickname of the blabla"


```

**Comment by alanz** [comment]
I think verbose is better, so long as it ends up on stdout during startup.

We may need to consider wrapping them in the transport output.

**Comment by cocreature** [comment]
I also like the verbose format. “In plugin "ghc-mod", command "check", the parameter name” sounds a bit strange to me, but I am not a native speaker. How about changing it to “In "ghc-mod:check"  the parameter name”? I think the colon syntax is pretty unterstandable and we also use that in other places.

I tend to agree that we should add that to the transport at some point, but imho that’s an orthogonal issue, so feel free to not tackle it in this pr.

**Comment by tobiasgwaaler** [comment]
I like plugin:command too, so I'll go for that unless @alanz thinks its unwise

**Comment by alanz** [comment]
That is fine by me. The main thing is that we do the check.
