### ISSUE TITLE
Auto format in VSCode

### ISSUE THREAD

**Issue by djm158** [haskell/haskell-ide-engine#520]
Visual Studio Code's format document feature behaves strangely:

Before format document:
![image](https://user-images.githubusercontent.com/8800738/38281510-d9c03456-3778-11e8-9987-29f45cc24ee5.png)

After:
![image](https://user-images.githubusercontent.com/8800738/38281519-e3c73256-3778-11e8-8aad-6e2a3c58df42.png)

Again:
![image](https://user-images.githubusercontent.com/8800738/38281530-ef212012-3778-11e8-9a37-b68c5d75ae34.png)

Using these extensions:
https://github.com/JustusAdam/language-haskell/
https://github.com/alanz/vscode-hie-server

![image](https://user-images.githubusercontent.com/8800738/38281598-50732f7c-3779-11e8-9cbf-dffe8137f3f4.png)

Windows 10
ghc 8.2.2
cabal-install 2.0.0.1

**Comment by lspitzner** [comment]
Same as #397

**Comment by djm158** [comment]
oops! sorry about that
