### ISSUE TITLE
Expose configuration to run only onSave also onEdit

### ISSUE THREAD

**Issue by Tehnix** [haskell/haskell-ide-engine#522]
From https://github.com/alanz/vscode-hie-server/issues/39.

It seems a good idea to be able to expose a configuration that lets a user decide if HIE should run on changes or file saves. It seems `onDidSave` got implemented in version 2.x of LSP, and a usage of it can be found here https://github.com/Microsoft/vscode-tslint/commit/fdc77483f110873ca1abe9dadc9340a20bfa5666.

I'm not really sure how the passing of configurations currently happen from the clients to HIE though? I've seen mention of `.clientrc` in the vscode client code, but no docs on what format or settings it supports.

**Comment by lorenzo** [comment]
I'd like to implement this. I'm finding it increasingly annoying to have diagnostics as I type.

Additionally I think that this  diagnostics `on save` should be the default, it would make things feel more snappy in general. How do you guys think I should go about this?

**Comment by mpickering** [comment]
@lorenzo I also support this. Including the part about the default.

**Comment by mpickering** [comment]
@lorenzo Did you make any progress yet? I want to disable the on edit functionality on my branch.

**Comment by mpickering** [comment]
I implemented the necessary parts in the backend to make this configurable on my branch.

https://github.com/mpickering/haskell-ide-engine/commit/a5fcf535c63d5efd3176e0b6e20ed9b6b383b337

If someone wants to upstream this then the UI parts need to be added to the plugin but I'm not going to do that immediately.

**Comment by lorenzo** [comment]
@mpickering I did not, was busy with work this week. Do you plan on opening a pull request with your changes?

**Comment by mpickering** [comment]
No I don't plan to but the commit is there if someone who knows how to modify the front end to expose this setting.

**Comment by lorenzo** [comment]
Ok, I'll start by making a pull request to this repo with your commit. Thanks!

**Comment by lorenzo** [comment]
This is done
