### ISSUE TITLE
Stopped working in both Atom and VS Code

### ISSUE THREAD

**Issue by razvan-panda** [haskell/haskell-ide-engine#524]
In the console of Atom following is logged:

    Cabal2.0.1.0: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory

Atom 1.25.1 x64

**Comment by razvan-panda** [comment]
I fixed above error by clearing the cabal-helper cache folder. But even after that types on hover or autocomplete is not working.

On autocomplete it prints following errors:

    Haskell (hie) rpc.sendRequest textDocument/completion threw Error: IdeError {ideCode = PluginError, ideMessage = "getCompletions: \"module not loaded\"", ideInfo = Null}
        at new ResponseError (/home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/messages.js:46)
        at handleResponse (/home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:430)
        at processMessageQueue (/home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:258)
        at Immediate.<anonymous> (/home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:242)
        at runCallback (timers.js:672)
        at tryOnImmediate (timers.js:645)
        at processImmediate [as _immediateCallback] (timers.js:617)
    error @ logger.ts:23
    (anonymous) @ languageclient.ts:443
    rejected @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/languageclient.…:5
    Promise rejected (async)
    handleResponse @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:430
    processMessageQueue @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:258
    (anonymous) @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:242
    runCallback @ timers.js:672
    tryOnImmediate @ timers.js:645
    processImmediate @ timers.js:617
    /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/messages.js:46 Uncaught (in promise) Error: IdeError {ideCode = PluginError, ideMessage = "getCompletions: \"module not loaded\"", ideInfo = Null}
        at new ResponseError (/home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/messages.js:46)
        at handleResponse (/home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:430)
        at processMessageQueue (/home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:258)
        at Immediate.<anonymous> (/home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:242)
        at runCallback (timers.js:672)
        at tryOnImmediate (timers.js:645)
        at processImmediate [as _immediateCallback] (timers.js:617)
    ResponseError @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/messages.js:46
    handleResponse @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:430
    processMessageQueue @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:258
    (anonymous) @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:242
    runCallback @ timers.js:672
    tryOnImmediate @ timers.js:645
    processImmediate @ timers.js:617
    Promise rejected (async)
    rejected @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/adapters/autoco…:5
    Promise rejected (async)
    rejected @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/utils.js:5
    Promise rejected (async)
    rejected @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/languageclient.…:5
    Promise rejected (async)
    handleResponse @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:430
    processMessageQueue @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:258
    (anonymous) @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/main.js:242
    runCallback @ timers.js:672
    tryOnImmediate @ timers.js:645
    processImmediate @ timers.js:617

**Comment by razvan-panda** [comment]
These are all the warnings printed after Atom starts:

    Haskell (hie) stderr 2018
    warn @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9
    /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9 Haskell (hie) stderr -04-13 01:45:04.389963977 [ThreadId 4] - Setting home directory:/home/
    warn @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9
    /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9 Haskell (hie) stderr neo
    warn @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9
    /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9 Haskell (hie) stderr 2018-04-13 
    warn @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9
    /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9 Haskell (hie) stderr 01:45:04.391443587 [ThreadId 4] - run entered for HIE Version 0.1.0.0 x86_
    warn @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9
    /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9 Haskell (hie) stderr 64 ghc-8.2.2
    warn @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9
    /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9 Haskell (hie) stderr 2018-04-13 01:45:04.391965326 [ThreadId 4] - Current dir
    warn @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9
    /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9 Haskell (hie) stderr ectory:/home/neo
    warn @ /home/neo/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js:9

Stuff like `stderr ectory:/home/neo` seems to be broken.

**Comment by razvan-panda** [comment]
In VS Code on hover it prints:

    ERR Cannot read property 'contents' of null: TypeError: Cannot read property 'contents' of null
        at Promise.resolve.then.r (/home/neo/.vscode/extensions/alanz.vscode-hie-server-0.0.15/out/src/docsBrowser.js:46:27)
        at <anonymous>
    errors.ts:48 WARNING: Promise with no error callback:300
    errors.ts:49

**Comment by alanz** [comment]
cc @Tehnix

**Comment by razvan-panda** [comment]
The problem is gone now. Not sure what change fixed it.
