### ISSUE TITLE
ghc-mod vs stack exec ghc-mod

### ISSUE THREAD

**Issue by rainwolf** [haskell/haskell-ide-engine#527]
When editing a standalone .hs file and importing Parsec, hie's ghcmod complains about a module not being found, and I can reproduce that error with the ghc-mod binary.

But, when invoking ghc-mod via stac exec ghc-mod, the error goes away, and I merely get a warning about a redundant import, as I expect. Is there any way to achieve this with hie?

**Comment by nponeccop** [comment]
Hie uses ghc-mod as a statically linked library. Generally it is a special fork of ghc-mod. So it doesn't/can't use any other ghc-mod.

So this error you get may be due to 2 reasons:

- a bug in the fork used by HIE
- incorrect HIE binary (e.g. for another GHC version)
