### ISSUE TITLE
Warnings are sometimes not shown for the files I open, sometimes shown for the files I not open

### ISSUE THREAD

**Issue by marmistrz** [haskell/haskell-ide-engine#528]
I have the warnings configured this way: 

```
library:
  source-dirs: src

executables:
  interpreter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - interpreter
```

I'm also using the `placeholders` package, which requires `TemplateHaskell` in one of the source files. Now, when I open `app/Main.hs`, the warnings from this file appear for a while and then instantly disappear. On the other hand, the warnings from the `src` directory appear when I open `app/Main.hs`.

**Comment by marmistrz** [comment]
I've removed the `ghc-options` from `package.yaml` and used `{-# OPTIONS_GHC -Wall #-}` instead, and the warnings from `app/Main.hs` disappear instantly too.

**Comment by otbe** [comment]
Im observing something similiar. It seems that `-Wall` in `ghc-options` from package.yaml gets ignoried by ghc-mod (or not passed?). Only if I add `{-# OPTIONS_GHC -Wall #-}` to my files I will be warned if something goes wrong.

**Comment by marmistrz** [comment]
I have just noticed that I'm not getting warnings from hlint in the problems view in case of such code:
```
evalSt (SAss v e) = do
    locm <- return $ asks (Map.lookup v)
    loc <- MaybeT locm
    val_e <- eval e
    modify (addBinding loc val_e)
```
the only indicator of the fact there's a warning is that I have three dots straight below `do`. (above `$ asks`) - actually that's below the letter `d`

**Comment by marmistrz** [comment]
And now I came across a situation when the warnings for `src/Somemodule.hs` always disappeared instantly after they appeared until I opened `app/Main.hs`

**Comment by marmistrz** [comment]
After disabling the `TemplateHaskell` pragma the problem is gone.

**Comment by HardRock** [comment]
I noticed too that the GHC options from stack projects are not passed to the ghc-mod in HIE as I would expect. Here's what I can confirm so far with the 0.2.0.0 version of HIE (as of now last commit was 0c04c75).

- Adding a `{-# OPTIONS_GHC -Wall #-}` pragma to files works as expected. Ghc-mod will print warnings for that file afterwards, but not for others.

- Adding -Wall to the ghc-options in the package.yaml file for a project seemingly has no effect, warnings will not be listed.

- Adding -Wall to the stack.yaml file of a project in the following way works for printing warnings:
`ghc-options: -Wall`

However, this will also result in parse errors on HIE startup and when building the project:

```
Using hie version: Version 0.2.0.0, Git revision 0c04c75defb5d8c42e24bdbd9c79780a0a833f4a (1367 commits) x86_64 ghc-8.2.2
Could not parse 'D:\Projects\test\stack.yaml':
Aeson exception:
Error in $['ghc-options']: failed to parse field 'ghc-options': expected Map k v, encountered String
See http://docs.haskellstack.org/en/stable/yaml_configuration/
Warning: readStack:
         Bootstrapping stack project environment failed: readCreateProcess: C:\Users\HardRock\AppData\Roaming\local\bin\stack.exe "path" (exit 1): failed
Using hoogle db at: C:\Users\HardRock\AppData\Roaming\hoogle\default-haskell-5.0.17.hoo
Could not parse 'D:\Projects\test\stack.yaml':
Aeson exception:
Error in $['ghc-options']: failed to parse field 'ghc-options': expected Map k v, encountered String
See http://docs.haskellstack.org/en/stable/yaml_configuration/
Warning: readStack:
         Bootstrapping stack project environment failed: readCreateProcess: C:\Users\HardRock\AppData\Roaming\local\bin\stack.exe "path" (exit 1): failed
```

It looks like ghc-mod is reading the ghc-options from a project's stack.yaml file, but the formatting it requires doesn't align with what stack would expect.

**Comment by tristangreeno** [comment]
The solution to this issue is to add the configuration to your global stack project YAML, not your local one.

**Comment by alanz** [comment]
Is this still a problem?

**Comment by Anrock** [comment]
@alanz yes. I get warnings with `{-# OPTIONS_GHC -Wall #-}` and no warnings with `ghc-options: -Wall` in cabal file.

**Comment by Anrock** [comment]
So i guess this isn't a problem anymore.
