### ISSUE TITLE
HIE gets out of sync with the actual code

### ISSUE THREAD

**Issue by marmistrz** [haskell/haskell-ide-engine#531]
It happens often while editing the code but I can't see any pattern here. Example: I currently have an error shown by `ghcmod` in this line

```
evalProgram (Prog decls) = do
```
with the message
```
parse error on input ‘]’
```
in the column 24, i.e. when one clicks on the error message, the `)` character is highlighted.

Arch Linux, r1270

**Comment by alanz** [comment]
Does this still happen with current master?

**Comment by marmistrz** [comment]
That's hard to say, I'm no longer developing that code and I'd need to have a longer coding session to be able to reproducing that bug. Let's assume it doesn't, me or someone else will reopen if they came across.
