### ISSUE TITLE
The Haddock databse is not detected

### ISSUE THREAD

**Issue by marmistrz** [haskell/haskell-ide-engine#532]
I created the haddock database as described in the README. Even though, I didn't get docs on hover and HIE complained about the missing hoogle database. 

Only when I created the database using `stack exec -- hoogle generate` did the docs on hover started appearing.

**Comment by alanz** [comment]
What you report is the required process, as defined in the readme.

Is there something else that should happen?

**Comment by marmistrz** [comment]
That was a long time ago, I don't remember what exactly was in the readme, but I have a feeling that I expected `stack haddock; hoogle generate` to do the trick and not require a separate hoogle call in the `stack` environment
