### ISSUE TITLE
Aliasing records pattern matching break if space exists

### ISSUE THREAD

**Issue by Yanpas** [haskell/haskell-ide-engine#555]
First I've opened an issue here: https://github.com/ndmitchell/hlint/issues/486 (full details there)

This snippet is parsed successfully:
```
data X = X {unX :: Int, unY :: Bool}
foo :: X -> Bool
foo x@X{unY = bb} = True
```

But after adding spaces:
```
data X = X {unX :: Int, unY :: Bool}
foo :: X -> Bool
foo x @ X{unY = bb} = True
```
I get '[hlint] Parse error'

It seems like the problem is not related to hlint, so concluding there are two subissues:
* Parse issue
* Error source is confusing, shouldn't be named hlint

**Comment by alanz** [comment]
I think the `@` symbol is sensitive to preceding space now in GHC, when the [VisibleTypeApplication](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#visible-type-application) extension is enabled:

> A visible type application is preceded with an @ sign. (To disambiguate the syntax, the @ must be preceded with a non-identifier letter, usually a space. For example, read@Int 5 would not parse.) It can be used whenever the full polymorphic type of the function is known.

So possibly hlint is enabling that extension by default.

**Comment by alanz** [comment]
Does anything need to be done in hie for this?

**Comment by Yanpas** [comment]
I think no, may be closed
