### ISSUE TITLE
Brittany "Format Selected"  adds an extra new line

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell/haskell-ide-engine#561]
Maybe not so critical, but very, very, very annoying.

To reproduce:
1) Select a function
2) Call "Format Selected"
3) Enjoy an extra newline after your selection

**Comment by HardRock** [comment]
For me new lines are getting added mid-selection or mid-file as well. Using VSCode, this only seems to be the case if I use CRLF line endings, the formatting works fine with LF.

**Comment by alanz** [comment]
@AlexeyRaga is this with the current master version of hie?  Because I understood that @lspitzner had sorted it out in the current brittany.
