### ISSUE TITLE
Cannot install hie,using instructions found on vacationslab

### ISSUE THREAD

**Issue by h2000Stefanov** [haskell/haskell-ide-engine#569]
`hstefanov@pop-os:~/.local/haskell-ide-engine$ stack install
Stack looks for packages in the directories configured in the 'packages' and 'extra-deps' fields defined in your stack.yaml
The current entry points to /home/hstefanov/.local/haskell-ide-engine/submodules/HaRe/ but no .cabal or package.yaml file could be found there.`

 When trying to install hlint:
`Warning: Installation path /.local/bin not found on the PATH environment variable.`

And afterwards:

`Stack looks for packages in the directories configured in the 'packages' and 'extra-deps' fields defined in your stack.yaml
The current entry points to /home/hstefanov/.local/haskell-ide-engine/submodules/HaRe/ but no .cabal or package.yaml file could be found there.
`

Operating system: Pop!OS,based on Ubuntu 18.04.

**Comment by alanz** [comment]
Please provide a link to the instructions you followed to get to this point.

**Comment by emaphis** [comment]
I'm guessing he's following this.
https://www.vacationlabs.com/haskell/environment-setup.html

**Comment by Anrock** [comment]
Looks like instructions on that site should be updated with `--recursive` flag to `git clone` command.

**Comment by alanz** [comment]
cc @saurabhnanda

**Comment by saurabhnanda** [comment]
@h2000Stefanov @AndreasVoellmy If `--recursive` the confirmed solution I can push a fix to the docs immediately. Else this might have to wait a few days. Just got back from vacations and have a lot of emails to look at.

**Comment by alanz** [comment]
@saurabhnanda I am pretty sure that will sort it out, introducing submodules has caused that problem in a number of different install instructions.

**Comment by Anrock** [comment]
Reopen if recursive clone doesn't help.
