### ISSUE TITLE
Add a signal handler to flush logs on exit

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#58]
At the moment if HIE is killed for any reason, it discards any logs that have not been flushed.

Add a set of signal handlers to flush the logs on SIGTERM etc.

Possible resource: http://zguide.zeromq.org/hs:interrupt

https://hackage.haskell.org/package/logging-3.0.2/docs/Control-Logging.html
https://hackage.haskell.org/package/fast-logger-2.4.1/docs/System-Log-FastLogger.html

Note: there is nothing holy about this logging package, it was just convenient.

**Comment by DanielG** [comment]
How about flushing every line in the log instead? Signal handlers are probably a pain non platforms other than linux.

**Comment by gracjan** [comment]
Line flushing is better. In case of `kill -9` nothing is lost.

**Comment by alanz** [comment]
This should probably go away as part of #112

**Comment by alanz** [comment]
We flush on every write to the log now, from https://github.com/haskell/haskell-ide-engine/pull/120
