### ISSUE TITLE
Installation with stack `make build-all` fails on a fresh ubuntu

### ISSUE THREAD

**Issue by fredericcogny** [haskell/haskell-ide-engine#591]
```
 Process exited with code: ExitFailure 1
    Logs have been written to: /home/fred/git/tools/haskell-ide-engine/.stack-work/logs/text-icu-0.7.0.1.log

    Configuring text-icu-0.7.0.1...
    Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: Missing dependencies on foreign
    libraries:
    * Missing C libraries: icuuc, icui18n, icudata
    This problem can usually be solved by installing the system packages that
    provide these libraries (you may need the "-dev" versions). If the libraries
    are already installed but in a non-standard location then you can use the
    flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1
```

this is fixed by `sudo apt install libicu-dev`

and I guess (not tested) could be fixed on mac-os by `brew install icu4c` as per https://github.com/yi-editor/yi/issues/795 

Can this be added in the actual make file ?

**Comment by Anrock** [comment]
I don't think adding make target for dependencies for every possible OS\package manager combination is a good thing. A subsection under "Installation" in README is more reasonable.

**Comment by fredericcogny** [comment]
@Anrock yes that is absolutely fine. My suggestion was based on those [lines](https://github.com/haskell/haskell-ide-engine/blob/master/Makefile#L67) in the MakeFile indicating that some of the fixes (here for mac-os) had their place in the makefile but I think having it in the readme is just as fine

**Comment by Anrock** [comment]
@fredericcogny are you using hie-0.1.0.0 branch or master? If latter - perform a pull, 8.0.2 target was removed some time ago.

**Comment by alanz** [comment]
I think the linker is complaining about a missing `-ltinfo`, which comes in from installing `libtinfo-dev`.

**Comment by fredericcogny** [comment]
@alanz thanks that did the trick and the whole script ran
so, in summary, the following needs to be added to the installation instructions:
```
sudo apt install libicu-dev libtinfo-dev
```
