### ISSUE TITLE
Document architecture

### ISSUE THREAD

**Issue by Bubba** [haskell/haskell-ide-engine#596]
We should make a diagram for the process and message flow internally.
This will also make it easier to find and identify points to write tests for.

## Reading
https://www.yesodweb.com/blog/2015/08/thoughts-on-documentation
http://www.mcternan.me.uk/mscgen/
https://en.wikipedia.org/wiki/Message_Sequence_Chart
https://github.com/haskell/haskell-ide-engine/pull/495
https://www.websequencediagrams.com/

**Comment by alanz** [comment]
Perhaps consider some of https://gist.github.com/rodneyrehm/40e7946c0cff68a31cea
