### ISSUE TITLE
hie-0.1.0.0 doesn't compile on windows 10 (due to text-icu-0.7.0.1)

### ISSUE THREAD

**Issue by hanjoosten** [haskell/haskell-ide-engine#599]
I am still on ghc 8.0.2 and unfortunatly currently not able to upgrade. I need hie to work with vscode. So I followed the installation instructions: 
  1) I cloned haskell-ide-engine into c:\hie
  1) checkout branch `hie-0.1.0.0`
  1) update the submodules
  1) fire up a cli and fired the command `stack --stack-yaml=stack-8.0.2.yaml install --extra-lib-dirs="C:\icu\icu4c-60_2-Win64-MSVC201" --extra-include-dirs="C:\icu\icu4c-60_2-Win64-MSVC2015\include"`

I get the following error message:

~~~~
C:\hie>stack --stack-yaml=stack-8.0.2.yaml install --extra-lib-dirs="C:\icu\icu4c-60_2-Win64-MSVC201" --extra-include-dirs="C:\icu\icu4c-60_2-Win64-MSVC2015\include"
text-icu-0.7.0.1: configure
Progress 1/5

--  While building custom Setup.hs for package text-icu-0.7.0.1 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe --builddir=.stack-work\dist\ca59d0ab configure --with-ghc=C:\Users\hjo20125\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc.EXE --with-ghc-pkg=C:\Users\hjo20125\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc-pkg.EXE --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\cd07658e\pkgdb --libdir=C:\sr\snapshots\cd07658e\lib --bindir=C:\sr\snapshots\cd07658e\bin --datadir=C:\sr\snapshots\cd07658e\share --libexecdir=C:\sr\snapshots\cd07658e\libexec --sysconfdir=C:\sr\snapshots\cd07658e\etc --docdir=C:\sr\snapshots\cd07658e\doc\text-icu-0.7.0.1 --htmldir=C:\sr\snapshots\cd07658e\doc\text-icu-0.7.0.1 --haddockdir=C:\sr\snapshots\cd07658e\doc\text-icu-0.7.0.1 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=deepseq=deepseq-1.4.2.0 --dependency=text=text-1.2.2.2-9UQZjEJZQFSGMffj1Z5g00 --extra-include-dirs=C:\Users\hjo20125\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include --extra-include-dirs=C:\icu\icu4c-60_2-Win64-MSVC2015\include --extra-lib-dirs=C:\Users\hjo20125\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin --extra-lib-dirs=C:\Users\hjo20125\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib --extra-lib-dirs=C:\icu\icu4c-60_2-Win64-MSVC201
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\hie\.stack-work\logs\text-icu-0.7.0.1.log

    Configuring text-icu-0.7.0.1...
    Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe: Missing dependencies on foreign
    libraries:
    * Missing C libraries: icuuc, icuin, icudt
    This problem can usually be solved by installing the system packages that
    provide these libraries (you may need the "-dev" versions). If the libraries
    are already installed but in a non-standard location then you can use the
    flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.

C:\hie>
~~~~

It is obvious that there is something wrong with the missing libraries. However, that is why I give the switches `--extra-lib-dirs="C:\icu\icu4c-60_2-Win64-MSVC201"` and `--extra-include-dirs="C:\icu\icu4c-60_2-Win64-MSVC2015\include"`. This is where these files are. I am not familiar with using non-haskell stuff. What could be wrong?

**Comment by nponeccop** [comment]
What is suspicious is the MSVC version of ICU. If you use precompiled versions, then MSVC import library format is incompatible with using GHC (which internally uses MinGW which is GCC).

I don't know how supported is that, but you can do the following:

- go to  `%USERPROFILE%\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\`
- run msys2_shell.bat
- in the shell run `pacman -Sy mingw-w64-x86_64-icu`
- then it should run out of the box (i.e. without passing pathes anywhere)

If you run into troubles, e.g. if you use 32-bit GHC, you can do `pacman -Ss icu` to see the various icu-related packages available

**Comment by hanjoosten** [comment]
Thanks @nponeccop  This **really** made my day. It works as a charm :smile:
