### ISSUE TITLE
thread/concurrency/memory usage safety?

### ISSUE THREAD

**Issue by cartazio** [haskell/haskell-ide-engine#6]
Just want to mention these while things are still in the planning phase.

this may be spurious (or obvious), but making sure that its easy to have nonblocking interaction with editors and their plugins. (i've definitely seen a number of haskell plugins which have bad cpu/memory usage or needless editor blocking from bad integration)

**Comment by cartazio** [comment]
to better elaborate: i default to not using any smart ide tools with haskell code because then opening eg the ghc source tree in my editor winds up pinning the cpu for quite a while, and kinda is bad on a laptop :)

**Comment by alanz** [comment]
Non-blocking interaction is a must, and getting the project to load into a GHC session once only for all tooling is an important goal

**Comment by cartazio** [comment]
agreed! I guess i'd also push for thinking carefully about making sure things are well behaved with respect to CPU and memory usage.

One example of an interesting point in the design space is that the emacs mode for the lean prover https://github.com/leanprover/lean  (or the underlying lean system ) maintains a disk cache of partially checked modules so it can very very quickly check modules incrementally with localized changes. (One feature that i find especially impressive is that it can type check later parts of a module that don't depend on earlier parts, EVEN when the earlier part of the module has a syntax error. I'm not suggesting we can do that, but aspirationally it'd be super awesome)

**Comment by alanz** [comment]
I am hoping that this project can work closely with GHC to the point where it can drive changes to the compiler that can enable that kind of awesomeness.

Some form of incremental compilation (even just down to type-checking) will be awesome

**Comment by nponeccop** [comment]
Are there any parts of this issue which are still relevant?

**Comment by alanz** [comment]
Closing, this is just discussion at this point, no actionable item.
