### ISSUE TITLE
"module ***:Main is defined in multiple files" [atom / monorepo configuration / ghc8.2.2]

### ISSUE THREAD

**Issue by OlivierSohn** [haskell/haskell-ide-engine#606]
I followed the installation procedure, ran on master branch:

`stack --stack-yaml=stack-8.2.2.yaml install`

and installed the atom plugins :

`apm install language-haskell atom-ide-ui ide-haskell-hie`

Then when opening atom for [my project](https://github.com/OlivierSohn/hamazed) I see the error :

```
Got error while processing diagnostics: : error: module ‘main:Main’ is defined in multiple files:
/private/var/folders/25/p3lxc5td4kg2q0bnpvy90wrc0000gn/T/ghc-mod14097/Main14096-0.hs
/private/var/folders/25/p3lxc5td4kg2q0bnpvy90wrc0000gn/T/ghc-mod14098/Main14096-1.hs
```

When saving a file in `imj-space` project, I have a similar message:

```
Got error while processing diagnostics: : error: module ‘imj-space-0.1.0.3:Main’ is defined in multiple files:
/private/var/folders/25/p3lxc5td4kg2q0bnpvy90wrc0000gn/T/ghc-mod14105/Spec14096-9.hs
/private/var/folders/25/p3lxc5td4kg2q0bnpvy90wrc0000gn/T/ghc-mod14097/Main14096-0.hs
/private/var/folders/25/p3lxc5td4kg2q0bnpvy90wrc0000gn/T/ghc-mod14098/Main14096-1.hs 
```

And then I see no diagnostic panel.

How can I fix it?

Note that I build my project with `stack-lts-11.9`, the same as the one used to build `haskell-ide-engine`

**Comment by nasyxx** [comment]
The same.

```
Got error while processing diagnostics: : error: module ‘main:Main’ is defined in multiple files: 
/private/var/folders/sn/pv0g90nd1j1cw20ct_7bpl100000gn/T/ghc-mod72362/site72360-273.hs 
/private/var/folders/sn/pv0g90nd1j1cw20ct_7bpl100000gn/T/ghc-mod72361/Main72360-551.hs
```

**Comment by alxdb** [comment]
this should be merged with https://github.com/haskell/haskell-ide-engine/issues/620

**Comment by lolepezy** [comment]
The same for me: 
Got error while processing diagnostics: : error: module ‘stm-ixset-0.1.0.0:Main’ is defined in multiple files: /private/var/folders/tf/w30cyv8d7c34thtj_4mcrnqh0000gq/T/ghc-mod31847/Bench31842-6.hs /private/var/folders/tf/w30cyv8d7c34thtj_4mcrnqh0000gq/T/ghc-mod31845/Spec31842-3.hs

having benchmarks and specs make the HIE go nuts about 'main' functions.

**Comment by alanz** [comment]
We will track progress in #620, sorry for the duplicate.
