### ISSUE TITLE
Cannot have two "Main" modules open at the same time

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#620]
e.g., working on hie, if `app/MainHie.hs` and `test/Functional.hs` are both loaded, we get

```
Got error while processing diagnostics: <no location info>: error:
    module ‘haskell-ide-engine-0.2.0.0-7HZrGfRRjONEXbBFqqpRFd:Main’ is defined in multiple files:
         /tmp/ghc-mod17562/MainHie17561-6.hs
         /tmp/ghc-mod17564/RealFunctional17561-5.hs
```

Note: I think is because we put all the mapped files into the targets list in ghc-mod when loading.

**Comment by alanz** [comment]
The problem is with the `mappedStrs` all being added to the list of targets to be loaded here: https://github.com/alanz/ghc-mod/blob/ghc-8.4-hie/core/GhcMod/Target.hs#L217

```haskell
    mappedStrs <- getMMappedFilePaths
    let targetStrs = mappedStrs ++ map moduleNameString mns ++ cfns
```

We need to filter out any know main modules from that list, by inspecting the cabal component graph, and marking any successfully loaded main modules.

**Comment by alanz** [comment]
As pointed out by @wz1000 on IRC, we should be able to reinstate 

https://github.com/wz1000/ghc-mod/commit/43606f3e7f0dc661c7b7ecb246ccafc7a7458bb8
https://github.com/wz1000/ghc-mod/commit/1279f611ecac636458393795eb937008e7c3d741

**Comment by ahpearce** [comment]
@alanz 
I am still getting this issue in VSCode
```
Got error while processing diagnostics: <no location info>: error: module ‘main:Main’ is defined in multiple files: /private/var/folders/9v/5p73rgqn65ddfzcvrjf2nj8c0000gn/T/ghc-mod560/problem5559-0.hs /private/var/folders/9v/5p73rgqn65ddfzcvrjf2nj8c0000gn/T/ghc-mod561/problem6559-3.hs
```
I've got a project setup like:
```
drwxr-xr-x   3 adam  staff   96 Jun 27 16:18 problem1
drwxr-xr-x   3 adam  staff   96 Jun 27 16:18 problem2
drwxr-xr-x   3 adam  staff   96 Jun 27 16:19 problem3
drwxr-xr-x   3 adam  staff   96 Jun 27 16:19 problem4
drwxr-xr-x   6 adam  staff  192 Jun 27 18:23 problem5
drwxr-xr-x   3 adam  staff   96 Jun 27 18:25 problem6
```
Where each directory has a `.hs` file specifying a main. 

```
> hie --version
Version 0.2.0.0, Git revision 3370c8a0a8808e03c1f6354bcecddd80593cf546 (1539 commits) x86_64 ghc-8.4.3
```

**Comment by alanz** [comment]
@ahpearce And you do not have any cabal or stack files?

**Comment by ahpearce** [comment]
@alanz 
Which files would be helpful?
`../haskell-ide-engine/haskell-ide-engine.cabal` : https://gist.github.com/ahpearce/faa5500e5b621108ea900333a4dd0da2

`../haskell-ide-engine/stack.yaml` : https://gist.github.com/ahpearce/abc2846b51c9d73b4fdf131de347840d

**Comment by Eoksni** [comment]
I have the same error with same setup as @ahpearce - no cabal or stack project, just number of .hs files, each .hs has Main module.

I'm on Windows 10, if that matters.

**Comment by Bubba** [comment]
@Eoksni for reference I believe this is the same issue as https://github.com/haskell/haskell-ide-engine/issues/770

**Comment by xhliu** [comment]
Any update on this? Still have this issue in VS Code with the same setup as @ahpearce.

**Comment by xhliu** [comment]
hello, anyone working on this?

**Comment by fendor** [comment]
Assuming you have a correct stack or cab project, e.g. Cabal build or stack build succeed, this problem does not occur on current master
