### ISSUE TITLE
upload to hackage

### ISSUE THREAD

**Issue by thkoch2001** [haskell/haskell-ide-engine#626]
I'd like to eventually have haskell-ide-engine in Debian. Debian has nice tooling to package from hackage, so it would help to have hie present there.

I see that there is #328 (presence in Stackage) which seems related, but I understand that there is no dependency missing on hackage at this moment?

**Comment by alanz** [comment]
Unfortunately there is a chain of dependencies missing, anchored on cabal-helper and ghc-mod

**Comment by l29ah** [comment]
Bump? Both cabal-helper and ghc-mod are present on hackage.

**Comment by l29ah** [comment]
Oh, okay, ghc-mod is not fresh enough.

**Comment by alanz** [comment]
This is basically the same as #328
