### ISSUE TITLE
How to control linters?

### ISSUE THREAD

**Issue by hasufell** [haskell/haskell-ide-engine#635]
I haven't found a way to completely disable hlint. I find most of its suggestions either outright wrong (it suggests changing semantics) or just annoying. So I don't want to use a `.hlint.yaml` for every single project.

`hie --help` doesn't show anything useful either.

It should somehow be possible to control the behavior of the linters, which are shown [here](https://github.com/haskell/haskell-ide-engine/blob/1051cc69d3434f4ccf67e03846410ec463135db9/docs/Tools.md#linters--refactoring).

**Comment by alanz** [comment]
Which IDE/client are you using? There is a configuration setting to turn off hlint, but it is only exposed in vscode at the moment, as far as I know.

**Comment by hasufell** [comment]
https://github.com/autozimu/LanguageClient-neovim

**Comment by Bubba** [comment]
For languageclient-neovim add
```json
{
    "languageServerHaskell": {
        "hlintOn": false
    }
}
```
to `.vim/settings.json` in your project root

**Comment by hasufell** [comment]
Can this be done globally?

**Comment by Anrock** [comment]
@hasufell yeah, set g:LanguageClient_settingsPath to some absolute path
@Bubba are those settings documented somewhere?

**Comment by hasufell** [comment]
That configuration option is just for hlint though. What about the others?

**Comment by alanz** [comment]
There are no others. The config is currently defined as

```haskell
data Config =
  Config
    { hlintOn             :: Bool
    , maxNumberOfProblems :: Int
    } deriving (Show)
```

in https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Transport/LspStdio.hs#L158

Note that `maxNumberOfProblems` applies across all sources of diagnostics, including GHC.
