### ISSUE TITLE
Cannot satisfy -package-id base

### ISSUE THREAD

**Issue by Josef-Vonasek** [haskell/haskell-ide-engine#637]
Windows10:
```
git clone https://github.com/haskell/haskell-ide-engine --recursive
cd haskell-ide-engine
stack install
cd ..
stack new foo
vscode foo
```

trigger hie => Got error while processing diagnostics: <command line>: cannot satisfy -package-id base-4.10.1.0

**Comment by Anrock** [comment]
Did you follow instructions from [readme](https://github.com/haskell/haskell-ide-engine#installation-with-stack)?

**Comment by Josef-Vonasek** [comment]
Setting `"languageServerHaskell.useHieWrapper": true` does not change anything.

**Comment by Anrock** [comment]
Can you run `hie-wrapper` manually?

**Comment by Josef-Vonasek** [comment]
Yes

**Comment by Anrock** [comment]
I'm out of options here.
@alanz halp?

**Comment by alanz** [comment]
That error looks like what you get when the project ghc version and the hie ghc version do not match.

**Comment by Josef-Vonasek** [comment]
Yes, I that's it. I have installed both 8.4 and 8.2 version, but the 8.2 version failed and I did not notice. This project requires the 8.2 version.
