### ISSUE TITLE
HIE fails to pick the GHC version

### ISSUE THREAD

**Issue by ShrykeWindgrace** [haskell/haskell-ide-engine#649]
Found this in the logs of SublimeText3:
```
LSP: starting ['/path/to/home/.local/bin/hie', '--lsp', '-d']
LSP:  --> initialize
server: 2018-06-21 14:09:58.661859 [ThreadId 4] - Using stack GHC version
server: /bin/sh: 1: stack: not found
server: hie: readCreateProcess: stack ghc -- --version (exit 127): failed
LSP: haskell-ide-engine in state 0  for view  /path/to/home/Projects/Haskell/Main.hs in window 6
LSP: LSP stream logger stopped.
LSP: LSP stdout process ended.
```
config: ST3 (3175) with LSP,  Ubuntu 16, stack:
```
stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```
hie:
```
hie --version
Version 0.2.0.0, Git revision 75e1aca6060840f3c3e011f8afbf3dc18f1fb710 (1522 commits) x86_64 ghc-8.2.2
```
I launch sublime as `stack exec -- sublime .` HIE would start normally from terminal.
How can I circumvent this problem?

**Comment by alanz** [comment]
We have put a check for matching the version of GHC in hie and the project, into hie itself.

This check calls stack as a subprocess.  So when the hie command is launched, stack needs to be on its path.

BTW, you can get auto-matching of hie versions if you set it up to do

`LSP: starting ['/path/to/home/.local/bin/hie-wrapper', '--lsp', '-d']`

i.e. use `hie-wrapper` instead of `hie`, and make sure you install `hie` via the makefile.

**Comment by Bubba** [comment]
@alanz should this degrade gracefully if stack isn't installed?

**Comment by alanz** [comment]
@Bubba, yes,  I think so.

**Comment by ShrykeWindgrace** [comment]
@alanz thanks for the suggestion, I tried with the wrapper, but the log is the same, up to the lines below:
```
server: 2018-06-21 16:39:19.154978147 [ThreadId 4] - run entered for hie-wrapper(hie-wrapper) Version 0.2.0.0, Git revision 75e1aca6060840f3c3e011f8afbf3dc18f1fb710 (1522 commits) x86_64 ghc-8.4.3
```
and
```
server: hie-wrapper: readCreateProcess: stack ghc -- --version (exit 127): failed
```
Similarly, vscode reported an error `Couldn't start client Haskell HIE (DummyProject)`. 

It seems that the problem come from `sh` not knowing about `stack` (in my setup only `bash` does). Normally, ST3 forces `bin/bash` as shell in its `exec.py`; I guess `bin/sh` comes from `hie`.

**Comment by Bubba** [comment]
Would it be overkill to use the `stack` library to check for the GHC version?
https://hackage.haskell.org/package/stack-1.7.1/docs/Stack-Config.html#v:loadConfig

**Comment by Bubba** [comment]
Similarly using `ghc`: https://hackage.haskell.org/package/ghc-8.4.1/docs/Config.html#v:cBooterVersion

**Comment by alanz** [comment]
Not at all, it is just one less thing to worry about (presence of stack). I think GHC we will have to check from the path though.
