### ISSUE TITLE
Don't throw so many errors

### ISSUE THREAD

**Issue by LeanderK** [haskell/haskell-ide-engine#663]
Sometimes when I write code, it won't compile for some time. It happens, I am writing code. Recently I was using the CPP for some task, but it took some time to come to a satisfying formulation for a macro. Under some of these conditions, haskell-ide-engine constantly spams me with a LOT of errors (probably every time it tries to compile the file). I recently had more than 110 errors over a short period of time popping up (vs-code tracks the unread ones) 

Sometimes they are also unavoidable, for example, if HIE can't satisfy a dependency, but you are only making a quick edit and don't want to set up HIE for the correct GHC-Version.

This ticket serves to both raise awareness and collects situations, where HIE bombards the user with errors:

- coding CPP-macros, which don't compile yet
- HIE being unable to satisfy a dependency

I think it's important that HIE communicates if it can't help you (for example if it's unable to satisfy a dependency). But it should not spam so much.

**Comment by wz1000** [comment]
I can't really think of a solution for this other than a setting that makes HIE only compile the file on save or something.

**Comment by LeanderK** [comment]
Hmm, that would be very unfortunate. 
But I don't think this affects all of the issues? I don't think illegal CPP-macros should result in an error. Typing illegal Haskell results in some red-lines, and illegal CPP-macros should do the same (but at least don't throw errors)

**Comment by LeanderK** [comment]
Maybe this issue should also be raised on the HIE-servers?

**Comment by wz1000** [comment]
Oh, you mean report CPP errors as diagnostics instead of error notifications? That might be doable.

**Comment by alanz** [comment]
We have an open issue to make a config option to only run diagnostics on save, see #522
