### ISSUE TITLE
brittanyCmd: Brittany error - invalid output

### ISSUE THREAD

**Issue by LeanderK** [haskell/haskell-ide-engine#666]
when I try to format my haskell-file
```
[Error - 23:53:29] Request textDocument/formatting failed.
  Message: brittanyCmd: Brittany error - invalid output

  Code: -32603 
```

it's working when I delete the export:

```haskell
(.. module declaration)
    (
        Scalar
    ,   type (><)
    ,   Cone (..)
    ,   Module (..)
    )
(..more haskell)
```

and just export `()`

**Comment by Bubba** [comment]
Does it work when you use Brittany on it from the command line?

**Comment by lspitzner** [comment]
This needs fixing/extension support in brittany; I have opened an issue.

**Comment by LeanderK** [comment]
i think this should be closed then

**Comment by lspitzner** [comment]
CI is still running, but i'll be optimistic and say this is fixed in brittany HEAD.

**Comment by LeanderK** [comment]
thanks 🙂
