### ISSUE TITLE
Windows 10, VS Code, useHieWrapper not honoured/working?

### ISSUE THREAD

**Issue by mpilgrem** [haskell/haskell-ide-engine#670]
Re #439: I am using Haskell Language Server 0.0.19 (HLS) with VS Code 1.25.0 on Windows 10. The `build-all` `hie.exe` family of executables are all on the path (`-8.2.1.exe`, `-8.2.2.exe`, `-8.2.exe`, `-8.4.2.exe`, `-8.4.3.exe`, `-8.4.exe`, and `-wrapper.exe`) (a path without spaces #565).

`hie-8.2.2 --version` is `Version 0.2.0.0, Git revision 8e0b60f3d47f6332c0f4415b9fff03815e229275 (1549 commits) x86_64 ghc-8.2.2`. `hie-wrapper --version` is `Version 0.2.0.0, Git revision 8e0b60f3d47f6332c0f4415b9fff03815e229275 (1549 commits) x86_64 ghc-8.4.3`.

In VS Code's user settings, `"languageServerHaskell.useHieWrapper": true,`. (All other extension settings are default ones.)

Creating a new project with `stack new test` (resolver `lts-11.17`; GHC 8.2.2) I get the following error when I first open `Lib.hs` in VS Code (and the HLS extension does not seem to work):

````
Mismatching GHC versions: Project is 8.2.2, HIE is 8.4.3
You may want to use hie-wrapper. Check the README for more information
````
It appears from the message that `hie-wrapper.exe` is not being used, despite the user setting. Any advice, gratefully received.

There is a subsequent error message, which I am assuming reflects the mismatch:
````
Got error while processing diagnostics: <command line>: cannot satisfy -package-id base-4.10.1.0
    (use -v for more information)
````

**Comment by Supernerd11** [comment]
Change "languageServerHaskell.userHieWraper" to false, and switch hie executable path to "hie-wrapper". The problem lies with the vscode extension, and that it uses an old wrapper script.

**Comment by mpilgrem** [comment]
Thank you. That fixed it.
