### ISSUE TITLE
Define Emacs menu

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-ide-engine#68]
Initial work on Emacs menu:

<img width="516" alt="emacs-menu" src="https://cloud.githubusercontent.com/assets/917978/11142544/543a5a58-89ee-11e5-9368-46ad333cea25.png">

This issue tracks the progress and will be closed by merging this work to master.

**Comment by alanz** [comment]
I think we need to extend the `pluginDescriptor` to give a short name and a description to each plugin.

e.g. "HaRe" "The haskell refactorer"

so that it can be used in the UI where it makes sense, perhaps around structuring the menu.
