### ISSUE TITLE
Go to definition on a project import should open that file

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#688]
If the cursor is on the module name in an import, e.g.

```haskell
import           Haskell.Ide.Engine.LSP.CodeActions
                             ^ (cursor pos)
```

then the `go to definition` function should open the file. Perhaps?

**Comment by MaskRay** [comment]
ccls/clangd/cquery have such `textDocument/definition` behavior. BTW, there is also `textDocument/documentLink` but I don't find it very useful.
