### ISSUE TITLE
Hoogle database not found

### ISSUE THREAD

**Issue by lorenzo** [haskell/haskell-ide-engine#697]
After building hie form latest master, I've tried many different combinations to get the code action for autocorrecting possibly misspelled functions to work in vim.

In all cases I get that the Hoopla database was not found and I need to generate it. Already have tried different versions of Hoogle, ranging form the latest in stacked back to 5.0.13.

Am I missing anything?

**Comment by Bubba** [comment]
Have you ran `stack exec hoogle generate` from the hie source directory? (or `make build-all` if you're using `hie-wrapper`) The typo corrections *shouldn't* depend on the hoogle database, but let me know if generating the database does fix it

**Comment by Bubba** [comment]
Do the autocorrections show up whenever you try to build from the command line? ghc should suggest something like "perhaps you meant"

**Comment by lorenzo** [comment]
Yes, they do. I can even see the suggestion in the error line coming from hie itself. The porblem is attempting a code action on the line having the compiler error

**Comment by lorenzo** [comment]
@Bubba Is hie supposed to use the hoogle database in that case?

**Comment by Bubba** [comment]
Hie uses the hoogle database to generate other code actions, so it possible that if the database isn't available it stops generating the ones that don't depend on it, i.e. the typo code actions in this case. This is definitely not intended though. #701 should try to fix this

**Comment by Bubba** [comment]
@Lorenzo Are you seeing any improvement on the latest version on master?

**Comment by lorenzo** [comment]
Much better, thanks a lot!

Sorry I could not answer before, I was out for holidays.
