### ISSUE TITLE
VS Code's hie complains that processing stack build failed.

### ISSUE THREAD

**Issue by Gurkenglas** [haskell/haskell-ide-engine#738]
`Got error while processing diagnostics: readCreateProcess: stack "build" "--only-configure" "." (exit 1): failed` sometimes pops up as a notification in the lower right corner.

**Comment by Gurkenglas** [comment]
This one just popped up next to the usual:

`Got error while processing diagnostics: C:\Users\gurke\haskell-ide-engine\haskell-ide-engine.cabal: getModificationTime:CreateFile "\\\\?\\C:\\Users\\gurke\\haskell-ide-engine\\haskell-ide-engine.cabal": does not exist (Das System kann die angegebene Datei nicht finden.)`

**Comment by willbasky** [comment]
@Gurkenglas 
I had the same error in Linux. I fixed it with deletion `.cabal` files from  `lib` and `app` folders of my project. It seems the error of wrong project structure.

**Comment by Avi-D-coder** [comment]
I keep getting this error when trying to use `stack-8.4.4.yaml` as  `stack.yaml` in this repository. No error when using 8.4.3 as `8.4.4.yaml`. With neovim and vscode on arch linux.

**Comment by JasonMFry** [comment]
I had the same output but was able to solve it by looking at the output in VSCode Output panel. I needed to add a package to `stack.yaml` and now HIE is working fine. For anyone else who is having this issue, make sure you look at the output panel.

**Comment by falsandtru** [comment]
I found a new unknown submodule which not initialized. I resolved the error by running `git submodule update --init --recursive`.
