### ISSUE TITLE
Vim usage instructions

### ISSUE THREAD

**Issue by wjdhamilton** [haskell/haskell-ide-engine#747]
Hello

Thanks for this excellent piece of software! I have an idiot question, though:

How do you do things like add missing imports, check types, and add missing imports in Vim?

**Comment by Bubba** [comment]
If you're using LanguageClient-neovim as your client, you can access the missing imports via code actions with `:call LanguageClient_textDocument_codeAction()`. You probably want to map it to something in your .vimrc, here's mine:

```vim
nnoremap <silent> go :call LanguageClient#textDocument_documentSymbol()<CR>
nnoremap <silent> ga :call LanguageClient#textDocument_codeAction()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> gr :call LanguageClient#textDocument_rename()<CR>
nnoremap <silent> gfd :call LanguageClient#textDocument_formatting()<CR>
```

For checking types you can use `:call LanguageClient_textDocument_hover()`!

**Comment by wjdhamilton** [comment]
Thank you so much for your response. 

Not all of these are working for me, this is probably more due to ignorance on my part than anything else. 

`_documentSymbol` just says `Document symbols populated to location list`. Not sure what that means.
`_codeAction` works fine
`_definition` works fine
`_rename` works fine
`_formatting` works fine
`call LanguageClient_textDocument_hover()` works the first time, but then writes the definition at the top of the document, overwriting the second line onwards. This is very odd behaviour!

**Comment by wjdhamilton** [comment]
Thanks very much for your help - I've managed to resolve most of these things, though to my embarrassment most of them were solved by restarting vim! I still haven't resolved the `hover()` problem, but I'll report back once I have.

For others trying to follow this:

FZF is a plugin that creates a popup window, that is needed for most of these commands. It can be found [here](junegunn/fzf).

**Comment by wjdhamilton** [comment]
`hover()` problem disappeared when I moved from Vim 8 to Neovim and switched from Vundle to Plug. Not blaming Vim 8 or Vundle, it might have just been the virtue of a clean install...
