### ISSUE TITLE
Make build-all is building all Haskell packages again and again

### ISSUE THREAD

**Issue by lou00011** [haskell/haskell-ide-engine#749]
Following the installation instructions, after make build-all packages repeatedly, including older versions
of GHC and its compatible modules. I am quite sure I've seen the same package being built again.
It used 6GB of space already, and it craves for more.

Is this the intended behavior?

**Comment by alanz** [comment]
The `make-build-all.bat` script (and `make build-all`) builds versions of hie for

- GHC-8.2.1
- GHC-8.2.2
- GHC-8.4.2
- GHC-8.4.3

On linux you can build just the versions you need, by calling

`make hie-8.4.3`

etc

**Comment by lorenzo** [comment]
I’ll close this as the question was answered. Please let us know if you need anything else.
