### ISSUE TITLE
Breaks type wildcards

### ISSUE THREAD

**Issue by lorenzo** [haskell/haskell-ide-engine#754]
Hi,

Today I was curious about how HIE handled type wildcards, thinking that it maybe would offer some interesting code action, but actually found a weird issue. I think it can be described faster with a short video:

[![asciicast](https://asciinema.org/a/c5sQhnYvvNAZYQWZUhyPZ004r.png)](https://asciinema.org/a/c5sQhnYvvNAZYQWZUhyPZ004r)

In summary, using a type wildcard shows the correct hint in the error message, but only the first time. The issue is solved by restarting the language server.

**Comment by Bubba** [comment]
@alanz This looks like it might be related to that issue with diagnostics not clearing I saw a while ago

But on a related note code actions for typed holes is a great idea!
