### ISSUE TITLE
Update design documentation page

### ISSUE THREAD

**Issue by sgronblo** [haskell/haskell-ide-engine#763]
It seems this page is last updated in 2015: https://github.com/haskell/haskell-ide-engine/blob/master/docs/Design.md

Is it still up-to-date?

**Comment by alanz** [comment]
Nope, it has been superseded by https://github.com/haskell/haskell-ide-engine/blob/master/docs/Architecture.md

**Comment by Anrock** [comment]
@alanz maybe delete it then? Or at least put a link to newer doc?
