### ISSUE TITLE
Consider showing local bindings for type hole substitutions in 8.4.3

### ISSUE THREAD

**Issue by lorenzo** [haskell/haskell-ide-engine#767]
Since GHC does not show local bindings as valid substitutions in 8.4.3, it would be cool to append the `Relevant bindings include` section in the bottom of the list.

 One heuristic could be that if the only valid substitution is `undefined` or the `error*` functions, then appending the local bindings for help may be a good idea.

Additionally, I think it would be helpful to show the type of the binding as part of the substitution. For instance, it could read as follows:

```
Substitute hole (ShellCheck.AST.Token) with allFlags (ShellCheck.AST.Token -> [String])
Substitute hole (ShellCheck.AST.Token) with hasYesOption (ShellCheck.AST.Token -> Bool)
Substitute hole (ShellCheck.AST.Token) with undefined
```

**Comment by lorenzo** [comment]
I've followed previous commits on implementing this feature, so I think I may be able to help implement this if you think it is a good idea.

**Comment by Bubba** [comment]
That sounds good to me! I think you should be able to hack away at `GhcMod.hs` for these code actions
