### ISSUE TITLE
Innoculate hie against .ghc.environment files

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#775]
Which can be done by the `DynFlags` initialisation shown in https://github.com/lspitzner/brittany/issues/173#issuecomment-414155227

It probably needs to happen in ghc-mod.

**Comment by alanz** [comment]
See https://github.com/alanz/ghc-exactprint/pull/68
and https://github.com/lspitzner/brittany/commit/8c5cce50709d6c0e41aed13df808a36ce13df4a4

**Comment by alanz** [comment]
I think this has been done, confirm.

**Comment by jneira** [comment]
Maybe we should close this one?
