### ISSUE TITLE
GHC Panic

### ISSUE THREAD

**Issue by pascalpoizat** [haskell/haskell-ide-engine#779]
**Note:** copied from https://github.com/alanz/vscode-hie-server/issues/108 after the discussion at https://github.com/DanielG/ghc-mod/issues/938#issuecomment-414463173

**In short:** there may be an issue with the forked ghc-mod in HIE when using stack + LTS 12.7 + GHC 8.4.3 + HIE wrapper -> HIE 8.4.3.
When using stack + LTS 11.17 + GHC 8.2.2 + HIE wrapper -> HIE 8.2.2 all is ok.

Hello

I have an issue that seems related to TemplateHaskell (not sure).

I am using https://github.com/haskell/haskell-ide-engine (0.2.1.0) + the https://github.com/alanz/vscode-hie-server plugin for VSC (0.0.21). I work on a stack generated project (using stack new, stack GHCI 8.4.3).

This is how the error comes.

1- type in the code (below) with the TemplateHaskell commented out : OK
2- uncomment it : this error arises
<img width="636" alt="capture d ecran 2018-08-19 a 12 03 21" src="https://user-images.githubusercontent.com/6471971/44308209-a2c69280-a3b9-11e8-97cf-2aff23df9b97.png">
3- erase the notification : OK
4- make one change in the file (add and remove a space) : GHC Panic
<img width="635" alt="capture d ecran 2018-08-19 a 12 04 11" src="https://user-images.githubusercontent.com/6471971/44308170-c5a47700-a3b8-11e8-97ba-67a714544a1a.png">
5- erase the notification and perform any change in the code : GHC panic comes again.

Note: at this step, if I use `stack ghci` all goes well, the code compiles. I also tried the code using Spacemacs + Haskell layer / intero and is it ok.

Since I am not sure if the error is fully coming from ghc-mod or partly from the HIE plugin (cf the first error message) I also filled an issue report for ghc-mod here https://github.com/DanielG/ghc-mod/issues/938.

code:
```haskell
{-# LANGUAGE DefaultSignatures #-}
{-# LANGUAGE EmptyCase #-}
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
--{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE DataKinds #-}
-- some experiments with dependent types / type-level programming in Haskell
-- references:
-- http://www.parsonsmatt.org/2017/04/26/basic_type_level_programming_in_haskell.html
-- https://www.schoolofhaskell.com/user/konn/prove-your-haskell-for-great-safety/dependent-types-in-haskell
-- https://hackage.haskell.org/package/singletons

module Lib
where

import Prelude hiding (head, tail, zipWith)
import Data.Singletons.TH

someFunc :: IO ()
someFunc = putStrLn "Hello, World!"

singletons
   [d|

  data Nat = Z
           | S Nat
               deriving (Show, Eq, Ord)

  (+) :: Nat -> Nat -> Nat
  Z + x = x
  (S n) + x = S (n + x)

  (*) :: Nat -> Nat -> Nat
  Z * x = Z
  (S n) * x = n * x + x

  mymin :: Nat -> Nat -> Nat
  mymin Z Z = Z
  mymin Z (S _) = Z
  mymin (S _) Z = Z
  mymin (S x) (S y) = S (mymin x y)

  |]

data Vector a n where
  Nil :: Vector a Z
  (:-) :: a -> Vector a n -> Vector a (S n)
infixr 5 :-

deriving instance Eq a => Eq (Vector a n)

toList :: Vector a n -> [a]
toList Nil = []
toList (a :- v) = a : toList v

instance Show a => Show (Vector a n) where
  showsPrec p = showsPrec p . toList

append :: Vector a n -> Vector a m -> Vector a (n + m)
append Nil v = v
append (a :- v1) v2 = a :- append v1 v2

head :: Vector a (S n) -> a
head (a :- v) = a

tail :: Vector a (S n) -> a
tail (a :- v) = a

zipWithSame :: (a -> b -> c) -> Vector a n -> Vector b n -> Vector c n
zipWithSame f Nil Nil = Nil
zipWithSame f (a :- v1) (b :- v2) = f a b :- zipWithSame f v1 v2

zipWith :: (a -> b -> c) -> Vector a n -> Vector b m -> Vector c (Mymin n m)
zipWith f Nil Nil = Nil
zipWith f Nil (b :- v) = Nil
zipWith f (a :- v) Nil = Nil
zipWith f (a :- v1) (b :- v2) = f a b :- zipWith f v1 v2

zipSame :: Vector a n -> Vector b n -> Vector (a, b) n
zipSame = zipWithSame (,)

zip :: Vector a n -> Vector b m -> Vector (a, b) (Mymin n m)
zip = zipWith (,)
```

**Comment by lorenzo** [comment]
This is a known issue, pleas refer to the troubleshooting section in the realms to fix this. It just involves deleting a file. 

The error is fixed in an iocomimg GHC version.

**Comment by pascalpoizat** [comment]
Thanks @lorenzo and sorry for not having seen this on the README (I looked at the issues but forgot the README).

**Comment by lorenzo** [comment]
@pascalpoizat Not your fault, I also spend a ticket here a few days ago with the same issue. I had also missed that section in the readme.

**Comment by Bubba** [comment]
It's pretty hidden at the bottom of the README, @alanz should we maybe leave a notice at the top of it for macOS users?

**Comment by lorenzo** [comment]
@Bubba Is it maybe possible to make that step part of the Makefile?

**Comment by Bubba** [comment]
@lorenzo I think it would require sudo, and it probably isn't polite to go moving about system files without asking first! I'm surprised it doesn't have any adverse side effects, well none that we've seen so far anyway.
I think we could make a small script for it though, to find the file and rename it, that could be run from the command line by the user. Or make it a separate build target like the icu fix for macOS, in the Makefile, so its only run when specified explicitly.
