### ISSUE TITLE
Provide async synchronisation methods

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#78]
We now have an ability to run an async plugin, through

``` haskell
data CommandFunc resp = CmdSync (SyncCommandFunc resp)
                      | CmdAsync (AsyncCommandFunc resp)
                        -- ^ Note: does not forkIO, the command must decide when
                        -- to do this.

type SyncCommandFunc resp = forall m. (MonadIO m,GHC.GhcMonad m,HasIdeState m)
                => [AcceptedContext] -> IdeRequest -> m (IdeResponse resp)

type AsyncCommandFunc resp = forall m. (MonadIO m,GHC.GhcMonad m,HasIdeState m)
                => (IdeResponse resp -> IO ()) -> [AcceptedContext] -> IdeRequest -> m ()
```

So an async command function gets given a function to call in IO to return the `IdeResponse`, but is otherwise unconstrained.

The intention is that there can either be a single command function which can server as a dispatcher to other async processes, or the function can fork off a separate process to handle the request.

In either case we potentially have multiple processes running, all wanting to make use of information from the underlying project.

At the moment a `PluginDescriptor` is defined as

``` haskell
data PluginDescriptor = PluginDescriptor
  { pdCommands        :: [Command]
  , pdExposedServices :: [Service]
  , pdUsedServices    :: [Service]
  }
```

The `Service` type is not really defined an unused at this point.

The intention is that a `Service` can be used as a synchronisation mechanism, and can expose access functions that are specifically multiprocess aware.

So there would be a base service providing access to the underlying project, which would make sure that e.g. more than one command does not trigger ghc-mod to reconfigure the project.

The question is, how should a `Service` be defined in concrete terms.

**Comment by cocreature** [comment]
I am not entirely sure I understand what `Service` is supposed to do. Here’s what I think about the synchronization methods we should provide:
I would like all commands to be run in a separate thread which means that they run in IO. This means that they need access to the state in `IdeM` somehow. Running in `IO` also means that by default they can’t mess up shared state (at least not as easily). We should then have some Channel or something else where plugins can send requests (which might simply be an `IdeM a` or a specific set of operations that we allow them to do) and then the main thread responds to that.

It might make sense to separate requests that modify the state and the requests that only read it. That way we can use some read-writer-lock to avoid blocking there as much as possible as this will become a bottleneck.

**Comment by alanz** [comment]
I think we should avoid complexity until we have a pressing need for it.

**Comment by alanz** [comment]
And a service could be access to the cached cabal config, dependency graph, that kind of thing.

Or even a synchronisation point to request a GhcMonad function to run.

**Comment by cocreature** [comment]
On the one hand I agree that avoiding complexity is a good default, but on the other hand I really hate the fact that a plugin can block all of hie. But I suppose we need to have some synchronization so this is inevitable, at least if a plugin needs write access to the state, so you might be right that the complexity here is not worth it.

**Comment by alanz** [comment]
If a plugin blocks the whole of HIE it has a bug. Rather have it visible so it can be fixed, than buried in some internal process, invisible

**Comment by cocreature** [comment]
Well it has a bug if it blocks infinitely. But it could also just take a fairly long time (1s is alreay quite a lot imho). Why shouldn’t another plugin be able to do things at the same time if it doesn’t require access to the same state?

**Comment by alanz** [comment]
I think by default a plugin should be sync, and only if it is known to be a hog we make it async.

So do the complex stuff only where it is needed.

**Comment by cocreature** [comment]
Alright, I’m convinced. One thing to note is that a long running command (maybe something that watches for file changes) that requires access to the state (or wants to run something in `IdeM` for some other reason) can’t make itself async since it has no way to get access to the state at that point. But we don’t have such a command yet and for most cases it’s probably more useful to have a long running background process and small commands communicating with them in which case this is not a problem. So let’s worry about that when we have to.

**Comment by alanz** [comment]
This has been superseded, we effectively have this now.
