### ISSUE TITLE
Code action to add signature to function

### ISSUE THREAD

**Issue by lorenzo** [haskell/haskell-ide-engine#787]
It would be nice if HIE could automatically insert function signatures when missing as a code action

**Comment by alanz** [comment]
Don't we already have this? I know I use it quite often.

**Comment by wedens** [comment]
If we're talking about any definition, not just top level, I've seen it in vscode frontend, but not in lsp-haskell. Not sure if it's implemented in hie itself though.

**Comment by lorenzo** [comment]
Oh yes, I implemented this. Forgot to close the issue.

**Comment by ivanperez-keera** [comment]
Sorry to comment on an old issue, but if this is indeed implemented, how is it used? I fail to find any document explaining that.

**Comment by bubba** [comment]
https://github.com/haskell/haskell-ide-engine/pull/813 added this, from what I can remember it shows up as a quick fix for the hlint warning for top-level definition with no type signature.
Perhaps it could be expanded to offer to insert the type signature for definitions not at the top level?

**Comment by ivanperez-keera** [comment]
This feature would be useful more generally (meaning, at least, without hlint, but for top-level definitions). Hlint does not complain about top-level definitions without signatures.

I don't see any in that commit, but are there functions that could be called directly (and bound to key commands in vim) to 1) see the signature of the expression under the cursor, and 2) insert it?

Later/in a separate issue, this could be changed to work also for local definitions.
