### ISSUE TITLE
Should we always defer typed holes?

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#790]
https://downloads.haskell.org/~ghc/8.4.3/docs/html/users_guide/glasgow_exts.html#typed-holes

At the moment in hie, we rely on the user to decide whether or not to defer typed holes.

This means that in the normal case (i.e. no special action taken), the presence of a typed hole will be treated as an error by GHC and it will terminate compilation, and return an error message.  This means we do not get a `TypeCheckedModule`, and a large chunk of useful information is not generated.

I think we should always pass `-fdefer-typed-holes` as a GHC option to ghc-mod, unless explicitly told not to in a config setting.

There may also be other similar settings we could use, to enable maximum information availability.

e.g. `-fdefer-type-errors`

**Comment by lorenzo** [comment]
Sounds like a good idea! Does it have an effect on how the types get inferred at the end, or do things get inferred the same with or without the flag?

**Comment by alanz** [comment]
Its the same, the only difference is that compilation continues, instead of stopping when the hole is found.
