### ISSUE TITLE
Got error while processing diagnostics: GHC panic! 

### ISSUE THREAD

**Issue by justjoheinz** [haskell/haskell-ide-engine#798]
```
Got error while processing diagnostics: GHC panic! (the 'impossible' happened)   ghc-mod version 5.9.0.0   GHC library version 8.4.3 for x86_64-apple-darwin:        Dynamic linker not initialised  Please report this as a bug: https://github.com/kazu-yamamoto/ghc-mod/issues
t.onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2386
```

I am not sure where to file this bug, as it is my understanding that you have your own branch of GHC-Mod integrated in the hiw server. I get this error frequently in Visual Code, but from the message it does not sound like a VS Code plugin problem. I get this error frequently inside a project, but thus far I have not been able to boil that project down to a minimal version which reproduces the error.  The project compiles fine with stack test and hie server is on the latest master as of today :
`cf08220f56d4692f82b8c44810fbbcb7273bde34`

**Comment by Bubba** [comment]
This sounds like it may be caused by the integer-GMP bug on macOS, can you try the workaround in troubleshooting section of the README?

**Comment by justjoheinz** [comment]
Yes, this seems to have fixed that. Thanks!
