### ISSUE TITLE
Cleanly report missing system GHC for standalone projects

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#803]
See
https://github.com/alanz/vscode-hie-server/issues/110

Or should it somehow try to use a stack one? or nix, or hvr-repo.

**Comment by Anrock** [comment]
Hm, i think there is no sane default for this, so it should be configurable via setting like `standalone-file-ghc-path` or just reported as missing (can't use hie with standalone files then).

**Comment by alanz** [comment]
The vscode issue relates to `hie-wrapper` trying to run the `ghc` exe without checking first for its existence.
