### ISSUE TITLE
fails to work with cabal - readCreateProcess failed

### ISSUE THREAD

**Issue by 2mol** [haskell/haskell-ide-engine#816]
Hi! I get the following error, on both on my mac and linux machines

```
Got error while processing diagnostics: readCreateProcess: cabal "configure" "--with-ghc=ghc" "--flags" "" (exit 1): failed
```

How can I give you more information? Why are no arguments supplied to '--flags'?

I'm using the cabal new-* flags to build my project, if that makes any difference.

**Comment by lorenzo** [comment]
We don't support at this time the `cabal new-*` builds. Is using stack a viable choice for your the meantime?

**Comment by 2mol** [comment]
Oh, good to know! Yeah, I can totally work with stack for now. Thanks for the quick reply.

**Comment by janat08** [comment]
Is this still the case? Maybe it should be opened until cabal new is supported.
