### ISSUE TITLE
Add "debounce" for VFS changes

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#819]
LSP clients can send a lot of changes in a row.

Perhaps add something like a 100ms delay after receiving a change, during which we wait for another change, and only process once we have some kind of steady state.

The trick is to keep it responsive, which means on the one side not hammering the machine with compiles as you type, and on the other side providing timeous feedback.

The current process of having a single thread for all the GHC compiles, which always takes the most recent version (via `docVersionTVar`), should already go a long way to do this.

The question is, can we do something more?  And I think the "more" is deferring a compile completely until the given change has a certain age.

cc @lorenzo

**Comment by lorenzo** [comment]
I'd like to quickly prototype this and see if there is going to be any visible improvement in performance. Then we can iterate and discuss on the implementations details of the smart queue. Some extra ideas that I had for avoiding compilation when none is needed:

-  Entirely avoiding a typecheck if we can detect you are writing a comment. Realistically we can only detect a comment if the line starts with `--` after trimming spaces
- Another change is to wait for whitespace (or a timeout) before triggering a recompile. Being in the middle of writing a function name, or binding will almos always result in a compilation error until it is delimited by some whitespace.

**Comment by alanz** [comment]
I think monitoring the specific changes is going to be difficult, given the way the layering works.

At some (unspecified) future date I intend to use an incremental parser, which should speed things up.

**Comment by MaskRay** [comment]
I know very little about hie but can you give some context about this debounce feature?

haskell-lsp
https://github.com/alanz/haskell-lsp/blob//src/Language/Haskell/LSP/VFS.hs#L68

Other language servers I know of update their states immediately.

ccls
https://github.com/maskray/ccls/blob/master/src/messages/textDocument_didChange.cc#L41

clangd
https://github.com/llvm-mirror/clang-tools-extra/blob/master/clangd/ClangdLSPServer.cpp#L161

**Comment by alanz** [comment]
Is there anything more to be done here?

**Comment by lorenzo** [comment]
Let's close, the immediate problem that I had is already solved. I can open new tickets later if I come up with new ideas
