### ISSUE TITLE
Can not build with ghc 8.4.3

### ISSUE THREAD

**Issue by vnluc** [haskell/haskell-ide-engine#820]
I have ghc 8.4.3 installed. however I can not build HIE. 

Here is the command output

`haskell-ide-engine-master>stack build --stack-yaml=stack-8.4.3.yaml
Stack looks for packages in the directories configured in the 'packages' and 'extra-deps' fields defined in your stack.yaml
The current entry points to D:\bin2\haskell-ide-engine-master\submodules\HaRe\ but no .cabal or package.yaml file could be found there.`

**Comment by lorenzo** [comment]
You need to execute `git submodule update --init` first

**Comment by vnluc** [comment]
Thank you very much. I do clone full repository again with option --recurse-submodules   and I can build it. 

```
git clone --recurse-submodules https://github.com/haskell/haskell-ide-engine
stack build

```
