### ISSUE TITLE
[vscode] - ghcmod Defined but not used

### ISSUE THREAD

**Issue by MQuy** [haskell/haskell-ide-engine#827]
I am not sure this is the correct place to report this issue. I use hie's master, run build on Mac and I get a lot of warnings related to ghcmod

![ghcmod](https://i.imgur.com/IUncclw.png)

Maybe I miss something?

**Comment by lorenzo** [comment]
That’s a compiler warning, it means that you declared the binding but not using it anywhere in the file. It is a warning because that usually leads to bugs

**Comment by lorenzo** [comment]
@MQuy there is a possibility that this has to do with the lack of a module name in your file like `Module Parser where`. I'm not super sure why the compiler would give you that warning, but try adding a module declaration or maybe a `main` function

**Comment by alanz** [comment]
@MQuy GHC takes this as a main module (since there is no module header)

If I open it up it complains about a missing "main" function.

GHC defines uses as functions that are transitively used from the main function.

So from GHC perspective, nothing in that file is used.

**Comment by MQuy** [comment]
thanks @lorenzo and @alanz 👍🏻
