### ISSUE TITLE
HIE fails in multi-folder project

### ISSUE THREAD

**Issue by ismailmustafa** [haskell/haskell-ide-engine#832]
If a haskell stack project is inside a sub folder when opened with vscode, it fails to start HIE. For example, my project is structured like so:

```
.
├── backend
│   ├── LICENSE
│   ├── README.md
│   ├── Setup.hs
│   ├── haskellProject.cabal
│   ├── resources
│   ├── src
│   └── stack.yaml
└── frontend
    └── ... js files ...
```

To fix the issue, I have to `cd` into `backend` and then open that specific folder within vscode.

**Comment by ismailmustafa** [comment]
Couple of ways I'm thinking about approaching this:

1) This function could recursively look for `stack.yaml` and use the first one it finds. This could be problematic if you have multiple folders each containing a different `stack.yaml` (though I'm unsure that this would ever be an issue/use-case):
https://github.com/haskell/haskell-ide-engine/blob/01189cf5848b3c03eb0cbea8a0bf3d0403135ee3/src/Haskell/Ide/Engine/Plugin/Base.hs#L107

2) the LSP client could pass a `stack.yaml` filepath to `hie` on start, however this would involve `stack.yaml` search logic on the client side which I'm not a big fan of. If it's possible to just get the filepath of the file being worked on, then logic could remain in `hie`. This approach would fix the issue mentioned in `1`.

**Comment by Anrock** [comment]
@ismailmustafa dunno about LSP client for VSCode but neovim LanguageClient implemented option 2 and it works pretty much ok.

**Comment by fendor** [comment]
Can be worked around now with explicit config files.
