### ISSUE TITLE
Add quickfix for unused variable warning

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#843]
Generate an edit that prefixes an underscore char to the unused var.

**Comment by jkeuhlen** [comment]
I'd be interested in helping out here since it's labelled as a good first issue. I'm not 100% sure I understand the change that needs to be made/where to get started?

**Comment by bubba** [comment]
@jkeuhlen You’ll probably want to check out `GhcMod.hs` in the plugins folder, there’s some code there for generating quick actions for import warnings, which should hopefully be similar to this!

**Comment by meck** [comment]
I started looking into this, as a beginner exercise. I managed to detect and prefix a lone term, however it isn't very nice if case you have accompanying signature or a pattern match, as it only changes one of the occurrences.

The reasonable thing seems to use ```rename``` from the ```hare``` plugin. But as far as I can see there is no provisioning from calling from one plugin to another in the api?

**Comment by bubba** [comment]
@meck you're probably better off just importing the HaRe module directly from the plugin that you're working on. I believe the Hoogle package is already used in multiple plugins
