### ISSUE TITLE
can't build hie with ghc 8.4.3 on arch linux

### ISSUE THREAD

**Issue by 3nigm4** [haskell/haskell-ide-engine#848]
Hi, thanks so much for HIE!

Unfortunately I can not build HIE, I get:

/home/foo/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3: startProcess: invalid argument (Bad file descriptor)

what am I doing wrong?

**Comment by bubba** [comment]
Sounds like you might need to delete that `setup-exe-cache` folder
