### ISSUE TITLE
hsimport for vscode?

### ISSUE THREAD

**Issue by witoldsz** [haskell/haskell-ide-engine#853]
Is hsimport (or equivalent) supported for vscode? I can see it's mentioned for Vim in README.md.

**Comment by bubba** [comment]
Yes, it should appear as a quick fix if you try to use a function that’s not imported but available via Hoogle! You need to generate the hoogle DB beforehand first though

**Comment by witoldsz** [comment]
Something is wrong with my setup, the _quick fix_ does not work at all in my editor.

Having that problem resolved, should the importing feature work for modules from the project itself or it's only for modules from Hoogle database?

**Comment by bubba** [comment]
Currently it's whatever shows up on hoogle. It's definitely something that could be added though, and I've created a new issue for it https://github.com/haskell/haskell-ide-engine/issues/865

**Comment by witoldsz** [comment]
Thanks.
