### ISSUE TITLE
Change makefile default target to build fewer versions

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#856]
Perhaps we should limit the number of versions that are built by default, currently it is

- hie-8.2.1
- hie-8.2.2
- hie-8.4.2
- hie-8.4.3

Perhaps it should default to only building `hie-8.4.3`, and have an `all` target for the rest.

**Comment by Anrock** [comment]
Reducing number of built hies is good. 
However selecting specific version to build by default, imo, is not good - there are many users that aren't using last ghc.

I suggest adding default help target which prints available hie versions and options, so user won't accidentally build unexpected version.

**Comment by lorenzo** [comment]
This was addressed already
