### ISSUE TITLE
Move module Haskell.Ide.Engine.Plugin.Fuzzy

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#859]
This is not a plugin, but supporting code.  I would like to see only plugins in the `Haskell.Ide.Engine.Plugin` directory.

I am not sure where it should go, perhaps it is time to make a `Utils` dir?

Suggestions welcome.

**Comment by bubba** [comment]
I would like to see the rest of `Haskell.Ide.Engine.Plugin.HieExtras` moved into a `Utils` folder or similar as well, since it's not a plugin either

**Comment by bubba** [comment]
I think it might also be worthwhile splitting up `HieExtras` into separate modules for completion/symbols/definitions as well, as some of these functions are getting quite beefy. Could they be moved to the LSP directory? I'm not sure if they're used by the JSON transport at all

**Comment by fendor** [comment]
This can be closed now, right?
