### ISSUE TITLE
Could not find module System.Random.

### ISSUE THREAD

**Issue by AnthonyJacob** [haskell/haskell-ide-engine#863]
Installed HIE, created new `myProject/main.hs`:

```haskell
module Main where

import System.Random (randomRs)

main = undefined
```

and I get the following error: `Could not find module System.Random.`.

```bash
$ ghci
> :l main.hs
```
does not have this problem. Does HIE need cabal / stack file to work?

**Comment by lorenzo** [comment]
Yes, it needs at least the cabal file

**Comment by bubba** [comment]
It generally works best with a cabal file but should work without one.
I'm not getting this error running your example locally. Did you install `random` via cabal?

**Comment by Anrock** [comment]
No repro and no movement for more than a month - closing.
