### ISSUE TITLE
Autocompletion for language extensions

### ISSUE THREAD

**Issue by lorenzo** [haskell/haskell-ide-engine#867]
It would be nice if hie could complete language extensions when it can detect the right completion context

**Comment by cronokirby** [comment]
What would be the place to look for adding this?

**Comment by lorenzo** [comment]
Look at how completions for import modules are done:

https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/HieExtras.hs#L328-L335

The list of visible modules is taken from the ghc-mod api. You could take the list of all available Language extensions from the same api, here is how it was done for the modules list:

https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/HieExtras.hs#L198

And this is how it could be done for the language extensions:

https://github.com/DanielG/ghc-mod/blob/master/GhcMod/Exe/Lang.hs#L10

@cronokirby let me know if you want to volunteer for this task and if you need further help.
