### ISSUE TITLE
Error starting language server

### ISSUE THREAD

**Issue by adityavkk** [haskell/haskell-ide-engine#897]
I'm seeing this error as VS code tries to start the language server.

```
[Error - 6:29:07 PM] Starting client failed
Error: spawn EACCES
	at _errnoException (util.js:1024:11)
	at ChildProcess.spawn (internal/child_process.js:323:11)
	at Object.exports.spawn (child_process.js:514:9)
	at _getServerWorkingDir.then.serverWorkingDir (/Users/USER/.vscode/extensions/alanz.vscode-hie-server-0.0.24/node_modules/vscode-languageclient/lib/main.js:347:40)
	at <anonymous>
```

I've confirmed that the HIE binaries exist for all versions in `~/.local/bin`. What could be causing this?

**Comment by bubba** [comment]
Have you given the hie executables execute permissions? (`chmod u+x ~/.local/bin/hie*`)

**Comment by adityavkk** [comment]
Yeah, all the HIE executables have permissions.

**Comment by alanz** [comment]
Is `$HOME/.local/bin` in your `$PATH`? Need to use `$HOME`, `~` won't work.

**Comment by adityavkk** [comment]
Yeah, it is. 
```
$ echo $PATH
....:/Users/Aditya/.local/bin
```

**Comment by ingun37** [comment]
@adityavkk I've ran into same error. Did you fix it? If so could you tell me how?
