### ISSUE TITLE
Name of project module hierarchy root question

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#9]
Where should the top of the project set

```haskell
Language.Haskell.Support
Language.Haskell.Daemon
Language.Haskell.IDE.Daemon
Tools.Haskell.Daemon
Tools.Haskell.Tools
```

Let the bikeshedding begin

**Comment by cartazio** [comment]
IDE.Haskell.Tools
:))))

**Comment by alanz** [comment]
I like it, but maybe

IDE.Tools.Haskell

**Comment by mgsloan** [comment]
I tend to like it when the package name relates to the module name, so I'm not sure if I like `IDE.Haskell`.  I'd be in favor of `Haskell.Ide` or possibly `Language.Haskell.Ide`.  Not everyone follows the convention of not capitializing acronyms, but personally I prefer it.  I think I picked that up from [tibbe's style guide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#naming)

**Comment by mgsloan** [comment]
Also, while we've already got `haskell-ide`, Chris Done doesn't mind if we re-use the name `ghc-server`.

**Comment by alanz** [comment]
There has already been a discussion on irc about whether the current name is appropriate.  The consensus is that it is not.

What it should be is one question, and whether it is worth changing is another.

Ghc-server could be a good one. Ide-backend is unfortunately taken.

But ide-tools or ide-tools-haskell could work quite well too

**Comment by alanz** [comment]
Given the project renaming, I propose

`Haskell.Ide.Engine` 

as the top level name

Or perhaps

`Ide.Engine.Haskell`

**Comment by bitemyapp** [comment]
@alanz  Apologies for the bikeshedding:

I think `engine` isn't adding any information here for the namespace, perhaps

`Haskell.Ide` or `Language.Haskell.Ide` for the top-level? With `Backend` (or similar) for the server bits, `API` (or similar) for the stuff exposed as a library?

**Comment by alanz** [comment]
Well,  by using `Engine` we are not polluting the name space for any future person wanting to write a haskell IDE.

Perhaps

`Language.Haskell.Hie`

And yes, it is a bit circular, but it is shorter than before.

**Comment by mgsloan** [comment]
I like `Haskell.Ide.Engine`, since it's `intercalate "." . map capitalize $ splitOn "-" packageName`

**Comment by alanz** [comment]
That was my initial thinking too. I like maintaining expectations

**Comment by bitemyapp** [comment]
@alanz @mgsloan concurring on `Haskell.Ide.Engine`
