### ISSUE TITLE
DuplicateRecordFields leads to incorrect completions 

### ISSUE THREAD

**Issue by Avi-D-coder** [haskell/haskell-ide-engine#903]
This bug is known to occur with vscode and LanguageClient-neovim.

#### Steps to Reproduce
```hs
{-# LANGUAGE DuplicateRecordFields #-}

data Foo = FooBar
  { bar :: Int
  }
```
Start typing `bar`
completion items: 
` $sel:bar:FooBar Function [+] [LC] Foo -> Int^@Main` 
`$tc'FooBar      Function [+] [LC] TyCon^@Main`

**Comment by lorenzo** [comment]
I’m not sure I understand why this issue is related to DuplicateRecordFields. Can you elaborate a bit more?

**Comment by Avi-D-coder** [comment]
`$sel:bar:FooBar Function [+] [LC] Foo -> Int^@Main` is suggested instead of `bar     Function [+] [LC] Foo -> Int Main` only when `DuplicateRecordFields` is active.

` $tc'FooBar Function [+] [LC] TyCon^@Main` seems to be suggested regardless of whether `DuplicateRecordFields` is used.

**Comment by alanz** [comment]
I think we need to filter the suggestions, we are definitely returning junk for these.

**Comment by alanz** [comment]
Trivial getting-started task: change completions like `$sel:bar:FooBar` into `bar`.

**Comment by jhrcek** [comment]
@alanz I'd like to tackle this. I'd like to clarify general expectation about the fix:
Should the fix strip the [$sel and constructor name](https://ghc.haskell.org/trac/ghc/wiki/Records/OverloadedRecordFields/DuplicateRecordFields#Implementation) name "blindly" from every completion, or should it check that DuplicateRecordFields extension is enabled (I'm not sure if that's even possible yet) before doing that?

**Comment by alanz** [comment]
I would strip it blindly, it is never a valid completion.

On vscode, go to File, Preferences, Settings. Then under Extensions find Haskell Language Server, and set "Trace:Server" to "Messages".

**Comment by jhrcek** [comment]
After spending some time trying to figure out the best place to do the stripping I came up with this.
https://github.com/jhrcek/haskell-ide-engine/commit/5cbfbdea9471492b264ceb70487ee54168ee0b40

**Comment by alanz** [comment]
LGTM, turn it into a PR

**Comment by Avi-D-coder** [comment]
Just ran into `$f` prefix for derived instances.

**Comment by alanz** [comment]
I am coming across some other cases, and just dived into GHC's [OccName.hs](https://github.com/ghc/ghc/blob/master/compiler/basicTypes/OccName.hs).

This has

```haskell
mkDataConWrapperOcc = mk_simple_deriv varName  "$W"
mkWorkerOcc         = mk_simple_deriv varName  "$w"
mkMatcherOcc        = mk_simple_deriv varName  "$m"
mkBuilderOcc        = mk_simple_deriv varName  "$b"
mkDefaultMethodOcc  = mk_simple_deriv varName  "$dm"
mkClassOpAuxOcc     = mk_simple_deriv varName  "$c"
mkDictOcc           = mk_simple_deriv varName  "$d"
mkIPOcc             = mk_simple_deriv varName  "$i"
mkSpecOcc           = mk_simple_deriv varName  "$s"
mkForeignExportOcc  = mk_simple_deriv varName  "$f"
mkRepEqOcc          = mk_simple_deriv tvName   "$r"   -- In RULES involving Coercible
mkClassDataConOcc   = mk_simple_deriv dataName "C:"     -- Data con for a class
mkNewTyCoOcc        = mk_simple_deriv tcName   "N:"   -- Coercion for newtypes
mkInstTyCoOcc       = mk_simple_deriv tcName   "D:"   -- Coercion for type functions
mkEqPredCoOcc       = mk_simple_deriv tcName   "$co"

-- Used in derived instances
mkCon2TagOcc        = mk_simple_deriv varName  "$con2tag_"
mkTag2ConOcc        = mk_simple_deriv varName  "$tag2con_"
mkMaxTagOcc         = mk_simple_deriv varName  "$maxtag_"

-- TyConRepName stuff; see Note [Grand plan for Typeable] in TcTypeable
mkTyConRepOcc occ = mk_simple_deriv varName prefix occ
  where
    prefix | isDataOcc occ = "$tc'"
           | otherwise     = "$tc"

mkRecFldSelOcc s = mk_deriv varName "$sel" [fsLit s]

  = mk_deriv varName "$cp" [fsLit $ show index, occNameFS cls_tc_occ]

  = mk_deriv varName "$p" [fsLit $ show index, occNameFS cls_tc_occ]

   = mk_deriv varName "$L" [fsLit $ show uniq, occNameFS occ]

    prefix | is_boot   = "$fx"
           | otherwise = "$f"

mkDataTOcc occ = chooseUniqueOcc VarName ("$t" ++ occNameString occ)
mkDataCOcc occ = chooseUniqueOcc VarName ("$c" ++ occNameString occ)

mkMethodOcc occ                     = mk_simple_deriv varName "$m" occ

```

So I think we should ignore/strip out all of those too.
