### ISSUE TITLE
GHC 8.4.4 support

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#910]
It seems that if we add

```
compiler-check: newer-minor
```
to the `stack.yaml` file specifying a GHC 8.4.3 snapshot, it will use GHC 8.4.4 (if it has been installed via `stack setup 8.4.4`).

So, do we add this to the existing 8.4.3 stack config, or make a new one specifically called `stack-8.4.4.yaml` with this in it?

**Comment by alanz** [comment]
And lts 12.15 now supports 8.4.4, so this becomes simple.

**Comment by bubba** [comment]
Done in #911
