### ISSUE TITLE
Generalize stripping of autogenerated stuff from compiler

### ISSUE THREAD

**Issue by jhrcek** [haskell/haskell-ide-engine#921]
Follow up on 
https://github.com/haskell/haskell-ide-engine/pull/918

- look into ghc codebase to see what other prefixes/sufixes are added to user-defined names and strip them whenever this can be done reliably
    - for now we know of [$f and $fx](https://github.com/ghc/ghc/blob/master/compiler/typecheck/TcRnDriver.hs#L733-L748)
- reuse the stripping code in "on hover" functionality

**Comment by alanz** [comment]
I think this is done by me, confirm.

**Comment by alanz** [comment]
See #958

**Comment by jhrcek** [comment]
@alanz Sorry I didn't check this in time, I was on christmas vacation. The fix looks good to me. Thank you
