### ISSUE TITLE
version update ?

### ISSUE THREAD

**Issue by shrynx** [haskell/haskell-ide-engine#922]
sorry for asking it here, but how does one go by updating hie to a newer version?
for eg, I had initially installed 8.4.2, after the release of latest 8.4.4 how do update hie to it?
the only way currently i know is to git pull and build this specific version I guess, is there something i am missing?

**Comment by lorenzo** [comment]
That is currently the only way of updating it. In the mid term we plan to provide pre-built binaries.

**Comment by shrynx** [comment]
Thanks for the prompt reply 😀
oh pre-built binaries with a `hie --upgrade` command would be awesome ?
is there any haskell ci tooling like https://github.com/japaric/trust

**Comment by lorenzo** [comment]
Having an upgrade flag would be really nice, thanks for the idea. I know of this project for generating travis scripts: https://github.com/haskell-CI/haskell-ci

Will close this ticket as your question has been answered. Let us know if you need anything else :)
