### ISSUE TITLE
ghc-options -Wall not honoured

### ISSUE THREAD

**Issue by leemhenson** [haskell/haskell-ide-engine#929]
Hi. 

I'm trying to get warnings as errors in VS Code but no warnings are being reported by HIE. I get type information on hover and if I force a parser error it is shown correctly, so the link between HIE and VS Code is clearly working. 

This is the output from HIE when VS Code boots:

```
2018-11-09 12:51:44.13896 [ThreadId 4] - Using stack GHC version
2018-11-09 12:51:44.362892 [ThreadId 4] - Run entered for HIE(hie) Version 0.3.0.0, Git revision d110059e430f4fafc69c6ec4af8379b3accd0f9f (2144 commits) x86_64 ghc-8.4.4
2018-11-09 12:51:44.365074 [ThreadId 4] - Current directory:<my project dir>
2018-11-09 12:51:44.398422 [ThreadId 13] - Using stack GHC version
Using hie version: Version 0.3.0.0, Git revision d110059e430f4fafc69c6ec4af8379b3accd0f9f (2144 commits) x86_64 ghc-8.4.4
Using hoogle db at: <my home dir>/.hoogle/default-haskell-5.0.17.hoo
```

My project was created with `stack new my-project new-template`, and I've added the following to `stack.yaml`:

```
ghc-options:
  "$locals": -W -Werror
```

Also, `stack build` shows me the expected `Pattern match(es) are non-exhaustive` error each time.

I'm still finding my feet with haskell tooling so I expect this will be some misconfiguration on my part!

Cheers

**Comment by lorenzo** [comment]
Ok, can you try setting the ghc-options in package.yaml or in the cabal file instead of stack.yaml?

This is a file that is working for me today https://github.com/hadolint/hadolint/blob/master/package.yaml#L13

You can use it as an example

**Comment by lorenzo** [comment]
good news, I’ll close the ticket :)

**Comment by alanz** [comment]
@lorenzo should this go into the README?

**Comment by lorenzo** [comment]
It wouldn’t hurt to add a note about it
