### ISSUE TITLE
Use macros in makefile

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#940]
At the moment the makefile supports GHC 8.2.1, 8.2.2, 8.4.2, 8.4.3, 8.4.4 and is about to get 8.6.1 and 8.6.2

The required targets should be constructed using some kind of macro.

Alternatively, we must use shake, as proposed in #650

**Comment by lorenzo** [comment]
I'll take care of this

**Comment by fendor** [comment]
I am currently working on a Shakefile, see issue #650
