### ISSUE TITLE
Type checker plugins?

### ISSUE THREAD

**Issue by alex404** [haskell/haskell-ide-engine#946]
Hello,

I haven't had luck running hie recently on my work, and I finally rolled up my sleeves and figured out it's due to my use of type checker plugins (from ghc-typelits-natnormalise and ghc-typelits-knownnat on hackage). The odd thing is that up to several months ago hie sort-of-mostly worked even with my use of type checker plugins, but now it's completely unresponsive.

Is it supposed to work with type checker plugins? Do others have it working, or is this something that currently falls outside of the functionality of hie?

Thanks!

**Comment by alanz** [comment]
We don't have any tests for these, so if you could provide a simple example, we would be able to investigate.

**Comment by alex404** [comment]
After trying to develop a minimal example, it seems that the problem isn't the type checker plugins. What I do find is that hie still seems very brittle when I try and use it. Even if I write an .hs file from scratch with a few definitions in it (foo :: Int, foo = 3, etc), hie will work, but then when I write the file hie hangs. I'm doing with the nvim + ALE.

I'm not sure how to better isolate or diagnose this issue. If you have any advise I'd appreciate it, but otherwise I'll close this issue until I can better isolate the problem. Thanks for your help!

**Comment by fread2281** [comment]
This could be #519
