### ISSUE TITLE
readCreateProcess : cabal-helper-wrapper failure

### ISSUE THREAD

**Issue by teto** [haskell/haskell-ide-engine#949]
Not sure what the problem is

I have hie configured in neovim as
`let g:LanguageClient_serverCommands.haskell = ['hie', '--lsp', '-d',  '--logfile', '/tmp/lsp_haskell.log' ]`

On neovim startup I have the following error with hie on nixos-unstable. This is from the log:
```
2018-11-19 18:24:57.426507074 [ThreadId 7] - ghcDispatcher: top of loop
2018-11-19 18:24:57.426627592 [ThreadId 5] - <--2--{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":1,"message":"Got error while processing diagnostics: readCreateProcess: /nix/store/l8hqkjgfrbmmlrcqm85x8ms4fn737ga0-cabal-helper-0.8.0.3/libexec/x86_64-linux-ghc-8.4.3/cabal-helper-0.8.0.3/cabal-helper-wrapper \"--with-ghc=ghc\" \"--with-ghc-pkg=ghc-pkg\" \"--with-cabal=cabal\" \"/home/teto/mptcpnetlink/hs\" \"/home/teto/mptcpnetlink/hs/dist\" \"package-db-stack\" \"flags\" \"compiler-version\" \"ghc-merged-pkg-options\" \"config-flags\" \"non-default-config-flags\" \"ghc-src-options\" \"ghc-pkg-options\" \"ghc-lang-options\" \"ghc-options\" \"source-dirs\" \"entrypoints\" \"needs-build-output\" (exit 1): failed"}}
2018-11-19 18:24:57.426715195 [ThreadId 5] - <--2--{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/teto/mptcpnetlink/hs/daemon.hs","diagnostics":[]}}
```

Using https://www.freeformatter.com/javascript-escape.html#ad-output, I unescaped the string and ran it within my nix-shell defined via
```
with import <nixpkgs> {};

haskellPackages.shellFor {
  packages = p: with p; [ haskellPackages.netlink-pm ];
  withHoogle = true;
  nativeBuildInputs = [ cabal-install ];
}
```
(netlink-pm being a pet project of mine).
The result is:
```
/nix/store/l8hqkjgfrbmmlrcqm85x8ms4fn737ga0-cabal-helper-0.8.0.3/libexec/x86_64-linux-ghc-8.4.3/cabal-helper-0.8.0.3/cabal-helper-wrapper "--with-ghc=ghc" "--with-ghc-pkg=ghc-pkg" "--with-cabal=cabal" "/home/teto/mptcpnetlink/hs" "/home/teto/mptcpnetlink/hs/dist" "package-db-stack" "flags" "compiler-version" "ghc-merged-pkg-options" "config-flags" "non-default-config-flags" "ghc-src-options" "ghc-pkg-options" "ghc-lang-options" "ghc-options" "source-dirs" "entrypoints" "needs-build-output"
cabal-helper-wrapper: Installing a private copy of Cabal because we couldn't
find the right version in your global/user package-db, this might take a
while but will only happen once per Cabal version you're using.

If anything goes horribly wrong just delete this directory and try again:
    /home/teto/.cache/cabal-helper

If you want to avoid this automatic installation altogether install
version 2.4.0.1 of Cabal manually (into your user or global package-db):
    $ cabal install Cabal --constraint "Cabal == 2.4.0.1"

Installing Cabal 2.4.0.1 ...
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
cabal: There is no package named 'Cabal'.
You may need to run 'cabal update' to get the latest list of available
packages.

cabal-helper-wrapper: Installing Cabal version 2.4.0.1 failed.

You have the following choices to fix this:

- The easiest way to try and fix this is just reconfigure the project and try
  again:
        $ cabal clean && cabal configure

- If that fails you can try to install the version of Cabal mentioned above
  into your global/user package-db somehow, you'll probably have to fix
  something otherwise it wouldn't have failed above:
        $ cabal install Cabal --constraint 'Cabal == 2.4.0.1'

- If you're using `Build-Type: Simple`:
  - You can see if you can reinstall your cabal-install executable while
    having it linked to a version of Cabal that's available in you
    package-dbs or can be built automatically:
        $ ghc-pkg list | grep Cabal  # find an available Cabal version
            Cabal-W.X.Y.Z
        $ cabal install cabal-install --constraint 'Cabal == W.X.*'
    Afterwards you'll have to reconfigure your project:
        $ cabal clean && cabal configure

- If you're using `Build-Type: Custom`:
  - Have cabal-install rebuild your Setup.hs executable with a version of the
    Cabal library that you have available in your global/user package-db:
        $ cabal clean && cabal configure
    You might also have to install some version of the Cabal to do this:
        $ cabal install Cabal

```

I wonder if the problem exists because hie is installed globally or what pulls up cabal since I don't need it (I think runghc should be enough) ?

**Comment by alanz** [comment]
If you are running under nix, you should use https://github.com/domenkozar/hie-nix, which makes sure that cabal, cabal-helper, cabal-helper wrapper and friends are all installed and visible to your process.

**Comment by teto** [comment]
I already use hie-nix :s

**Comment by benkolera** [comment]
What you'll need to do is add the right Cabal to your deps. See this example (sorry about the noise of the other stuff). Note this setup doesn't allow hie to find the hoogle db. Still need to figure that out. 

````nix 
/*bkolera at bkolera in ~/src/gitlab/qfpl/open-banking-conformance-suite/open-banking-au-api-types (master●●) 
$ cat shell.nix */ 
{ nixpkgs ? import ../nix/nixpkgs.nix
, compiler ? "default"
, hie ? false
}:

let
  inherit (nixpkgs) pkgs;

  drv = (import ./. {});

  haskellPackages = import ./nix/haskellPackages.nix {inherit nixpkgs compiler;};
  hie-tools = if !hie then [] else (with pkgs.haskellPackages; 
    [ Cabal_2_4_0_1 apply-refact hsimport hasktags hlint hoogle brittany ]); 

  shellDrv = pkgs.haskell.lib.overrideCabal drv (drv': {
    buildDepends =
      (drv'.buildDepends or []) ++
      [ (haskellPackages.hoogleLocal {
          packages =
            (drv'.libraryHaskellDepends or []) ++
            (drv'.executableHaskellDepends or []) ++
            (drv'.testHaskellDepends or []) ;
        })
        pkgs.cabal-install
      ];
    buildTools = (drv'.buildTools or []) ++ hie-tools;
  });

in
  shellDrv.env
```

**Comment by benkolera** [comment]
Also, I'm not sure why my colleague setup the hoogle DB this way,  so don't copy the hoogle part! But the build tools adding in Cabal_2_4_0_1 should fix it. You can use haskell.lib.addBuildTool for that.

**Comment by teto** [comment]
Seems to fix it, even if it's annoying it doesn't work out of the box. Thanks.

**Comment by alanz** [comment]
@benkolera @domenkozar would it make sense to either update `hie-nix` or add this information to its README?

**Comment by benkolera** [comment]
@teto It doesn't work out of the box because it expects you to have a cabal that has a package index. It looks like you have never run cabal update because you don't install haskell deps via cabal-install. If you are happy running cabal update and having cabal helper install it into a home ghc db, you could also do that. I tend to avoid that because:

a) Not everything will build happily into there (e.g. stuff that depends on zlib, etc)
b) You can get weirdness in nix builds with a package db there. 

But if you'd rather go down that route, it ought to work.

**Comment by benkolera** [comment]
Yeah @alanz . I have this on my list to update. There are a few other notes I have to document too. 

PRs to hie-nix and hie incoming soon. :slightly_smiling_face:

**Comment by teto** [comment]
`cabal that has a package index`
what is that (noob) :) ? Ideally I try to manage everything with nix since I've spent much time getting to know it and have no or little prior experience with cabal/stack (bootstrapping nix can be dauting but once you reap the benefits, it's hard to go back).


I've tried getting a proper haskell IDE-like environment for months and between haskell crazy dependencies ecosystem and nix difficulties, it is a bumpy ride. Thanks to all of you for improving it, helping noobs on IRC/github.

**Comment by benkolera** [comment]
The list of packages that you can get from hackage via cabal-install. Initially, cabal-install doesn't ship with one of these and you need to run `cabal update` to get one. Before you do that, you can't actually cabal install anything. That's what the error here is saying:

```
Installing Cabal 2.4.0.1 ...
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
cabal: There is no package named 'Cabal'.
You may need to run 'cabal update' to get the latest list of available
packages.
```

You don't actually ever need to cabal install anything with nix, so that's why you've never had to do such a thing and why it isn't there. When you cabal install it will install into a separate place for ghc packages that gets used in addition to the one in nix-shell and globally with ghc.

See an example here. Note how that locally cabal installed thing went into my home dir?
```
bkolera at bkolera in ~/.emacs.d/private/hie-nix (master) 
$ cabal install acme-default
Resolving dependencies...
Downloading acme-default-0.1.0...
Configuring acme-default-0.1.0...
Building acme-default-0.1.0...
Installed acme-default-0.1.0

bkolera at bkolera in ~/.emacs.d/private/hie-nix (master) 
$ ghc-pkg list
/nix/store/n5i1zdpmk2b1s3z96649xh8f9kr3g96s-ghc-8.4.3/lib/ghc-8.4.3/package.conf.d
    Cabal-2.2.0.1
    array-0.5.2.0
    base-4.11.1.0
    binary-0.8.5.1
    bytestring-0.10.8.2
    containers-0.5.11.0
    deepseq-1.4.3.0
    directory-1.3.1.5
    filepath-1.4.2
    ghc-8.4.3
    ghc-boot-8.4.3
    ghc-boot-th-8.4.3
    ghc-compact-0.1.0.0
    ghc-prim-0.5.2.0
    ghci-8.4.3
    haskeline-0.7.4.2
    hpc-0.6.0.3
    integer-gmp-1.0.2.0
    mtl-2.2.2
    parsec-3.1.13.0
    pretty-1.1.3.6
    process-1.6.3.0
    rts-1.0
    stm-2.4.5.0
    template-haskell-2.13.0.0
    terminfo-0.4.1.1
    text-1.2.3.0
    time-1.8.0.2
    transformers-0.5.5.0
    unix-2.7.2.2
    xhtml-3000.2.2.1
/home/bkolera/.ghc/x86_64-linux-8.4.3/package.conf.d
    acme-default-0.1.0
```

But don't worry about this too much if you are doing everything with nix. You can either cabal update and cabal helper will install to your home dir, or bring the thing in your shell.nix like you did to fix it before. Having anything but Cabal installed in your ~/.ghc is a recipe for nix troubles with old school cabal (configure, build, run, test, repl instead of new-build, new-run, new-test, etc) like hie does, so beware! 

Btw, if you are new to all of this, the command `ghc-pkg list` is your friend for figuring out what packages an instance of ghc knows about!! You can run that in a nix-shell or anywhere you have a ghc. 

Please feel free to pester me on IRC if you have more questions. It's interesting to meet someone who has gone straight to haskell and nix without having prior scars from cabal and/or stack prior. I can probably answer things quickly if you ask.

**Comment by teto** [comment]
thanks for the great explanation. Bookmarked :)
