### ISSUE TITLE
Manage bad project configuration

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#951]
If a project is not building, because a dependency is missing from the cabal file, or not listed in the stack file, then

- Report this as a problem in a clear way
- Disable the normal GHC checking, until something is known to change in the config that may fix it.

Otherwise the client becomes unusable as hie tries to build the file being edited, without any prospect of success.

**Comment by alanz** [comment]
Related (for bullet point 1) #1011

**Comment by jneira** [comment]
Has this behaviour changed after hie-bios merge?

**Comment by fendor** [comment]
Yeah, it probably got worse.

**Comment by jneira** [comment]
Yeah vscode directly crashes with no clue: 😞 

```
hie-wrapper: callProcessStderr: cabal v2-build --with-ghc=D:\bin\stack\x86_64-windows\ghc-8.6.5\bin\ghc.exe --with-ghc-pkg=D:\bin\stack\x86_64-windows\ghc-8.6.5\bin\ghc-pkg.exe --with-haddock=D:\bin\stack\x86_64-windows\ghc-8.6.5\bin\haddock.exe --project-file=d:\dev\ws\haskell\cabal-test\cabal.project --builddir=d:\dev\ws\haskell\cabal-test\dist-newstyle --dry-run all (exit 1): failed
[Error - 20:46:40] Connection to server got closed. Server will not be restarted.
```

**Comment by fendor** [comment]
Weird, hie-wrapper should not crash.

**Comment by jneira** [comment]
hie-wrapper tries to guess ghc doing a `v2-build --dry-run`, right? that process fail if the cabal file is bad

Moreover hie-bios also fail, but i think your recent work about error messages in cradle init could help a lot with that:

```
PS D:\dev\ws\haskell\cabal-test> hie-bios debug .\src\Lib.hs 
Cradle failed to load
Exit Code: ExitFailure 1
Stderr: Failed to parse result of calling cabal
Resolving dependencies...

cabal: Could not resolve dependencies:
[__0] trying: cabal-test-0.1.0.0 (user goal)
[__1] unknown package: badpackage (dependency of cabal-test)
[__1] fail (backjumping, conflict set: badpackage, cabal-test)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cabal-test, badpackage
```

**Comment by fendor** [comment]
no, if cabal-helper crashes in hie-wrapper, we have no way of reporting that since we havent even started the lsp-server yet :(

**Comment by jneira** [comment]
Yeah, i was optimistically  assuming that we will fix that  😄

**Comment by jneira** [comment]
Closing in favor of #1536
