### ISSUE TITLE
current master cannot build 

### ISSUE THREAD

**Issue by zedongh** [haskell/haskell-ide-engine#960]
Using configuration file: stack.yaml
The following packages are missing from the config:
- submodules/HaRe/
- submodules/HaRe/hareview/
- submodules/HaRe/submodules/cabal-helper/
- submodules/HaRe/submodules/cabal-helper/tests/bkpregex/
- submodules/HaRe/submodules/cabal-helper/tests/exeintlib/
- submodules/HaRe/submodules/cabal-helper/tests/exelib/
- submodules/HaRe/submodules/cabal-helper/tests/fliblib/
- submodules/HaRe/submodules/ghc-exactprint/
- submodules/HaRe/submodules/ghc-mod/
- submodules/HaRe/submodules/ghc-mod/bench/data/simple-cabal/
- submodules/HaRe/submodules/ghc-mod/core/
- submodules/HaRe/submodules/ghc-mod/shelltest/browse/cabal/
- submodules/HaRe/submodules/ghc-mod/test/data/broken-cabal/
- submodules/HaRe/submodules/ghc-mod/test/data/broken-sandbox/
- submodules/HaRe/submodules/ghc-mod/test/data/cabal-flags/
- submodules/HaRe/submodules/ghc-mod/test/data/cabal-preprocessors/
- submodules/HaRe/submodules/ghc-mod/test/data/cabal-project/
- submodules/HaRe/submodules/ghc-mod/test/data/check-test-subdir/
- submodules/HaRe/submodules/ghc-mod/test/data/custom-cradle/
- submodules/HaRe/submodules/ghc-mod/test/data/duplicate-pkgver/
- submodules/HaRe/submodules/ghc-mod/test/data/ghc-mod-check/
- submodules/HaRe/submodules/ghc-mod/test/data/pattern-synonyms/
- submodules/HaRe/submodules/ghc-mod/test/data/stack-project/
- submodules/HaRe/submodules/ghc-mod/test/manual/not-interpreted-error/proj/
- submodules/HaRe/submodules/hslogger/
- submodules/HaRe/submodules/monad-journal/
- submodules/HaRe/test/testdata/
- submodules/HaRe/test/testdata/cabal/cabal1/
- submodules/HaRe/test/testdata/cabal/cabal2/
- submodules/HaRe/test/testdata/cabal/cabal3/
- submodules/HaRe/test/testdata/cabal/cabal4/
- submodules/HaRe/test/testdata/cabal/foo/
- submodules/brittany/
- submodules/brittany/doc-svg-gen/
- submodules/cabal-helper/
- submodules/cabal-helper/tests/bkpregex/
- submodules/cabal-helper/tests/exeintlib/
- submodules/cabal-helper/tests/exelib/
- submodules/cabal-helper/tests/fliblib/
- submodules/ghc-mod/
- submodules/ghc-mod/bench/data/simple-cabal/
- submodules/ghc-mod/core/
- submodules/ghc-mod/shelltest/browse/cabal/
- submodules/ghc-mod/test/data/broken-cabal/
- submodules/ghc-mod/test/data/broken-sandbox/
- submodules/ghc-mod/test/data/cabal-flags/
- submodules/ghc-mod/test/data/cabal-preprocessors/
- submodules/ghc-mod/test/data/cabal-project/
- submodules/ghc-mod/test/data/check-test-subdir/
- submodules/ghc-mod/test/data/custom-cradle/
- submodules/ghc-mod/test/data/duplicate-pkgver/
- submodules/ghc-mod/test/data/ghc-mod-check/
- submodules/ghc-mod/test/data/pattern-synonyms/
- submodules/ghc-mod/test/data/stack-project/
- submodules/ghc-mod/test/manual/not-interpreted-error/proj/
- submodules/haskell-lsp/
- submodules/haskell-lsp/haskell-lsp-types/
- submodules/yi-rope/
- test/testdata/
- test/testdata/addPackageTest/cabal/
- test/testdata/addPackageTest/hpack/
- test/testdata/definition/
- test/testdata/gototest/
- test/testdata/redundantImportTest/
- test/testdata/wErrorTest/

Using cabal packages:
- ./
- hie-plugin-api/

Using resolver: lts-12.17

Warning: Installed version of cabal-install (2.2.0.0) is newer than stack has been tested with.  If you run into difficulties, consider downgrading.
         
Using compiler: ghc-8.4.4
Asking cabal to calculate a build plan...
Trying with packages from lts-12.17 and 21 external packages as hard constraints...
Attempt failed.

>>>> Cabal errors begin
Warning: Constraint refers to an unknown package: ghc-mod-core ==5.9.0.0 (main
config /tmp/cabal-solver29826/cabal.config)
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:238:21 in cabal-install-2.2.0.0-13yJmKUjI2XFeq9gwXVEMz:Distribution.Client.Install
cabal: Could not resolve dependencies:
[__0] trying: haskell-ide-engine-0.3.0.0 (user goal)
[__1] unknown package: ghc-mod-core (dependency of haskell-ide-engine)
[__1] fail (backjumping, conflict set: ghc-mod-core, haskell-ide-engine)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: haskell-ide-engine (2), ghc-mod-core
(1)

<<<< Cabal errors end

Could not parse cabal-install errors:

>>>> Cabal errors begin
Warning: Constraint refers to an unknown package: ghc-mod-core ==5.9.0.0 (main
config /tmp/cabal-solver29826/cabal.config)
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:238:21 in cabal-install-2.2.0.0-13yJmKUjI2XFeq9gwXVEMz:Distribution.Client.Install
cabal: Could not resolve dependencies:
[__0] trying: haskell-ide-engine-0.3.0.0 (user goal)
[__1] unknown package: ghc-mod-core (dependency of haskell-ide-engine)
[__1] fail (backjumping, conflict set: ghc-mod-core, haskell-ide-engine)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: haskell-ide-engine (2), ghc-mod-core
(1)

<<<< Cabal errors end

CallStack (from HasCallStack):
  error, called at src/Stack/Solver.hs:131:25 in stack-1.9.1-3pkMneYlY9yXBwwTVoQza:Stack.Solver

**Comment by alanz** [comment]
what did you do to get all of this?

You should be able to just `make hie-8.4.4`.

**Comment by zedongh** [comment]
```
> stack solver
```
by the way i have built success 2 commits before

**Comment by alanz** [comment]
you should just do `stack build` or `stack --stack-yaml=stack-8.4.4.yaml build`.

The stack files are already set up, no need to run stack solver.

**Comment by zedongh** [comment]
```
> stack build
> stack install
```
I found that the hie version was the old version, but i try `stack clean` and do those agian, it works.
Thanks!
