### ISSUE TITLE
Can't install without ghc in PATH

### ISSUE THREAD

**Issue by LukaHorvat** [haskell/haskell-ide-engine#964]
The `cabal install Cabal-2.4.1.0` step in the makefile requires `ghc` in PATH, which isn't really the default for stack installations. Is there a way around this?

**Comment by lorenzo** [comment]
The only step for installing with stack is to run stack install. There is no need to install cabal separately.

**Comment by lorenzo** [comment]
did you try the `make` executable? You can select the versions you need to install

**Comment by LukaHorvat** [comment]
Yes. This is what I'm saying. The makefile specifies the `cabal` build target as a dependency for all the versions and that build target fails.

**Comment by lorenzo** [comment]
Alright, I think that needs to be improved. Thanks for the heads up. This is what I did before running the makefile:

```stack install cabal-install`

I'll make sure that's what the makefile does.

**Comment by LukaHorvat** [comment]
This isn't enough. The `cabal` executable IS on my path because stack put it there. `ghc` isn't, and that what cabal expects.

**Comment by lorenzo** [comment]
Not sure what is different for you, then. I don't have a global ghc executable, and I installed hie with the  Makefile. What do you think the different could be?

**Comment by LukaHorvat** [comment]
I'm not sure. Internet seems to suggest that a global GHC is required when installing with cabal.

**Comment by lorenzo** [comment]
Can you show the error message you get from cabal? And the command line you are executing?

**Comment by LukaHorvat** [comment]
Sure. I'm running `make hie-8.2.2` and getting 

```
Warning: The update command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-update command
or the legacy v1-update alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal update --index-state='2018-11-30T12:32:34Z'
cabal -- install Cabal-2.4.1.0
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

cabal.exe: The program 'ghc' version >=7.0.1 is required but it could not be
found.

make: *** [Makefile:95: cabal] Error 1
```

**Comment by alanz** [comment]
Unfortunately Cabal needs to be installed using the old style command.

And I only just noticed this thread now, after pushing 0.4.0.0. Whoops.

**Comment by alanz** [comment]
Please try the Makefile in https://github.com/alanz/haskell-ide-engine/tree/stack-install-cabal

**Comment by LukaHorvat** [comment]
Just commenting that this works for me.
