### ISSUE TITLE
brittany and hlint disagree on how EmptyCase should look

### ISSUE THREAD

**Issue by dspies-leapyear** [haskell/haskell-ide-engine#967]
When `brittany` sees

```
foo x = case x of {}

bar = undefined
```

it reformats it as

```
foo x = case x of

bar = undefined
```

but when `hlint` sees it without the `{}`s it complains

`Parse error: virtual }`

**Comment by alanz** [comment]
I think this is a brittany problem.

cc @lspitzner

**Comment by dspies-leapyear** [comment]
Nit: While I agree that I prefer the `{}`s to be present and would like a way to stop `brittany` from removing them, that's technically a feature request. Meanwhile `hlint` is actually failing to parse valid Haskell code, so this may be more appropriately classified as an `hlint` bug.

**Comment by dspies-leapyear** [comment]
cc @ndmitchell

**Comment by ndmitchell** [comment]
haskell-src-exts (which HLint uses as the parser) is wrong, so of the two programs HLint is wrong. I have a plan to fix these issues, but it's going to take a few months. I added this ticket to https://github.com/haskell-suite/haskell-src-exts/issues/282, which I suspect is related.

**Comment by alanz** [comment]
So does anything have to happen in hie still?

**Comment by ndmitchell** [comment]
I raised a ticket for HLint at https://github.com/ndmitchell/hlint/issues/574. There's nothing HIE can do, so suggest you close it.
