### ISSUE TITLE
Error highlighting can't keep up with code changes

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell/haskell-ide-engine#972]
I am not sure if the issue is the same as #531 but it feels similar.

The issue manifests itself when I press `Command+S` (Save current file) when I finish typing. At this time it looks like HIE kind of gives up on checking the file and keeps showing irrelevant error highlights.
However, if I do not press "Save" (or I press it after the check is completed), then everything works fine.

![out-of-sync-errors](https://user-images.githubusercontent.com/1394391/49407653-6c1c5880-f7ad-11e8-99c8-d0d94c3af885.gif)

Note on that screenshot where I correct an error and immediately press "Save" the line stays highlighted.

**Comment by alanz** [comment]
I have noticed something similar, but it was in alex/happy generated files so I assumed the #LINE pragmas were the cause.

**Comment by AlexeyRaga** [comment]
There are no pragmas in this file/project. This is also reproducible in any project.

I suspect that it has something to do with the current request to HIE being cancelled (or the response is treated as obsolete) when Save is pressed. But it is just my imagination talking :)

**Comment by AlexeyRaga** [comment]
@alanz thanks, looks like your commit has fixed this issue. I am closing it because I can't reproduce it anymore.
