### ISSUE TITLE
Unable to download ghc during make due to network

### ISSUE THREAD

**Issue by patoncrispy** [haskell/haskell-ide-engine#984]
Having really bad issues trying get through `make build-all` as system is unable to fully install `ghc-8.4.2`: 

<img width="687" alt="screenshot 2018-12-07 at 16 51 46" src="https://user-images.githubusercontent.com/2559414/49661365-c54fea80-fa40-11e8-9d84-a58ef5d73880.png">

It seems to just hang. Is there a different CDN I can use to download the different versions?

**Comment by Anrock** [comment]
Issues with stack CDN are responsibility of stack project, not HIE. Try posting issue here: https://github.com/commercialhaskell/stack.
