### ISSUE TITLE
Use Azure for CI?

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-ide-engine#993]
https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/
> Starting today, Azure Pipelines provides unlimited CI/CD minutes and 10 parallel jobs to every open source project for free. All open source projects run on the same infrastructure that our paying customers use.

via @ndmitchell

**Comment by power-fungus** [comment]
I will work on this in the next week.

**Comment by mpickering** [comment]
@power-fungus 

Perhaps this branch is a good start https://github.com/rossng/haskell-ide-engine

**Comment by bubba** [comment]
If you are feeling generous someone could also take a look at fixing https://github.com/bubba/lsp-test/issues/28 and running the tests on windows

**Comment by fendor** [comment]
@bubba I am trying to fix the tests, but I can only do that in the evening since I have no windows otherwise. May take a while, though.

**Comment by power-fungus** [comment]
I needed to sell my soul (i.e. grant exhaustive r/w-access) in order to setup a Azure Pipeline. This would be necessary for this project as well. Are there objections to this? @alanz @Anrock @mpickering @bubba

**Comment by alanz** [comment]
I hate this, especially in the light of the recent dockerhub thing.  Does the scope apply only to hie?

But, we it is a token that can be revoked, and we do have backups of the repo on all our various machines and forks, so maybe it is ok?

**Comment by power-fungus** [comment]
If I get maintainer rights to this repository, the azure will find the repository automatically via my account and will be usable via my account. Currently, I can setup Pipelines for all projects I have access to, which is a bit scary. It crawls my whole account...

**Comment by ndmitchell** [comment]
FWIW CircleCI does this at a much more annoying level - merely viewing a different projects CI output requires you to give read/write permission to everything you own. It is sad :( But in truth, not that dangerous, I think...

**Comment by power-fungus** [comment]
its still only r/w access via the github-api. So deleting everything for good is not possible (I *think*).

I will experiment with my repositories and will report back in a few days

**Comment by DanielG** [comment]
@power-fungus might you be able to just revoke the API access after first setup? I would assume they just use it to register a webhook to trigger builds. At least thats how things work for GitLab CI.
