### ISSUE TITLE
Auto-complete OPTIONS_GHC inserts an extra `-`

### ISSUE THREAD

**Issue by dspies-leapyear** [haskell/haskell-ide-engine#994]
I'm using the ide-haskell-hie package for Atom

When I start to type `GHC` at the top of the file it offers the suggestion `GHC` and I can hit enter to autocomplete
{-# OPTIONS_GHC -option #-}
with `option` selected

Then if I start to type in `Wno-red`, it offers the option `-Wno-redundant-constraints` and I can hit enter to auto-complete again. But now there are _two_ dashes in front of the option so I get an unknown flag error.

**Comment by alanz** [comment]
I can recreate this in vscode too.  I think there is a mismatch at the client level, where the scope of the thing being completed does not include the leading `-`, but the replacement text does.

I suspect the simplest solution is to remove the leading `-` in the provided completions, but I am not 100% sure this is the *correct* solution.

**Comment by dspies-leapyear** [comment]
I thought the fix would be to have `-option` be selected rather than just `option` when you autocomplete the first time. That way the `-` gets replaced rather than appended to.
I just checked right now and if I manually select `-option` and start typing, autocompletion works fine.

**Comment by alanz** [comment]
Yes, but I think the default behaviour is to work on a symbol, so the client will not include the leading -.

So my proposed fix should make that work better.
