### ISSUE TITLE
Why the huge installation sizes?

### ISSUE THREAD

**Issue by DavSanchez** [haskell/haskell-ide-engine#999]
Hello there!

I'm sorry because this is more like a general question than an issue per se... but why having this development environment for Haskell can take more than 20 GB of hard disk space (when building all targets with `make` for example)? Are all these libraries really needed for easy development of Haskell programs?

I'm very interested in this project, having a kind of Haskell IntelliSense, but I don't know why that huge tradeoff in space...

Greetings!

**Comment by Anrock** [comment]
> but why having this development environment for Haskell can take more than 20 GB of hard disk space (when building all targets with make for example)?

Because building hie for all supported GHC versions also requires installation of all this GHC versions + hie dependencies for each version.

>  Are all these libraries really needed for easy development of Haskell programs?

Only if you really have projects that use all the GHC versions. Mostly people have only one or two versions installed and most dependencies for hie are already built.

**Comment by ianchanning** [comment]
I have wondered this, but it's not a HIE issue, it's a general Haskell issue. There's a few suggestions on this SO question: https://stackoverflow.com/questions/4858585/why-is-ghc-so-large-big (from 2011), but that talks in 100s of MBs and this is on a scale 100x larger.

**Comment by Anrock** [comment]
Closing as answered.
1. GHC is big, but it's out of HIE area of responsibility
2. Don't use `make build-all` to install every supported version of HIE 'cause it brings all those big GHCs. Use `make help` to get list of supported GHC versions, find one you need and run `make hie-X.Y.Z` to install HIE only for specific version.
